-- Sample STEM simulations for Virtual Lab Cambodia
-- This migration adds sample simulation data for demonstration purposes

INSERT INTO stem_simulations_catalog (
  simulation_name,
  display_name_en,
  display_name_km,
  description_en,
  description_km,
  subject_area,
  difficulty_level,
  grade_levels,
  estimated_duration,
  learning_objectives_en,
  learning_objectives_km,
  simulation_url,
  preview_image,
  tags,
  is_featured,
  is_active
) VALUES
-- Physics Simulations
(
  'pendulum-lab',
  'Pendulum Lab',
  'មន្ទីរពិសោធន៍ប៉ោល',
  'Explore the motion of pendulums and discover how length, mass, and angle affect the period.',
  'ស្វែងយល់ពីចលនាប៉ោល និងរកឃើញពីរបៀបដែលប្រវែង ម៉ាស់ និងមុំប៉ះពាល់លើរយៈពេល។',
  'Physics',
  'Intermediate',
  ARRAY[9, 10, 11],
  45,
  ARRAY['Understand pendulum motion and period', 'Investigate factors affecting pendulum period', 'Apply pendulum principles to real-world situations'],
  ARRAY['យល់ដឹងពីចលនាប៉ោល និងរយៈពេល', 'ស្រាវជ្រាវកត្តាដែលប៉ះពាល់លើរយៈពេលប៉ោល', 'អនុវត្តគោលការណ៍ប៉ោលទៅស្ថានភាពជាក់ស្តែង'],
  'https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html',
  '/images/simulations/pendulum-lab.png',
  ARRAY['physics', 'pendulum', 'oscillation', 'period', 'gravity'],
  true,
  true
),

(
  'circuit-construction-kit',
  'Circuit Construction Kit',
  'ឧបករណ៍សាងសង់សៀគ្វីអគ្គិសនី',
  'Build circuits with resistors, light bulbs, batteries, and switches. Explore conductors and insulators.',
  'សាងសង់សៀគ្វីអគ្គិសនីជាមួយរេស៊ីស្ទ័រ អំពូលភ្លើង ថ្ម និងកុងតាក់។ ស្វែងយល់ពីអង្គធាតុចម្លង និងអ៊ីសូឡង់។',
  'Physics',
  'Beginner',
  ARRAY[7, 8, 9],
  30,
  ARRAY['Build and analyze simple circuits', 'Understand current, voltage, and resistance', 'Identify conductors and insulators'],
  ARRAY['សាងសង់ និងវិភាគសៀគ្វីសាមញ្ញ', 'យល់ដឹងពីចរន្ត តង់ស្យុង និងរេស៊ីស្តង់', 'កំណត់អត្តសញ្ញាណអង្គធាតុចម្លង និងអ៊ីសូឡង់'],
  'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html',
  '/images/simulations/circuit-kit.png',
  ARRAY['physics', 'electricity', 'circuits', 'current', 'voltage'],
  true,
  true
),

(
  'wave-interference',
  'Wave Interference',
  'អន្តរាគមន៍រលក',
  'Make waves with water, sound, and light. Explore wave interference patterns.',
  'បង្កើតរលកជាមួយទឹក សំឡេង និងពន្លឺ។ ស្វែងយល់ពីគំរូអន្តរាគមន៍រលក។',
  'Physics',
  'Advanced',
  ARRAY[10, 11, 12],
  60,
  ARRAY['Understand wave properties and behavior', 'Explore constructive and destructive interference', 'Apply wave concepts to sound and light'],
  ARRAY['យល់ដឹងពីលក្ខណៈ និងឥរិយាបថរលក', 'ស្វែងយល់ពីអន្តរាគមន៍ស្ថាបនា និងបំផ្លាញ', 'អនុវត្តគំនិតរលកទៅសំឡេង និងពន្លឺ'],
  'https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html',
  '/images/simulations/wave-interference.png',
  ARRAY['physics', 'waves', 'interference', 'sound', 'light'],
  false,
  true
),

-- Chemistry Simulations
(
  'build-a-molecule',
  'Build a Molecule',
  'សាងសង់ម៉ូលេគុល',
  'Construct simple molecules from atoms. Learn about molecular structure and formulas.',
  'សាងសង់ម៉ូលេគុលសាមញ្ញពីអាតូម។ រៀនអំពីរចនាសម្ព័ន្ធម៉ូលេគុល និងរូបមន្ត។',
  'Chemistry',
  'Beginner',
  ARRAY[7, 8, 9],
  30,
  ARRAY['Build molecules from individual atoms', 'Understand molecular formulas', 'Recognize common molecular structures'],
  ARRAY['សាងសង់ម៉ូលេគុលពីអាតូមនីមួយៗ', 'យល់ដឹងពីរូបមន្តម៉ូលេគុល', 'ស្គាល់រចនាសម្ព័ន្ធម៉ូលេគុលទូទៅ'],
  'https://phet.colorado.edu/sims/html/build-a-molecule/latest/build-a-molecule_en.html',
  '/images/simulations/build-molecule.png',
  ARRAY['chemistry', 'molecules', 'atoms', 'bonding', 'structure'],
  true,
  true
),

(
  'ph-scale',
  'pH Scale',
  'មាត្រដ្ឋាន pH',
  'Test the pH of everyday liquids. Explore acids and bases with interactive measurements.',
  'សាកល្បង pH នៃសារធាតុរាវប្រចាំថ្ងៃ។ ស្វែងយល់ពីអាស៊ីត និងបាសជាមួយការវាស់វែងអន្តរកម្ម។',
  'Chemistry',
  'Intermediate',
  ARRAY[8, 9, 10],
  40,
  ARRAY['Measure pH of common substances', 'Understand acids, bases, and neutral solutions', 'Relate pH to hydrogen ion concentration'],
  ARRAY['វាស់ pH នៃសារធាតុទូទៅ', 'យល់ដឹងពីអាស៊ីត បាស និងសូលុយស្យុងអព្យាក្រឹត', 'ទាក់ទង pH ទៅកំហាប់អ៊ីយ៉ុងអ៊ីដ្រូសែន'],
  'https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_en.html',
  '/images/simulations/ph-scale.png',
  ARRAY['chemistry', 'pH', 'acids', 'bases', 'measurement'],
  true,
  true
),

(
  'states-of-matter',
  'States of Matter',
  'ស្ថានភាពរូបធាតុ',
  'Explore how atoms and molecules behave in solids, liquids, and gases.',
  'ស្វែងយល់ពីរបៀបដែលអាតូម និងម៉ូលេគុលមានឥរិយាបថក្នុងរឹង រាវ និងឧស្ម័ន។',
  'Chemistry',
  'Beginner',
  ARRAY[6, 7, 8],
  35,
  ARRAY['Identify properties of solids, liquids, and gases', 'Observe molecular motion in different states', 'Understand phase transitions'],
  ARRAY['កំណត់លក្ខណៈរឹង រាវ និងឧស្ម័ន', 'សង្កេតចលនាម៉ូលេគុលក្នុងស្ថានភាពផ្សេងៗ', 'យល់ដឹងពីការផ្លាស់ប្តូរដំណាក់កាល'],
  'https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_en.html',
  '/images/simulations/states-matter.png',
  ARRAY['chemistry', 'states', 'matter', 'phase', 'molecules'],
  false,
  true
),

-- Biology Simulations
(
  'gene-expression-essentials',
  'Gene Expression Essentials',
  'មូលដ្ឋានការបង្ហាញហ្សែន',
  'Learn how genes control cell function. Explore transcription and translation.',
  'រៀនពីរបៀបដែលហ្សែនគ្រប់គ្រងមុខងារកោសិកា។ ស្វែងយល់ពីការចម្លងកូដ និងការបកប្រែ។',
  'Biology',
  'Advanced',
  ARRAY[10, 11, 12],
  60,
  ARRAY['Understand gene structure and function', 'Explore protein synthesis process', 'Learn about gene regulation'],
  ARRAY['យល់ដឹងពីរចនាសម្ព័ន្ធ និងមុខងារហ្សែន', 'ស្វែងយល់ពីដំណើរការសំយោគប្រូតេអ៊ីន', 'រៀនអំពីការគ្រប់គ្រងហ្សែន'],
  'https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_en.html',
  '/images/simulations/gene-expression.png',
  ARRAY['biology', 'genetics', 'DNA', 'protein', 'gene'],
  false,
  true
),

(
  'natural-selection',
  'Natural Selection',
  'ការជ្រើសរើសធម្មជាតិ',
  'Explore how environmental pressures affect trait distribution in populations.',
  'ស្វែងយល់ពីរបៀបដែលសម្ពាធបរិស្ថានប៉ះពាល់លើការចែកចាយលក្ខណៈក្នុងចំនួនប្រជាជន។',
  'Biology',
  'Intermediate',
  ARRAY[9, 10, 11],
  45,
  ARRAY['Understand natural selection principles', 'Observe trait changes over generations', 'Explore factors affecting evolution'],
  ARRAY['យល់ដឹងពីគោលការណ៍ការជ្រើសរើសធម្មជាតិ', 'សង្កេតការផ្លាស់ប្តូរលក្ខណៈតាមជំនាន់', 'ស្វែងយល់ពីកត្តាប៉ះពាល់លើវិវត្តន៍'],
  'https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html',
  '/images/simulations/natural-selection.png',
  ARRAY['biology', 'evolution', 'natural selection', 'adaptation', 'genetics'],
  true,
  true
),

-- Mathematics Simulations
(
  'function-builder',
  'Function Builder',
  'អ្នកសាងសង់អនុគមន៍',
  'Build and explore mathematical functions. Understand input-output relationships.',
  'សាងសង់ និងស្វែងយល់អនុគមន៍គណិតវិទ្យា។ យល់ដឹងពីទំនាក់ទំនងធាតុចូល-ធាតុចេញ។',
  'Mathematics',
  'Intermediate',
  ARRAY[8, 9, 10],
  40,
  ARRAY['Build and analyze functions', 'Understand function notation', 'Explore patterns and relationships'],
  ARRAY['សាងសង់ និងវិភាគអនុគមន៍', 'យល់ដឹងពីសញ្ញាណអនុគមន៍', 'ស្វែងយល់ពីគំរូ និងទំនាក់ទំនង'],
  'https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_en.html',
  '/images/simulations/function-builder.png',
  ARRAY['mathematics', 'functions', 'algebra', 'patterns', 'equations'],
  false,
  true
),

(
  'graphing-lines',
  'Graphing Lines',
  'គូសក្រាហ្វបន្ទាត់',
  'Graph linear equations and explore slope-intercept form interactively.',
  'គូសក្រាហ្វសមីការលីនេអ៊ែរ និងស្វែងយល់ទម្រង់ជម្រាល-ចំណុចប្រសព្វអន្តរកម្ម។',
  'Mathematics',
  'Beginner',
  ARRAY[7, 8, 9],
  30,
  ARRAY['Graph linear equations', 'Understand slope and y-intercept', 'Connect equations to visual representations'],
  ARRAY['គូសក្រាហ្វសមីការលីនេអ៊ែរ', 'យល់ដឹងពីជម្រាល និងចំណុចប្រសព្វ y', 'ភ្ជាប់សមីការទៅតំណាងរូបភាព'],
  'https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html',
  '/images/simulations/graphing-lines.png',
  ARRAY['mathematics', 'graphing', 'linear', 'slope', 'algebra'],
  true,
  true
)
ON CONFLICT (simulation_name) DO UPDATE SET
  display_name_en = EXCLUDED.display_name_en,
  display_name_km = EXCLUDED.display_name_km,
  description_en = EXCLUDED.description_en,
  description_km = EXCLUDED.description_km,
  is_featured = EXCLUDED.is_featured,
  updated_at = CURRENT_TIMESTAMP;