-- Add exercises for ALL simulations that are missing them
-- This comprehensive script covers Biology, Chemistry, Mathematics, and remaining Physics simulations

DO $$
DECLARE
  sim_id UUID;
  teacher_id UUID;
  sim_record RECORD;
BEGIN
  -- Get a teacher ID for all exercises
  SELECT id INTO teacher_id FROM users WHERE role = 'teacher' LIMIT 1;
  
  -- If no teacher found, create a system teacher
  IF teacher_id IS NULL THEN
    INSERT INTO users (username, email, role, first_name, last_name)
    VALUES ('system', 'system@virtuallabcambodia.edu.kh', 'teacher', 'System', 'Teacher')
    RETURNING id INTO teacher_id;
  END IF;

  -- Loop through all simulations that don't have exercises yet
  FOR sim_record IN 
    SELECT s.id, s.simulation_name, s.subject_area, s.difficulty_level
    FROM stem_simulations_catalog s
    WHERE s.is_active = true 
    AND NOT EXISTS (SELECT 1 FROM simulation_exercises e WHERE e.simulation_id = s.id)
    ORDER BY s.subject_area, s.simulation_name
  LOOP
    sim_id := sim_record.id;
    
    -- BIOLOGY SIMULATIONS
    IF sim_record.simulation_name = 'natural-selection' THEN
      -- Natural Selection Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is natural selection?', 'តើការជ្រើសរើសធម្មជាតិគឺជាអ្វី?', 'Choose the best definition of natural selection.', 'ជ្រើសរើសនិយមន៍ល្អបំផុតនៃការជ្រើសរើសធម្មជាតិ។', '{"options_en": ["Process where organisms with favorable traits survive and reproduce", "Random changes in DNA", "Organisms choosing their traits", "Environmental changes"], "options_km": ["ដំណើរការដែលសារពាង្គកាយដែលមានលក្ខណៈល្អរស់នៅនិងបន្តពូជ", "ការផ្លាស់ប្តូរចៃដន្យនៅក្នុង DNA", "សារពាង្គកាយជ្រើសរើសលក្ខណៈរបស់ពួកគេ", "ការផ្លាស់ប្តូរបរិស្ថាន"]}', 'Process where organisms with favorable traits survive and reproduce', 10, 'easy', 'Think about survival of the fittest.', 'គិតអំពីការរស់រានមានជីវិតរបស់អ្នកខ្លាំងបំផុត។', 'Natural selection is the process by which organisms with traits better adapted to their environment tend to survive and reproduce more successfully.', 'ការជ្រើសរើសធម្មជាតិគឺជាដំណើរការដែលសារពាង្គកាយដែលមានលក្ខណៈសម្រប់បានល្អជាងនឹងបរិស្ថានរបស់ពួកគេមានទំនោររស់រានមានជីវិតនិងបន្តពូជបានជោគជ័យជាង។', true, true),
      (sim_id, teacher_id, 2, 'true_false', 'Environmental factors can influence which traits are advantageous.', 'កត្តាបរិស្ថានអាចជះឥទ្ធិពលដល់លក្ខណៈណាដែលមានប្រយោជន៍។', 'Consider how different environments favor different traits.', 'ពិចារណាអំពីរបៀបដែលបរិស្ថានផ្សេងៗគាំទ្រលក្ខណៈផ្សេងៗ។', 'true', 10, 'medium', 'Think about how climate affects survival.', 'គិតអំពីរបៀបដែលអាកាសធាតុប៉ះពាល់ដល់ការរស់រានមានជីវិត។', 'Environmental factors like climate, predators, and food availability determine which traits provide survival advantages.', 'កត្តាបរិស្ថានដូចជាអាកាសធាតុ សត្វមំសាសី និងភាពអាចរកបានអាហារកំណត់លក្ខណៈណាដែលផ្តល់នូវអត្ថប្រយោជន៍នៃការរស់រានមានជីវិត។', true, true),
      (sim_id, teacher_id, 3, 'short_answer', 'Describe how a population of rabbits might evolve over time in response to increased predation.', 'ពិពណ៌នាអំពីរបៀបដែលចំនួនកូនទន្សាយអាចវិវត្តតាមពេលវេលាដើម្បីឆ្លើយតបនឹងការកើនឡើងនៃការស៊ីចំណី។', 'Explain the evolutionary process step by step.', 'ពន្យល់ដំណើរការវិវត្តនីយកម្មជំហានម្តងៗ។', 20, 'hard', 'Think about which rabbit traits would help escape predators.', 'គិតអំពីលក្ខណៈកូនទន្សាយណាដែលនឹងជួយគេចពីសត្វមំសាសី។', 'Rabbits with advantageous traits like faster running, better camouflage, or sharper hearing would be more likely to survive and pass these traits to offspring, gradually increasing these traits in the population.', 'កូនទន្សាយដែលមានលក្ខណៈប្រយោជន៍ដូចជាការរត់លឿនជាង ការបិតបាំងល្អជាង ឬការស្តាប់ស្រួចស្រាវជាងនឹងមានលទ្ធភាពរស់រានមានជីវិតនិងបញ្ជូនលក្ខណៈទាំងនេះទៅកូនចៅ ដោយបង្កើនលក្ខណៈទាំងនេះនៅក្នុងចំនួនជនជាតិ។', true, true);

    ELSIF sim_record.simulation_name = 'food-chain' THEN
      -- Food Chain Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is a food chain?', 'តើខ្សែអាហារជាអ្វី?', 'Choose the best definition of a food chain.', 'ជ្រើសរើសនិយមន៍ល្អបំផុតនៃខ្សែអាហារ។', '{"options_en": ["A sequence showing energy flow through organisms", "A place where animals eat", "A type of plant", "A hunting method"], "options_km": ["លំដាប់បង្ហាញលំហូរថាមពលតាមរយៈសារពាង្គកាយ", "កន្លែងដែលសត្វញ៉ាំ", "ប្រភេទរុក្ខជាតិ", "វិធីសាស្ត្របរបាញ់"]}', 'A sequence showing energy flow through organisms', 10, 'easy', 'Think about how energy moves from one organism to another.', 'គិតអំពីរបៀបដែលថាមពលផ្លាស់ទីពីសារពាង្គកាយមួយទៅមួយទៀត។', 'A food chain shows the linear sequence of energy transfer from producers to consumers in an ecosystem.', 'ខ្សែអាហារបង្ហាញលំដាប់លីនេអ៊ែរនៃការផ្ទេរថាមពលពីអ្នកផលិតទៅអ្នកប្រើប្រាស់នៅក្នុងប្រព័ន្ធអេកូឡូស៊ី។', true, true),
      (sim_id, teacher_id, 2, 'multiple_choice', 'Which organisms are at the base of most food chains?', 'តើសារពាង្គកាយណាស្ថិតនៅបាតនៃខ្សែអាហារភាគច្រើន?', 'Identify the primary producers in food chains.', 'កំណត់អ្នកផលិតបឋមនៅក្នុងខ្សែអាហារ។', '{"options_en": ["Plants/Producers", "Carnivores", "Herbivores", "Decomposers"], "options_km": ["រុក្ខជាតិ/អ្នកផលិត", "សត្វស៊ីសាច់", "សត្វស៊ីស្មៅ", "អ្នករំលាយ"]}', 'Plants/Producers', 10, 'easy', 'Think about what makes their own food.', 'គិតអំពីអ្វីដែលបង្កើតអាហាររបស់ពួកគេផ្ទាល់។', 'Plants and other producers form the base of food chains because they convert solar energy into chemical energy through photosynthesis.', 'រុក្ខជាតិនិងអ្នកផលិតដទៃទៀតបង្កើតជាមូលដ្ឋាននៃខ្សែអាហារព្រោះពួកគេបំប្លែងថាមពលព្រះអាទិត្យទៅជាថាមពលគីមីតាមរយៈការសំយោគពន្លឺ។', true, true),
      (sim_id, teacher_id, 3, 'calculation', 'If there are 1000 plants, 100 herbivores, and 10 carnivores, what is the energy transfer efficiency between each level?', 'ប្រសិនបើមានរុក្ខជាតិ 1000 សត្វស៊ីស្មៅ 100 និងសត្វស៊ីសាច់ 10 តើអត្រាប្រសិទ្ធភាពផ្ទេរថាមពលរវាងកម្រិតនីមួយៗគឺប៉ុន្មាន?', 'Calculate the percentage of energy transferred between trophic levels.', 'គណនាភាគរយនៃថាមពលដែលផ្ទេររវាងកម្រិត trophic។', '10', '["10", "10%", "១០%"]', 15, 'medium', 'Divide the number at each level by the previous level.', 'ចែកចំនួននៅកម្រិតនីមួយៗដោយកម្រិតមុន។', 'Energy transfer efficiency is typically 10%: 100/1000 = 10% from plants to herbivores, and 10/100 = 10% from herbivores to carnivores.', 'ប្រសិទ្ធភាពផ្ទេរថាមពលជាធម្មតាគឺ 10%៖ 100/1000 = 10% ពីរុក្ខជាតិទៅសត្វស៊ីស្មៅ និង 10/100 = 10% ពីសត្វស៊ីស្មៅទៅសត្វស៊ីសាច់។', true, true);

    ELSIF sim_record.simulation_name = 'neuron-lab' THEN
      -- Neuron Lab Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is the resting potential of a typical neuron?', 'តើសក្តានុពលសម្រាករបស់ neuron ធម្មតាគឺប៉ុន្មាន?', 'Select the typical resting membrane potential.', 'ជ្រើសរើសសក្តានុពលភ្នាសកោសិកាសម្រាកធម្មតា។', '{"options_en": ["-70mV", "+30mV", "0mV", "-90mV"], "options_km": ["-70mV", "+30mV", "0mV", "-90mV"]}', '-70mV', 10, 'medium', 'Think about the negative charge inside the cell.', 'គិតអំពីបន្ទុកអវិជ្ជមាននៅខាងក្នុងកោសិកា។', 'The typical resting potential of a neuron is approximately -70mV due to the distribution of ions across the membrane.', 'សក្តានុពលសម្រាកធម្មតារបស់ neuron គឺប្រហែល -70mV ដោយសារការចែកចាយអ៊ីយ៉ុងនៅលើភ្នាសកោសិកា។', true, true),
      (sim_id, teacher_id, 2, 'true_false', 'An action potential travels in both directions along the axon.', 'សកម្មភាពសក្តានុពលធ្វើដំណើរក្នុងទិសទាំងពីរតាម axon។', 'Consider the direction of action potential propagation.', 'ពិចារណាអំពីទិសនៃការរីករាលដាលសកម្មភាពសក្តានុពល។', 'false', 10, 'medium', 'Think about the refractory period.', 'គិតអំពីកំឡុងពេល refractory។', 'Action potentials travel in only one direction due to the refractory period, which prevents backward propagation.', 'សកម្មភាពសក្តានុពលធ្វើដំណើរក្នុងទិសតែមួយដោយសារកំឡុងពេល refractory ដែលរារាំងការរីករាលដាលថយក្រោយ។', true, true),
      (sim_id, teacher_id, 3, 'short_answer', 'Explain how sodium and potassium ions contribute to the action potential.', 'ពន្យល់អំពីរបៀបដែលអ៊ីយ៉ុងសូដ្យូមនិងប៉ូតាស្យូមរួមចំណែកដល់សកម្មភាពសក្តានុពល។', 'Describe the role of these ions in neural signaling.', 'ពិពណ៌នាអំពីតួនាទីរបស់អ៊ីយ៉ុងទាំងនេះនៅក្នុងការផ្ញើសញ្ញា neural។', 20, 'hard', 'Think about depolarization and repolarization.', 'គិតអំពី depolarization និង repolarization។', 'Sodium influx causes depolarization (rising phase), while potassium efflux causes repolarization (falling phase) of the action potential.', 'ការហូរចូលសូដ្យូមបណ្តាលឱ្យ depolarization (ដំណាក់កាលកើនឡើង) ខណៈដែលការហូរចេញប៉ូតាស្យូមបណ្តាលឱ្យ repolarization (ដំណាក់កាលធ្លាក់ចុះ) នៃសកម្មភាពសក្តានុពល។', true, true);

    -- CHEMISTRY SIMULATIONS
    ELSIF sim_record.simulation_name = 'build-a-molecule' THEN
      -- Build a Molecule Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is a chemical bond?', 'តើសំណាប់គីមីគឺជាអ្វី?', 'Choose the best definition of a chemical bond.', 'ជ្រើសរើសនិយមន៍ល្អបំផុតនៃសំណាប់គីមី។', '{"options_en": ["Force holding atoms together", "Breaking apart of atoms", "Movement of atoms", "Color of molecules"], "options_km": ["កម្លាំងកាន់អាតូមទុកជាមួយគ្នា", "ការបំបែកអាតូម", "ចលនាអាតូម", "ពណ៌ម៉ូលេគុល"]}', 'Force holding atoms together', 10, 'easy', 'Think about what keeps atoms connected.', 'គិតអំពីអ្វីដែលរក្សាអាតូមឱ្យតភ្ជាប់គ្នា។', 'A chemical bond is the force of attraction that holds atoms together in molecules and compounds.', 'សំណាប់គីមីគឺជាកម្លាំងទាក់ទាញដែលកាន់អាតូមទុកជាមួយគ្នានៅក្នុងម៉ូលេគុលនិងសមាសធាតុ។', true, true),
      (sim_id, teacher_id, 2, 'multiple_choice', 'How many bonds can carbon typically form?', 'តើកាបូនអាចបង្កើតសំណាប់បានប៉ុន្មានជាធម្មតា?', 'Identify the bonding capacity of carbon.', 'កំណត់សមត្ថភាពភ្ជាប់របស់កាបូន។', '{"options_en": ["4", "2", "6", "8"], "options_km": ["4", "2", "6", "8"]}', '4', 10, 'easy', 'Think about carbon\'s valence electrons.', 'គិតអំពីអេឡិចត្រុង valence របស់កាបូន។', 'Carbon has 4 valence electrons and can form 4 covalent bonds with other atoms.', 'កាបូនមានអេឡិចត្រុង valence 4 និងអាចបង្កើតសំណាប់ covalent 4 ជាមួយអាតូមដទៃទៀត។', true, true),
      (sim_id, teacher_id, 3, 'calculation', 'If you have 2 hydrogen atoms and 1 oxygen atom, what molecule can you make?', 'ប្រសិនបើអ្នកមានអាតូមហ៊ីដ្រូសែន 2 និងអាតូមអុកស៊ីសែន 1 តើអ្នកអាចបង្កើតម៉ូលេគុលអ្វី?', 'Determine the molecular formula.', 'កំណត់រូបមន្តម៉ូលេគុល។', 'H2O', '["H2O", "Water", "ទឹក"]', 10, 'easy', 'Think about the most common compound with these atoms.', 'គិតអំពីសមាសធាតុទូទៅបំផុតដែលមានអាតូមទាំងនេះ។', 'Two hydrogen atoms and one oxygen atom combine to form water (H2O).', 'អាតូមហ៊ីដ្រូសែនពីរនិងអាតូមអុកស៊ីសែនមួយរួមគ្នាបង្កើតជាទឹក (H2O)។', true, true);

    ELSIF sim_record.simulation_name = 'ph-scale' THEN
      -- pH Scale Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What does pH measure?', 'តើ pH វាស់អ្វី?', 'Identify what the pH scale indicates.', 'កំណត់អ្វីដែលមាត្រដ្ឋាន pH បង្ហាញ។', '{"options_en": ["Acidity or alkalinity", "Temperature", "Pressure", "Volume"], "options_km": ["ភាពជូរឬអាល់កាឡាំង", "សីតុណ្ហភាព", "សម្ពាធ", "បរិមាត្រ"]}', 'Acidity or alkalinity', 10, 'easy', 'Think about acids and bases.', 'គិតអំពីអាស៊ីតនិងបេស។', 'pH measures the concentration of hydrogen ions, indicating how acidic or basic a solution is.', 'pH វាស់កំហាប់អ៊ីយ៉ុងហ៊ីដ្រូសែន ដោយបង្ហាញថាតើដំណោះស្រាយមួយមានជូរឬបេសប៉ុន្មាន។', true, true),
      (sim_id, teacher_id, 2, 'multiple_choice', 'A solution with pH 7 is considered:', 'ដំណោះស្រាយដែលមាន pH 7 ត្រូវបានចាត់ទុកថា៖', 'Identify the nature of a pH 7 solution.', 'កំណត់ធម្មជាតិនៃដំណោះស្រាយ pH 7។', '{"options_en": ["Neutral", "Acidic", "Basic", "Unknown"], "options_km": ["អព្យាក្រឹត", "ជូរ", "បេស", "មិនដឹង"]}', 'Neutral', 10, 'easy', 'Think about pure water.', 'គិតអំពីទឹកសុទ្ធ។', 'A pH of 7 is neutral, meaning the solution is neither acidic nor basic, like pure water.', 'pH នៃ 7 គឺអព្យាក្រឹត មានន័យថាដំណោះស្រាយមិនជូរហើយក៏មិនមែនបេសដូចជាទឹកសុទ្ធ។', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'Lower pH values indicate higher acidity.', 'តម្លៃ pH ទាបជាងបង្ហាញពីជូរខ្ពស់ជាង។', 'Consider the relationship between pH and acidity.', 'ពិចារណាអំពីទំនាក់ទំនងរវាង pH និងជូរ។', 'true', 10, 'medium', 'Think about the pH scale direction.', 'គិតអំពីទិសមាត្រដ្ឋាន pH។', 'The pH scale is inverse - lower numbers mean higher acidity, higher numbers mean higher alkalinity.', 'មាត្រដ្ឋាន pH គឺផ្ទុយ - លេខទាបមានន័យជូរខ្ពស់ លេខខ្ពស់មានន័យអាល់កាឡាំងខ្ពស់។', true, true);

    ELSIF sim_record.simulation_name = 'states-of-matter' THEN
      -- States of Matter Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What are the three main states of matter?', 'តើសភាពធម្មតាបីរបស់វត្ថុគឺអ្វីខ្លះ?', 'Identify the three primary phases of matter.', 'កំណត់ដំណាក់កាលបឋមបីនៃវត្ថុ។', '{"options_en": ["Solid, Liquid, Gas", "Hot, Cold, Warm", "Big, Medium, Small", "Fast, Slow, Still"], "options_km": ["រឹង រាវ ឧស្ម័ន", "ក្តៅ ត្រជាក់ កក់ក្តៅ", "ធំ មធ្យម តូច", "លឿន យឺត នឹង"]}', 'Solid, Liquid, Gas', 10, 'easy', 'Think about ice, water, and steam.', 'គិតអំពីទឹកកក ទឹក និងចំហាយទឹក។', 'The three main states of matter are solid, liquid, and gas, distinguished by molecular arrangement and movement.', 'សភាពធម្មតាបីរបស់វត្ថុគឺរឹង រាវ និងឧស្ម័ន ដែលត្រូវបានសម្គាល់ដោយការរៀបចំនិងចលនាម៉ូលេគុល។', true, true),
      (sim_id, teacher_id, 2, 'true_false', 'Heating a substance always increases its temperature.', 'ការកំដៅវត្ថុតែងតែបង្កើនសីតុណ្ហភាពរបស់វា។', 'Consider what happens during phase changes.', 'ពិចារណាអំពីអ្វីដែលកើតឡើងអំឡុងពេលការផ្លាស់ប្តូរដំណាក់កាល។', 'false', 15, 'medium', 'Think about melting and boiling points.', 'គិតអំពីចំណុចរលាយនិងចំណុចស្ទុះ។', 'During phase changes (melting, boiling), added heat energy goes into breaking bonds rather than increasing temperature.', 'កំឡុងពេលការផ្លាស់ប្តូរដំណាក់កាល (រលាយ ស្ទុះ) ថាមពលកំដៅដែលបន្ថែមចូលទៅក្នុងការបំបែកសំណាប់ជាជាងការបង្កើនសីតុណ្ហភាព។', true, true),
      (sim_id, teacher_id, 3, 'short_answer', 'Explain what happens to water molecules when water changes from liquid to gas.', 'ពន្យល់អំពីអ្វីដែលកើតឡើងចំពោះម៉ូលេគុលទឹកនៅពេលទឹកផ្លាស់ប្តូរពីរាវទៅឧស្ម័ន។', 'Describe the molecular changes during evaporation.', 'ពិពណ៌នាអំពីការផ្លាស់ប្តូរម៉ូលេគុលអំឡុងពេលហួត។', 15, 'medium', 'Think about molecular movement and energy.', 'គិតអំពីចលនានិងថាមពលម៉ូលេគុល។', 'Water molecules gain kinetic energy, move faster, and overcome intermolecular forces to escape the liquid phase and become gas.', 'ម៉ូលេគុលទឹកទទួលបានថាមពលកាយនិទាគ ផ្លាស់ទីលឿនជាង និងយកឈ្នះលើកម្លាំងរវាងម៉ូលេគុលដើម្បីគេចពីដំណាក់កាលរាវនិងក្លាយជាឧស្ម័ន។', true, true);

    ELSIF sim_record.simulation_name = 'concentration-lab' THEN
      -- Concentration Lab Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is molarity?', 'តើ molarity គឺជាអ្វី?', 'Define the concept of molarity.', 'កំណត់គំនិតនៃ molarity។', '{"options_en": ["Moles of solute per liter of solution", "Grams per milliliter", "Percentage by weight", "Temperature measurement"], "options_km": ["ម៉ុលនៃ solute ក្នុងមួយលីត្រនៃដំណោះស្រាយ", "ក្រាមក្នុងមួយមីលីលីត្រ", "ភាគរយតាមទម្ងន់", "ការវាស់សីតុណ្ហភាព"]}', 'Moles of solute per liter of solution', 15, 'medium', 'Think about the units of concentration.', 'គិតអំពីឯកតានៃកំហាប់។', 'Molarity is defined as the number of moles of solute dissolved in one liter of solution.', 'Molarity ត្រូវបានកំណត់ថាជាចំនួនម៉ុលនៃ solute ដែលរលាយនៅក្នុងដំណោះស្រាយមួយលីត្រ។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'If you dissolve 2 moles of salt in 4 liters of water, what is the molarity?', 'ប្រសិនបើអ្នករលាយអំបិល 2 ម៉ុលនៅក្នុងទឹក 4 លីត្រ តើ molarity គឺប៉ុន្មាន?', 'Calculate the molarity of the solution.', 'គណនា molarity នៃដំណោះស្រាយ។', '0.5', '["0.5", "0.5 M", "០.៥"]', 15, 'medium', 'Molarity = moles ÷ liters', 'Molarity = ម៉ុល ÷ លីត្រ', 'Molarity = 2 moles ÷ 4 liters = 0.5 M', 'Molarity = 2 ម៉ុល ÷ 4 លីត្រ = 0.5 M', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'Dilution decreases the concentration of a solution.', 'ការបន្ថយកំហាប់បន្ថយកំហាប់នៃដំណោះស្រាយ។', 'Consider what happens when you add more solvent.', 'ពិចារណាអំពីអ្វីដែលកើតឡើងនៅពេលអ្នកបន្ថែម solvent បន្ថែម។', 'true', 10, 'easy', 'Think about adding water to a concentrated solution.', 'គិតអំពីការបន្ថែមទឹកទៅដំណោះស្រាយប្រមូលផ្តុំ។', 'Adding more solvent (like water) to a solution increases the total volume while keeping the amount of solute constant, thus decreasing concentration.', 'ការបន្ថែម solvent បន្ថែម (ដូចជាទឹក) ទៅដំណោះស្រាយបង្កើនបរិមាត្រសរុបខណៈដែលរក្សាបរិមាណ solute ថេរ ដូច្នេះបន្ថយកំហាប់។', true, true);

    -- MATHEMATICS SIMULATIONS
    ELSIF sim_record.simulation_name = 'function-builder' THEN
      -- Function Builder Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is a function in mathematics?', 'តើអនុគមន៍គណិតវិទ្យាគឺជាអ្វី?', 'Choose the best definition of a mathematical function.', 'ជ្រើសរើសនិយមន៍ល្អបំផុតនៃអនុគមន៍គណិតវិទ្យា។', '{"options_en": ["A rule that assigns each input exactly one output", "A random number generator", "A type of equation", "A graph with curves"], "options_km": ["ច្បាប់ដែលកំណត់ការបញ្ចូលនីមួយៗមានលទ្ធផលតែមួយ", "ម៉ាស៊ីនបង្កើតលេខចៃដន្យ", "ប្រភេទសមីការ", "ក្រាហ្វដែលមានខ្សែកោង"]}', 'A rule that assigns each input exactly one output', 10, 'medium', 'Think about input and output relationships.', 'គិតអំពីទំនាក់ទំនងបញ្ចូលនិងលទ្ធផល។', 'A function is a mathematical relationship where each input value corresponds to exactly one output value.', 'អនុគមន៍គឺជាទំនាក់ទំនងគណិតវិទ្យាដែលតម្លៃបញ្ចូលនីមួយៗទាក់ទងនឹងតម្លៃលទ្ធផលតែមួយ។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'If f(x) = 2x + 3, what is f(5)?', 'ប្រសិនបើ f(x) = 2x + 3 តើ f(5) គឺប៉ុន្មាន?', 'Substitute x = 5 into the function.', 'ជំនួស x = 5 ចូលក្នុងអនុគមន៍។', '13', '["13", "១៣"]', 10, 'easy', 'Replace x with 5 and calculate.', 'ជំនួស x ដោយ 5 ហើយគណនា។', 'f(5) = 2(5) + 3 = 10 + 3 = 13', 'f(5) = 2(5) + 3 = 10 + 3 = 13', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'A vertical line can intersect the graph of a function at most once.', 'បន្ទាត់បញ្ឈរអាចកាត់ក្រាហ្វនៃអនុគមន៍បានច្រើនបំផុតម្តង។', 'Consider the vertical line test for functions.', 'ពិចារណាការធ្វើតេស្តបន្ទាត់បញ្ឈរសម្រាប់អនុគមន៍។', 'true', 15, 'medium', 'Think about the definition of a function.', 'គិតអំពីនិយមន៍នៃអនុគមន៍។', 'This is the vertical line test - if any vertical line intersects a graph more than once, it is not a function.', 'នេះគឺជាការធ្វើតេស្តបន្ទាត់បញ្ឈរ - ប្រសិនបើបន្ទាត់បញ្ឈរណាមួយកាត់ក្រាហ្វច្រើនជាងម្តង វាមិនមែនជាអនុគមន៍ទេ។', true, true);

    ELSIF sim_record.simulation_name = 'graphing-lines' THEN
      -- Graphing Lines Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What does the slope of a line represent?', 'តើបម្រេនបន្ទាត់តំណាងឱ្យអ្វី?', 'Identify what slope measures in a linear graph.', 'កំណត់អ្វីដែលបម្រេនវាស់នៅក្នុងក្រាហ្វលីនេអ៊ែរ។', '{"options_en": ["Rate of change", "Starting point", "Length of line", "Color intensity"], "options_km": ["អត្រាផ្លាស់ប្តូរ", "ចំណុចចាប់ផ្តើម", "ប្រវែងបន្ទាត់", "ពណ៌ក្រាស់"]}', 'Rate of change', 10, 'easy', 'Think about rise over run.', 'គិតអំពីការកើនលើការដំណើរ។', 'Slope represents the rate of change - how much y changes for each unit change in x.', 'បម្រេនតំណាងឱ្យអត្រាផ្លាស់ប្តូរ - y ផ្លាស់ប្តូរប៉ុន្មានសម្រាប់ការផ្លាស់ប្តូរឯកតាមួយនៅ x។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'What is the slope of a line passing through points (2,3) and (4,7)?', 'តើបម្រេននៃបន្ទាត់ដែលកាត់ចំណុច (2,3) និង (4,7) គឺប៉ុន្មាន?', 'Use the slope formula: (y2-y1)/(x2-x1)', 'ប្រើរូបមន្តបម្រេន៖ (y2-y1)/(x2-x1)', '2', '["2", "២"]', 15, 'medium', 'Calculate the change in y over change in x.', 'គណនាការផ្លាស់ប្តូរ y លើការផ្លាស់ប្តូរ x។', 'Slope = (7-3)/(4-2) = 4/2 = 2', 'បម្រេន = (7-3)/(4-2) = 4/2 = 2', true, true),
      (sim_id, teacher_id, 3, 'multiple_choice', 'What is the y-intercept of the line y = 3x + 5?', 'តើ y-intercept នៃបន្ទាត់ y = 3x + 5 គឺប៉ុន្មាន?', 'Identify where the line crosses the y-axis.', 'កំណត់កន្លែងដែលបន្ទាត់កាត់ប័ក្ស y។', '{"options_en": ["5", "3", "0", "8"], "options_km": ["5", "3", "0", "8"]}', '5', 10, 'easy', 'Look at the constant term in the equation.', 'មើលពាក្យថេរនៅក្នុងសមីការ។', 'In the form y = mx + b, the y-intercept is b, which is 5 in this equation.', 'នៅក្នុងទម្រង់ y = mx + b, y-intercept គឺ b ដែលគឺ 5 នៅក្នុងសមីការនេះ។', true, true);

    ELSIF sim_record.simulation_name = 'fraction-matcher' THEN
      -- Fraction Matcher Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'Which fraction is equivalent to 1/2?', 'តើប្រភាគណាស្មើនឹង 1/2?', 'Find the equivalent fraction.', 'រកប្រភាគស្មើគ្នា។', '{"options_en": ["2/4", "1/3", "3/5", "2/3"], "options_km": ["2/4", "1/3", "3/5", "2/3"]}', '2/4', 10, 'easy', 'Think about equivalent fractions.', 'គិតអំពីប្រភាគស្មើគ្នា។', '2/4 equals 1/2 because both numerator and denominator are multiplied by 2.', '2/4 ស្មើនឹង 1/2 ព្រោះទាំងភាគបែងនិងភាគទាប់ត្រូវបានគុណដោយ 2។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'What is 1/4 + 1/4?', 'តើ 1/4 + 1/4 គឺប៉ុន្មាន?', 'Add the fractions with same denominators.', 'បូកប្រភាគដែលមានភាគទាប់ដូចគ្នា។', '1/2', '["1/2", "2/4", "០.៥"]', 10, 'easy', 'Add the numerators, keep the denominator.', 'បូកភាគបែង រក្សាភាគទាប់។', '1/4 + 1/4 = 2/4 = 1/2', '1/4 + 1/4 = 2/4 = 1/2', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'The fraction 3/6 can be simplified to 1/2.', 'ប្រភាគ 3/6 អាចធ្វើឱ្យសាមញ្ញទៅជា 1/2។', 'Determine if the fraction can be reduced.', 'កំណត់ថាតើប្រភាគអាចត្រូវបានកាត់បន្ថយបានទេ។', 'true', 10, 'easy', 'Find the greatest common factor.', 'រកកត្តាទូទៅធំបំផុត។', '3/6 = 1/2 because both 3 and 6 can be divided by 3.', '3/6 = 1/2 ព្រោះទាំង 3 និង 6 អាចត្រូវបានចែកដោយ 3។', true, true);

    ELSIF sim_record.simulation_name = 'area-builder' THEN
      -- Area Builder Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is the formula for the area of a rectangle?', 'តើរូបមន្តសម្រាប់ផ្ទៃដីរបស់ចតុកោណកែងគឺជាអ្វី?', 'Choose the correct area formula.', 'ជ្រើសរើសរូបមន្តផ្ទៃដីត្រឹមត្រូវ។', '{"options_en": ["Length × Width", "2 × (Length + Width)", "Length + Width", "Length ÷ Width"], "options_km": ["ប្រវែង × ទទឹង", "2 × (ប្រវែង + ទទឹង)", "ប្រវែង + ទទឹង", "ប្រវែង ÷ ទទឹង"]}', 'Length × Width', 10, 'easy', 'Think about covering a surface with unit squares.', 'គិតអំពីការគ្របដណ្តប់ពីលើដោយការ៉េឯកតា។', 'The area of a rectangle is calculated by multiplying its length by its width.', 'ផ្ទៃដីរបស់ចតុកោណកែងត្រូវបានគណនាដោយគុណប្រវែងដោយទទឹងរបស់វា។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'What is the area of a rectangle with length 6 units and width 4 units?', 'តើផ្ទៃដីរបស់ចតុកោណកែងដែលមានប្រវែង 6 ឯកតានិងទទឹង 4 ឯកតាគឺប៉ុន្មាន?', 'Calculate the area using the formula.', 'គណនាផ្ទៃដីដោយប្រើរូបមន្ត។', '24', '["24", "២៤", "24 square units"]', 10, 'easy', 'Multiply length by width.', 'គុណប្រវែងដោយទទឹង។', 'Area = 6 × 4 = 24 square units', 'ផ្ទៃដី = 6 × 4 = 24 ឯកតាការ៉េ', true, true),
      (sim_id, teacher_id, 3, 'multiple_choice', 'What happens to the area if you double both the length and width of a rectangle?', 'តើមានអ្វីកើតឡើងចំពោះផ្ទៃដីប្រសិនបើអ្នកទ្វេដងទាំងប្រវែងនិងទទឹងរបស់ចតុកោណកែង?', 'Consider how scaling affects area.', 'ពិចារណាអំពីរបៀបដែលការធ្វើមាត្រដ្ឋានប៉ះពាល់ដល់ផ្ទៃដី។', '{"options_en": ["Area becomes 4 times larger", "Area doubles", "Area stays the same", "Area becomes 3 times larger"], "options_km": ["ផ្ទៃដីធំឡើង 4 ដង", "ផ្ទៃដីកើនទ្វេដង", "ផ្ទៃដីនៅដដែល", "ផ្ទៃដីធំឡើង 3 ដង"]}', 'Area becomes 4 times larger', 15, 'medium', 'Think about (2×L) × (2×W).', 'គិតអំពី (2×L) × (2×W)។', 'When both dimensions are doubled, the new area is (2L) × (2W) = 4LW, which is 4 times the original area.', 'នៅពេលរង្វាស់ទាំងពីរត្រូវបានទ្វេដង ផ្ទៃដីថ្មីគឺ (2L) × (2W) = 4LW ដែលគឺ 4 ដងនៃផ្ទៃដីដើម។', true, true);

    ELSIF sim_record.simulation_name = 'trigonometry-tour' THEN
      -- Trigonometry Tour Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is the definition of sine in a right triangle?', 'តើនិយមន៍នៃសីនុសនៅក្នុងត្រីកោណកែងគឺជាអ្វី?', 'Choose the correct definition of sine.', 'ជ្រើសរើសនិយមន៍ត្រឹមត្រូវនៃសីនុស។', '{"options_en": ["Opposite / Hypotenuse", "Adjacent / Hypotenuse", "Opposite / Adjacent", "Hypotenuse / Opposite"], "options_km": ["ម្ខាងទល់មុខ / ម្ខាងតេរ", "ម្ខាងជាប់ / ម្ខាងតេរ", "ម្ខាងទល់មុខ / ម្ខាងជាប់", "ម្ខាងតេរ / ម្ខាងទល់មុខ"]}', 'Opposite / Hypotenuse', 15, 'medium', 'Remember SOH-CAH-TOA.', 'ចូរចាំ SOH-CAH-TOA។', 'Sine is defined as the ratio of the opposite side to the hypotenuse in a right triangle.', 'សីនុសត្រូវបានកំណត់ថាជាសមាមាត្រនៃម្ខាងទល់មុខទៅម្ខាងតេរនៅក្នុងត្រីកោណកែង។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'What is sin(30°)?', 'តើ sin(30°) គឺប៉ុន្មាន?', 'Find the sine of 30 degrees.', 'រកសីនុសនៃ 30 ដឺក្រេ។', '0.5', '["0.5", "1/2", "០.៥"]', 15, 'medium', 'This is a special angle value.', 'នេះគឺជាតម្លៃមុំពិសេស។', 'sin(30°) = 1/2 = 0.5. This is one of the standard trigonometric values.', 'sin(30°) = 1/2 = 0.5។ នេះគឺជាតម្លៃត្រីកោណមាត្រស្តង់ដារមួយ។', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'The sine function has a period of 360° (or 2π radians).', 'អនុគមន៍សីនុសមានកំឡុងពេល 360° (ឬ 2π រ៉ាដ្យាន)។', 'Consider the repeating pattern of the sine function.', 'ពិចារណាលំនាំធ្វើម្តងទៀតនៃអនុគមន៍សីនុស។', 'true', 10, 'medium', 'Think about the unit circle.', 'គិតអំពីរង្វង់ឯកតា។', 'The sine function repeats its values every 360° (2π radians), making this its period.', 'អនុគមន៍សីនុសធ្វើម្តងទៀតតម្លៃរបស់វារៀងរាល់ 360° (2π រ៉ាដ្យាន) ធ្វើឱ្យនេះជាកំឡុងពេលរបស់វា។', true, true);

    -- REMAINING PHYSICS SIMULATIONS
    ELSIF sim_record.simulation_name = 'circuit-construction-kit' THEN
      -- Circuit Construction Kit Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is electric current?', 'តើចរន្តអគ្គិសនីគឺជាអ្វី?', 'Define electric current.', 'កំណត់ចរន្តអគ្គិសនី។', '{"options_en": ["Flow of electric charge", "Stored electrical energy", "Resistance to electricity", "Magnetic field strength"], "options_km": ["លំហូរបន្ទុកអគ្គិសនី", "ថាមពលអគ្គិសនីដែលរក្សាទុក", "ធន់នឹងអគ្គិសនី", "កម្លាំងដែនម៉ាញ៉េទិក"]}', 'Flow of electric charge', 10, 'easy', 'Think about electrons moving through a wire.', 'គិតអំពីអេឡិចត្រុងដែលផ្លាស់ទីតាមរយៈខ្សែភ្លើង។', 'Electric current is the flow of electric charge, typically electrons, through a conductor.', 'ចរន្តអគ្គិសនីគឺជាលំហូរបន្ទុកអគ្គិសនី ដែលជាធម្មតាអេឡិចត្រុង តាមរយៈអ្នកនាំ។', true, true),
      (sim_id, teacher_id, 2, 'multiple_choice', 'What happens to current in a series circuit?', 'តើមានអ្វីកើតឡើងចំពោះចរន្តនៅក្នុងសៀគ្វីស៊េរី?', 'Describe current behavior in series circuits.', 'ពិពណ៌នាអំពីឥរិយាបថចរន្តនៅក្នុងសៀគ្វីស៊េរី។', '{"options_en": ["Same everywhere", "Decreases through each component", "Increases through each component", "Changes randomly"], "options_km": ["ដូចគ្នានៅគ្រប់ទីកន្លែង", "ថយចុះតាមរយៈធាតុផ្សំនីមួយៗ", "កើនឡើងតាមរយៈធាតុផ្សំនីមួយៗ", "ផ្លាស់ប្តូរដោយចៃដន្យ"]}', 'Same everywhere', 15, 'medium', 'Think about conservation of charge.', 'គិតអំពីការរក្សាបន្ទុក។', 'In a series circuit, current is the same everywhere because charge cannot accumulate at any point.', 'នៅក្នុងសៀគ្វីស៊េរី ចរន្តគឺដូចគ្នានៅគ្រប់ទីកន្លែងព្រោះបន្ទុកមិនអាចប្រមូលផ្តុំនៅចំណុចណាមួយបានទេ។', true, true),
      (sim_id, teacher_id, 3, 'calculation', 'If a circuit has a 12V battery and a 4Ω resistor, what is the current?', 'ប្រសិនបើសៀគ្វីមួយមានថ្ម 12V និងធន់ 4Ω តើចរន្តគឺប៉ុន្មាន?', 'Use Ohm\'s Law to calculate current.', 'ប្រើច្បាប់ Ohm ដើម្បីគណនាចរន្ត។', '3', '["3", "3A", "៣"]', 15, 'medium', 'Use V = I × R, solve for I.', 'ប្រើ V = I × R, ដោះស្រាយសម្រាប់ I។', 'Using Ohm\'s Law: I = V/R = 12V/4Ω = 3A', 'ប្រើច្បាប់ Ohm៖ I = V/R = 12V/4Ω = 3A', true, true);

    ELSIF sim_record.simulation_name = 'wave-interference' THEN
      -- Wave Interference Exercises  
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What happens when two waves with the same frequency and amplitude meet in phase?', 'តើមានអ្វីកើតឡើងនៅពេលរលកពីរដែលមានប្រេកង់និងទំហំដូចគ្នាជួបគ្នានៅក្នុងដំណាក់កាល?', 'Describe constructive interference.', 'ពិពណ៌នាអំពីការរំខានបង្កើត។', '{"options_en": ["Constructive interference - amplitude doubles", "Destructive interference - waves cancel", "No change occurs", "Waves reflect backwards"], "options_km": ["ការរំខានបង្កើត - ទំហំកើនទ្វេដង", "ការរំខានបំផ្លាញ - រលកលុបចោល", "គ្មានការផ្លាស់ប្តូរកើតឡើង", "រលកឆ្លុះថយក្រោយ"]}', 'Constructive interference - amplitude doubles', 15, 'medium', 'Think about waves adding together.', 'គិតអំពីរលកបូកគ្នា។', 'When waves meet in phase, their amplitudes add together, creating constructive interference with doubled amplitude.', 'នៅពេលរលកជួបគ្នានៅក្នុងដំណាក់កាល ទំហំរបស់ពួកគេបូកគ្នា បង្កើតការរំខានបង្កើតដែលមានទំហំទ្វេដង។', true, true),
      (sim_id, teacher_id, 2, 'true_false', 'Wave interference only occurs with water waves.', 'ការរំខានរលកកើតឡើងតែជាមួយរលកទឹកប៉ុណ្ណោះ។', 'Consider different types of waves that can interfere.', 'ពិចារណាប្រភេទរលកផ្សេងៗដែលអាចរំខាន។', 'false', 10, 'easy', 'Think about sound and light waves.', 'គិតអំពីរលកសំឡេងនិងពន្លឺ។', 'Wave interference occurs with all types of waves including sound, light, water, and radio waves.', 'ការរំខានរលកកើតឡើងជាមួយរលកគ្រប់ប្រភេទរួមទាំងសំឡេង ពន្លឺ ទឹក និងរលករេឌីយ៉ូ។', true, true),
      (sim_id, teacher_id, 3, 'short_answer', 'Explain what creates the interference pattern in a double-slit experiment.', 'ពន្យល់អំពីអ្វីដែលបង្កើតលំនាំការរំខាននៅក្នុងការពិសោធន៍ចំហៀងទ្វេ។', 'Describe the physics behind the double-slit pattern.', 'ពិពណ៌នាអំពីរូបវិទ្យានៅពីក្រោយលំនាំចំហៀងទ្វេ។', 20, 'hard', 'Think about waves from each slit interfering.', 'គិតអំពីរលកពីចំហៀងនីមួយៗរំខាន។', 'Light passing through two slits creates two coherent wave sources that interfere with each other, producing alternating bright and dark bands.', 'ពន្លឺដែលឆ្លងកាត់ចំហៀងពីរបង្កើតប្រភពរលកស្របពីរដែលរំខានគ្នា បង្កើតក្រុមភ្លឺនិងងងឹតឆ្លាស់គ្នា។', true, true);

    ELSIF sim_record.simulation_name = 'energy-skate-park' THEN
      -- Energy Skate Park Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What type of energy does a skater have at the top of a ramp?', 'តើអ្នករំកិលមានថាមពលប្រភេទអ្វីនៅលើកំពូលកន្លែងរំកិល?', 'Identify the energy type at maximum height.', 'កំណត់ប្រភេទថាមពលនៅកម្ពស់អតិបរមា។', '{"options_en": ["Potential energy", "Kinetic energy", "Heat energy", "Sound energy"], "options_km": ["ថាមពលសក្តានុពល", "ថាមពលកាយនិទាគ", "ថាមពលកំដៅ", "ថាមពលសំឡេង"]}', 'Potential energy', 10, 'easy', 'Think about stored energy due to position.', 'គិតអំពីថាមពលដែលរក្សាទុកដោយសារទីតាំង។', 'At the top of the ramp, the skater has maximum potential energy due to their elevated position.', 'នៅលើកំពូលកន្លែងរំកិល អ្នករំកិលមានថាមពលសក្តានុពលអតិបរមាដោយសារទីតាំងខ្ពស់របស់ពួកគេ។', true, true),
      (sim_id, teacher_id, 2, 'true_false', 'Energy is conserved in the skate park (ignoring friction).', 'ថាមពលត្រូវបានរក្សានៅក្នុងកន្លែងរំកិល (មិនគិតការកកកំទេច)។', 'Consider the principle of energy conservation.', 'ពិចារណាគោលការណ៍នៃការរក្សាថាមពល។', 'true', 15, 'medium', 'Think about potential + kinetic = constant.', 'គិតអំពីសក្តានុពល + កាយនិទាគ = ថេរ។', 'The total mechanical energy (potential + kinetic) remains constant throughout the motion when friction is ignored.', 'ថាមពលមេកានិកសរុប (សក្តានុពល + កាយនិទាគ) នៅថេរពេញមួយចលនានៅពេលការកកកំទេចត្រូវបានមិនអើពើ។', true, true),
      (sim_id, teacher_id, 3, 'calculation', 'If a 50kg skater is 10m high and has 200J of kinetic energy, what is their total energy?', 'ប្រសិនបើអ្នករំកិល 50kg មានកម្ពស់ 10m និងមានថាមពលកាយនិទាគ 200J តើថាមពលសរុបរបស់ពួកគេគឺប៉ុន្មាន?', 'Calculate total mechanical energy.', 'គណនាថាមពលមេកានិកសរុប។', '5100', '["5100", "5100J", "៥១០០J"]', 20, 'hard', 'Total = Potential + Kinetic, PE = mgh', 'សរុប = សក្តានុពល + កាយនិទាគ, PE = mgh', 'PE = mgh = 50 × 10 × 10 = 5000J, Total = 5000J + 200J = 5100J', 'PE = mgh = 50 × 10 × 10 = 5000J, សរុប = 5000J + 200J = 5100J', true, true);

    ELSIF sim_record.simulation_name = 'forces-and-motion' THEN
      -- Forces and Motion Exercises
      INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km, is_required, is_active) VALUES
      (sim_id, teacher_id, 1, 'multiple_choice', 'What is Newton\'s First Law of Motion?', 'តើច្បាប់ចលនាទីមួយរបស់ Newton គឺជាអ្វី?', 'Choose the correct statement of Newton\'s First Law.', 'ជ្រើសរើសសេចក្តីថ្លែងត្រឹមត្រូវនៃច្បាប់ទីមួយរបស់ Newton។', '{"options_en": ["An object at rest stays at rest unless acted upon by a force", "Force equals mass times acceleration", "For every action there is an equal and opposite reaction", "Energy cannot be created or destroyed"], "options_km": ["វត្ថុដែលនៅទីកន្លែងនឹងនៅទីកន្លែងលុះត្រាតែមានកម្លាំងប៉ះពាល់", "កម្លាំងស្មើម៉ាស់គុណនឹងការពន្លឿន", "សម្រាប់សកម្មភាពនីមួយៗមានប្រតិកម្មស្មើនិងផ្ទុយ", "ថាមពលមិនអាចត្រូវបានបង្កើតឬបំផ្លាញបានទេ"]}', 'An object at rest stays at rest unless acted upon by a force', 10, 'medium', 'Think about inertia.', 'គិតអំពីអង់ស៊ី។', 'Newton\'s First Law, also called the law of inertia, states that objects tend to maintain their state of motion unless acted upon by an unbalanced force.', 'ច្បាប់ទីមួយរបស់ Newton ដែលហៅផងដែរថាច្បាប់អង់ស៊ី ចែងថាវត្ថុមានទំនោររក្សាស្ថានភាពចលនារបស់ពួកគេលុះត្រាតែត្រូវបានគេធ្វើសកម្មភាពដោយកម្លាំងមិនតុល្យភាព។', true, true),
      (sim_id, teacher_id, 2, 'calculation', 'What force is needed to accelerate a 10kg object at 5 m/s²?', 'តើកម្លាំងប៉ុន្មានត្រូវការដើម្បីពន្លឿនវត្ថុ 10kg នៅ 5 m/s²?', 'Use F = ma to calculate the force.', 'ប្រើ F = ma ដើម្បីគណនាកម្លាំង។', '50', '["50", "50N", "៥០N"]', 15, 'easy', 'Force = mass × acceleration', 'កម្លាំង = ម៉ាស់ × ការពន្លឿន', 'F = ma = 10 kg × 5 m/s² = 50 N', 'F = ma = 10 kg × 5 m/s² = 50 N', true, true),
      (sim_id, teacher_id, 3, 'true_false', 'Friction always opposes motion.', 'ការកកកំទេចតែងតែប្រឆាំងនឹងចលនា។', 'Consider the direction of friction force.', 'ពិចារណាទិសនៃកម្លាំងកកកំទេច។', 'true', 10, 'easy', 'Think about which direction friction acts.', 'គិតអំពីទិសណាដែលការកកកំទេចធ្វើសកម្មភាព។', 'Friction force always acts in the direction opposite to the motion or intended motion of an object.', 'កម្លាំងកកកំទេចតែងតែធ្វើសកម្មភាពក្នុងទិសផ្ទុយនឹងចលនាឬចលនាដែលបានបំពាក់នៃវត្ថុ។', true, true);

    END IF;

    RAISE NOTICE 'Added exercises for simulation: %', sim_record.simulation_name;
  END LOOP;

  RAISE NOTICE 'Completed adding exercises for all simulations that were missing them.';
END $$;