-- Complete PhET Khmer Simulations Insert Script
-- This script adds all remaining simulations to the database

-- First, let's check what we already have
-- Already inserted (20 simulations):
-- Physics: forces-and-motion-basics, energy-skate-park-basics, gravity-and-orbits, pendulum-lab, projectile-motion, plate-tectonics, greenhouse-effect
-- Chemistry: build-an-atom, balancing-chemical-equations, ph-scale-basics, states-of-matter-basics, concentration
-- Biology: natural-selection, gene-expression-essentials, neuron
-- Mathematics: area-builder, fraction-matcher, graphing-lines, arithmetic, function-builder

-- Insert all remaining simulations
INSERT INTO stem_simulations_catalog (
    simulation_name,
    display_name_en,
    display_name_km,
    description_en,
    description_km,
    subject_area,
    difficulty_level,
    grade_levels,
    estimated_duration,
    learning_objectives_en,
    learning_objectives_km,
    simulation_url,
    preview_image,
    tags,
    is_featured,
    is_active
) VALUES 

-- PHYSICS SIMULATIONS (Additional 38)
('models-of-the-hydrogen-atom', 'Models of the Hydrogen Atom', 'គំរូនៃអាតូមអ៊ីដ្រូសែន', 'How did scientists figure out the structure of atoms? Try different models by shooting light at the atom.', 'តើអ្នកវិទ្យាសាស្ត្ររកឃើញរចនាសម្ព័ន្ធអាតូមដោយរបៀបណា? សាកល្បងគំរូផ្សេងៗដោយបាញ់ពន្លឺទៅអាតូម។', 'Physics', 'Advanced', '{11,12}', 45, '{"Understand atomic models", "Learn quantum mechanics", "Explore light-matter interaction"}', '{"យល់ដឹងពីគំរូអាតូម", "រៀនមេកានិចកង់ទិច", "ស្វែងយល់អន្តរកម្មពន្លឺ-សារធាតុ"}', 'https://phet.colorado.edu/sims/html/models-of-the-hydrogen-atom/latest/models-of-the-hydrogen-atom_km.html', 'https://phet.colorado.edu/sims/html/models-of-the-hydrogen-atom/latest/models-of-the-hydrogen-atom-600.png', '{"physics", "quantum", "atom", "hydrogen"}', false, true),

('buoyancy', 'Buoyancy', 'កម្លាំងរំកិល', 'When will objects float and when will they sink? Learn how buoyancy works.', 'តើវត្ថុអណ្តែតនៅពេលណា និងលិចនៅពេលណា? រៀនពីរបៀបដែលកម្លាំងរំកិលដំណើរការ។', 'Physics', 'Intermediate', '{8,9,10,11}', 35, '{"Understand buoyancy", "Learn Archimedes principle", "Explore density"}', '{"យល់ដឹងពីកម្លាំងរំកិល", "រៀនគោលការណ៍អាកីមេដ", "ស្វែងយល់ដង់ស៊ីតេ"}', 'https://phet.colorado.edu/sims/html/buoyancy/latest/buoyancy_km.html', 'https://phet.colorado.edu/sims/html/buoyancy/latest/buoyancy-600.png', '{"physics", "buoyancy", "density", "float"}', true, true),

('generator', 'Generator', 'ម៉ាស៊ីនភ្លើង', 'Generate electricity with a bar magnet!', 'បង្កើតអគ្គិសនីជាមួយដែកអំបៅ!', 'Physics', 'Intermediate', '{9,10,11,12}', 30, '{"Understand electromagnetic induction", "Learn generator principles"}', '{"យល់ដឹងពីអាំងឌុចស្យុងអេឡិចត្រូម៉ាញេទិច", "រៀនគោលការណ៍ម៉ាស៊ីនភ្លើង"}', 'https://phet.colorado.edu/sims/html/generator/latest/generator_km.html', 'https://phet.colorado.edu/sims/html/generator/latest/generator-600.png', '{"physics", "generator", "electricity", "magnetism"}', false, true),

('magnets-and-electromagnets', 'Magnets and Electromagnets', 'ដែកអំបៅ និងអេឡិចត្រូម៉ាញេទិច', 'Explore the interactions between a compass and bar magnet.', 'ស្វែងយល់អន្តរកម្មរវាងត្រីវិស័យ និងដែកអំបៅ។', 'Physics', 'Intermediate', '{8,9,10,11}', 35, '{"Understand magnetism", "Create electromagnets"}', '{"យល់ដឹងពីម៉ាញេទិច", "បង្កើតអេឡិចត្រូម៉ាញេទិច"}', 'https://phet.colorado.edu/sims/html/magnets-and-electromagnets/latest/magnets-and-electromagnets_km.html', 'https://phet.colorado.edu/sims/html/magnets-and-electromagnets/latest/magnets-and-electromagnets-600.png', '{"physics", "magnets", "electromagnets"}', true, true),

('magnet-and-compass', 'Magnet and Compass', 'ដែកអំបៅ និងត្រីវិស័យ', 'Ever wonder how a compass works?', 'ធ្លាប់ឆ្ងល់ថាត្រីវិស័យដំណើរការយ៉ាងណា?', 'Physics', 'Beginner', '{6,7,8,9}', 25, '{"Understand compass function", "Learn about Earths magnetic field"}', '{"យល់ដឹងពីមុខងារត្រីវិស័យ", "រៀនអំពីវាលម៉ាញេទិចផែនដី"}', 'https://phet.colorado.edu/sims/html/magnet-and-compass/latest/magnet-and-compass_km.html', 'https://phet.colorado.edu/sims/html/magnet-and-compass/latest/magnet-and-compass-600.png', '{"physics", "magnet", "compass", "magnetic field"}', false, true),

('faradays-electromagnetic-lab', 'Faradays Electromagnetic Lab', 'មន្ទីរពិសោធន៍អេឡិចត្រូម៉ាញេទិចរបស់ហ្វារ៉ាដេ', 'Play with bar magnets and coils to learn about Faradays law.', 'លេងជាមួយដែកអំបៅ និងរង្វិលដើម្បីរៀនអំពីច្បាប់ហ្វារ៉ាដេ។', 'Physics', 'Advanced', '{10,11,12}', 40, '{"Master Faradays law", "Understand electromagnetic induction"}', '{"ស្ទាត់ជំនាញច្បាប់ហ្វារ៉ាដេ", "យល់ដឹងពីអាំងឌុចស្យុងអេឡិចត្រូម៉ាញេទិច"}', 'https://phet.colorado.edu/sims/html/faradays-electromagnetic-lab/latest/faradays-electromagnetic-lab_km.html', 'https://phet.colorado.edu/sims/html/faradays-electromagnetic-lab/latest/faradays-electromagnetic-lab-600.png', '{"physics", "Faraday", "electromagnetic", "induction"}', true, true),

('sound-waves', 'Sound Waves', 'រលកសំឡេង', 'This simulation lets you see sound waves.', 'ការក្លែងធ្វើនេះអនុញ្ញាតឲ្យអ្នកមើលរលកសំឡេង។', 'Physics', 'Intermediate', '{8,9,10,11}', 30, '{"Understand sound waves", "Explore frequency and amplitude"}', '{"យល់ដឹងពីរលកសំឡេង", "ស្វែងយល់ប្រេកង់ និងអំព្លីទុត"}', 'https://phet.colorado.edu/sims/html/sound-waves/latest/sound-waves_km.html', 'https://phet.colorado.edu/sims/html/sound-waves/latest/sound-waves-600.png', '{"physics", "sound", "waves", "frequency"}', true, true),

('my-solar-system', 'My Solar System', 'ប្រព័ន្ធព្រះអាទិត្យរបស់ខ្ញុំ', 'Build your own system of heavenly bodies and watch the gravitational ballet.', 'សាងសង់ប្រព័ន្ធតារាវត្ថុផ្ទាល់ខ្លួនរបស់អ្នក ហើយមើលរបាំទំនាញ។', 'Physics', 'Advanced', '{9,10,11,12}', 40, '{"Design orbital systems", "Apply gravitational laws"}', '{"រចនាប្រព័ន្ធគន្លង", "អនុវត្តច្បាប់ទំនាញ"}', 'https://phet.colorado.edu/sims/html/my-solar-system/latest/my-solar-system_km.html', 'https://phet.colorado.edu/sims/html/my-solar-system/latest/my-solar-system-600.png', '{"physics", "solar system", "gravity", "orbit"}', false, true),

('geometric-optics-basics', 'Geometric Optics: Basics', 'អុបទិចធរណីមាត្រ៖ មូលដ្ឋាន', 'How does a lens form an image?', 'តើកញ្ចក់បង្កើតរូបភាពដោយរបៀបណា?', 'Physics', 'Beginner', '{8,9,10}', 30, '{"Understand lens and mirror optics", "Learn about image formation"}', '{"យល់ដឹងពីអុបទិចកញ្ចក់ និងកែវ", "រៀនអំពីការបង្កើតរូបភាព"}', 'https://phet.colorado.edu/sims/html/geometric-optics-basics/latest/geometric-optics-basics_km.html', 'https://phet.colorado.edu/sims/html/geometric-optics-basics/latest/geometric-optics-basics-600.png', '{"physics", "optics", "lens", "mirror"}', true, true),

('geometric-optics', 'Geometric Optics', 'អុបទិចធរណីមាត្រ', 'How does a lens form an image? Advanced version.', 'តើកញ្ចក់បង្កើតរូបភាពដោយរបៀបណា? កំណែកម្រិតខ្ពស់។', 'Physics', 'Intermediate', '{9,10,11,12}', 35, '{"Master lens optics", "Calculate magnification"}', '{"ស្ទាត់ជំនាញអុបទិចកញ្ចក់", "គណនាការពង្រីក"}', 'https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_km.html', 'https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics-600.png', '{"physics", "optics", "lens", "refraction"}', false, true),

('circuit-construction-kit-ac', 'Circuit Construction Kit: AC', 'ឧបករណ៍សាងសង់សៀគ្វី៖ AC', 'Build circuits with AC voltage sources.', 'សាងសង់សៀគ្វីជាមួយប្រភពវ៉ុល AC។', 'Physics', 'Advanced', '{10,11,12}', 45, '{"Build AC circuits", "Understand impedance"}', '{"សាងសង់សៀគ្វី AC", "យល់ដឹងពីអាំងពេដង់"}', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac_km.html', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac-600.png', '{"physics", "circuit", "AC", "electricity"}', true, true),

('circuit-construction-kit-ac-virtual-lab', 'Circuit Construction Kit: AC - Virtual Lab', 'ឧបករណ៍សាងសង់សៀគ្វី៖ AC - មន្ទីរពិសោធន៍និម្មិត', 'Advanced AC circuit virtual lab.', 'មន្ទីរពិសោធន៍និម្មិតសៀគ្វី AC កម្រិតខ្ពស់។', 'Physics', 'Advanced', '{10,11,12}', 50, '{"Design complex AC circuits", "Analyze frequency response"}', '{"រចនាសៀគ្វី AC ស្មុគស្មាញ", "វិភាគការឆ្លើយតបប្រេកង់"}', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac-virtual-lab/latest/circuit-construction-kit-ac-virtual-lab_km.html', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac-virtual-lab/latest/circuit-construction-kit-ac-virtual-lab-600.png', '{"physics", "circuit", "AC", "virtual lab"}', false, true),

('gravity-force-lab-basics', 'Gravity Force Lab: Basics', 'មន្ទីរពិសោធន៍កម្លាំងទំនាញ៖ មូលដ្ឋាន', 'Visualize the gravitational force between two objects.', 'មើលឃើញកម្លាំងទំនាញរវាងវត្ថុពីរ។', 'Physics', 'Beginner', '{7,8,9,10}', 25, '{"Understand gravitational force", "Explore mass relationships"}', '{"យល់ដឹងពីកម្លាំងទំនាញ", "ស្វែងយល់ទំនាក់ទំនងម៉ាស់"}', 'https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_km.html', 'https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics-600.png', '{"physics", "gravity", "force", "mass"}', true, true),

('waves-intro', 'Waves Intro', 'ការណែនាំរលក', 'Make waves with water, sound, and light.', 'បង្កើតរលកជាមួយទឹក សំឡេង និងពន្លឺ។', 'Physics', 'Beginner', '{7,8,9,10}', 30, '{"Understand wave basics", "Compare wave types"}', '{"យល់ដឹងពីមូលដ្ឋានរលក", "ប្រៀបធៀបប្រភេទរលក"}', 'https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_km.html', 'https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro-600.png', '{"physics", "waves", "water", "sound", "light"}', true, true),

('gas-properties', 'Gas Properties', 'លក្ខណៈសម្បត្តិឧស្ម័ន', 'Pump gas molecules to a box and see what happens.', 'បូមម៉ូលេគុលឧស្ម័នទៅក្នុងប្រអប់ ហើយមើលអ្វីដែលកើតឡើង។', 'Physics', 'Intermediate', '{9,10,11,12}', 35, '{"Understand gas laws", "Explore PVT relationships"}', '{"យល់ដឹងពីច្បាប់ឧស្ម័ន", "ស្វែងយល់ទំនាក់ទំនង PVT"}', 'https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_km.html', 'https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties-600.png', '{"physics", "gas", "pressure", "temperature"}', true, true),

('wave-interference', 'Wave Interference', 'ការជ្រៀតជ្រែករលក', 'Make waves with a dripping faucet, audio speaker, or laser!', 'បង្កើតរលកជាមួយរ៉ូប៊ីនេស្រក់ទឹក ឧបាល័រសំឡេង ឬឡាសែរ!', 'Physics', 'Advanced', '{10,11,12}', 40, '{"Understand wave interference", "Explore diffraction patterns"}', '{"យល់ដឹងពីការជ្រៀតជ្រែករលក", "ស្វែងយល់លំនាំបែកពន្លឺ"}', 'https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_km.html', 'https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference-600.png', '{"physics", "waves", "interference", "diffraction"}', true, true),

('coulombs-law', 'Coulombs Law', 'ច្បាប់កូឡុំ', 'Visualize the electrostatic force between two charges.', 'មើលឃើញកម្លាំងអេឡិចត្រូស្តាទិចរវាងបន្ទុកពីរ។', 'Physics', 'Intermediate', '{9,10,11,12}', 30, '{"Understand Coulombs law", "Explore electric force"}', '{"យល់ដឹងពីច្បាប់កូឡុំ", "ស្វែងយល់កម្លាំងអគ្គិសនី"}', 'https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law_km.html', 'https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law-600.png', '{"physics", "electricity", "Coulomb", "force"}', false, true),

('capacitor-lab-basics', 'Capacitor Lab: Basics', 'មន្ទីរពិសោធន៍កុងដង់សាទ័រ៖ មូលដ្ឋាន', 'Explore how a capacitor works!', 'ស្វែងយល់ពីរបៀបដែលកុងដង់សាទ័រដំណើរការ!', 'Physics', 'Intermediate', '{10,11,12}', 30, '{"Understand capacitor function", "Calculate capacitance"}', '{"យល់ដឹងពីមុខងារកុងដង់សាទ័រ", "គណនាកាប៉ាស៊ីតង់"}', 'https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics_km.html', 'https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics-600.png', '{"physics", "capacitor", "electricity", "charge"}', false, true),

('circuit-construction-kit-dc-virtual-lab', 'Circuit Construction Kit: DC - Virtual Lab', 'ឧបករណ៍សាងសង់សៀគ្វី៖ DC - មន្ទីរពិសោធន៍និម្មិត', 'Build circuits with batteries, resistors, and more.', 'សាងសង់សៀគ្វីជាមួយថ្ម រេស៊ីស្ទ័រ និងច្រើនទៀត។', 'Physics', 'Beginner', '{8,9,10,11}', 35, '{"Build DC circuits", "Use circuit instruments"}', '{"សាងសង់សៀគ្វី DC", "ប្រើឧបករណ៍សៀគ្វី"}', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/latest/circuit-construction-kit-dc-virtual-lab_km.html', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/latest/circuit-construction-kit-dc-virtual-lab-600.png', '{"physics", "circuit", "DC", "virtual lab"}', true, true),

('circuit-construction-kit-dc', 'Circuit Construction Kit: DC', 'ឧបករណ៍សាងសង់សៀគ្វី៖ DC', 'Build DC circuits with batteries and resistors.', 'សាងសង់សៀគ្វី DC ជាមួយថ្ម និងរេស៊ីស្ទ័រ។', 'Physics', 'Beginner', '{8,9,10,11}', 30, '{"Design DC circuits", "Apply Ohms law"}', '{"រចនាសៀគ្វី DC", "អនុវត្តច្បាប់អូម"}', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_km.html', 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc-600.png', '{"physics", "circuit", "DC", "electricity"}', true, true),

('charges-and-fields', 'Charges and Fields', 'បន្ទុក និងវាល', 'Arrange charges in space and view the electric field.', 'រៀបចំបន្ទុកក្នុងលំហ ហើយមើលវាលអគ្គិសនី។', 'Physics', 'Advanced', '{10,11,12}', 40, '{"Visualize electric fields", "Understand field lines"}', '{"មើលឃើញវាលអគ្គិសនី", "យល់ដឹងពីបន្ទាត់វាល"}', 'https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_km.html', 'https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields-600.png', '{"physics", "electricity", "charges", "fields"}', false, true),

('rutherford-scattering', 'Rutherford Scattering', 'ការខ្ចាត់ខ្ចាយរូតឺហ្វត', 'How did Rutherford figure out the structure of the atom?', 'តើរូតឺហ្វតរកឃើញរចនាសម្ព័ន្ធអាតូមដោយរបៀបណា?', 'Physics', 'Advanced', '{11,12}', 35, '{"Understand atomic structure discovery", "Learn about alpha particle scattering"}', '{"យល់ដឹងពីការរកឃើញរចនាសម្ព័ន្ធអាតូម", "រៀនអំពីការខ្ចាត់ខ្ចាយភាគល្អិតអាល់ហ្វា"}', 'https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering_km.html', 'https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering-600.png', '{"physics", "atomic", "Rutherford", "scattering"}', false, true),

('bending-light', 'Bending Light', 'ពន្លឺកោង', 'Explore bending of light between two media.', 'ស្វែងយល់ការកោងពន្លឺរវាងមជ្ឈដ្ឋានពីរ។', 'Physics', 'Intermediate', '{9,10,11,12}', 30, '{"Understand refraction", "Apply Snells law"}', '{"យល់ដឹងពីការចំណាំង", "អនុវត្តច្បាប់ស្នែល"}', 'https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_km.html', 'https://phet.colorado.edu/sims/html/bending-light/latest/bending-light-600.png', '{"physics", "optics", "refraction", "light"}', true, true),

('hookes-law', 'Hookes Law', 'ច្បាប់ហុក', 'Stretch and compress springs to explore relationships.', 'ទាញ និងបង្ហាប់ស្ព្រីងដើម្បីស្វែងយល់ទំនាក់ទំនង។', 'Physics', 'Intermediate', '{9,10,11,12}', 30, '{"Understand Hookes law", "Calculate spring constants"}', '{"យល់ដឹងពីច្បាប់ហុក", "គណនាថេរស្ព្រីង"}', 'https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law_km.html', 'https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law-600.png', '{"physics", "spring", "force", "Hooke"}', false, true),

('faradays-law', 'Faradays Law', 'ច្បាប់ហ្វារ៉ាដេ', 'Investigate Faradays law and electromagnetic induction.', 'ស៊ើបអង្កេតច្បាប់ហ្វារ៉ាដេ និងអាំងឌុចស្យុងអេឡិចត្រូម៉ាញេទិច។', 'Physics', 'Advanced', '{10,11,12}', 35, '{"Master electromagnetic induction", "Calculate induced EMF"}', '{"ស្ទាត់ជំនាញអាំងឌុចស្យុងអេឡិចត្រូម៉ាញេទិច", "គណនា EMF បង្កើត"}', 'https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_km.html', 'https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law-600.png', '{"physics", "Faraday", "induction", "magnetism"}', false, true),

('wave-on-a-string', 'Wave on a String', 'រលកនៅលើខ្សែ', 'Explore the world of waves on a string.', 'ស្វែងរកពិភពនៃរលកនៅលើខ្សែ។', 'Physics', 'Intermediate', '{8,9,10,11}', 30, '{"Create wave patterns", "Understand wave properties"}', '{"បង្កើតលំនាំរលក", "យល់ដឹងពីលក្ខណៈសម្បត្តិរលក"}', 'https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_km.html', 'https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string-600.png', '{"physics", "waves", "string", "oscillation"}', true, true),

('color-vision', 'Color Vision', 'ការមើលឃើញពណ៌', 'Make a whole rainbow by mixing red, green, and blue light.', 'បង្កើតឥន្ធនូពេញលេញដោយលាយពន្លឺក្រហម បៃតង និងខៀវ។', 'Physics', 'Intermediate', '{8,9,10,11}', 30, '{"Understand color mixing", "Learn about RGB color model"}', '{"យល់ដឹងពីការលាយពណ៌", "រៀនអំពីគំរូពណ៌ RGB"}', 'https://phet.colorado.edu/sims/html/color-vision/latest/color-vision_km.html', 'https://phet.colorado.edu/sims/html/color-vision/latest/color-vision-600.png', '{"physics", "optics", "color", "light", "vision"}', false, true),

('friction', 'Friction', 'កកិត', 'Explore the forces at work when you try to push a filing cabinet.', 'ស្វែងយល់កម្លាំងដែលដំណើរការនៅពេលអ្នកព្យាយាមរុញទូឯកសារ។', 'Physics', 'Beginner', '{7,8,9,10}', 25, '{"Understand friction forces", "Explore static and kinetic friction"}', '{"យល់ដឹងពីកម្លាំងកកិត", "ស្វែងយល់កកិតស្តាទិច និងស៊ីនេទិច"}', 'https://phet.colorado.edu/sims/html/friction/latest/friction_km.html', 'https://phet.colorado.edu/sims/html/friction/latest/friction-600.png', '{"physics", "friction", "force", "motion"}', false, true),

('john-travoltage', 'John Travoltage', 'ចន ត្រាវ៉ុលតាស', 'Make sparks fly with John Travoltage!', 'ធ្វើឲ្យផ្កាភ្លើងហោះជាមួយចន ត្រាវ៉ុលតាស!', 'Physics', 'Beginner', '{6,7,8,9}', 20, '{"Understand static electricity", "Explore charge transfer"}', '{"យល់ដឹងពីអគ្គិសនីស្តាទិច", "ស្វែងយល់ការផ្ទេរបន្ទុក"}', 'https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_km.html', 'https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage-600.png', '{"physics", "electricity", "static", "charge"}', false, true),

('gravity-force-lab', 'Gravity Force Lab', 'មន្ទីរពិសោធន៍កម្លាំងទំនាញ', 'Visualize the gravitational force between objects.', 'មើលឃើញកម្លាំងទំនាញរវាងវត្ថុ។', 'Physics', 'Intermediate', '{8,9,10,11}', 30, '{"Calculate gravitational force", "Explore inverse square law"}', '{"គណនាកម្លាំងទំនាញ", "ស្វែងយល់ច្បាប់ការេច្រាស"}', 'https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_km.html', 'https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab-600.png', '{"physics", "gravity", "force", "Newton"}', false, true),

('balloons-and-static-electricity', 'Balloons and Static Electricity', 'ប៉េងប៉ោង និងអគ្គិសនីស្តាទិច', 'Why does a balloon stick to your sweater?', 'ហេតុអ្វីប៉េងប៉ោងជាប់នឹងអាវយឺតរបស់អ្នក?', 'Physics', 'Beginner', '{6,7,8,9}', 25, '{"Understand static electricity", "Explore charge interactions"}', '{"យល់ដឹងពីអគ្គិសនីស្តាទិច", "ស្វែងយល់អន្តរកម្មបន្ទុក"}', 'https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_km.html', 'https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity-600.png', '{"physics", "electricity", "static", "balloons"}', true, true),

('ohms-law', 'Ohms Law', 'ច្បាប់អូម', 'See how the equation form of Ohms law relates to a simple circuit.', 'មើលពីរបៀបដែលទម្រង់សមីការនៃច្បាប់អូមទាក់ទងនឹងសៀគ្វីសាមញ្ញ។', 'Physics', 'Beginner', '{8,9,10}', 25, '{"Understand Ohms law", "Calculate resistance"}', '{"យល់ដឹងពីច្បាប់អូម", "គណនារេស៊ីស្តង់"}', 'https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_km.html', 'https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law-600.png', '{"physics", "electricity", "Ohm", "resistance"}', true, true),

('resistance-in-a-wire', 'Resistance in a Wire', 'រេស៊ីស្តង់ក្នុងខ្សែ', 'Learn about factors that affect electrical resistance.', 'រៀនអំពីកត្តាដែលប៉ះពាល់ដល់រេស៊ីស្តង់អគ្គិសនី។', 'Physics', 'Intermediate', '{9,10,11}', 25, '{"Understand resistance factors", "Apply resistivity concepts"}', '{"យល់ដឹងពីកត្តារេស៊ីស្តង់", "អនុវត្តគំនិតរេស៊ីស្ទីវីតេ"}', 'https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_km.html', 'https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire-600.png', '{"physics", "electricity", "resistance", "wire"}', false, true),

('buoyancy-basics', 'Buoyancy Basics', 'មូលដ្ឋានកម្លាំងរំកិល', 'Explore what makes things float or sink.', 'ស្វែងយល់អ្វីដែលធ្វើឲ្យវត្ថុអណ្តែត ឬលិច។', 'Physics', 'Beginner', '{7,8,9}', 25, '{"Understand buoyancy basics", "Predict floating and sinking"}', '{"យល់ដឹងពីមូលដ្ឋានកម្លាំងរំកិល", "ទស្សន៍ទាយការអណ្តែត និងលិច"}', 'https://phet.colorado.edu/sims/html/buoyancy-basics/latest/buoyancy-basics_km.html', 'https://phet.colorado.edu/sims/html/buoyancy-basics/latest/buoyancy-basics-600.png', '{"physics", "buoyancy", "float", "sink"}', false, true),

('keplers-laws', 'Keplers Laws', 'ច្បាប់កេប្លែរ', 'Explore Keplers laws of planetary motion.', 'ស្វែងយល់ច្បាប់ចលនាភពរបស់កេប្លែរ។', 'Physics', 'Advanced', '{10,11,12}', 40, '{"Understand Keplers laws", "Analyze orbital periods"}', '{"យល់ដឹងពីច្បាប់កេប្លែរ", "វិភាគរយៈពេលគន្លង"}', 'https://phet.colorado.edu/sims/html/keplers-laws/latest/keplers-laws_km.html', 'https://phet.colorado.edu/sims/html/keplers-laws/latest/keplers-laws-600.png', '{"physics", "astronomy", "Kepler", "orbits"}', false, true),

('density', 'Density', 'ដង់ស៊ីតេ', 'Why do objects like wood float in water?', 'ហេតុអ្វីវត្ថុដូចជាឈើអណ្តែតក្នុងទឹក?', 'Physics', 'Beginner', '{7,8,9,10}', 30, '{"Understand density concept", "Compare material densities"}', '{"យល់ដឹងពីគំនិតដង់ស៊ីតេ", "ប្រៀបធៀបដង់ស៊ីតេសម្ភារៈ"}', 'https://phet.colorado.edu/sims/html/density/latest/density_km.html', 'https://phet.colorado.edu/sims/html/density/latest/density-600.png', '{"physics", "density", "mass", "volume"}', true, true),

('normal-modes', 'Normal Modes', 'របៀបធម្មតា', 'Explore normal modes in coupled oscillator systems.', 'ស្វែងយល់របៀបធម្មតាក្នុងប្រព័ន្ធលំយោលភ្ជាប់គ្នា។', 'Physics', 'Advanced', '{11,12}', 40, '{"Understand normal modes", "Analyze coupled oscillators"}', '{"យល់ដឹងពីរបៀបធម្មតា", "វិភាគលំយោលភ្ជាប់គ្នា"}', 'https://phet.colorado.edu/sims/html/normal-modes/latest/normal-modes_km.html', 'https://phet.colorado.edu/sims/html/normal-modes/latest/normal-modes-600.png', '{"physics", "oscillation", "normal modes", "waves"}', false, true),

('fourier-making-waves', 'Fourier: Making Waves', 'ហ្វូរីយេ៖ បង្កើតរលក', 'Learn how to make waves of all different shapes.', 'រៀនពីរបៀបបង្កើតរលកដែលមានរាងផ្សេងៗ។', 'Physics', 'Advanced', '{11,12}', 45, '{"Understand Fourier analysis", "Build complex waveforms"}', '{"យល់ដឹងពីការវិភាគហ្វូរីយេ", "សាងសង់ទម្រង់រលកស្មុគស្មាញ"}', 'https://phet.colorado.edu/sims/html/fourier-making-waves/latest/fourier-making-waves_km.html', 'https://phet.colorado.edu/sims/html/fourier-making-waves/latest/fourier-making-waves-600.png', '{"physics", "Fourier", "waves", "harmonics"}', false, true),

('collision-lab', 'Collision Lab', 'មន្ទីរពិសោធន៍ការប៉ះទង្គិច', 'Explore conservation of momentum in collisions.', 'ស្វែងយល់ការអភិរក្សបរិមាណចលនាក្នុងការប៉ះទង្គិច។', 'Physics', 'Intermediate', '{9,10,11,12}', 35, '{"Understand momentum conservation", "Analyze collision types"}', '{"យល់ដឹងពីការអភិរក្សបរិមាណចលនា", "វិភាគប្រភេទការប៉ះទង្គិច"}', 'https://phet.colorado.edu/sims/html/collision-lab/latest/collision-lab_km.html', 'https://phet.colorado.edu/sims/html/collision-lab/latest/collision-lab-600.png', '{"physics", "collision", "momentum", "conservation"}', false, true),

('energy-skate-park', 'Energy Skate Park', 'ឧទ្យានជិះស្គីថាមពល', 'Learn about energy conservation with a skater (full version).', 'រៀនអំពីការអភិរក្សថាមពលជាមួយអ្នកជិះស្គី (កំណែពេញលេញ)។', 'Physics', 'Advanced', '{8,9,10,11,12}', 50, '{"Master energy conservation", "Design complex tracks", "Analyze energy graphs"}', '{"ស្ទាត់ជំនាញការអភិរក្សថាមពល", "រចនាផ្លូវស្មុគស្មាញ", "វិភាគក្រាហ្វថាមពល"}', 'https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_km.html', 'https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park-600.png', '{"physics", "energy", "conservation", "kinetic", "potential"}', true, true),

('blackbody-spectrum', 'Blackbody Spectrum', 'វិសាលគមវត្ថុខ្មៅ', 'How does the blackbody spectrum depend on temperature?', 'តើវិសាលគមវត្ថុខ្មៅអាស្រ័យលើសីតុណ្ហភាពដោយរបៀបណា?', 'Physics', 'Advanced', '{11,12}', 35, '{"Understand blackbody radiation", "Explore Wiens law"}', '{"យល់ដឹងពីវិទ្យុសកម្មវត្ថុខ្មៅ", "ស្វែងយល់ច្បាប់វីន"}', 'https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum_km.html', 'https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum-600.png', '{"physics", "blackbody", "radiation", "spectrum"}', false, true),

('masses-and-springs-basics', 'Masses and Springs: Basics', 'ម៉ាស់ និងស្ព្រីង៖ មូលដ្ឋាន', 'Hang masses from springs and discover relationships.', 'ព្យួរម៉ាស់ពីស្ព្រីង ហើយរកឃើញទំនាក់ទំនង។', 'Physics', 'Beginner', '{8,9,10}', 30, '{"Explore spring-mass systems", "Understand oscillations"}', '{"ស្វែងយល់ប្រព័ន្ធស្ព្រីង-ម៉ាស់", "យល់ដឹងពីលំយោល"}', 'https://phet.colorado.edu/sims/html/masses-and-springs-basics/latest/masses-and-springs-basics_km.html', 'https://phet.colorado.edu/sims/html/masses-and-springs-basics/latest/masses-and-springs-basics-600.png', '{"physics", "springs", "mass", "oscillation"}', false, true),

('energy-forms-and-changes', 'Energy Forms and Changes', 'ទម្រង់ និងការផ្លាស់ប្តូរថាមពល', 'Explore how heating and cooling adds or removes energy.', 'ស្វែងយល់ពីរបៀបដែលការកំដៅ និងត្រជាក់បន្ថែម ឬដកថាមពល។', 'Physics', 'Intermediate', '{8,9,10,11}', 35, '{"Explore energy transformations", "Understand heat transfer"}', '{"ស្វែងយល់ការបំប្លែងថាមពល", "យល់ដឹងពីការផ្ទេរកំដៅ"}', 'https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes_km.html', 'https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes-600.png', '{"physics", "energy", "heat", "temperature"}', true, true),

('masses-and-springs', 'Masses and Springs', 'ម៉ាស់ និងស្ព្រីង', 'A realistic mass-spring laboratory.', 'មន្ទីរពិសោធន៍ម៉ាស់-ស្ព្រីងជាក់ស្តែង។', 'Physics', 'Intermediate', '{9,10,11,12}', 40, '{"Analyze spring-mass motion", "Measure spring constants"}', '{"វិភាគចលនាស្ព្រីង-ម៉ាស់", "វាស់ថេរស្ព្រីង"}', 'https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_km.html', 'https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs-600.png', '{"physics", "springs", "harmonic motion", "lab"}', false, true),

('under-pressure', 'Under Pressure', 'ក្រោមសម្ពាធ', 'Explore pressure under and above water.', 'ស្វែងយល់សម្ពាធក្រោម និងលើទឹក។', 'Physics', 'Beginner', '{7,8,9,10}', 30, '{"Understand pressure concepts", "Explore fluid pressure"}', '{"យល់ដឹងពីគំនិតសម្ពាធ", "ស្វែងយល់សម្ពាធអង្គធាតុរាវ"}', 'https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_km.html', 'https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure-600.png', '{"physics", "pressure", "fluid", "water"}', false, true),

-- CHEMISTRY SIMULATIONS (Additional 16)
('molecule-polarity', 'Molecule Polarity', 'ប៉ូលនៃម៉ូលេគុល', 'When is a molecule polar?', 'តើម៉ូលេគុលមានប៉ូលនៅពេលណា?', 'Chemistry', 'Intermediate', '{10,11,12}', 30, '{"Understand molecular polarity", "Explore dipole moments"}', '{"យល់ដឹងពីប៉ូលម៉ូលេគុល", "ស្វែងយល់ម៉ូម៉ង់ឌីប៉ូល"}', 'https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_km.html', 'https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity-600.png', '{"chemistry", "molecule", "polarity", "dipole"}', false, true),

('molecules-and-light', 'Molecules and Light', 'ម៉ូលេគុល និងពន្លឺ', 'How do greenhouse gases affect the climate?', 'តើឧស្ម័នផ្ទះកញ្ចក់ប៉ះពាល់ដល់អាកាសធាតុដោយរបៀបណា?', 'Chemistry', 'Intermediate', '{9,10,11,12}', 35, '{"Understand light-molecule interactions", "Explore greenhouse effect"}', '{"យល់ដឹងពីអន្តរកម្មពន្លឺ-ម៉ូលេគុល", "ស្វែងយល់ឥទ្ធិពលផ្ទះកញ្ចក់"}', 'https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_km.html', 'https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light-600.png', '{"chemistry", "molecules", "light", "greenhouse"}', false, true),

('reactants-products-and-leftovers', 'Reactants, Products and Leftovers', 'សារធាតុប្រតិកម្ម ផលិតផល និងសំណល់', 'Create sandwiches and chemical reactions.', 'បង្កើតសាំងវិច និងប្រតិកម្មគីមី។', 'Chemistry', 'Beginner', '{8,9,10,11}', 30, '{"Understand limiting reactants", "Balance chemical equations"}', '{"យល់ដឹងពីសារធាតុប្រតិកម្មកំណត់", "តុល្យភាពសមីការគីមី"}', 'https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_km.html', 'https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers-600.png', '{"chemistry", "reactions", "stoichiometry", "limiting"}', true, true),

('acid-base-solutions', 'Acid-Base Solutions', 'សូលុយស្យុងអាស៊ីត-បាស', 'How do strong and weak acids differ?', 'តើអាស៊ីតខ្លាំង និងខ្សោយខុសគ្នាដោយរបៀបណា?', 'Chemistry', 'Intermediate', '{10,11,12}', 35, '{"Understand acid-base chemistry", "Calculate pH values"}', '{"យល់ដឹងពីគីមីអាស៊ីត-បាស", "គណនាតម្លៃ pH"}', 'https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_km.html', 'https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions-600.png', '{"chemistry", "acid", "base", "pH", "solutions"}', true, true),

('molarity', 'Molarity', 'ម៉ូឡារីតេ', 'What determines the concentration of a solution?', 'តើអ្វីកំណត់កំហាប់នៃសូលុយស្យុង?', 'Chemistry', 'Intermediate', '{9,10,11,12}', 30, '{"Calculate molarity", "Understand solution concentration"}', '{"គណនាម៉ូឡារីតេ", "យល់ដឹងពីកំហាប់សូលុយស្យុង"}', 'https://phet.colorado.edu/sims/html/molarity/latest/molarity_km.html', 'https://phet.colorado.edu/sims/html/molarity/latest/molarity-600.png', '{"chemistry", "molarity", "concentration", "solutions"}', false, true),

('build-a-nucleus', 'Build a Nucleus', 'សាងសង់នុយក្លេអ៊ែរ', 'Build an atom out of protons and neutrons.', 'សាងសង់អាតូមពីប្រូតុង និងនឺត្រុង។', 'Chemistry', 'Advanced', '{11,12}', 35, '{"Understand nuclear structure", "Explore nuclear stability"}', '{"យល់ដឹងពីរចនាសម្ព័ន្ធនុយក្លេអ៊ែរ", "ស្វែងយល់ស្ថិរភាពនុយក្លេអ៊ែរ"}', 'https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus_km.html', 'https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus-600.png', '{"chemistry", "nucleus", "nuclear", "isotopes"}', false, true),

('build-a-molecule', 'Build a Molecule', 'សាងសង់ម៉ូលេគុល', 'Starting from atoms, build molecules!', 'ចាប់ផ្តើមពីអាតូម សាងសង់ម៉ូលេគុល!', 'Chemistry', 'Beginner', '{7,8,9,10}', 30, '{"Build simple molecules", "Understand molecular structure"}', '{"សាងសង់ម៉ូលេគុលសាមញ្ញ", "យល់ដឹងពីរចនាសម្ព័ន្ធម៉ូលេគុល"}', 'https://phet.colorado.edu/sims/html/build-a-molecule/latest/build-a-molecule_km.html', 'https://phet.colorado.edu/sims/html/build-a-molecule/latest/build-a-molecule-600.png', '{"chemistry", "molecules", "atoms", "bonding"}', true, true),

('diffusion', 'Diffusion', 'ការសាយភាយ', 'Explore diffusion of particles through a membrane.', 'ស្វែងយល់ការសាយភាយនៃភាគល្អិតតាមរយៈភ្នាស។', 'Chemistry', 'Intermediate', '{9,10,11,12}', 30, '{"Understand diffusion process", "Explore concentration gradients"}', '{"យល់ដឹងពីដំណើរការសាយភាយ", "ស្វែងយល់ជម្រាលកំហាប់"}', 'https://phet.colorado.edu/sims/html/diffusion/latest/diffusion_km.html', 'https://phet.colorado.edu/sims/html/diffusion/latest/diffusion-600.png', '{"chemistry", "diffusion", "particles", "membrane"}', false, true),

('gases-intro', 'Gases Intro', 'ការណែនាំឧស្ម័ន', 'Pump gas molecules and see what happens.', 'បូមម៉ូលេគុលឧស្ម័ន ហើយមើលអ្វីដែលកើតឡើង។', 'Chemistry', 'Beginner', '{8,9,10}', 25, '{"Understand gas behavior", "Explore pressure and temperature"}', '{"យល់ដឹងពីឥរិយាបថឧស្ម័ន", "ស្វែងយល់សម្ពាធ និងសីតុណ្ហភាព"}', 'https://phet.colorado.edu/sims/html/gases-intro/latest/gases-intro_km.html', 'https://phet.colorado.edu/sims/html/gases-intro/latest/gases-intro-600.png', '{"chemistry", "gas", "pressure", "temperature"}', false, true),

('isotopes-and-atomic-mass', 'Isotopes and Atomic Mass', 'អ៊ីសូតូប និងម៉ាស់អាតូម', 'Are all atoms of an element the same?', 'តើអាតូមទាំងអស់នៃធាតុមួយដូចគ្នាទេ?', 'Chemistry', 'Intermediate', '{9,10,11,12}', 35, '{"Understand isotopes", "Calculate atomic mass"}', '{"យល់ដឹងពីអ៊ីសូតូប", "គណនាម៉ាស់អាតូម"}', 'https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass_km.html', 'https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass-600.png', '{"chemistry", "isotopes", "atomic mass", "elements"}', false, true),

('molecule-shapes', 'Molecule Shapes', 'រាងម៉ូលេគុល', 'Explore molecule shapes by building molecules in 3D!', 'ស្វែងយល់រាងម៉ូលេគុលដោយសាងសង់ម៉ូលេគុលក្នុង 3D!', 'Chemistry', 'Intermediate', '{10,11,12}', 35, '{"Understand molecular geometry", "Apply VSEPR theory"}', '{"យល់ដឹងពីធរណីមាត្រម៉ូលេគុល", "អនុវត្តទ្រឹស្តី VSEPR"}', 'https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_km.html', 'https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes-600.png', '{"chemistry", "molecules", "3D", "geometry", "VSEPR"}', true, true),

('molecule-shapes-basics', 'Molecule Shapes: Basics', 'រាងម៉ូលេគុល៖ មូលដ្ឋាន', 'Explore basic molecule shapes.', 'ស្វែងយល់រាងម៉ូលេគុលមូលដ្ឋាន។', 'Chemistry', 'Beginner', '{9,10,11}', 30, '{"Learn basic molecular shapes", "Understand bonding"}', '{"រៀនរាងម៉ូលេគុលមូលដ្ឋាន", "យល់ដឹងពីការភ្ជាប់"}', 'https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics_km.html', 'https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics-600.png', '{"chemistry", "molecules", "shapes", "bonding"}', false, true),

('ph-scale', 'pH Scale', 'មាត្រដ្ឋាន pH', 'Test the pH of everyday liquids.', 'សាកល្បង pH នៃអង្គធាតុរាវប្រចាំថ្ងៃ។', 'Chemistry', 'Intermediate', '{8,9,10,11}', 30, '{"Measure pH values", "Understand logarithmic scale"}', '{"វាស់តម្លៃ pH", "យល់ដឹងពីមាត្រដ្ឋានឡូការីត"}', 'https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_km.html', 'https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale-600.png', '{"chemistry", "pH", "acid", "base", "scale"}', true, true),

('beers-law-lab', 'Beers Law Lab', 'មន្ទីរពិសោធន៍ច្បាប់ប៊ែរ', 'How does concentration affect light absorption?', 'តើកំហាប់ប៉ះពាល់ដល់ការស្រូបពន្លឺដោយរបៀបណា?', 'Chemistry', 'Advanced', '{11,12}', 40, '{"Apply Beers law", "Measure absorbance"}', '{"អនុវត្តច្បាប់ប៊ែរ", "វាស់ការស្រូប"}', 'https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_km.html', 'https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab-600.png', '{"chemistry", "Beer law", "absorbance", "concentration"}', false, true),

('atomic-interactions', 'Atomic Interactions', 'អន្តរកម្មអាតូម', 'Explore forces between atoms.', 'ស្វែងយល់កម្លាំងរវាងអាតូម។', 'Chemistry', 'Advanced', '{11,12}', 35, '{"Understand intermolecular forces", "Explore van der Waals"}', '{"យល់ដឹងពីកម្លាំងអន្តរម៉ូលេគុល", "ស្វែងយល់វ៉ាន់ដឺវ៉ាល់"}', 'https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_km.html', 'https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions-600.png', '{"chemistry", "atoms", "forces", "interactions"}', false, true),

('states-of-matter', 'States of Matter', 'សភាពរូបធាតុ', 'Watch atoms and molecules change states.', 'មើលអាតូម និងម៉ូលេគុលផ្លាស់ប្តូរសភាព។', 'Chemistry', 'Intermediate', '{8,9,10,11}', 35, '{"Explore phase changes", "Understand molecular behavior"}', '{"ស្វែងយល់ការផ្លាស់ប្តូរដំណាក់កាល", "យល់ដឹងពីឥរិយាបថម៉ូលេគុល"}', 'https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_km.html', 'https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter-600.png', '{"chemistry", "states", "matter", "phase"}', true, true),

-- MATHEMATICS SIMULATIONS (Additional 39)
('balancing-act', 'Balancing Act', 'អំពើតុល្យភាព', 'Play with objects on a teeter totter to learn about balance.', 'លេងជាមួយវត្ថុនៅលើទោងទាំងដើម្បីរៀនអំពីតុល្យភាព។', 'Mathematics', 'Beginner', '{5,6,7,8}', 25, '{"Understand balance and torque", "Explore proportional reasoning"}', '{"យល់ដឹងពីតុល្យភាព និងម៉ូម៉ង់", "ស្វែងយល់ការវែកញែកសមាមាត្រ"}', 'https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_km.html', 'https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act-600.png', '{"mathematics", "balance", "torque", "proportion"}', true, true),

('quantum-coin-toss', 'Quantum Coin Toss', 'ការបោះកាក់កង់ទិច', 'Explore probability with quantum coins.', 'ស្វែងយល់ប្រូបាប៊ីលីតេជាមួយកាក់កង់ទិច។', 'Mathematics', 'Advanced', '{11,12}', 30, '{"Understand quantum probability", "Explore superposition"}', '{"យល់ដឹងពីប្រូបាប៊ីលីតេកង់ទិច", "ស្វែងយល់ការត្រួតគ្នា"}', 'https://phet.colorado.edu/sims/html/quantum-coin-toss/latest/quantum-coin-toss_km.html', 'https://phet.colorado.edu/sims/html/quantum-coin-toss/latest/quantum-coin-toss-600.png', '{"mathematics", "quantum", "probability", "statistics"}', false, true),

('number-pairs', 'Number Pairs', 'គូលេខ', 'Practice finding number pairs that add to 10.', 'អនុវត្តការរកគូលេខដែលបូកបាន 10។', 'Mathematics', 'Beginner', '{1,2,3,4}', 20, '{"Find number pairs", "Build addition fluency"}', '{"រកគូលេខ", "កសាងភាពស្ទាត់ជំនាញបូក"}', 'https://phet.colorado.edu/sims/html/number-pairs/latest/number-pairs_km.html', 'https://phet.colorado.edu/sims/html/number-pairs/latest/number-pairs-600.png', '{"mathematics", "addition", "pairs", "numbers"}', false, true),

('quantum-measurement', 'Quantum Measurement', 'ការវាស់វែងកង់ទិច', 'Explore quantum measurement and uncertainty.', 'ស្វែងយល់ការវាស់វែងកង់ទិច និងភាពមិនប្រាកដប្រជា។', 'Mathematics', 'Advanced', '{11,12}', 35, '{"Understand measurement uncertainty", "Explore quantum states"}', '{"យល់ដឹងពីភាពមិនប្រាកដប្រជានៃការវាស់វែង", "ស្វែងយល់សភាពកង់ទិច"}', 'https://phet.colorado.edu/sims/html/quantum-measurement/latest/quantum-measurement_km.html', 'https://phet.colorado.edu/sims/html/quantum-measurement/latest/quantum-measurement-600.png', '{"mathematics", "quantum", "measurement", "uncertainty"}', false, true),

('mean-share-and-balance', 'Mean: Share and Balance', 'មធ្យម៖ ចែករំលែក និងតុល្យភាព', 'Explore mean as fair share and balance point.', 'ស្វែងយល់មធ្យមជាចំណែកត្រឹមត្រូវ និងចំណុចតុល្យភាព។', 'Mathematics', 'Intermediate', '{6,7,8,9}', 30, '{"Understand mean concept", "Calculate averages"}', '{"យល់ដឹងពីគំនិតមធ្យម", "គណនាមធ្យមភាគ"}', 'https://phet.colorado.edu/sims/html/mean-share-and-balance/latest/mean-share-and-balance_km.html', 'https://phet.colorado.edu/sims/html/mean-share-and-balance/latest/mean-share-and-balance-600.png', '{"mathematics", "mean", "average", "statistics"}', true, true),

('projectile-sampling-distributions', 'Projectile Sampling Distributions', 'ការបែងចែកគំរូគ្រាប់កាំភ្លើង', 'Explore sampling distributions with projectiles.', 'ស្វែងយល់ការបែងចែកគំរូជាមួយគ្រាប់កាំភ្លើង។', 'Mathematics', 'Advanced', '{11,12}', 40, '{"Understand sampling distributions", "Apply central limit theorem"}', '{"យល់ដឹងពីការបែងចែកគំរូ", "អនុវត្តទ្រឹស្តីបទដែនកណ្តាល"}', 'https://phet.colorado.edu/sims/html/projectile-sampling-distributions/latest/projectile-sampling-distributions_km.html', 'https://phet.colorado.edu/sims/html/projectile-sampling-distributions/latest/projectile-sampling-distributions-600.png', '{"mathematics", "statistics", "sampling", "distributions"}', false, true),

('projectile-data-lab', 'Projectile Data Lab', 'មន្ទីរពិសោធន៍ទិន្នន័យគ្រាប់កាំភ្លើង', 'Collect and analyze projectile data.', 'ប្រមូល និងវិភាគទិន្នន័យគ្រាប់កាំភ្លើង។', 'Mathematics', 'Intermediate', '{9,10,11}', 35, '{"Collect experimental data", "Analyze statistical patterns"}', '{"ប្រមូលទិន្នន័យពិសោធន៍", "វិភាគលំនាំស្ថិតិ"}', 'https://phet.colorado.edu/sims/html/projectile-data-lab/latest/projectile-data-lab_km.html', 'https://phet.colorado.edu/sims/html/projectile-data-lab/latest/projectile-data-lab-600.png', '{"mathematics", "data", "statistics", "analysis"}', false, true),

('center-and-variability', 'Center and Variability', 'កណ្តាល និងភាពប្រែប្រួល', 'Explore measures of center and spread.', 'ស្វែងយល់រង្វាស់នៃកណ្តាល និងការរីករាល។', 'Mathematics', 'Intermediate', '{7,8,9,10}', 35, '{"Calculate mean, median, mode", "Understand variability measures"}', '{"គណនាមធ្យម មេដ្យាន ម៉ូត", "យល់ដឹងពីរង្វាស់ភាពប្រែប្រួល"}', 'https://phet.colorado.edu/sims/html/center-and-variability/latest/center-and-variability_km.html', 'https://phet.colorado.edu/sims/html/center-and-variability/latest/center-and-variability-600.png', '{"mathematics", "statistics", "center", "variability"}', true, true),

('quadrilateral', 'Quadrilateral', 'ចតុកោណ', 'Explore properties of quadrilaterals.', 'ស្វែងយល់លក្ខណៈសម្បត្តិនៃចតុកោណ។', 'Mathematics', 'Intermediate', '{7,8,9,10}', 30, '{"Classify quadrilaterals", "Explore geometric properties"}', '{"ចាត់ថ្នាក់ចតុកោណ", "ស្វែងយល់លក្ខណៈសម្បត្តិធរណីមាត្រ"}', 'https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral_km.html', 'https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral-600.png', '{"mathematics", "geometry", "quadrilateral", "shapes"}', false, true),

('calculus-grapher', 'Calculus Grapher', 'អ្នកគូសក្រាហ្វកាល់គុលុស', 'Graph derivatives and integrals.', 'គូសក្រាហ្វដេរីវេ និងអាំងតេក្រាល់។', 'Mathematics', 'Advanced', '{11,12}', 45, '{"Visualize derivatives", "Understand integrals"}', '{"មើលឃើញដេរីវេ", "យល់ដឹងពីអាំងតេក្រាល់"}', 'https://phet.colorado.edu/sims/html/calculus-grapher/latest/calculus-grapher_km.html', 'https://phet.colorado.edu/sims/html/calculus-grapher/latest/calculus-grapher-600.png', '{"mathematics", "calculus", "derivatives", "integrals"}', false, true),

('number-compare', 'Number Compare', 'ប្រៀបធៀបលេខ', 'Compare numbers and build number sense.', 'ប្រៀបធៀបលេខ និងកសាងការយល់ដឹងលេខ។', 'Mathematics', 'Beginner', '{1,2,3,4}', 20, '{"Compare number values", "Build number sense"}', '{"ប្រៀបធៀបតម្លៃលេខ", "កសាងការយល់ដឹងលេខ"}', 'https://phet.colorado.edu/sims/html/number-compare/latest/number-compare_km.html', 'https://phet.colorado.edu/sims/html/number-compare/latest/number-compare-600.png', '{"mathematics", "numbers", "comparison", "counting"}', false, true),

('number-play', 'Number Play', 'លេងលេខ', 'Explore numbers through play.', 'ស្វែងយល់លេខតាមរយៈការលេង។', 'Mathematics', 'Beginner', '{1,2,3}', 20, '{"Explore number concepts", "Build counting skills"}', '{"ស្វែងយល់គំនិតលេខ", "កសាងជំនាញរាប់"}', 'https://phet.colorado.edu/sims/html/number-play/latest/number-play_km.html', 'https://phet.colorado.edu/sims/html/number-play/latest/number-play-600.png', '{"mathematics", "numbers", "counting", "play"}', true, true),

('number-line-distance', 'Number Line: Distance', 'បន្ទាត់លេខ៖ ចម្ងាយ', 'Explore distance on a number line.', 'ស្វែងយល់ចម្ងាយនៅលើបន្ទាត់លេខ។', 'Mathematics', 'Intermediate', '{6,7,8,9}', 25, '{"Understand absolute value", "Calculate distances"}', '{"យល់ដឹងពីតម្លៃដាច់ខាត", "គណនាចម្ងាយ"}', 'https://phet.colorado.edu/sims/html/number-line-distance/latest/number-line-distance_km.html', 'https://phet.colorado.edu/sims/html/number-line-distance/latest/number-line-distance-600.png', '{"mathematics", "number line", "distance", "absolute value"}', false, true),

('ratio-and-proportion', 'Ratio and Proportion', 'សមាមាត្រ និងផលធៀប', 'Discover patterns with ratio and proportion.', 'រកឃើញលំនាំជាមួយសមាមាត្រ និងផលធៀប។', 'Mathematics', 'Intermediate', '{6,7,8,9}', 30, '{"Understand ratios", "Solve proportions"}', '{"យល់ដឹងពីសមាមាត្រ", "ដោះស្រាយផលធៀប"}', 'https://phet.colorado.edu/sims/html/ratio-and-proportion/latest/ratio-and-proportion_km.html', 'https://phet.colorado.edu/sims/html/ratio-and-proportion/latest/ratio-and-proportion-600.png', '{"mathematics", "ratio", "proportion", "patterns"}', true, true),

('number-line-operations', 'Number Line: Operations', 'បន្ទាត់លេខ៖ ប្រតិបត្តិការ', 'Add and subtract on a number line.', 'បូក និងដកនៅលើបន្ទាត់លេខ។', 'Mathematics', 'Beginner', '{3,4,5,6}', 25, '{"Visualize addition and subtraction", "Use number line models"}', '{"មើលឃើញការបូក និងដក", "ប្រើគំរូបន្ទាត់លេខ"}', 'https://phet.colorado.edu/sims/html/number-line-operations/latest/number-line-operations_km.html', 'https://phet.colorado.edu/sims/html/number-line-operations/latest/number-line-operations-600.png', '{"mathematics", "number line", "addition", "subtraction"}', false, true),

('number-line-integers', 'Number Line: Integers', 'បន្ទាត់លេខ៖ ចំនួនគត់', 'Explore integers on a number line.', 'ស្វែងយល់ចំនួនគត់នៅលើបន្ទាត់លេខ។', 'Mathematics', 'Intermediate', '{6,7,8}', 25, '{"Understand negative numbers", "Compare integers"}', '{"យល់ដឹងពីលេខអវិជ្ជមាន", "ប្រៀបធៀបចំនួនគត់"}', 'https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers_km.html', 'https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers-600.png', '{"mathematics", "integers", "number line", "negative"}', true, true),

('vector-addition-equations', 'Vector Addition: Equations', 'ការបូកវ៉ិចទ័រ៖ សមីការ', 'Add vectors using equations.', 'បូកវ៉ិចទ័រដោយប្រើសមីការ។', 'Mathematics', 'Advanced', '{10,11,12}', 35, '{"Add vectors algebraically", "Solve vector equations"}', '{"បូកវ៉ិចទ័រពិជគណិត", "ដោះស្រាយសមីការវ៉ិចទ័រ"}', 'https://phet.colorado.edu/sims/html/vector-addition-equations/latest/vector-addition-equations_km.html', 'https://phet.colorado.edu/sims/html/vector-addition-equations/latest/vector-addition-equations-600.png', '{"mathematics", "vectors", "equations", "addition"}', false, true),

('vector-addition', 'Vector Addition', 'ការបូកវ៉ិចទ័រ', 'Learn how to add vectors graphically.', 'រៀនពីរបៀបបូកវ៉ិចទ័រដោយក្រាហ្វិច។', 'Mathematics', 'Intermediate', '{9,10,11,12}', 30, '{"Add vectors graphically", "Understand vector components"}', '{"បូកវ៉ិចទ័រដោយក្រាហ្វិច", "យល់ដឹងពីសមាសភាគវ៉ិចទ័រ"}', 'https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition_km.html', 'https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition-600.png', '{"mathematics", "vectors", "addition", "components"}', false, true),

('curve-fitting', 'Curve Fitting', 'ការបំពេញខ្សែកោង', 'Find the best fit curve for data points.', 'រកខ្សែកោងសមល្អបំផុតសម្រាប់ចំណុចទិន្នន័យ។', 'Mathematics', 'Advanced', '{10,11,12}', 35, '{"Fit curves to data", "Understand regression"}', '{"បំពេញខ្សែកោងទៅទិន្នន័យ", "យល់ដឹងពីការតំរែតំរង់"}', 'https://phet.colorado.edu/sims/html/curve-fitting/latest/curve-fitting_km.html', 'https://phet.colorado.edu/sims/html/curve-fitting/latest/curve-fitting-600.png', '{"mathematics", "statistics", "curve fitting", "regression"}', false, true),

('fractions-mixed-numbers', 'Fractions: Mixed Numbers', 'ប្រភាគ៖ លេខចម្រុះ', 'Build mixed numbers with fraction pieces.', 'សាងសង់លេខចម្រុះជាមួយបំណែកប្រភាគ។', 'Mathematics', 'Intermediate', '{4,5,6,7}', 30, '{"Understand mixed numbers", "Convert between forms"}', '{"យល់ដឹងពីលេខចម្រុះ", "បំប្លែងរវាងទម្រង់"}', 'https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers_km.html', 'https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers-600.png', '{"mathematics", "fractions", "mixed numbers", "conversion"}', false, true),

('fractions-intro', 'Fractions: Intro', 'ប្រភាគ៖ ការណែនាំ', 'Explore fractions using numbers and pictures.', 'ស្វែងយល់ប្រភាគដោយប្រើលេខ និងរូបភាព។', 'Mathematics', 'Beginner', '{3,4,5}', 25, '{"Understand fraction basics", "Visualize fractions"}', '{"យល់ដឹងពីមូលដ្ឋានប្រភាគ", "មើលឃើញប្រភាគ"}', 'https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_km.html', 'https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro-600.png', '{"mathematics", "fractions", "introduction", "basics"}', true, true),

('build-a-fraction', 'Build a Fraction', 'សាងសង់ប្រភាគ', 'Build fractions from shapes and numbers.', 'សាងសង់ប្រភាគពីរាង និងលេខ។', 'Mathematics', 'Beginner', '{3,4,5,6}', 25, '{"Build fractions", "Match representations"}', '{"សាងសង់ប្រភាគ", "ផ្គូផ្គងតំណាង"}', 'https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction_km.html', 'https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction-600.png', '{"mathematics", "fractions", "building", "shapes"}', true, true),

('fractions-equality', 'Fractions: Equality', 'ប្រភាគ៖ សមភាព', 'Explore equivalent fractions.', 'ស្វែងយល់ប្រភាគស្មើគ្នា។', 'Mathematics', 'Intermediate', '{4,5,6,7}', 30, '{"Find equivalent fractions", "Understand fraction equality"}', '{"រកប្រភាគស្មើគ្នា", "យល់ដឹងពីសមភាពប្រភាគ"}', 'https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality_km.html', 'https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality-600.png', '{"mathematics", "fractions", "equality", "equivalent"}', false, true),

('graphing-quadratics', 'Graphing Quadratics', 'គូសក្រាហ្វការេ', 'Discover how changing coefficients changes the shape.', 'រកឃើញពីរបៀបដែលការផ្លាស់ប្តូរមេគុណផ្លាស់ប្តូររាង។', 'Mathematics', 'Intermediate', '{8,9,10,11}', 35, '{"Graph quadratic functions", "Explore parabola properties"}', '{"គូសក្រាហ្វអនុគមន៍ការេ", "ស្វែងយល់លក្ខណៈសម្បត្តិប៉ារ៉ាបូល"}', 'https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics_km.html', 'https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics-600.png', '{"mathematics", "quadratics", "graphing", "parabola"}', true, true),

('equality-explorer-two-variables', 'Equality Explorer: Two Variables', 'អ្នកស្វែងរកសមភាព៖ អថេរពីរ', 'Solve systems of equations.', 'ដោះស្រាយប្រព័ន្ធសមីការ។', 'Mathematics', 'Advanced', '{8,9,10,11}', 40, '{"Solve systems of equations", "Understand two variables"}', '{"ដោះស្រាយប្រព័ន្ធសមីការ", "យល់ដឹងពីអថេរពីរ"}', 'https://phet.colorado.edu/sims/html/equality-explorer-two-variables/latest/equality-explorer-two-variables_km.html', 'https://phet.colorado.edu/sims/html/equality-explorer-two-variables/latest/equality-explorer-two-variables-600.png', '{"mathematics", "equations", "systems", "variables"}', false, true),

('equality-explorer-basics', 'Equality Explorer: Basics', 'អ្នកស្វែងរកសមភាព៖ មូលដ្ឋាន', 'Learn about equality with balance scales.', 'រៀនអំពីសមភាពជាមួយជញ្ជីងតុល្យភាព។', 'Mathematics', 'Beginner', '{6,7,8}', 25, '{"Understand equation balance", "Solve simple equations"}', '{"យល់ដឹងពីតុល្យភាពសមីការ", "ដោះស្រាយសមីការសាមញ្ញ"}', 'https://phet.colorado.edu/sims/html/equality-explorer-basics/latest/equality-explorer-basics_km.html', 'https://phet.colorado.edu/sims/html/equality-explorer-basics/latest/equality-explorer-basics-600.png', '{"mathematics", "equality", "balance", "equations"}', true, true),

('equality-explorer', 'Equality Explorer', 'អ្នកស្វែងរកសមភាព', 'Solve equations using balance scales.', 'ដោះស្រាយសមីការដោយប្រើជញ្ជីងតុល្យភាព។', 'Mathematics', 'Intermediate', '{7,8,9,10}', 30, '{"Solve equations visually", "Maintain equation balance"}', '{"ដោះស្រាយសមីការដោយមើលឃើញ", "រក្សាតុល្យភាពសមីការ"}', 'https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_km.html', 'https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer-600.png', '{"mathematics", "equations", "solving", "balance"}', true, true),

('area-model-algebra', 'Area Model Algebra', 'គំរូផ្ទៃពិជគណិត', 'Visualize algebraic expressions with area.', 'មើលឃើញកន្សោមពិជគណិតជាមួយផ្ទៃ។', 'Mathematics', 'Intermediate', '{7,8,9,10}', 35, '{"Multiply polynomials visually", "Factor quadratics"}', '{"គុណពហុធាដោយមើលឃើញ", "កត្តាការេ"}', 'https://phet.colorado.edu/sims/html/area-model-algebra/latest/area-model-algebra_km.html', 'https://phet.colorado.edu/sims/html/area-model-algebra/latest/area-model-algebra-600.png', '{"mathematics", "algebra", "area model", "polynomials"}', false, true),

('area-model-decimals', 'Area Model Decimals', 'គំរូផ្ទៃទសភាគ', 'Multiply decimals using area models.', 'គុណទសភាគដោយប្រើគំរូផ្ទៃ។', 'Mathematics', 'Intermediate', '{5,6,7,8}', 30, '{"Multiply decimals visually", "Understand place value"}', '{"គុណទសភាគដោយមើលឃើញ", "យល់ដឹងពីតម្លៃខ្ទង់"}', 'https://phet.colorado.edu/sims/html/area-model-decimals/latest/area-model-decimals_km.html', 'https://phet.colorado.edu/sims/html/area-model-decimals/latest/area-model-decimals-600.png', '{"mathematics", "decimals", "multiplication", "area"}', false, true),

('area-model-multiplication', 'Area Model Multiplication', 'គំរូផ្ទៃគុណ', 'Multiply using area models.', 'គុណដោយប្រើគំរូផ្ទៃ។', 'Mathematics', 'Beginner', '{3,4,5,6}', 25, '{"Visualize multiplication", "Build multiplication concepts"}', '{"មើលឃើញការគុណ", "កសាងគំនិតគុណ"}', 'https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication_km.html', 'https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication-600.png', '{"mathematics", "multiplication", "area", "visual"}', true, true),

('area-model-introduction', 'Area Model Introduction', 'ការណែនាំគំរូផ្ទៃ', 'Introduction to multiplication with area.', 'ការណែនាំការគុណជាមួយផ្ទៃ។', 'Mathematics', 'Beginner', '{3,4,5}', 20, '{"Introduce area models", "Basic multiplication"}', '{"ណែនាំគំរូផ្ទៃ", "ការគុណមូលដ្ឋាន"}', 'https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction_km.html', 'https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction-600.png', '{"mathematics", "area", "introduction", "multiplication"}', false, true),

('expression-exchange', 'Expression Exchange', 'ការប្តូរកន្សោម', 'Build and explore algebraic expressions.', 'សាងសង់ និងស្វែងយល់កន្សោមពិជគណិត។', 'Mathematics', 'Intermediate', '{6,7,8,9}', 35, '{"Build algebraic expressions", "Understand like terms"}', '{"សាងសង់កន្សោមពិជគណិត", "យល់ដឹងពីធាតុដូចគ្នា"}', 'https://phet.colorado.edu/sims/html/expression-exchange/latest/expression-exchange_km.html', 'https://phet.colorado.edu/sims/html/expression-exchange/latest/expression-exchange-600.png', '{"mathematics", "algebra", "expressions", "variables"}', false, true),

('graphing-slope-intercept', 'Graphing Slope-Intercept', 'គូសក្រាហ្វជម្រាល-ប្រសព្វ', 'Graph lines in slope-intercept form.', 'គូសក្រាហ្វបន្ទាត់ក្នុងទម្រង់ជម្រាល-ប្រសព្វ។', 'Mathematics', 'Intermediate', '{8,9,10}', 30, '{"Graph y = mx + b", "Understand slope and intercept"}', '{"គូសក្រាហ្វ y = mx + b", "យល់ដឹងពីជម្រាល និងប្រសព្វ"}', 'https://phet.colorado.edu/sims/html/graphing-slope-intercept/latest/graphing-slope-intercept_km.html', 'https://phet.colorado.edu/sims/html/graphing-slope-intercept/latest/graphing-slope-intercept-600.png', '{"mathematics", "graphing", "slope", "linear"}', false, true),

('function-builder-basics', 'Function Builder: Basics', 'អ្នកសាងសង់អនុគមន៍៖ មូលដ្ឋាន', 'Build and explore simple functions.', 'សាងសង់ និងស្វែងយល់អនុគមន៍សាមញ្ញ។', 'Mathematics', 'Beginner', '{5,6,7,8}', 25, '{"Build simple functions", "Understand input-output"}', '{"សាងសង់អនុគមន៍សាមញ្ញ", "យល់ដឹងពីធាតុចូល-ចេញ"}', 'https://phet.colorado.edu/sims/html/function-builder-basics/latest/function-builder-basics_km.html', 'https://phet.colorado.edu/sims/html/function-builder-basics/latest/function-builder-basics-600.png', '{"mathematics", "functions", "basics", "patterns"}', false, true),

('proportion-playground', 'Proportion Playground', 'សួនកុមារផលធៀប', 'Play with proportions in different contexts.', 'លេងជាមួយផលធៀបក្នុងបរិបទផ្សេងៗ។', 'Mathematics', 'Intermediate', '{6,7,8,9}', 30, '{"Explore proportional relationships", "Apply ratios"}', '{"ស្វែងយល់ទំនាក់ទំនងសមាមាត្រ", "អនុវត្តសមាមាត្រ"}', 'https://phet.colorado.edu/sims/html/proportion-playground/latest/proportion-playground_km.html', 'https://phet.colorado.edu/sims/html/proportion-playground/latest/proportion-playground-600.png', '{"mathematics", "proportion", "ratio", "relationships"}', true, true),

('unit-rates', 'Unit Rates', 'អត្រាឯកតា', 'Discover unit rates in everyday situations.', 'រកឃើញអត្រាឯកតាក្នុងស្ថានភាពប្រចាំថ្ងៃ។', 'Mathematics', 'Intermediate', '{6,7,8}', 25, '{"Calculate unit rates", "Compare rates"}', '{"គណនាអត្រាឯកតា", "ប្រៀបធៀបអត្រា"}', 'https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_km.html', 'https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates-600.png', '{"mathematics", "rates", "ratios", "unit"}', false, true),

('make-a-ten', 'Make a Ten', 'បង្កើតដប់', 'Add numbers by making tens.', 'បូកលេខដោយបង្កើតដប់។', 'Mathematics', 'Beginner', '{1,2,3,4}', 20, '{"Make tens strategy", "Build addition fluency"}', '{"យុទ្ធសាស្ត្របង្កើតដប់", "កសាងភាពស្ទាត់ជំនាញបូក"}', 'https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten_km.html', 'https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten-600.png', '{"mathematics", "addition", "tens", "strategy"}', true, true),

('plinko-probability', 'Plinko Probability', 'ប្រូបាប៊ីលីតេផ្លីងកូ', 'Play Plinko and develop probability intuition.', 'លេងផ្លីងកូ និងអភិវឌ្ឍវិចារណញាណប្រូបាប៊ីលីតេ។', 'Mathematics', 'Intermediate', '{7,8,9,10}', 35, '{"Explore probability distributions", "Understand randomness"}', '{"ស្វែងយល់ការបែងចែកប្រូបាប៊ីលីតេ", "យល់ដឹងពីភាពចៃដន្យ"}', 'https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability_km.html', 'https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability-600.png', '{"mathematics", "probability", "statistics", "distribution"}', true, true),

('trig-tour', 'Trig Tour', 'ដំណើរទេសចរណ៍ត្រីកោណមាត្រ', 'Take a tour of trigonometry.', 'ធ្វើដំណើរទេសចរណ៍នៃត្រីកោណមាត្រ។', 'Mathematics', 'Advanced', '{10,11,12}', 40, '{"Explore trigonometric functions", "Understand unit circle"}', '{"ស្វែងយល់អនុគមន៍ត្រីកោណមាត្រ", "យល់ដឹងពីរង្វង់ឯកតា"}', 'https://phet.colorado.edu/sims/html/trig-tour/latest/trig-tour_km.html', 'https://phet.colorado.edu/sims/html/trig-tour/latest/trig-tour-600.png', '{"mathematics", "trigonometry", "sine", "cosine"}', false, true),

('least-squares-regression', 'Least-Squares Regression', 'ការតំរែតំរង់ការេតូចបំផុត', 'Find the line of best fit.', 'រកបន្ទាត់សមល្អបំផុត។', 'Mathematics', 'Advanced', '{11,12}', 35, '{"Perform linear regression", "Minimize squared errors"}', '{"ធ្វើការតំរែតំរង់លីនេអ៊ែរ", "បន្ថយកំហុសការេ"}', 'https://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression_km.html', 'https://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression-600.png', '{"mathematics", "statistics", "regression", "least squares"}', false, true);

-- Count total simulations
SELECT COUNT(*) as total_simulations FROM stem_simulations_catalog;