-- Stage 3: Exercises for simulations 18-32
-- Creating 5 exercises per simulation for 15 simulations = 75 total exercises

-- 18. Build an Atom (d33f834a-20e4-49b5-97b6-2bb73b4dc72f)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 1, 'multiple_choice',
'Which subatomic particle has a negative charge?',
'តើភាគល្អិតតូចជាងអាតូមមួយណាមានបន្ទុកអវិជ្ជមាន?',
'Choose the correct particle.',
'ជ្រើសរើសភាគល្អិតត្រឹមត្រូវ។',
'{"options": [{"en": "Proton", "km": "ប្រូតុង"}, {"en": "Neutron", "km": "នឺត្រុង"}, {"en": "Electron", "km": "អេឡិចត្រុង"}, {"en": "Nucleus", "km": "ស្នូល"}]}',
'Electron',
10, 'easy',
'It orbits the nucleus.',
'វាគោចរជុំវិញស្នូល។',
'Electrons have a negative charge (-1), protons have a positive charge (+1), and neutrons are neutral (0).',
'អេឡិចត្រុងមានបន្ទុកអវិជ្ជមាន (-1) ប្រូតុងមានបន្ទុកវិជ្ជមាន (+1) និងនឺត្រុងអព្យាក្រឹត (0)។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 2, 'true_false',
'A neutral atom has equal numbers of protons and electrons.',
'អាតូមអព្យាក្រឹតមានចំនួនប្រូតុង និងអេឡិចត្រុងស្មើគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about charge balance.',
'គិតអំពីតុល្យភាពបន្ទុក។',
'In a neutral atom, the positive charges from protons balance the negative charges from electrons.',
'ក្នុងអាតូមអព្យាក្រឹត បន្ទុកវិជ្ជមានពីប្រូតុងតុល្យភាពបន្ទុកអវិជ្ជមានពីអេឡិចត្រុង។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 3, 'calculation',
'An ion has 11 protons and 10 electrons. What is its charge?',
'អ៊ីយ៉ុងមួយមានប្រូតុង 11 និងអេឡិចត្រុង 10។ តើបន្ទុករបស់វាគឺប៉ុន្មាន?',
'Calculate the net charge.',
'គណនាបន្ទុកសុទ្ធ។',
NULL,
'+1',
10, 'easy',
'Compare positive and negative charges.',
'ប្រៀបធៀបបន្ទុកវិជ្ជមាន និងអវិជ្ជមាន។',
'Charge = number of protons - number of electrons = 11 - 10 = +1',
'បន្ទុក = ចំនួនប្រូតុង - ចំនួនអេឡិចត្រុង = 11 - 10 = +1'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 4, 'short_answer',
'What element has 79 protons?',
'តើធាតុអ្វីមានប្រូតុង 79?',
'Name the element.',
'បញ្ជាក់ឈ្មោះធាតុ។',
NULL,
'Gold',
10, 'medium',
'Check the periodic table.',
'ពិនិត្យតារាងខួបធាតុគីមី។',
'Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.',
'មាស (Au) មានលេខអាតូម 79 មានន័យថាវាមានប្រូតុង 79 ក្នុងស្នូលរបស់វា។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 5, 'fill_blank',
'The atomic number of an element equals the number of _____ in its atoms.',
'លេខអាតូមនៃធាតុស្មើនឹងចំនួន _____ ក្នុងអាតូមរបស់វា។',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
NULL,
'protons',
10, 'easy',
'This defines the element.',
'នេះកំណត់ធាតុ។',
'The atomic number is defined as the number of protons in an atom and determines which element it is.',
'លេខអាតូមត្រូវបានកំណត់ជាចំនួនប្រូតុងក្នុងអាតូម និងកំណត់ថាវាជាធាតុមួយណា។'),

-- 19. Buoyancy (12d928e0-03b4-468c-922a-f2b68c735a3b)
('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 1, 'multiple_choice',
'What force causes objects to float in fluids?',
'តើកម្លាំងអ្វីធ្វើឲ្យវត្ថុអណ្តែតក្នុងអង្គធាតុរាវ?',
'Choose the correct force.',
'ជ្រើសរើសកម្លាំងត្រឹមត្រូវ។',
'{"options": [{"en": "Gravity", "km": "ទំនាញផែនដី"}, {"en": "Buoyant force", "km": "កម្លាំងអណ្តែត"}, {"en": "Magnetic force", "km": "កម្លាំងម៉ាញេទិច"}, {"en": "Friction", "km": "កកិត"}]}',
'Buoyant force',
10, 'easy',
'Upward force from fluid.',
'កម្លាំងឡើងលើពីអង្គធាតុរាវ។',
'Buoyant force is the upward force exerted by fluid on immersed objects, opposing gravity.',
'កម្លាំងអណ្តែតគឺជាកម្លាំងឡើងលើដែលអង្គធាតុរាវបង្កើតលើវត្ថុដែលជ្រមុជ ប្រឆាំងនឹងទំនាញផែនដី។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 2, 'true_false',
'An object will float if its density is less than the fluid density.',
'វត្ថុនឹងអណ្តែតប្រសិនបើដង់ស៊ីតេរបស់វាតិចជាងដង់ស៊ីតេអង្គធាតុរាវ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Think about Archimedes\' principle.',
'គិតអំពីគោលការណ៍អារកេម៉ែដ។',
'Objects float when their average density is less than the fluid they are in.',
'វត្ថុអណ្តែតនៅពេលដង់ស៊ីតេមធ្យមរបស់វាតិចជាងអង្គធាតុរាវដែលវាស្ថិតក្នុង។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 3, 'calculation',
'A 2 kg object displaces 3 liters of water. What is the buoyant force? (g = 10 N/kg)',
'វត្ថុ 2 kg បណ្តេញទឹក 3 លីត្រ។ តើកម្លាំងអណ្តែតគឺប៉ុន្មាន? (g = 10 N/kg)',
'Use Archimedes\' principle.',
'ប្រើគោលការណ៍អារកេម៉ែដ។',
NULL,
'30 N',
15, 'medium',
'Buoyant force = weight of displaced fluid',
'កម្លាំងអណ្តែត = ទម្ងន់អង្គធាតុរាវដែលបណ្តេញ',
'Buoyant force = volume × density × g = 3 L × 1 kg/L × 10 N/kg = 30 N',
'កម្លាំងអណ្តែត = មាឌ × ដង់ស៊ីតេ × g = 3 L × 1 kg/L × 10 N/kg = 30 N'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 4, 'short_answer',
'Why do ships made of steel float on water?',
'ហេតុអ្វីបានជាកប៉ាល់ធ្វើពីដែកអណ្តែតលើទឹក?',
'Explain the principle.',
'ពន្យល់គោលការណ៍។',
NULL,
'They displace more water than their weight',
15, 'medium',
'Consider the ship\'s shape.',
'ពិចារណារូបរាងកប៉ាល់។',
'Ships have hollow hulls that displace large volumes of water, making their overall density less than water.',
'កប៉ាល់មានតួប្រហោងដែលបណ្តេញទឹកបរិមាណច្រើន ធ្វើឲ្យដង់ស៊ីតេសរុបតិចជាងទឹក។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 5, 'fill_blank',
'According to Archimedes\' principle, buoyant force equals the _____ of displaced fluid.',
'យោងតាមគោលការណ៍អារកេម៉ែដ កម្លាំងអណ្តែតស្មើនឹង _____ នៃអង្គធាតុរាវដែលបណ្តេញ។',
'Complete the principle.',
'បំពេញគោលការណ៍។',
NULL,
'weight',
10, 'easy',
'What does the fluid weigh?',
'តើអង្គធាតុរាវមានទម្ងន់ប៉ុន្មាន?',
'Archimedes\' principle: buoyant force equals the weight of the fluid displaced by the object.',
'គោលការណ៍អារកេម៉ែដ៖ កម្លាំងអណ្តែតស្មើនឹងទម្ងន់នៃអង្គធាតុរាវដែលវត្ថុបណ្តេញ។'),

-- 20. Buoyancy: Basics (df501e19-2322-4026-ac6f-77abf12a4015)
('df501e19-2322-4026-ac6f-77abf12a4015', 1, 1, 'multiple_choice',
'What happens when you put a cork in water?',
'តើអ្វីកើតឡើងនៅពេលអ្នកដាក់ឆ្នុកក្នុងទឹក?',
'Predict the result.',
'ទាយលទ្ធផល។',
'{"options": [{"en": "It sinks", "km": "វាលិច"}, {"en": "It floats", "km": "វាអណ្តែត"}, {"en": "It dissolves", "km": "វារលាយ"}, {"en": "Nothing happens", "km": "គ្មានអ្វីកើតឡើង"}]}',
'It floats',
10, 'easy',
'Cork is less dense than water.',
'ឆ្នុកមានដង់ស៊ីតេតិចជាងទឹក។',
'Cork floats because it is less dense than water, so the buoyant force is greater than its weight.',
'ឆ្នុកអណ្តែតពីព្រោះវាមានដង់ស៊ីតេតិចជាងទឹក ដូច្នេះកម្លាំងអណ្តែតធំជាងទម្ងន់របស់វា។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 2, 'true_false',
'All metals sink in water.',
'លោហៈទាំងអស់លិចក្នុងទឹក។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Think about shape and air.',
'គិតអំពីរូបរាង និងខ្យល់។',
'While most solid metals are denser than water, metal objects with air inside (like boats) can float.',
'ទោះបីលោហៈរឹងភាគច្រើនមានដង់ស៊ីតេខ្ពស់ជាងទឹក វត្ថុលោហៈដែលមានខ្យល់នៅខាងក្នុង (ដូចជាទូក) អាចអណ្តែតបាន។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 3, 'short_answer',
'Why does ice float on water?',
'ហេតុអ្វីបានជាទឹកកកអណ្តែតលើទឹក?',
'Explain the reason.',
'ពន្យល់មូលហេតុ។',
NULL,
'Ice is less dense than water',
10, 'easy',
'Water expands when it freezes.',
'ទឹកពង្រីកនៅពេលកក។',
'When water freezes, it expands and becomes less dense than liquid water, so ice floats.',
'នៅពេលទឹកកក វាពង្រីក និងក្លាយជាដង់ស៊ីតេតិចជាងទឹករាវ ដូច្នេះទឹកកកអណ្តែត។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 4, 'fill_blank',
'Objects that are _____ dense than water will float.',
'វត្ថុដែលមានដង់ស៊ីតេ _____ ជាងទឹកនឹងអណ្តែត។',
'Complete the comparison.',
'បំពេញការប្រៀបធៀប។',
NULL,
'less',
10, 'easy',
'Floating objects are lighter.',
'វត្ថុអណ្តែតស្រាលជាង។',
'Objects with density less than water (1 g/cm³) will float on water\'s surface.',
'វត្ថុដែលមានដង់ស៊ីតេតិចជាងទឹក (1 g/cm³) នឹងអណ្តែតលើផ្ទៃទឹក។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 5, 'multiple_choice',
'What would happen to a floating object if you pushed it underwater?',
'តើអ្វីនឹងកើតឡើងចំពោះវត្ថុអណ្តែតប្រសិនបើអ្នករុញវាចុះក្រោមទឹក?',
'Predict the behavior.',
'ទាយអាកប្បកិរិយា។',
'{"options": [{"en": "It stays underwater", "km": "វានៅក្រោមទឹក"}, {"en": "It pops back up", "km": "វាលេចឡើងវិញ"}, {"en": "It dissolves", "km": "វារលាយ"}, {"en": "It gets heavier", "km": "វាធ្ងន់ឡើង"}]}',
'It pops back up',
15, 'medium',
'Buoyant force pushes it up.',
'កម្លាំងអណ្តែតរុញវាឡើងលើ។',
'When submerged, the buoyant force becomes greater than the object\'s weight, pushing it back to the surface.',
'នៅពេលជ្រមុជ កម្លាំងអណ្តែតក្លាយជាធំជាងទម្ងន់វត្ថុ រុញវាត្រលប់ទៅផ្ទៃ។'),

-- 21. Calculus Grapher (01ad94ed-a1ba-4f5d-816e-9edd940b7ab0)
('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 1, 'multiple_choice',
'What does the derivative of a function represent?',
'តើដេរីវេនៃអនុគមន៍តំណាងឲ្យអ្វី?',
'Choose the mathematical meaning.',
'ជ្រើសរើសន័យគណិតវិទ្យា។',
'{"options": [{"en": "The area under the curve", "km": "ផ្ទៃក្រោមខ្សែកោង"}, {"en": "The rate of change", "km": "អត្រាការផ្លាស់ប្តូរ"}, {"en": "The maximum value", "km": "តម្លៃអតិបរមា"}, {"en": "The average", "km": "មធ្យម"}]}',
'The rate of change',
15, 'medium',
'Think about slope.',
'គិតអំពីជម្រាល។',
'The derivative represents the instantaneous rate of change or slope of the function at any point.',
'ដេរីវេតំណាងឲ្យអត្រាការផ្លាស់ប្តូរភ្លាមៗ ឬជម្រាលនៃអនុគមន៍នៅចំណុចណាមួយ។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 2, 'calculation',
'What is the derivative of f(x) = x²?',
'តើដេរីវេនៃ f(x) = x² គឺអ្វី?',
'Apply the power rule.',
'អនុវត្តច្បាប់កម្លាំង។',
NULL,
'2x',
10, 'easy',
'Power rule: d/dx(xⁿ) = nxⁿ⁻¹',
'ច្បាប់កម្លាំង៖ d/dx(xⁿ) = nxⁿ⁻¹',
'Using the power rule: d/dx(x²) = 2x²⁻¹ = 2x¹ = 2x',
'ប្រើច្បាប់កម្លាំង៖ d/dx(x²) = 2x²⁻¹ = 2x¹ = 2x'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 3, 'true_false',
'The integral is the reverse operation of differentiation.',
'អាំងតេក្រាលគឺជាប្រតិបត្តិការច្រាសនៃការធ្វើដេរីវេ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'They are inverse operations.',
'ពួកវាជាប្រតិបត្តិការច្រាស។',
'Integration and differentiation are inverse operations - integration undoes differentiation.',
'អាំងតេក្រាល និងការធ្វើដេរីវេជាប្រតិបត្តិការច្រាស - អាំងតេក្រាលដោះសេចការធ្វើដេរីវេ។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 4, 'fill_blank',
'The second derivative tells us about the _____ of a function.',
'ដេរីវេទីពីរប្រាប់យើងអំពី _____ របស់អនុគមន៍។',
'What property does it describe?',
'តើវាពិពណ៌នាលក្ខណៈសម្បត្តិអ្វី?',
NULL,
'concavity',
15, 'medium',
'Up or down curvature.',
'ខ្សែកោងឡើងលើ ឬចុះក្រោម។',
'The second derivative indicates concavity - whether the function curves up (positive) or down (negative).',
'ដេរីវេទីពីរបង្ហាញភាពកោង - ថាតើអនុគមន៍កោងឡើងលើ (វិជ្ជមាន) ឬចុះក្រោម (អវិជ្ជមាន)។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 5, 'short_answer',
'What does it mean when the derivative equals zero?',
'តើមានន័យអ្វីនៅពេលដេរីវេស្មើសូន្យ?',
'Describe this condition.',
'ពិពណ៌នាលក្ខខណ្ឌនេះ។',
NULL,
'Critical point or turning point',
15, 'medium',
'The slope is zero.',
'ជម្រាលស្មើសូន្យ។',
'When f\'(x) = 0, we have a critical point where the function may have a maximum, minimum, or inflection point.',
'នៅពេល f\'(x) = 0 យើងមានចំណុចវិបត្តិដែលអនុគមន៍អាចមានអតិបរមា អប្បបរមា ឬចំណុចពត់។'),

-- 22. Capacitor Lab: Basics (3649be5b-3c1d-4468-a690-00675ae843a4)
('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 1, 'multiple_choice',
'What is a capacitor?',
'តើកាប៉ាស៊ីតរ័គឺជាអ្វី?',
'Choose the best definition.',
'ជ្រើសរើសនិយមន្តល្អបំផុត។',
'{"options": [{"en": "A device that stores electric charge", "km": "ឧបករណ៍រក្សាទុកបន្ទុកអគ្គិសនី"}, {"en": "A device that creates electricity", "km": "ឧបករណ៍បង្កើតអគ្គិសនី"}, {"en": "A type of battery", "km": "ប្រភេទថ្ម"}, {"en": "A resistor", "km": "ធាតុទប់"}]}',
'A device that stores electric charge',
10, 'easy',
'It holds electrical energy.',
'វារក្សាទុកថាមពលអគ្គិសនី។',
'A capacitor stores electric charge on two conducting plates separated by an insulator (dielectric).',
'កាប៉ាស៊ីតរ័រក្សាទុកបន្ទុកអគ្គិសនីលើបន្ទះចំនួនពីរដែលបំបែកដោយអ៊ីសូឡង់ (ដាយអេឡិចត្រិច)។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 2, 'calculation',
'A capacitor has a capacitance of 10 μF and is charged to 12 V. How much charge does it store?',
'កាប៉ាស៊ីតរ័មួយមានកាប៉ាស៊ីតង់ 10 μF និងត្រូវបានបញ្ចូលបន្ទុកទៅ 12 V។ តើវារក្សាទុកបន្ទុកប៉ុន្មាន?',
'Use Q = CV',
'ប្រើ Q = CV',
NULL,
'120 μC',
15, 'medium',
'Q = C × V',
'Q = C × V',
'Q = CV = 10 μF × 12 V = 120 μC (microcoulombs)',
'Q = CV = 10 μF × 12 V = 120 μC (មីក្រូកូឡុម)'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 3, 'true_false',
'Increasing the distance between capacitor plates decreases capacitance.',
'ការបង្កើនចម្ងាយរវាងបន្ទះកាប៉ាស៊ីតរ័បន្ថយកាប៉ាស៊ីតង់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Think about the capacitance formula.',
'គិតអំពីរូបមន្តកាប៉ាស៊ីតង់។',
'Capacitance C = ε₀A/d, so increasing distance d decreases capacitance.',
'កាប៉ាស៊ីតង់ C = ε₀A/d ដូច្នេះការបង្កើនចម្ងាយ d បន្ថយកាប៉ាស៊ីតង់។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 4, 'short_answer',
'What happens to the electric field when you increase the voltage across a capacitor?',
'តើអ្វីកើតឡើងចំពោះវាលអគ្គិសនីនៅពេលអ្នកបង្កើនវ៉ុលនៅលើកាប៉ាស៊ីតរ័?',
'Describe the relationship.',
'ពិពណ៌នាទំនាក់ទំនង។',
NULL,
'Electric field increases',
10, 'easy',
'E = V/d',
'E = V/d',
'Electric field E = V/d, so increasing voltage V increases the electric field between the plates.',
'វាលអគ្គិសនី E = V/d ដូច្នេះការបង្កើនវ៉ុល V បង្កើនវាលអគ្គិសនីរវាងបន្ទះ។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 5, 'fill_blank',
'The energy stored in a capacitor is given by U = ½_____ .',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័ត្រូវបានផ្តល់ដោយ U = ½_____ ។',
'Complete the energy formula.',
'បំពេញរូបមន្តថាមពល។',
NULL,
'CV²',
15, 'medium',
'Energy formula for capacitors.',
'រូបមន្តថាមពលសម្រាប់កាប៉ាស៊ីតរ័។',
'The energy stored in a capacitor is U = ½CV², where C is capacitance and V is voltage.',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័គឺ U = ½CV² ដែល C គឺកាប៉ាស៊ីតង់ និង V គឺវ៉ុល។'),

-- 23. Center and Variability (6e40860a-bdf2-4d87-915e-ae7562e11c3e)
('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 1, 'multiple_choice',
'Which measure of center is most affected by outliers?',
'តើរង្វាស់កណ្តាលមួយណាត្រូវបានប៉ះពាល់បំផុតដោយតម្លៃខុសពីធម្មតា?',
'Choose the most sensitive measure.',
'ជ្រើសរើសរង្វាស់រសើបបំផុត។',
'{"options": [{"en": "Mean", "km": "មធ្យម"}, {"en": "Median", "km": "មេដ្យាន"}, {"en": "Mode", "km": "ម៉ូដ"}, {"en": "Range", "km": "ជួរ"}]}',
'Mean',
10, 'medium',
'Think about calculation methods.',
'គិតអំពីវិធីគណនា។',
'The mean uses all data values in its calculation, so extreme values (outliers) greatly affect it.',
'មធ្យមប្រើតម្លៃទិន្នន័យទាំងអស់ក្នុងការគណនា ដូច្នេះតម្លៃខុសពីធម្មតាប៉ះពាល់វាយ៉ាងខ្លាំង។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 2, 'calculation',
'Find the median of: 3, 7, 2, 9, 5, 8, 4',
'រកមេដ្យាននៃ៖ 3, 7, 2, 9, 5, 8, 4',
'Order the data first.',
'រៀបលំដាប់ទិន្នន័យមុន។',
NULL,
'5',
10, 'easy',
'Find the middle value.',
'រកតម្លៃកណ្តាល។',
'Ordered: 2, 3, 4, 5, 7, 8, 9. The median is the middle value: 5.',
'រៀបលំដាប់៖ 2, 3, 4, 5, 7, 8, 9។ មេដ្យានគឺតម្លៃកណ្តាល៖ 5។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 3, 'true_false',
'Standard deviation measures how spread out the data is.',
'ស្ដង់ដារដេវីយ៉ាស៊ុងវាស់បរិមាណការបែកខ្ចាត់ខ្ចាយទិន្នន័យ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'It measures variability.',
'វាវាស់ភាពប្រែប្រួល។',
'Standard deviation quantifies the average distance of data points from the mean, indicating spread.',
'ស្ដង់ដារដេវីយ៉ាស៊ុងកំណត់បរិមាណចម្ងាយមធ្យមនៃចំណុចទិន្នន័យពីមធ្យម បង្ហាញការបែកខ្ចាត់ខ្ចាយ។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 4, 'fill_blank',
'The _____ is the difference between the maximum and minimum values in a dataset.',
'_____ គឺជាភាពខុសគ្នារវាងតម្លៃអតិបរមា និងអប្បបរមាក្នុងសំណុំទិន្នន័យ។',
'Name this measure of spread.',
'ដាក់ឈ្មោះរង្វាស់ការបែកខ្ចាយនេះ។',
NULL,
'range',
10, 'easy',
'Simplest measure of variability.',
'រង្វាស់ភាពប្រែប្រួលសាមញ្ញបំផុត។',
'Range = Maximum - Minimum, giving the total spread of the data.',
'ជួរ = អតិបរមា - អប្បបរមា ផ្តល់ការបែកខ្ចាត់ខ្ចាយសរុបនៃទិន្នន័យ។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 5, 'short_answer',
'When is the median a better measure of center than the mean?',
'តើនៅពេលណាមេដ្យានជារង្វាស់កណ្តាលល្អជាងមធ្យម?',
'Consider data characteristics.',
'ពិចារណាលក្ខណៈទិន្នន័យ។',
NULL,
'When data has outliers or is skewed',
15, 'medium',
'Think about robustness.',
'គិតអំពីភាពធន់។',
'Median is better when data is skewed or has outliers because it\'s not affected by extreme values.',
'មេដ្យានល្អជាងនៅពេលទិន្នន័យលំអៀង ឬមានតម្លៃខុសពីធម្មតាពីព្រោះវាមិនត្រូវបានប៉ះពាល់ដោយតម្លៃខុសពីធម្មតា។'),

-- 24. Charges and Fields (1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f)
('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 1, 'multiple_choice',
'What happens between two positive charges?',
'តើអ្វីកើតឡើងរវាងបន្ទុកវិជ្ជមានពីរ?',
'Choose the interaction.',
'ជ្រើសរើសអន្តរកម្ម។',
'{"options": [{"en": "They attract", "km": "ពួកវាទាក់ទាញ"}, {"en": "They repel", "km": "ពួកវាច្រាន"}, {"en": "No interaction", "km": "គ្មានអន្តរកម្ម"}, {"en": "They neutralize", "km": "ពួកវាអព្យាក្រឹត"}]}',
'They repel',
10, 'easy',
'Like charges repel.',
'បន្ទុកដូចគ្នាច្រាន។',
'According to Coulomb\'s law, like charges (same sign) repel each other with a force.',
'យោងតាមច្បាប់កូឡុម បន្ទុកដូចគ្នា (សញ្ញាដូចគ្នា) ច្រានគ្នាដោយកម្លាំង។'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 2, 'calculation',
'Two charges of +2 μC each are 3 cm apart. What is the force between them? (k = 9×10⁹ N⋅m²/C²)',
'បន្ទុកពីរ +2 μC នីមួយៗនៅចម្ងាយ 3 cm ពីគ្នា។ តើកម្លាំងរវាងពួកវាគឺប៉ុន្មាន? (k = 9×10⁹ N⋅m²/C²)',
'Use Coulomb\'s law: F = kq₁q₂/r²',
'ប្រើច្បាប់កូឡុម៖ F = kq₁q₂/r²',
NULL,
'40 N',
20, 'hard',
'Convert units first.',
'បម្លែងឯកតាមុន។',
'F = (9×10⁹)(2×10⁻⁶)(2×10⁻⁶)/(0.03)² = 36×10⁻³/9×10⁻⁴ = 40 N',
'F = (9×10⁹)(2×10⁻⁶)(2×10⁻⁶)/(0.03)² = 36×10⁻³/9×10⁻⁴ = 40 N'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 3, 'true_false',
'Electric field lines always point away from positive charges.',
'បន្ទាត់វាលអគ្គិសនីតែងតែចង្អុលចេញពីបន្ទុកវិជ្ជមាន។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Convention for field direction.',
'ការសម្រេចសម្រាប់ទិសវាល។',
'By convention, electric field lines point away from positive charges and toward negative charges.',
'យោងតាមការសម្រេច បន្ទាត់វាលអគ្គិសនីចង្អុលចេញពីបន្ទុកវិជ្ជមាន និងទៅកាន់បន្ទុកអវិជ្ជមាន។'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 4, 'fill_blank',
'The electric field strength is measured in units of _____.',
'កម្លាំងវាលអគ្គិសនីត្រូវបានវាស់ជាឯកតា _____។',
'What are the SI units?',
'តើឯកតា SI អ្វីខ្លះ?',
NULL,
'N/C',
10, 'easy',
'Force per unit charge.',
'កម្លាំងក្នុងមួយឯកតាបន្ទុក។',
'Electric field E = F/q, so units are Newtons per Coulomb (N/C) or Volts per meter (V/m).',
'វាលអគ្គិសនី E = F/q ដូច្នេះឯកតាគឺនូតុនក្នុងមួយកូឡុម (N/C) ឬវ៉ុលក្នុងមួយម៉ែត្រ (V/m)។'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 5, 'short_answer',
'What is an electric dipole?',
'តើឌីប៉ូលអគ្គិសនីជាអ្វី?',
'Define this configuration.',
'កំណត់និយមន្តការរៀបចំនេះ។',
NULL,
'Two equal and opposite charges separated by distance',
15, 'medium',
'Positive and negative pair.',
'គូវិជ្ជមាន និងអវិជ្ជមាន។',
'An electric dipole consists of two equal but opposite charges (+q and -q) separated by a small distance.',
'ឌីប៉ូលអគ្គិសនីមានបន្ទុកពីរស្មើគ្នាប៉ុន្តែផ្ទុយគ្នា (+q និង -q) បំបែកដោយចម្ងាយតូច។'),

-- 25. Circuit Construction Kit: AC (c0ee9bf6-3691-4cee-931d-33e3106b5413)
('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 1, 'multiple_choice',
'What does AC stand for in electrical circuits?',
'តើ AC មានន័យថាអ្វីក្នុងសៀគ្វីអគ្គិសនី?',
'Choose the correct term.',
'ជ្រើសរើសពាក្យត្រឹមត្រូវ។',
'{"options": [{"en": "Alternating Current", "km": "ចរន្តឆ្លាស់"}, {"en": "Active Circuit", "km": "សៀគ្វីសកម្ម"}, {"en": "Automatic Control", "km": "ការគ្រប់គ្រងស្វ័យប្រវត្តិ"}, {"en": "Additional Capacity", "km": "ចំណុះបន្ថែម"}]}',
'Alternating Current',
10, 'easy',
'Current that changes direction.',
'ចរន្តដែលផ្លាស់ប្តូរទិស។',
'AC (Alternating Current) periodically reverses direction, unlike DC which flows in one direction.',
'AC (ចរន្តឆ្លាស់) ផ្លាស់ប្តូរទិសជាកាលកំណត់ ខុសពី DC ដែលហូរតាមមួយទិស។'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 2, 'true_false',
'AC voltage constantly changes its polarity.',
'វ៉ុល AC ផ្លាស់ប្តូរប៉ូលារ៉ីតេជាប់ៗ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'That\'s what makes it alternating.',
'នោះហើយជាការធ្វើឲ្យវាឆ្លាស់។',
'In AC circuits, voltage alternates between positive and negative values in a sinusoidal pattern.',
'ក្នុងសៀគ្វី AC វ៉ុលឆ្លាស់រវាងតម្លៃវិជ្ជមាន និងអវិជ្ជមានតាមលំនាំស៊ីនុស។'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 3, 'calculation',
'If an AC source has a frequency of 60 Hz, what is its period?',
'ប្រសិនបើប្រភព AC មានប្រេកង់ 60 Hz តើខួបកាលរបស់វាគឺប៉ុន្មាន?',
'Use T = 1/f',
'ប្រើ T = 1/f',
NULL,
'1/60 s or 0.0167 s',
15, 'medium',
'Period and frequency are reciprocals.',
'ខួបកាល និងប្រេកង់ជាផ្ទុយគ្នា។',
'T = 1/f = 1/60 Hz = 0.0167 seconds (about 16.7 milliseconds)',
'T = 1/f = 1/60 Hz = 0.0167 វិនាទី (ប្រហែល 16.7 មីលីវិនាទី)'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 4, 'fill_blank',
'In an AC circuit, the effective (RMS) voltage is _____ times the peak voltage.',
'ក្នុងសៀគ្វី AC វ៉ុលប្រសិទ្ធភាព (RMS) គឺ _____ ដងវ៉ុលកំពូល។',
'Enter the multiplier.',
'បញ្ចូលតួគុណ។',
NULL,
'0.707',
15, 'medium',
'RMS = Peak/√2',
'RMS = កំពូល/√2',
'RMS voltage = Peak voltage / √2 ≈ 0.707 × Peak voltage',
'វ៉ុល RMS = វ៉ុលកំពូល / √2 ≈ 0.707 × វ៉ុលកំពូល'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 5, 'short_answer',
'Why is AC used for power transmission over long distances?',
'ហេតុអ្វីបានជា AC ត្រូវបានប្រើសម្រាប់ការបញ្ជូនថាមពលចម្ងាយឆ្ងាយ?',
'Explain the advantage.',
'ពន្យល់គុណសម្បត្តិ។',
NULL,
'Easier to transform voltage levels',
15, 'medium',
'Think about transformers.',
'គិតអំពីឧបករណ៍បម្លែង។',
'AC voltage can be easily stepped up or down using transformers, minimizing power loss during transmission.',
'វ៉ុល AC អាចបង្កើន ឬបន្ថយបានយ៉ាងងាយស្រួលដោយប្រើឧបករណ៍បម្លែង បន្ថយការបាត់បង់ថាមពលអំឡុងការបញ្ជូន។'),

-- 26. Circuit Construction Kit: AC - Virtual Lab (5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7)
('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 1, 'multiple_choice',
'What happens to current in a purely resistive AC circuit?',
'តើអ្វីកើតឡើងចំពោះចរន្តក្នុងសៀគ្វី AC ដែលមានតែធាតុទប់?',
'Choose the relationship.',
'ជ្រើសរើសទំនាក់ទំនង។',
'{"options": [{"en": "Current lags voltage by 90°", "km": "ចរន្តយឺតជាងវ៉ុល 90°"}, {"en": "Current leads voltage by 90°", "km": "ចរន្តមុនវ៉ុល 90°"}, {"en": "Current is in phase with voltage", "km": "ចរន្តស្របដំណាក់កាលជាមួយវ៉ុល"}, {"en": "No current flows", "km": "គ្មានចរន្តហូរ"}]}',
'Current is in phase with voltage',
15, 'medium',
'Resistors don\'t cause phase shift.',
'ធាតុទប់មិនបណ្តាលការផ្លាស់ប្តូរដំណាក់កាល។',
'In a purely resistive circuit, current and voltage are in phase - they reach maximum and minimum at the same time.',
'ក្នុងសៀគ្វីដែលមានតែធាតុទប់ ចរន្ត និងវ៉ុលស្របដំណាក់កាល - ពួកវាឈានដល់អតិបរមា និងអប្បបរមានៅពេលដូចគ្នា។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 2, 'true_false',
'Capacitors block DC but allow AC to pass.',
'កាប៉ាស៊ីតរ័ទប់ DC ប៉ុន្តែអនុញ្ញាត AC ឆ្លងកាត់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Think about changing electric fields.',
'គិតអំពីវាលអគ្គិសនីដែលផ្លាស់ប្តូរ។',
'Capacitors block steady DC current but allow changing AC current due to the changing electric field.',
'កាប៉ាស៊ីតរ័ទប់ចរន្ត DC ថេរ ប៉ុន្តែអនុញ្ញាតចរន្ត AC ដែលផ្លាស់ប្តូរដោយសារវាលអគ្គិសនីដែលផ្លាស់ប្តូរ។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 3, 'fill_blank',
'In an AC circuit with an inductor, current _____ the voltage.',
'ក្នុងសៀគ្វី AC ដែលមានឧបករណ៍កម្រើន ចរន្ត _____ វ៉ុល។',
'Describe the phase relationship.',
'ពិពណ៌នាទំនាក់ទំនងដំណាក់កាល។',
NULL,
'lags',
15, 'medium',
'ELI the ICE man rule.',
'ច្បាប់ ELI the ICE man។',
'In an inductive circuit, current lags voltage by 90° (ELI: voltage E leads current I in an inductor L).',
'ក្នុងសៀគ្វីឧបករណ៍កម្រើន ចរន្តយឺតជាងវ៉ុល 90° (ELI: វ៉ុល E មុនចរន្ត I ក្នុងឧបករណ៍កម្រើន L)។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 4, 'calculation',
'What is the reactance of a 10 mH inductor at 1000 Hz? (Use XL = 2πfL)',
'តើ reactance នៃឧបករណ៍កម្រើន 10 mH នៅ 1000 Hz គឺប៉ុន្មាន? (ប្រើ XL = 2πfL)',
'Calculate the inductive reactance.',
'គណនា reactance ឧបករណ៍កម្រើន។',
NULL,
'62.8 Ω',
20, 'hard',
'Convert mH to H first.',
'បម្លែង mH ទៅ H មុន។',
'XL = 2πfL = 2π × 1000 × 0.01 = 62.8 Ω',
'XL = 2πfL = 2π × 1000 × 0.01 = 62.8 Ω'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 5, 'short_answer',
'What is impedance in an AC circuit?',
'តើ impedance ក្នុងសៀគ្វី AC គឺជាអ្វី?',
'Define this AC concept.',
'កំណត់និយមន្តសេវកម្ម AC នេះ។',
NULL,
'Total opposition to AC current flow',
15, 'medium',
'Combines resistance and reactance.',
'រួមបញ្ចូលធាតុទប់ និង reactance។',
'Impedance (Z) is the total opposition to AC current, combining resistance (R) and reactance (X): Z = √(R² + X²).',
'Impedance (Z) គឺជាការប្រឆាំងសរុបចំពោះចរន្ត AC រួមបញ្ចូលធាតុទប់ (R) និង reactance (X): Z = √(R² + X²)។'),

-- 27. Circuit Construction Kit: DC (8d1f5409-fc3b-431d-b418-5446f0121cf1)
('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 1, 'multiple_choice',
'What does DC stand for in electrical circuits?',
'តើ DC មានន័យថាអ្វីក្នុងសៀគ្វីអគ្គិសនី?',
'Choose the correct term.',
'ជ្រើសរើសពាក្យត្រឹមត្រូវ។',
'{"options": [{"en": "Direct Current", "km": "ចរន្តផ្ទាល់"}, {"en": "Dual Circuit", "km": "សៀគ្វីទ្វេ"}, {"en": "Dynamic Control", "km": "ការគ្រប់គ្រងថាមវន្ត"}, {"en": "Digital Component", "km": "គ្រឿងផ្សំឌីជីតល់"}]}',
'Direct Current',
10, 'easy',
'Current flows in one direction.',
'ចរន្តហូរតាមមួយទិស។',
'DC (Direct Current) flows continuously in one direction, unlike AC which alternates.',
'DC (ចរន្តផ្ទាល់) ហូរជាប់ៗក្នុងមួយទិស ខុសពី AC ដែលឆ្លាស់។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 2, 'calculation',
'In a series circuit with 12V battery and two 6Ω resistors, what is the current?',
'ក្នុងសៀគ្វីធៀបជាមួយថ្ម 12V និងធាតុទប់ 6Ω ពីរ តើចរន្តគឺប៉ុន្មាន?',
'Use Ohm\'s law: V = IR',
'ប្រើច្បាប់អូម៖ V = IR',
NULL,
'1 A',
15, 'medium',
'Add resistances in series.',
'បូកធាតុទប់ក្នុងធៀប។',
'Total resistance = 6Ω + 6Ω = 12Ω. Current I = V/R = 12V/12Ω = 1A',
'ធាតុទប់សរុប = 6Ω + 6Ω = 12Ω។ ចរន្ត I = V/R = 12V/12Ω = 1A'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 3, 'true_false',
'In a parallel circuit, voltage is the same across all branches.',
'ក្នុងសៀគ្វីប៉ារ៉ាឡែល វ៉ុលគឺដូចគ្នានៅលើសាខាទាំងអស់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Parallel branches share voltage.',
'សាខាប៉ារ៉ាឡែលចែករំលែកវ៉ុល។',
'In parallel circuits, each branch experiences the same voltage as the source.',
'ក្នុងសៀគ្វីប៉ារ៉ាឡែល សាខានីមួយៗទទួលបានវ៉ុលដូចគ្នានឹងប្រភព។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 4, 'fill_blank',
'Ohm\'s law states that V = _____ × _____ .',
'ច្បាប់អូមចែងថា V = _____ × _____ ។',
'Complete the formula.',
'បំពេញរូបមន្ត។',
NULL,
'I, R',
10, 'easy',
'Current times resistance.',
'ចរន្តគុណធាតុទប់។',
'Ohm\'s law: V = I × R, where V is voltage, I is current, and R is resistance.',
'ច្បាប់អូម៖ V = I × R ដែល V គឺវ៉ុល I គឺចរន្ត និង R គឺធាតុទប់។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 5, 'short_answer',
'What happens to total resistance when resistors are connected in parallel?',
'តើអ្វីកើតឡើងចំពោះធាតុទប់សរុបនៅពេលធាតុទប់ត្រូវបានភ្ជាប់ជាប៉ារ៉ាឡែល?',
'Describe the effect.',
'ពិពណ៌នាឥទ្ធិពល។',
NULL,
'Total resistance decreases',
15, 'medium',
'More paths for current.',
'ផ្លូវច្រើនសម្រាប់ចរន្ត។',
'Parallel resistors provide multiple paths for current, so total resistance is less than the smallest individual resistor.',
'ធាតុទប់ប៉ារ៉ាឡែលផ្តល់ផ្លូវច្រើនសម្រាប់ចរន្ត ដូច្នេះធាតុទប់សរុបតិចជាងធាតុទប់តូចបំផុត។'),

-- 28. Circuit Construction Kit: DC - Virtual Lab (da313250-729a-4c2b-9558-d55f8126cc05)
('da313250-729a-4c2b-9558-d55f8126cc05', 1, 1, 'multiple_choice',
'What tool measures current in a circuit?',
'តើឧបករណ៍អ្វីវាស់ចរន្តក្នុងសៀគ្វី?',
'Choose the measuring device.',
'ជ្រើសរើសឧបករណ៍វាស់។',
'{"options": [{"en": "Voltmeter", "km": "វ៉ុលម៉ែត្រ"}, {"en": "Ammeter", "km": "អាំម៉ែត្រ"}, {"en": "Ohmmeter", "km": "អូមម៉ែត្រ"}, {"en": "Wattmeter", "km": "វ៉ាត់ម៉ែត្រ"}]}',
'Ammeter',
10, 'easy',
'Measures amperes.',
'វាស់អាំប៊ែរ។',
'An ammeter measures electric current in amperes and must be connected in series with the component.',
'អាំម៉ែត្រវាស់ចរន្តអគ្គិសនីជាអាំប៊ែរ និងត្រូវតែភ្ជាប់ជាធៀបជាមួយគ្រឿង។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 2, 'true_false',
'A voltmeter should be connected in parallel to measure voltage across a component.',
'វ៉ុលម៉ែត្រគួរត្រូវបានភ្ជាប់ជាប៉ារ៉ាឡែលដើម្បីវាស់វ៉ុលនៅលើគ្រឿង។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Voltmeters measure potential difference.',
'វ៉ុលម៉ែត្រវាស់ភាពខុសគ្នាសក្តានុពល។',
'Voltmeters are connected in parallel to measure the potential difference (voltage) across components.',
'វ៉ុលម៉ែត្រត្រូវបានភ្ជាប់ជាប៉ារ៉ាឡែលដើម្បីវាស់ភាពខុសគ្នាសក្តានុពល (វ៉ុល) នៅលើគ្រឿង។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 3, 'calculation',
'A 9V battery powers a 3Ω resistor. How much power is dissipated?',
'ថ្ម 9V ផ្គត់ផ្គង់ធាតុទប់ 3Ω។ តើថាមពលប៉ុន្មានត្រូវបានបាត់បង់?',
'Use P = V²/R',
'ប្រើ P = V²/R',
NULL,
'27 W',
15, 'medium',
'Power formulas: P = V²/R = I²R = VI',
'រូបមន្តថាមពល៖ P = V²/R = I²R = VI',
'P = V²/R = (9V)²/3Ω = 81/3 = 27 watts',
'P = V²/R = (9V)²/3Ω = 81/3 = 27 វ៉ាត់'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 4, 'short_answer',
'What happens to the brightness of bulbs when you add more bulbs in series?',
'តើអ្វីកើតឡើងចំពោះពន្លឺអំពូលនៅពេលអ្នកបន្ថែមអំពូលច្រើនក្នុងធៀប?',
'Describe the effect.',
'ពិពណ៌នាឥទ្ធិពល។',
NULL,
'Bulbs get dimmer',
10, 'easy',
'More resistance, less current.',
'ធាតុទប់ច្រើន ចរន្តតិច។',
'Adding bulbs in series increases total resistance, reducing current and making all bulbs dimmer.',
'ការបន្ថែមអំពូលក្នុងធៀបបង្កើនធាតុទប់សរុប បន្ថយចរន្ត និងធ្វើឲ្យអំពូលទាំងអស់ងងឹត។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 5, 'fill_blank',
'In a series circuit, the _____ is the same through all components.',
'ក្នុងសៀគ្វីធៀប _____ គឺដូចគ្នាឆ្លងកាត់គ្រឿងទាំងអស់។',
'What quantity is constant?',
'តើបរិមាណអ្វីថេរ?',
NULL,
'current',
10, 'easy',
'Only one path for current.',
'មានតែផ្លូវតែមួយសម្រាប់ចរន្ត។',
'In series circuits, current is the same throughout because there\'s only one path for charge to flow.',
'ក្នុងសៀគ្វីធៀប ចរន្តដូចគ្នាទាំងអស់ព្រោះមានតែផ្លូវតែមួយសម្រាប់បន្ទុកហូរ។'),

-- 29. Collision Lab (8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04)
('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 1, 'multiple_choice',
'What is conserved in all collisions?',
'តើអ្វីត្រូវបានអភិរក្សក្នុងការប៉ះទង្គិចទាំងអស់?',
'Choose the conserved quantity.',
'ជ្រើសរើសបរិមាណអភិរក្ស។',
'{"options": [{"en": "Kinetic energy only", "km": "តែថាមពលស៊ីនេទិច"}, {"en": "Momentum only", "km": "តែម៉ូម៉ង់ទិម"}, {"en": "Both momentum and kinetic energy", "km": "ទាំងម៉ូម៉ង់ទិម និងថាមពលស៊ីនេទិច"}, {"en": "Neither", "km": "គ្មានទាំងពីរ"}]}',
'Momentum only',
15, 'medium',
'Energy may be lost to heat/sound.',
'ថាមពលអាចបាត់ទៅកំដៅ/សំឡេង។',
'Momentum is always conserved in collisions, but kinetic energy is only conserved in perfectly elastic collisions.',
'ម៉ូម៉ង់ទិមតែងតែត្រូវបានអភិរក្សក្នុងការប៉ះទង្គិច ប៉ុន្តែថាមពលស៊ីនេទិចត្រូវបានអភិរក្សតែក្នុងការប៉ះទង្គិចសាទសុទ្ធ។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 2, 'calculation',
'A 2 kg ball moving at 4 m/s collides with a stationary 3 kg ball. If they stick together, what is their final velocity?',
'បាល់ 2 kg ចលនាក្នុងល្បឿន 4 m/s ប៉ះទង្គិចជាមួយបាល់ 3 kg ដែលនៅស្ថិត។ ប្រសិនបើពួកវាជាប់គ្នា តើល្បឿនចុងក្រោយគឺប៉ុន្មាន?',
'Use conservation of momentum.',
'ប្រើការអភិរក្សម៉ូម៉ង់ទិម។',
NULL,
'1.6 m/s',
20, 'medium',
'm₁v₁ + m₂v₂ = (m₁ + m₂)vf',
'm₁v₁ + m₂v₂ = (m₁ + m₂)vf',
'(2)(4) + (3)(0) = (2 + 3)vf → 8 = 5vf → vf = 1.6 m/s',
'(2)(4) + (3)(0) = (2 + 3)vf → 8 = 5vf → vf = 1.6 m/s'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 3, 'true_false',
'In a perfectly elastic collision, both momentum and kinetic energy are conserved.',
'ក្នុងការប៉ះទង្គិចសាទសុទ្ធ ទាំងម៉ូម៉ង់ទិម និងថាមពលស៊ីនេទិចត្រូវបានអភិរក្ស។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'No energy is lost in elastic collisions.',
'គ្មានថាមពលបាត់បង់ក្នុងការប៉ះទង្គិចសាទ។',
'Elastic collisions conserve both momentum and kinetic energy - no energy is lost to deformation or heat.',
'ការប៉ះទង្គិចសាទអភិរក្សទាំងម៉ូម៉ង់ទិម និងថាមពលស៊ីនេទិច - គ្មានថាមពលបាត់បង់ទៅការខូចរូបរាង ឬកំដៅ។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 4, 'fill_blank',
'Momentum is calculated as mass times _____.',
'ម៉ូម៉ង់ទិមត្រូវបានគណនាជាម៉ាស់គុណ _____។',
'Complete the formula.',
'បំពេញរូបមន្ត។',
NULL,
'velocity',
10, 'easy',
'p = mv',
'p = mv',
'Momentum p = mass × velocity. It\'s a vector quantity with both magnitude and direction.',
'ម៉ូម៉ង់ទិម p = ម៉ាស់ × ល្បឿន។ វាជាបរិមាណវ៉ិចទ័រដែលមានទាំងរង្វៈ និងទិស។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 5, 'short_answer',
'What is the difference between elastic and inelastic collisions?',
'តើភាពខុសគ្នារវាងការប៉ះទង្គិចសាទ និងមិនសាទគឺអ្វី?',
'Explain the key difference.',
'ពន្យល់ភាពខុសគ្នាសំខាន់។',
NULL,
'Kinetic energy conservation',
15, 'medium',
'Think about energy loss.',
'គិតអំពីការបាត់បង់ថាមពល។',
'Elastic collisions conserve kinetic energy; inelastic collisions lose some kinetic energy to heat, sound, or deformation.',
'ការប៉ះទង្គិចសាទអភិរក្សថាមពលស៊ីនេទិច ការប៉ះទង្គិចមិនសាទបាត់បង់ថាមពលស៊ីនេទិចខ្លះទៅកំដៅ សំឡេង ឬការខូចរូបរាង។'),

-- 30. Color Vision (b5e80869-d70e-4596-89e0-36d9c3a753c4)
('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 1, 'multiple_choice',
'What are the three primary colors of light?',
'តើអ្វីជាពណ៌មូលដ្ឋានបីនៃពន្លឺ?',
'Choose the correct set.',
'ជ្រើសរើសសំណុំត្រឹមត្រូវ។',
'{"options": [{"en": "Red, Yellow, Blue", "km": "ក្រហម លឿង ខៀវ"}, {"en": "Red, Green, Blue", "km": "ក្រហម បៃតង ខៀវ"}, {"en": "Cyan, Magenta, Yellow", "km": "ស៊ីយ៉ាន់ ម៉ាសិនតា លឿង"}, {"en": "Orange, Green, Purple", "km": "ទឹកក្រូច បៃតង ម្វង"}]}',
'Red, Green, Blue',
10, 'easy',
'RGB - additive color model.',
'RGB - គំរូពណ៌បូក។',
'Red, Green, and Blue (RGB) are the primary colors of light that combine to create all other colors.',
'ក្រហម បៃតង និងខៀវ (RGB) គឺជាពណ៌មូលដ្ឋាននៃពន្លឺដែលរួមបញ្ចូលគ្នាដើម្បីបង្កើតពណ៌ផ្សេងទៀត។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 2, 'true_false',
'White light contains all colors of the visible spectrum.',
'ពន្លឺសមាន់ពណ៌ទាំងអស់នៃវិសាលគមមើលឃើញ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about prisms and rainbows.',
'គិតអំពីភ្លុក និងឈូងព្រះនរាយណ៍។',
'White light is a mixture of all visible wavelengths, which can be separated using a prism or seen in rainbows.',
'ពន្លឺសគឺជាការលាយបញ្ចូលនៃរលកវែងមើលឃើញទាំងអស់ ដែលអាចបំបែកដោយប្រើភ្លុក ឬមើលក្នុងឈូងព្រះនរាយណ៍។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 3, 'short_answer',
'Why do we see objects as having different colors?',
'ហេតុអ្វីបានជាយើងមើលឃើញវត្ថុមានពណ៌ខុសៗគ្នា?',
'Explain color perception.',
'ពន្យល់ការទទួលយល់ពណ៌។',
NULL,
'Objects reflect certain wavelengths and absorb others',
15, 'medium',
'Think about reflection and absorption.',
'គិតអំពីការឆ្លុះ និងការស្រូប។',
'Objects appear colored because they reflect certain wavelengths of light to our eyes while absorbing others.',
'វត្ថុលេចពណ៌ពីព្រោះពួកវាឆ្លុះរលកវែងពន្លឺមួយចំនួនទៅភ្នែកយើង ខណៈស្រូបផ្សេងទៀត។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 4, 'fill_blank',
'The visible light spectrum ranges from about _____ nm to _____ nm.',
'វិសាលគមពន្លឺមើលឃើញមានជួរពីប្រហែល _____ nm ដល់ _____ nm។',
'Enter the wavelength range.',
'បញ្ចូលជួររលកវែង។',
NULL,
'400, 700',
15, 'medium',
'Violet to red range.',
'ជួរពីបែងស្វាយដល់ក្រហម។',
'Visible light spans approximately 400 nm (violet) to 700 nm (red) in wavelength.',
'ពន្លឺមើលឃើញមានប្រហែល 400 nm (បែងស្វាយ) ដល់ 700 nm (ក្រហម) ក្នុងរលកវែង។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 5, 'multiple_choice',
'What type of color blindness is most common?',
'តើប្រភេទខ្វាក់ពណ៌មួយណាធម្មតាបំផុត?',
'Choose the most frequent type.',
'ជ្រើសរើសប្រភេទញឹកញាប់បំផុត។',
'{"options": [{"en": "Red-green color blindness", "km": "ខ្វាក់ពណ៌ក្រហម-បៃតង"}, {"en": "Blue-yellow color blindness", "km": "ខ្វាក់ពណ៌ខៀវ-លឿង"}, {"en": "Complete color blindness", "km": "ខ្វាក់ពណ៌ទាំងស្រុង"}, {"en": "Purple blindness", "km": "ខ្វាក់ពណ៌ម្វង"}]}',
'Red-green color blindness',
15, 'medium',
'Affects mostly males.',
'ប៉ះពាល់បុរសភាគច្រើន។',
'Red-green color blindness is the most common form, affecting about 8% of men and 0.5% of women.',
'ខ្វាក់ពណ៌ក្រហម-បៃតងគឺជារូបភាពធម្មតាបំផុត ប៉ះពាល់ប្រហែល 8% បុរស និង 0.5% ស្ត្រី។'),

-- 31. Concentration (b75fc5d8-caf2-4684-b516-fa5a52267f6b) - Already done in Stage 1

-- 32. Coulomb's Law (03d96604-735d-480d-ab18-89033ec90361)
('03d96604-735d-480d-ab18-89033ec90361', 1, 1, 'multiple_choice',
'Coulomb\'s law describes the force between:',
'ច្បាប់កូឡុមពិពណ៌នាកម្លាំងរវាង៖',
'Choose what interacts.',
'ជ្រើសរើសអ្វីដែលអន្តរកម្ម។',
'{"options": [{"en": "Electric charges", "km": "បន្ទុកអគ្គិសនី"}, {"en": "Magnetic poles", "km": "ប៉ូលម៉ាញេទិច"}, {"en": "Masses", "km": "ម៉ាល់"}, {"en": "Currents", "km": "ចរន្ត"}]}',
'Electric charges',
10, 'easy',
'Electrostatic force law.',
'ច្បាប់កម្លាំងអគ្គិសនីស្ថិត។',
'Coulomb\'s law quantifies the electrostatic force between electrically charged particles.',
'ច្បាប់កូឡុមកំណត់បរិមាណកម្លាំងអគ្គិសនីស្ថិតរវាងភាគល្អិតដែលមានបន្ទុកអគ្គិសនី។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 2, 'calculation',
'What happens to the force if the distance between two charges is doubled?',
'តើអ្វីកើតឡើងចំពោះកម្លាំងប្រសិនបើចម្ងាយរវាងបន្ទុកពីរត្រូវបានបង្កើនទ្វេដង?',
'Use the inverse square law.',
'ប្រើច្បាប់ការ៉េច្រាស។',
NULL,
'Force becomes 1/4 of original',
15, 'medium',
'F ∝ 1/r²',
'F ∝ 1/r²',
'Since F ∝ 1/r², doubling distance makes r² = 4r², so force becomes 1/4 of the original.',
'ដោយសារ F ∝ 1/r² ការបង្កើនចម្ងាយទ្វេដងធ្វើឲ្យ r² = 4r² ដូច្នេះកម្លាំងក្លាយជា 1/4 នៃដើម។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 3, 'true_false',
'The electrostatic force is always attractive.',
'កម្លាំងអគ្គិសនីស្ថិតតែងតែទាក់ទាញ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Consider like vs unlike charges.',
'ពិចារណាបន្ទុកដូចគ្នា និងខុសគ្នា។',
'The force can be attractive (opposite charges) or repulsive (like charges) depending on the signs.',
'កម្លាំងអាចទាក់ទាញ (បន្ទុកផ្ទុយ) ឬច្រាន (បន្ទុកដូចគ្នា) អាស្រ័យលើសញ្ញា។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 4, 'fill_blank',
'Coulomb\'s law formula is F = k_____/_____.',
'រូបមន្តច្បាប់កូឡុមគឺ F = k_____/_____។',
'Complete the equation.',
'បំពេញសមីការ។',
NULL,
'q₁q₂, r²',
15, 'medium',
'Charges in numerator, distance squared in denominator.',
'បន្ទុកនៅលេខាន្ក ចម្ងាយការ៉េនៅភាគេបែង។',
'F = kq₁q₂/r², where k is Coulomb\'s constant, q₁ and q₂ are charges, and r is distance.',
'F = kq₁q₂/r² ដែល k គឺថេរកូឡុម q₁ និង q₂ គឺបន្ទុក និង r គឺចម្ងាយ។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 5, 'short_answer',
'What is the value of Coulomb\'s constant k in SI units?',
'តើតម្លៃនៃថេរកូឡុម k ក្នុងឯកតា SI គឺប៉ុន្មាន?',
'Give the numerical value.',
'ផ្តល់តម្លៃជាលេខ។',
NULL,
'9 × 10⁹ N⋅m²/C²',
15, 'medium',
'Fundamental constant.',
'ថេរមូលដ្ឋាន។',
'Coulomb\'s constant k = 9.0 × 10⁹ N⋅m²/C² in SI units.',
'ថេរកូឡុម k = 9.0 × 10⁹ N⋅m²/C² ក្នុងឯកតា SI។');