-- Stage 1 Continued: More exercises for Chemistry simulations

-- 6. Balancing Chemical Equations (e8755c96-44da-4567-841d-bcb918b83a2e)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 1, 'multiple_choice',
'What does the Law of Conservation of Mass state?',
'តើច្បាប់អភិរក្សម៉ាស់ចែងយ៉ាងដូចម្តេច?',
'Choose the correct statement.',
'ជ្រើសរើសសេចក្តីថ្លែងការណ៍ត្រឹមត្រូវ។',
'{"options": [{"en": "Mass can be created but not destroyed", "km": "ម៉ាស់អាចបង្កើតបានប៉ុន្តែមិនអាចបំផ្លាញបាន"}, {"en": "Mass is neither created nor destroyed in chemical reactions", "km": "ម៉ាស់មិនត្រូវបានបង្កើត ឬបំផ្លាញក្នុងប្រតិកម្មគីមីទេ"}, {"en": "Mass increases during reactions", "km": "ម៉ាស់កើនឡើងក្នុងអំឡុងប្រតិកម្ម"}, {"en": "Mass always decreases", "km": "ម៉ាស់តែងតែថយចុះ"}]}',
'Mass is neither created nor destroyed in chemical reactions',
10, 'easy',
'This is a fundamental law in chemistry.',
'នេះគឺជាច្បាប់មូលដ្ឋានក្នុងគីមីវិទ្យា។',
'The Law of Conservation of Mass states that in a chemical reaction, the total mass of reactants equals the total mass of products.',
'ច្បាប់អភិរក្សម៉ាស់ចែងថាក្នុងប្រតិកម្មគីមី ម៉ាស់សរុបនៃសារធាតុប្រតិកម្មស្មើនឹងម៉ាស់សរុបនៃផលិតផល។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 2, 'fill_blank',
'In the equation 2H2 + O2 → 2H2O, the coefficient in front of H2 is _____.',
'ក្នុងសមីការ 2H2 + O2 → 2H2O មេគុណនៅមុខ H2 គឺ _____។',
'Enter the number.',
'បញ្ចូលលេខ។',
NULL,
'2',
10, 'easy',
'Look at the number before H2.',
'មើលលេខនៅមុខ H2។',
'The coefficient 2 in front of H2 indicates that 2 molecules of hydrogen gas are needed for the reaction.',
'មេគុណ 2 នៅមុខ H2 បង្ហាញថាម៉ូលេគុលឧស្ម័នអ៊ីដ្រូសែនចំនួន 2 ត្រូវការសម្រាប់ប្រតិកម្ម។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 3, 'short_answer',
'Balance this equation: Fe + O2 → Fe2O3',
'តុល្យភាពសមីការនេះ៖ Fe + O2 → Fe2O3',
'Write the balanced equation with coefficients.',
'សរសេរសមីការតុល្យភាពជាមួយមេគុណ។',
NULL,
'4Fe + 3O2 → 2Fe2O3',
20, 'medium',
'Count atoms on both sides.',
'រាប់អាតូមនៅលើភាគីទាំងពីរ។',
'Balanced: 4Fe + 3O2 → 2Fe2O3. This gives 4 Fe atoms and 6 O atoms on each side.',
'តុល្យភាព៖ 4Fe + 3O2 → 2Fe2O3។ នេះផ្តល់អាតូម Fe 4 និងអាតូម O 6 នៅលើភាគីនីមួយៗ។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 4, 'true_false',
'Changing subscripts in chemical formulas is an acceptable way to balance equations.',
'ការផ្លាស់ប្តូរអក្សរតូចក្នុងរូបមន្តគីមីគឺជាវិធីដែលអាចទទួលយកបានដើម្បីតុល្យភាពសមីការ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'What do subscripts represent?',
'តើអក្សរតូចតំណាងឲ្យអ្វី?',
'Subscripts indicate the number of atoms in a molecule and cannot be changed. Only coefficients can be adjusted to balance equations.',
'អក្សរតូចបង្ហាញចំនួនអាតូមក្នុងម៉ូលេគុល និងមិនអាចផ្លាស់ប្តូរបានទេ។ មានតែមេគុណប៉ុណ្ណោះដែលអាចកែតម្រូវដើម្បីតុល្យភាពសមីការ។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 5, 'calculation',
'In the balanced equation 2Al + 3Cl2 → 2AlCl3, how many moles of Cl2 are needed to react with 4 moles of Al?',
'ក្នុងសមីការតុល្យភាព 2Al + 3Cl2 → 2AlCl3 តើត្រូវការ Cl2 ប៉ុន្មានម៉ូលដើម្បីប្រតិកម្មជាមួយ Al 4 ម៉ូល?',
'Use stoichiometry to calculate.',
'ប្រើស្តូអ៊ីចូម៉ែត្រីដើម្បីគណនា។',
NULL,
'6',
15, 'medium',
'Use the mole ratio from the balanced equation.',
'ប្រើផលធៀបម៉ូលពីសមីការតុល្យភាព។',
'From the equation: 2 mol Al : 3 mol Cl2. So for 4 mol Al: (4 mol Al) × (3 mol Cl2 / 2 mol Al) = 6 mol Cl2',
'ពីសមីការ៖ 2 mol Al : 3 mol Cl2។ ដូច្នេះសម្រាប់ 4 mol Al: (4 mol Al) × (3 mol Cl2 / 2 mol Al) = 6 mol Cl2'),

-- 7. Beer's Law Lab (7c7346a5-9428-414e-a203-dce04e727747)
('7c7346a5-9428-414e-a203-dce04e727747', 1, 1, 'multiple_choice',
'According to Beer''s Law, absorbance is directly proportional to:',
'យោងតាមច្បាប់បៀរ ការស្រូបមានសមាមាត្រដោយផ្ទាល់ទៅនឹង៖',
'Select all that apply.',
'ជ្រើសរើសទាំងអស់ដែលអនុវត្ត។',
'{"options": [{"en": "Concentration only", "km": "កំហាប់តែប៉ុណ្ណោះ"}, {"en": "Path length only", "km": "ប្រវែងផ្លូវតែប៉ុណ្ណោះ"}, {"en": "Both concentration and path length", "km": "ទាំងកំហាប់ និងប្រវែងផ្លូវ"}, {"en": "Neither", "km": "គ្មានមួយណា"}]}',
'Both concentration and path length',
10, 'medium',
'Remember A = εbc',
'ចងចាំ A = εbc',
'Beer''s Law states that A = εbc, where absorbance (A) is proportional to both concentration (c) and path length (b).',
'ច្បាប់បៀរចែងថា A = εbc ដែលការស្រូប (A) មានសមាមាត្រទៅនឹងទាំងកំហាប់ (c) និងប្រវែងផ្លូវ (b)។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 2, 'calculation',
'If a solution with concentration 0.1 M has an absorbance of 0.4, what is the absorbance of a 0.25 M solution? (Same substance and path length)',
'ប្រសិនបើសូលុយស្យុងដែលមានកំហាប់ 0.1 M មានការស្រូប 0.4 តើការស្រូបនៃសូលុយស្យុង 0.25 M គឺប៉ុន្មាន? (សារធាតុដូចគ្នា និងប្រវែងផ្លូវដូចគ្នា)',
'Use the proportional relationship.',
'ប្រើទំនាក់ទំនងសមាមាត្រ។',
NULL,
'1.0',
15, 'medium',
'Absorbance is proportional to concentration.',
'ការស្រូបមានសមាមាត្រទៅនឹងកំហាប់។',
'Since A ∝ c: A₁/c₁ = A₂/c₂. So: 0.4/0.1 = A₂/0.25. Therefore: A₂ = (0.4 × 0.25)/0.1 = 1.0',
'ដោយសារ A ∝ c: A₁/c₁ = A₂/c₂។ ដូច្នេះ៖ 0.4/0.1 = A₂/0.25។ ហេតុនេះ៖ A₂ = (0.4 × 0.25)/0.1 = 1.0'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 3, 'short_answer',
'What instrument is used to measure the absorbance of a solution?',
'តើឧបករណ៍អ្វីត្រូវបានប្រើដើម្បីវាស់ការស្រូបនៃសូលុយស្យុង?',
'Name the analytical instrument.',
'បញ្ជាក់ឈ្មោះឧបករណ៍វិភាគ។',
NULL,
'spectrophotometer',
10, 'easy',
'It measures how much light passes through.',
'វាវាស់បរិមាណពន្លឺដែលឆ្លងកាត់។',
'A spectrophotometer measures the absorbance by comparing the intensity of light before and after passing through a sample.',
'ស្ប៉ិចត្រូហ្វូតូម៉ែត្រវាស់ការស្រូបដោយប្រៀបធៀបអាំងតង់ស៊ីតេពន្លឺមុន និងក្រោយឆ្លងកាត់គំរូ។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 4, 'true_false',
'Darker colored solutions always have higher concentrations.',
'សូលុយស្យុងពណ៌ងងឹតជាងតែងតែមានកំហាប់ខ្ពស់ជាង។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'Consider different substances.',
'ពិចារណាសារធាតុផ្សេងៗ។',
'Color intensity depends on both concentration AND the molar absorptivity of the substance. Different substances absorb differently.',
'អាំងតង់ស៊ីតេពណ៌អាស្រ័យលើទាំងកំហាប់ និងការស្រូបម៉ូលនៃសារធាតុ។ សារធាតុផ្សេងៗស្រូបខុសគ្នា។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 5, 'multiple_choice',
'What happens to transmittance as absorbance increases?',
'តើអ្វីកើតឡើងចំពោះការបញ្ជូនពេលការស្រូបកើនឡើង?',
'Choose the correct relationship.',
'ជ្រើសរើសទំនាក់ទំនងត្រឹមត្រូវ។',
'{"options": [{"en": "Transmittance increases", "km": "ការបញ្ជូនកើនឡើង"}, {"en": "Transmittance decreases", "km": "ការបញ្ជូនថយចុះ"}, {"en": "No change", "km": "គ្មានការផ្លាស់ប្តូរ"}, {"en": "Random change", "km": "ការផ្លាស់ប្តូរចៃដន្យ"}]}',
'Transmittance decreases',
10, 'medium',
'They have an inverse relationship.',
'ពួកវាមានទំនាក់ទំនងច្រាស។',
'Transmittance and absorbance are inversely related: A = -log(T). As more light is absorbed, less is transmitted.',
'ការបញ្ជូន និងការស្រូបមានទំនាក់ទំនងច្រាស៖ A = -log(T)។ នៅពេលពន្លឺត្រូវបានស្រូបច្រើន ការបញ្ជូនតិច។'),

-- 8. Build a Molecule (b68766ea-36ad-4535-addb-877f78a44a2f)
('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 1, 'multiple_choice',
'How many bonds can a carbon atom typically form?',
'តើអាតូមកាបូនអាចបង្កើតចំណងប៉ុន្មានជាទូទៅ?',
'Select the correct number.',
'ជ្រើសរើសលេខត្រឹមត្រូវ។',
'{"options": [{"en": "1", "km": "1"}, {"en": "2", "km": "2"}, {"en": "3", "km": "3"}, {"en": "4", "km": "4"}]}',
'4',
10, 'easy',
'Think about carbon''s valence electrons.',
'គិតអំពីអេឡិចត្រុងវ៉ាឡង់របស់កាបូន។',
'Carbon has 4 valence electrons and needs 4 more to complete its octet, so it typically forms 4 bonds.',
'កាបូនមានអេឡិចត្រុងវ៉ាឡង់ 4 និងត្រូវការ 4 ទៀតដើម្បីបំពេញអុកតេតរបស់វា ដូច្នេះវាជាទូទៅបង្កើតចំណង 4។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 2, 'fill_blank',
'The molecular formula for water is _____.',
'រូបមន្តម៉ូលេគុលសម្រាប់ទឹកគឺ _____។',
'Write the chemical formula.',
'សរសេររូបមន្តគីមី។',
NULL,
'H2O',
10, 'easy',
'Two hydrogen, one oxygen.',
'អ៊ីដ្រូសែនពីរ អុកស៊ីសែនមួយ។',
'Water consists of 2 hydrogen atoms bonded to 1 oxygen atom, giving the formula H2O.',
'ទឹកមានអាតូមអ៊ីដ្រូសែន 2 ភ្ជាប់ទៅអាតូមអុកស៊ីសែន 1 ផ្តល់រូបមន្ត H2O។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 3, 'short_answer',
'Name three different molecules you can build using only carbon and hydrogen atoms.',
'បញ្ជាក់ឈ្មោះម៉ូលេគុលផ្សេងគ្នាបីដែលអ្នកអាចសាងសង់ដោយប្រើតែអាតូមកាបូន និងអ៊ីដ្រូសែន។',
'List three hydrocarbons.',
'រាយបញ្ជីអ៊ីដ្រូកាបូនបី។',
NULL,
'Methane, Ethane, Propane',
15, 'medium',
'Think of simple alkanes.',
'គិតអំពីអាល់កានសាមញ្ញ។',
'Examples include methane (CH4), ethane (C2H6), propane (C3H8), ethene (C2H4), and many other hydrocarbons.',
'ឧទាហរណ៍រួមមានមេតាន (CH4) អេតាន (C2H6) ប្រូប៉ាន (C3H8) អេតែន (C2H4) និងអ៊ីដ្រូកាបូនជាច្រើនទៀត។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 4, 'true_false',
'All atoms follow the octet rule when forming molecules.',
'អាតូមទាំងអស់អនុវត្តតាមក្រឹត្យអុកតេតនៅពេលបង្កើតម៉ូលេគុល។',
'Is this always true?',
'តើនេះតែងតែពិតទេ?',
NULL,
'false',
10, 'medium',
'Consider hydrogen and other exceptions.',
'ពិចារណាអ៊ីដ្រូសែន និងករណីលើកលែងផ្សេងទៀត។',
'Hydrogen only needs 2 electrons (duet rule), and some atoms like sulfur and phosphorus can exceed the octet.',
'អ៊ីដ្រូសែនត្រូវការតែអេឡិចត្រុង 2 (ក្រឹត្យឌួអេត) ហើយអាតូមខ្លះដូចជាស្ពាន់ និងផូស្វ័រអាចលើសអុកតេត។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 5, 'multiple_choice',
'What type of bond forms between two chlorine atoms in Cl2?',
'តើប្រភេទចំណងអ្វីបង្កើតរវាងអាតូមក្លរពីរក្នុង Cl2?',
'Choose the bond type.',
'ជ្រើសរើសប្រភេទចំណង។',
'{"options": [{"en": "Ionic bond", "km": "ចំណងអ៊ីយ៉ុង"}, {"en": "Covalent bond", "km": "ចំណងកូវ៉ាឡង់"}, {"en": "Metallic bond", "km": "ចំណងលោហៈ"}, {"en": "Hydrogen bond", "km": "ចំណងអ៊ីដ្រូសែន"}]}',
'Covalent bond',
10, 'easy',
'Both atoms are the same nonmetal.',
'អាតូមទាំងពីរគឺអលោហៈដូចគ្នា។',
'Two chlorine atoms share electrons equally to form a nonpolar covalent bond in Cl2.',
'អាតូមក្លរពីរចែករំលែកអេឡិចត្រុងស្មើគ្នាដើម្បីបង្កើតចំណងកូវ៉ាឡង់អប៉ូលក្នុង Cl2។'),

-- 9. Build a Nucleus (a2d8910c-0b52-4954-927a-a4a8d498cd21)
('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 1, 'multiple_choice',
'What particles are found in the nucleus of an atom?',
'តើភាគល្អិតអ្វីខ្លះត្រូវបានរកឃើញក្នុងស្នូលនៃអាតូម?',
'Select all correct answers.',
'ជ្រើសរើសចម្លើយត្រឹមត្រូវទាំងអស់។',
'{"options": [{"en": "Protons and neutrons", "km": "ប្រូតុង និងនឺត្រុង"}, {"en": "Protons and electrons", "km": "ប្រូតុង និងអេឡិចត្រុង"}, {"en": "Neutrons and electrons", "km": "នឺត្រុង និងអេឡិចត្រុង"}, {"en": "Only protons", "km": "តែប្រូតុងប៉ុណ្ណោះ"}]}',
'Protons and neutrons',
10, 'easy',
'Electrons orbit outside the nucleus.',
'អេឡិចត្រុងគោចរនៅខាងក្រៅស្នូល។',
'The nucleus contains protons (positive charge) and neutrons (neutral), while electrons orbit outside.',
'ស្នូលមានប្រូតុង (បន្ទុកវិជ្ជមាន) និងនឺត្រុង (អព្យាក្រឹត) ខណៈអេឡិចត្រុងគោចរនៅខាងក្រៅ។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 2, 'calculation',
'An atom has 6 protons and 8 neutrons. What is its mass number?',
'អាតូមមួយមានប្រូតុង 6 និងនឺត្រុង 8។ តើលេខម៉ាស់របស់វាគឺប៉ុន្មាន?',
'Add the nucleons.',
'បូកនុយក្លេអុង។',
NULL,
'14',
10, 'easy',
'Mass number = protons + neutrons',
'លេខម៉ាស់ = ប្រូតុង + នឺត្រុង',
'Mass number = number of protons + number of neutrons = 6 + 8 = 14',
'លេខម៉ាស់ = ចំនួនប្រូតុង + ចំនួននឺត្រុង = 6 + 8 = 14'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 3, 'fill_blank',
'Atoms of the same element with different numbers of neutrons are called _____.',
'អាតូមនៃធាតុដូចគ្នាដែលមានចំនួននឺត្រុងខុសគ្នាត្រូវបានគេហៅថា _____។',
'Fill in the scientific term.',
'បំពេញពាក្យវិទ្យាសាស្ត្រ។',
NULL,
'isotopes',
10, 'medium',
'Same protons, different neutrons.',
'ប្រូតុងដូចគ្នា នឺត្រុងខុសគ្នា។',
'Isotopes are atoms of the same element (same number of protons) with different numbers of neutrons.',
'អ៊ីសូតូបគឺជាអាតូមនៃធាតុដូចគ្នា (ចំនួនប្រូតុងដូចគ្នា) ដែលមានចំនួននឺត្រុងខុសគ្នា។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 4, 'true_false',
'All isotopes of an element have the same chemical properties.',
'អ៊ីសូតូបទាំងអស់នៃធាតុមួយមានលក្ខណៈសម្បត្តិគីមីដូចគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Chemical properties depend on electrons.',
'លក្ខណៈសម្បត្តិគីមីអាស្រ័យលើអេឡិចត្រុង។',
'Isotopes have the same number of electrons and thus the same chemical properties, but different physical properties.',
'អ៊ីសូតូបមានចំនួនអេឡិចត្រុងដូចគ្នា ហើយដូច្នេះមានលក្ខណៈសម្បត្តិគីមីដូចគ្នា ប៉ុន្តែលក្ខណៈសម្បត្តិរូបវិទ្យាខុសគ្នា។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 5, 'short_answer',
'What determines the identity of an element?',
'តើអ្វីកំណត់អត្តសញ្ញាណនៃធាតុ?',
'Name the specific particle.',
'បញ្ជាក់ឈ្មោះភាគល្អិតជាក់លាក់។',
NULL,
'number of protons',
10, 'medium',
'This is the atomic number.',
'នេះគឺជាលេខអាតូម។',
'The number of protons (atomic number) uniquely identifies an element. All atoms of the same element have the same number of protons.',
'ចំនួនប្រូតុង (លេខអាតូម) កំណត់អត្តសញ្ញាណធាតុយ៉ាងពិសេស។ អាតូមទាំងអស់នៃធាតុដូចគ្នាមានចំនួនប្រូតុងដូចគ្នា។'),

-- 10. Build an Atom (d33f834a-20e4-49b5-97b6-2bb73b4dc72f)
('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 1, 'multiple_choice',
'Which subatomic particle has a negative charge?',
'តើភាគល្អិតតូចជាងអាតូមមួយណាមានបន្ទុកអវិជ្ជមាន?',
'Choose the correct particle.',
'ជ្រើសរើសភាគល្អិតត្រឹមត្រូវ។',
'{"options": [{"en": "Proton", "km": "ប្រូតុង"}, {"en": "Neutron", "km": "នឺត្រុង"}, {"en": "Electron", "km": "អេឡិចត្រុង"}, {"en": "Nucleus", "km": "ស្នូល"}]}',
'Electron',
10, 'easy',
'It orbits the nucleus.',
'វាគោចរជុំវិញស្នូល។',
'Electrons have a negative charge (-1), protons have a positive charge (+1), and neutrons are neutral (0).',
'អេឡិចត្រុងមានបន្ទុកអវិជ្ជមាន (-1) ប្រូតុងមានបន្ទុកវិជ្ជមាន (+1) និងនឺត្រុងអព្យាក្រឹត (0)។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 2, 'true_false',
'A neutral atom has equal numbers of protons and electrons.',
'អាតូមអព្យាក្រឹតមានចំនួនប្រូតុង និងអេឡិចត្រុងស្មើគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about charge balance.',
'គិតអំពីតុល្យភាពបន្ទុក។',
'In a neutral atom, the positive charges from protons balance the negative charges from electrons.',
'ក្នុងអាតូមអព្យាក្រឹត បន្ទុកវិជ្ជមានពីប្រូតុងតុល្យភាពបន្ទុកអវិជ្ជមានពីអេឡិចត្រុង។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 3, 'calculation',
'An ion has 11 protons and 10 electrons. What is its charge?',
'អ៊ីយ៉ុងមួយមានប្រូតុង 11 និងអេឡិចត្រុង 10។ តើបន្ទុករបស់វាគឺប៉ុន្មាន?',
'Calculate the net charge.',
'គណនាបន្ទុកសុទ្ធ។',
NULL,
'+1',
10, 'easy',
'Compare positive and negative charges.',
'ប្រៀបធៀបបន្ទុកវិជ្ជមាន និងអវិជ្ជមាន។',
'Charge = number of protons - number of electrons = 11 - 10 = +1',
'បន្ទុក = ចំនួនប្រូតុង - ចំនួនអេឡិចត្រុង = 11 - 10 = +1'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 4, 'short_answer',
'What element has 79 protons?',
'តើធាតុអ្វីមានប្រូតុង 79?',
'Name the element.',
'បញ្ជាក់ឈ្មោះធាតុ។',
NULL,
'Gold',
10, 'medium',
'Check the periodic table.',
'ពិនិត្យតារាងខួបធាតុគីមី។',
'Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.',
'មាស (Au) មានលេខអាតូម 79 មានន័យថាវាមានប្រូតុង 79 ក្នុងស្នូលរបស់វា។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 5, 'fill_blank',
'The atomic number of an element equals the number of _____ in its atoms.',
'លេខអាតូមនៃធាតុស្មើនឹងចំនួន _____ ក្នុងអាតូមរបស់វា។',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
NULL,
'protons',
10, 'easy',
'This defines the element.',
'នេះកំណត់ធាតុ។',
'The atomic number is defined as the number of protons in an atom and determines which element it is.',
'លេខអាតូមត្រូវបានកំណត់ជាចំនួនប្រូតុងក្នុងអាតូម និងកំណត់ថាវាជាធាតុមួយណា។');