-- Stage 3 Batch 1: Exercises for first 5 simulations (25 exercises total)

INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

-- 18. Build an Atom (d33f834a-20e4-49b5-97b6-2bb73b4dc72f)
('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 1, 'multiple_choice',
'Which subatomic particle has a negative charge?',
'តើភាគល្អិតតូចជាងអាតូមមួយណាមានបន្ទុកអវិជ្ជមាន?',
'Choose the correct particle.',
'ជ្រើសរើសភាគល្អិតត្រឹមត្រូវ។',
'{"options": [{"en": "Proton", "km": "ប្រូតុង"}, {"en": "Neutron", "km": "នឺត្រុង"}, {"en": "Electron", "km": "អេឡិចត្រុង"}, {"en": "Nucleus", "km": "ស្នូល"}]}',
'Electron',
10, 'easy',
'It orbits the nucleus.',
'វាគោចរជុំវិញស្នូល។',
'Electrons have a negative charge (-1), protons have a positive charge (+1), and neutrons are neutral (0).',
'អេឡិចត្រុងមានបន្ទុកអវិជ្ជមាន (-1) ប្រូតុងមានបន្ទុកវិជ្ជមាន (+1) និងនឺត្រុងអព្យាក្រឹត (0)។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 2, 'true_false',
'A neutral atom has equal numbers of protons and electrons.',
'អាតូមអព្យាក្រឹតមានចំនួនប្រូតុង និងអេឡិចត្រុងស្មើគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about charge balance.',
'គិតអំពីតុល្យភាពបន្ទុក។',
'In a neutral atom, the positive charges from protons balance the negative charges from electrons.',
'ក្នុងអាតូមអព្យាក្រឹត បន្ទុកវិជ្ជមានពីប្រូតុងតុល្យភាពបន្ទុកអវិជ្ជមានពីអេឡិចត្រុង។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 3, 'calculation',
'An ion has 11 protons and 10 electrons. What is its charge?',
'អ៊ីយ៉ុងមួយមានប្រូតុង 11 និងអេឡិចត្រុង 10។ តើបន្ទុករបស់វាគឺប៉ុន្មាន?',
'Calculate the net charge.',
'គណនាបន្ទុកសុទ្ធ។',
NULL,
'+1',
10, 'easy',
'Compare positive and negative charges.',
'ប្រៀបធៀបបន្ទុកវិជ្ជមាន និងអវិជ្ជមាន។',
'Charge = number of protons - number of electrons = 11 - 10 = +1',
'បន្ទុក = ចំនួនប្រូតុង - ចំនួនអេឡិចត្រុង = 11 - 10 = +1'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 4, 'short_answer',
'What element has 79 protons?',
'តើធាតុអ្វីមានប្រូតុង 79?',
'Name the element.',
'បញ្ជាក់ឈ្មោះធាតុ។',
NULL,
'Gold',
10, 'medium',
'Check the periodic table.',
'ពិនិត្យតារាងខួបធាតុគីមី។',
'Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.',
'មាស (Au) មានលេខអាតូម 79 មានន័យថាវាមានប្រូតុង 79 ក្នុងស្នូលរបស់វា។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 5, 'fill_blank',
'The atomic number of an element equals the number of _____ in its atoms.',
'លេខអាតូមនៃធាតុស្មើនឹងចំនួន _____ ក្នុងអាតូមរបស់វា។',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
NULL,
'protons',
10, 'easy',
'This defines the element.',
'នេះកំណត់ធាតុ។',
'The atomic number is defined as the number of protons in an atom and determines which element it is.',
'លេខអាតូមត្រូវបានកំណត់ជាចំនួនប្រូតុងក្នុងអាតូម និងកំណត់ថាវាជាធាតុមួយណា។'),

-- 19. Buoyancy (12d928e0-03b4-468c-922a-f2b68c735a3b)  
('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 1, 'multiple_choice',
'What force causes objects to float in fluids?',
'តើកម្លាំងអ្វីធ្វើឲ្យវត្ថុអណ្តែតក្នុងអង្គធាតុរាវ?',
'Choose the correct force.',
'ជ្រើសរើសកម្លាំងត្រឹមត្រូវ។',
'{"options": [{"en": "Gravity", "km": "ទំនាញផែនដី"}, {"en": "Buoyant force", "km": "កម្លាំងអណ្តែត"}, {"en": "Magnetic force", "km": "កម្លាំងមាញេទិច"}, {"en": "Friction", "km": "កកិត"}]}',
'Buoyant force',
10, 'easy',
'Upward force from fluid.',
'កម្លាំងឡើងលើពីអង្គធាតុរាវ។',
'Buoyant force is the upward force exerted by fluid on immersed objects, opposing gravity.',
'កម្លាំងអណ្តែតគឺជាកម្លាំងឡើងលើដែលអង្គធាតុរាវបង្កើតលើវត្ថុដែលជ្រមុជ ប្រឆាំងនឹងទំនាញផែនដី។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 2, 'true_false',
'An object will float if its density is less than the fluid density.',
'វត្ថុនឹងអណ្តែតប្រសិនបើដង់ស៊ីតេរបស់វាតិចជាងដង់ស៊ីតេអង្គធាតុរាវ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Think about Archimedes principle.',
'គិតអំពីគោលការណ៍អារកេម៉ែដ។',
'Objects float when their average density is less than the fluid they are in.',
'វត្ថុអណ្តែតនៅពេលដង់ស៊ីតេមធ្យមរបស់វាតិចជាងអង្គធាតុរាវដែលវាស្ថិតក្នុង។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 3, 'calculation',
'A 2 kg object displaces 3 liters of water. What is the buoyant force? (g = 10 N/kg)',
'វត្ថុ 2 kg បណ្តេញទឹក 3 លីត្រ។ តើកម្លាំងអណ្តែតគឺប៉ុន្មាន? (g = 10 N/kg)',
'Use Archimedes principle.',
'ប្រើគោលការណ៍អារកេម៉ែដ។',
NULL,
'30 N',
15, 'medium',
'Buoyant force = weight of displaced fluid',
'កម្លាំងអណ្តែត = ទម្ងន់អង្គធាតុរាវដែលបណ្តេញ',
'Buoyant force = volume × density × g = 3 L × 1 kg/L × 10 N/kg = 30 N',
'កម្លាំងអណ្តែត = មាត្រាថ្ត × ដង់ស៊ីតេ × g = 3 L × 1 kg/L × 10 N/kg = 30 N'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 4, 'short_answer',
'Why do ships made of steel float on water?',
'ហេតុអ្វីបានជាកប៉ាល់ធ្វើពីដែកអណ្តែតលើទឹក?',
'Explain the principle.',
'ពន្យល់គោលការណ៍។',
NULL,
'They displace more water than their weight',
15, 'medium',
'Consider the ship shape.',
'ពិចារណារូបរាងកប៉ាល់។',
'Ships have hollow hulls that displace large volumes of water, making their overall density less than water.',
'កប៉ាល់មានតួប្រហោងដែលបណ្តេញទឹកបរិមាណច្រើន ធ្វើឲ្យដង់ស៊ីតេសរុបតិចជាងទឹក។'),

('12d928e0-03b4-468c-922a-f2b68c735a3b', 1, 5, 'fill_blank',
'According to Archimedes principle, buoyant force equals the _____ of displaced fluid.',
'យោងតាមគោលការណ៍អារកេម៉ែដ កម្លាំងអណ្តែតស្មើនឹង _____ នៃអង្គធាតុរាវដែលបណ្តេញ។',
'Complete the principle.',
'បំពេញគោលការណ៍។',
NULL,
'weight',
10, 'easy',
'What does the fluid weigh?',
'តើអង្គធាតុរាវមានទម្ងន់ប៉ុន្មាន?',
'Archimedes principle: buoyant force equals the weight of the fluid displaced by the object.',
'គោលការណ៍អារកេម៉ែដ៖ កម្លាំងអណ្តែតស្មើនឹងទម្ងន់នៃអង្គធាតុរាវដែលវត្ថុបណ្តេញ។'),

-- 20. Buoyancy: Basics (df501e19-2322-4026-ac6f-77abf12a4015)
('df501e19-2322-4026-ac6f-77abf12a4015', 1, 1, 'multiple_choice',
'What happens when you put a cork in water?',
'តើអ្វីកើតឡើងនៅពេលអ្នកដាក់ឆ្នុកក្នុងទឹក?',
'Predict the result.',
'ទាយលទ្ធផល។',
'{"options": [{"en": "It sinks", "km": "វាលិច"}, {"en": "It floats", "km": "វាអណ្តែត"}, {"en": "It dissolves", "km": "វារលាយ"}, {"en": "Nothing happens", "km": "គ្មានអ្វីកើតឡើង"}]}',
'It floats',
10, 'easy',
'Cork is less dense than water.',
'ឆ្នុកមានដង់ស៊ីតេតិចជាងទឹក។',
'Cork floats because it is less dense than water, so the buoyant force is greater than its weight.',
'ឆ្នុកអណ្តែតពីព្រោះវាមានដង់ស៊ីតេតិចជាងទឹក ដូច្នេះកម្លាំងអណ្តែតធំជាងទម្ងន់របស់វា។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 2, 'true_false',
'All metals sink in water.',
'លោហៈទាំងអស់លិចក្នុងទឹក។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Think about shape and air.',
'គិតអំពីរូបរាង និងខ្យល់។',
'While most solid metals are denser than water, metal objects with air inside (like boats) can float.',
'ទោះបីលោហៈរឹងភាគច្រើនមានដង់ស៊ីតេខ្ពស់ជាងទឹក វត្ថុលោហៈដែលមានខ្យល់នៅខាងក្នុង (ដូចជាទូក) អាចអណ្តែតបាន។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 3, 'short_answer',
'Why does ice float on water?',
'ហេតុអ្វីបានជាទឹកកកអណ្តែតលើទឹក?',
'Explain the reason.',
'ពន្យល់មូលហេតុ។',
NULL,
'Ice is less dense than water',
10, 'easy',
'Water expands when it freezes.',
'ទឹកពង្រីកនៅពេលកក។',
'When water freezes, it expands and becomes less dense than liquid water, so ice floats.',
'នៅពេលទឹកកក វាពង្រីក និងក្លាយជាដង់ស៊ីតេតិចជាងទឹករាវ ដូច្នេះទឹកកកអណ្តែត។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 4, 'fill_blank',
'Objects that are _____ dense than water will float.',
'វត្ថុដែលមានដង់ស៊ីតេ _____ ជាងទឹកនឹងអណ្តែត។',
'Complete the comparison.',
'បំពេញការប្រៀបធៀប។',
NULL,
'less',
10, 'easy',
'Floating objects are lighter.',
'វត្ថុអណ្តែតស្រាលជាង។',
'Objects with density less than water (1 g/cm³) will float on water surface.',
'វត្ថុដែលមានដង់ស៊ីតេតិចជាងទឹក (1 g/cm³) នឹងអណ្តែតលើផ្ទៃទឹក។'),

('df501e19-2322-4026-ac6f-77abf12a4015', 1, 5, 'multiple_choice',
'What would happen to a floating object if you pushed it underwater?',
'តើអ្វីនឹងកើតឡើងចំពោះវត្ថុអណ្តែតប្រសិនបើអ្នករុញវាចុះក្រោមទឹក?',
'Predict the behavior.',
'ទាយអាកប្បកិរិយា។',
'{"options": [{"en": "It stays underwater", "km": "វានៅក្រោមទឹក"}, {"en": "It pops back up", "km": "វាលេចឡើងវិញ"}, {"en": "It dissolves", "km": "វារលាយ"}, {"en": "It gets heavier", "km": "វាធ្ងន់ឡើង"}]}',
'It pops back up',
15, 'medium',
'Buoyant force pushes it up.',
'កម្លាំងអណ្តែតរុញវាឡើងលើ។',
'When submerged, the buoyant force becomes greater than the object weight, pushing it back to the surface.',
'នៅពេលជ្រមុជ កម្លាំងអណ្តែតក្លាយជាធំជាងទម្ងន់វត្ថុ រុញវាត្រលប់ទៅផ្ទៃ។'),

-- 21. Calculus Grapher (01ad94ed-a1ba-4f5d-816e-9edd940b7ab0)
('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 1, 'multiple_choice',
'What does the derivative of a function represent?',
'តើដេរីវេនៃអនុគមន៍តំណាងឲ្យអ្វី?',
'Choose the mathematical meaning.',
'ជ្រើសរើសន័យគណិតវិទ្យា។',
'{"options": [{"en": "The area under the curve", "km": "ផ្ទៃក្រោមខ្សែកោង"}, {"en": "The rate of change", "km": "អត្រាការផ្លាស់ប្តូរ"}, {"en": "The maximum value", "km": "តម្លៃអតិបរមា"}, {"en": "The average", "km": "មធ្យម"}]}',
'The rate of change',
15, 'medium',
'Think about slope.',
'គិតអំពីជម្រាល។',
'The derivative represents the instantaneous rate of change or slope of the function at any point.',
'ដេរីវេតំណាងឲ្យអត្រាការផ្លាស់ប្តូរភ្លាមៗ ឬជម្រាលនៃអនុគមន៍នៅចំណុចណាមួយ។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 2, 'calculation',
'What is the derivative of f(x) = x²?',
'តើដេរីវេនៃ f(x) = x² គឺអ្វី?',
'Apply the power rule.',
'អនុវត្តច្បាប់កម្លាំង។',
NULL,
'2x',
10, 'easy',
'Power rule: d/dx(xⁿ) = nxⁿ⁻¹',
'ច្បាប់កម្លាំង៖ d/dx(xⁿ) = nxⁿ⁻¹',
'Using the power rule: d/dx(x²) = 2x²⁻¹ = 2x¹ = 2x',
'ប្រើច្បាប់កម្លាំង៖ d/dx(x²) = 2x²⁻¹ = 2x¹ = 2x'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 3, 'true_false',
'The integral is the reverse operation of differentiation.',
'អាំងតេក្រាលគឺជាប្រតិបត្តិការច្រាសនៃការធ្វើដេរីវេ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'They are inverse operations.',
'ពួកវាជាប្រតិបត្តិការច្រាស។',
'Integration and differentiation are inverse operations - integration undoes differentiation.',
'អាំងតេក្រាល និងការធ្វើដេរីវេជាប្រតិបត្តិការច្រាស - អាំងតេក្រាលដោះសេចការធ្វើដេរីវេ។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 4, 'fill_blank',
'The second derivative tells us about the _____ of a function.',
'ដេរីវេទីពីរប្រាប់យើងអំពី _____ របស់អនុគមន៍។',
'What property does it describe?',
'តើវាពិពណ៌នាលក្ខណៈសម្បត្តិអ្វី?',
NULL,
'concavity',
15, 'medium',
'Up or down curvature.',
'ខ្សែកោងឡើងលើ ឬចុះក្រោម។',
'The second derivative indicates concavity - whether the function curves up (positive) or down (negative).',
'ដេរីវេទីពីរបង្ហាញភាពកោង - ថាតើអនុគមន៍កោងឡើងលើ (វិជ្ជមាន) ឬចុះក្រោម (អវិជ្ជមាន)។'),

('01ad94ed-a1ba-4f5d-816e-9edd940b7ab0', 1, 5, 'short_answer',
'What does it mean when the derivative equals zero?',
'តើមានន័យអ្វីនៅពេលដេរីវេស្មើសូន្យ?',
'Describe this condition.',
'ពិពណ៌នាលក្ខខណ្ឌនេះ។',
NULL,
'Critical point or turning point',
15, 'medium',
'The slope is zero.',
'ជម្រាលស្មើសូន្យ។',
'When f prime (x) = 0, we have a critical point where the function may have a maximum, minimum, or inflection point.',
'នៅពេល f prime (x) = 0 យើងមានចំណុចវិបត្តិដែលអនុគមន៍អាចមានអតិបរមា អប្បបរមា ឬចំណុចពត់។'),

-- 22. Capacitor Lab: Basics (3649be5b-3c1d-4468-a690-00675ae843a4)
('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 1, 'multiple_choice',
'What is a capacitor?',
'តើកាប៉ាស៊ីតរ័គឺជាអ្វី?',
'Choose the best definition.',
'ជ្រើសរើសនិយមន្តល្អបំផុត។',
'{"options": [{"en": "A device that stores electric charge", "km": "ឧបករណ៍រក្សាទុកបន្ទុកអគ្គិសនី"}, {"en": "A device that creates electricity", "km": "ឧបករណ៍បង្កើតអគ្គិសនី"}, {"en": "A type of battery", "km": "ប្រភេទថ្ម"}, {"en": "A resistor", "km": "ធាតុទប់"}]}',
'A device that stores electric charge',
10, 'easy',
'It holds electrical energy.',
'វារក្សាទុកថាមពលអគ្គិសនី។',
'A capacitor stores electric charge on two conducting plates separated by an insulator (dielectric).',
'កាប៉ាស៊ីតរ័រក្សាទុកបន្ទុកអគ្គិសនីលើបន្ទះចំនួនពីរដែលបំបែកដោយអ៊ីសូឡង់ (ដាយអេឡិចត្រិច)។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 2, 'calculation',
'A capacitor has a capacitance of 10 μF and is charged to 12 V. How much charge does it store?',
'កាប៉ាស៊ីតរ័មួយមានកាប៉ាស៊ីតង់ 10 μF និងត្រូវបានបញ្ចូលបន្ទុកទៅ 12 V។ តើវារក្សាទុកបន្ទុកប៉ុន្មាន?',
'Use Q = CV',
'ប្រើ Q = CV',
NULL,
'120 μC',
15, 'medium',
'Q = C × V',
'Q = C × V',
'Q = CV = 10 μF × 12 V = 120 μC (microcoulombs)',
'Q = CV = 10 μF × 12 V = 120 μC (មីក្រូកូឡុម)'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 3, 'true_false',
'Increasing the distance between capacitor plates decreases capacitance.',
'ការបង្កើនចម្ងាយរវាងបន្ទះកាប៉ាស៊ីតរ័បន្ថយកាប៉ាស៊ីតង់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Think about the capacitance formula.',
'គិតអំពីរូបមន្តកាប៉ាស៊ីតង់។',
'Capacitance C = ε₀A/d, so increasing distance d decreases capacitance.',
'កាប៉ាស៊ីតង់ C = ε₀A/d ដូច្នេះការបង្កើនចម្ងាយ d បន្ថយកាប៉ាស៊ីតង់។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 4, 'short_answer',
'What happens to the electric field when you increase the voltage across a capacitor?',
'តើអ្វីកើតឡើងចំពោះវាលអគ្គិសនីនៅពេលអ្នកបង្កើនវ៉ុលនៅលើកាប៉ាស៊ីតរ័?',
'Describe the relationship.',
'ពិពណ៌នាទំនាក់ទំនង។',
NULL,
'Electric field increases',
10, 'easy',
'E = V/d',
'E = V/d',
'Electric field E = V/d, so increasing voltage V increases the electric field between the plates.',
'វាលអគ្គិសនី E = V/d ដូច្នេះការបង្កើនវ៉ុល V បង្កើនវាលអគ្គិសនីរវាងបន្ទះ។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 5, 'fill_blank',
'The energy stored in a capacitor is given by U = ½_____ .',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័ត្រូវបានផ្តល់ដោយ U = ½_____ ។',
'Complete the energy formula.',
'បំពេញរូបមន្តថាមពល។',
NULL,
'CV²',
15, 'medium',
'Energy formula for capacitors.',
'រូបមន្តថាមពលសម្រាប់កាប៉ាស៊ីតរ័។',
'The energy stored in a capacitor is U = ½CV², where C is capacitance and V is voltage.',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័គឺ U = ½CV² ដែល C គឺកាប៉ាស៊ីតង់ និង V គឺវ៉ុល។');