-- Stage 4 Batch 2: Exercises for next 10 simulations (50 exercises total - 5 per simulation)

INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

-- 1. Balloons and Static Electricity (a46f56eb-577f-4f71-b8c0-54ecdcac1a2c)
('a46f56eb-577f-4f71-b8c0-54ecdcac1a2c', 1, 1, 'multiple_choice',
'What happens when you rub a balloon on your hair?',
'តើអ្វីកើតឡើងនៅពេលអ្នកខូសប៉ោងលើសក់របស់អ្នក?',
'Choose the correct result.',
'ជ្រើសរើសលទ្ធផលត្រឹមត្រូវ។',
'{"options": [{"en": "The balloon becomes positively charged", "km": "ប៉ោងក្លាយជាបន្ទុកវិជ្ជមាន"}, {"en": "The balloon becomes negatively charged", "km": "ប៉ោងក្លាយជាបន្ទុកអវិជ្ជមាន"}, {"en": "Nothing happens", "km": "គ្មានអ្វីកើតឡើង"}, {"en": "The balloon loses all charge", "km": "ប៉ោងបាត់បង់បន្ទុកទាំងអស់"}]}',
'The balloon becomes negatively charged',
10, 'easy',
'Electrons transfer from hair to balloon.',
'អេឡិចត្រុងផ្ទេរពីសក់ទៅប៉ោង។',
'When you rub a balloon on hair, electrons transfer from hair to the balloon, giving the balloon a negative charge.',
'នៅពេលអ្នកខូសប៉ោងលើសក់ អេឡិចត្រុងផ្ទេរពីសក់ទៅប៉ោង ធ្វើឲ្យប៉ោងមានបន្ទុកអវិជ្ជមាន។'),

('a46f56eb-577f-4f71-b8c0-54ecdcac1a2c', 1, 2, 'true_false',
'Like charges repel each other.',
'បន្ទុកដូចគ្នាធាត់គ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about magnetic poles.',
'គិតអំពីប៉ូលម៉ាញេទិច។',
'Like charges (positive-positive or negative-negative) repel, while opposite charges attract.',
'បន្ទុកដូចគ្នា (វិជ្ជមាន-វិជ្ជមាន ឬអវិជ្ជមាន-អវិជ្ជមាន) ធាត់គ្នា ខណៈបន្ទុកផ្ទុយគ្នាទាក់ទាញ។'),

('a46f56eb-577f-4f71-b8c0-54ecdcac1a2c', 1, 3, 'short_answer',
'Why does your hair stand up after rubbing a balloon on it?',
'ហេតុអ្វីបានជាសក់របស់អ្នកឈរឡើងបន្ទាប់ពីខូសប៉ោងលើវា?',
'Explain the phenomenon.',
'ពន្យល់បាតុភូតនេះ។',
NULL,
'Hair loses electrons and becomes positively charged',
15, 'medium',
'Hair and balloon have opposite charges.',
'សក់ និងប៉ោងមានបន្ទុកផ្ទុយគ្នា។',
'After losing electrons to the balloon, hair becomes positively charged and is attracted to the negatively charged balloon.',
'បន្ទាប់ពីបាត់បង់អេឡិចត្រុងទៅប៉ោង សក់ក្លាយជាបន្ទុកវិជ្ជមាន និងត្រូវបានទាក់ទាញទៅប៉ោងដែលមានបន្ទុកអវិជ្ជមាន។'),

('a46f56eb-577f-4f71-b8c0-54ecdcac1a2c', 1, 4, 'fill_blank',
'Static electricity is caused by the buildup of _____ in one place.',
'អគ្គិសនីឈរស្ងៀមបណ្តាលមកពីការបង្កកុំឡុង _____ នៅកន្លែងមួយ។',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
NULL,
'electric charge',
10, 'easy',
'What builds up on surfaces?',
'តើអ្វីបង្កកុំឡុងលើផ្ទៃ?',
'Static electricity results from the buildup of electric charge (usually electrons) on a surface.',
'អគ្គិសនីឈរស្ងៀមកើតចេញពីការបង្កកុំឡុងបន្ទុកអគ្គិសនី (ជាធម្មតាអេឡិចត្រុង) លើផ្ទៃ។'),

('a46f56eb-577f-4f71-b8c0-54ecdcac1a2c', 1, 5, 'multiple_choice',
'What happens when you bring a charged balloon near small pieces of paper?',
'តើអ្វីកើតឡើងនៅពេលអ្នកយកប៉ោងដែលមានបន្ទុកមកជិតបំណែកក្រដាសតូចៗ?',
'Predict the result.',
'ទាយលទ្ធផល។',
'{"options": [{"en": "Paper is repelled", "km": "ក្រដាសត្រូវបានធាត់"}, {"en": "Paper is attracted", "km": "ក្រដាសត្រូវបានទាក់ទាញ"}, {"en": "Nothing happens", "km": "គ្មានអ្វីកើតឡើង"}, {"en": "Paper becomes hot", "km": "ក្រដាសក្លាយជាក្តៅ"}]}',
'Paper is attracted',
15, 'medium',
'Induced charges in neutral objects.',
'បន្ទុកណាំនាំក្នុងវត្ថុអព្យាក្រឹត។',
'The charged balloon induces opposite charges on the paper surface, causing attraction.',
'ប៉ោងដែលមានបន្ទុកណាំនាំបន្ទុកផ្ទុយគ្នាលើផ្ទៃក្រដាស បណ្តាលឲ្យមានការទាក់ទាញ។'),

-- 2. Bending Light (112da4a3-3504-4ea5-9d7e-c75d9bed4c21)
('112da4a3-3504-4ea5-9d7e-c75d9bed4c21', 1, 1, 'multiple_choice',
'What happens to light when it passes from air into water?',
'តើអ្វីកើតឡើងចំពោះពន្លឺនៅពេលវាឆ្លងពីខ្យល់ចូលទៅក្នុងទឹក?',
'Choose the correct behavior.',
'ជ្រើសរើសអាកប្បកិរិយាត្រឹមត្រូវ។',
'{"options": [{"en": "It bends toward the normal", "km": "វាកោងទៅរកខ្សែកម្រិត"}, {"en": "It bends away from the normal", "km": "វាកោងឆ្ងាយពីខ្សែកម្រិត"}, {"en": "It continues straight", "km": "វាបន្តត្រង់"}, {"en": "It reflects completely", "km": "វាឆ្លុះទាំងស្រុង"}]}',
'It bends toward the normal',
15, 'medium',
'Light slows down in denser medium.',
'ពន្លឺយឺតក្នុងមធ្យមក្រាស់។',
'Light bends toward the normal when entering a denser medium because it slows down.',
'ពន្លឺកោងទៅរកខ្សែកម្រិតនៅពេលចូលទៅក្នុងមធ្យមក្រាស់ ពីព្រោះវាយឺតចុះ។'),

('112da4a3-3504-4ea5-9d7e-c75d9bed4c21', 1, 2, 'calculation',
'If light travels from air (n=1.0) to glass (n=1.5) at 30°, what is the refraction angle?',
'ប្រសិនបើពន្លឺធ្វើដំណើរពីខ្យល់ (n=1.0) ទៅកញ្ចក់ (n=1.5) នៅ 30°, តើមុំចំណាក់គឺប៉ុន្មាន?',
'Use Snells law.',
'ប្រើច្បាប់ស្នែល។',
NULL,
'19.5°',
20, 'hard',
'n₁sin(θ₁) = n₂sin(θ₂)',
'n₁sin(θ₁) = n₂sin(θ₂)',
'Using Snells law: 1.0 × sin(30°) = 1.5 × sin(θ₂), so sin(θ₂) = 0.5/1.5 = 0.333, θ₂ = 19.5°',
'ប្រើច្បាប់ស្នែល៖ 1.0 × sin(30°) = 1.5 × sin(θ₂) ដូច្នេះ sin(θ₂) = 0.5/1.5 = 0.333, θ₂ = 19.5°'),

('112da4a3-3504-4ea5-9d7e-c75d9bed4c21', 1, 3, 'true_false',
'Total internal reflection occurs when light travels from a denser to a less dense medium.',
'ការឆ្លុះខាងក្នុងទាំងស្រុងកើតឡើងនៅពេលពន្លឺធ្វើដំណើរពីមធ្យមក្រាស់ទៅមធ្យមស្រាល។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'At angles greater than critical angle.',
'នៅមុំធំជាងមុំវិបត្តិ។',
'Total internal reflection happens when light travels from denser to less dense medium at angles greater than the critical angle.',
'ការឆ្លុះខាងក្នុងទាំងស្រុងកើតឡើងនៅពេលពន្លឺធ្វើដំណើរពីមធ្យមក្រាស់ទៅមធ្យមស្រាលនៅមុំធំជាងមុំវិបត្តិ។'),

('112da4a3-3504-4ea5-9d7e-c75d9bed4c21', 1, 4, 'fill_blank',
'The bending of light when it changes medium is called _____.',
'ការកោងពន្លឺនៅពេលវាផ្លាស់ប្តូរមធ្យមត្រូវបានហៅថា _____។',
'Name the phenomenon.',
'បញ្ជាក់ឈ្មោះបាតុភូត។',
NULL,
'refraction',
10, 'easy',
'Not reflection.',
'មិនមែនការឆ្លុះទេ។',
'Refraction is the bending of light when it passes from one medium to another with different density.',
'ការចំណាក់គឺជាការកោងពន្លឺនៅពេលវាឆ្លងពីមធ្យមមួយទៅមធ្យមផ្សេងដែលមានដង់ស៊ីតេខុសគ្នា។'),

('112da4a3-3504-4ea5-9d7e-c75d9bed4c21', 1, 5, 'short_answer',
'Why do objects under water appear closer than they actually are?',
'ហេតុអ្វីបានជាវត្ថុក្រោមទឹកមើលទៅជិតជាងពិតប្រាកដ?',
'Explain the optical illusion.',
'ពន្យល់អំពីការបំភាន់ទស្សនៈ។',
NULL,
'Light refracts when leaving water',
15, 'medium',
'Light bends at water-air interface.',
'ពន្លឺកោងនៅចំណុចប្រសព្វទឹក-ខ្យល់។',
'Light from underwater objects bends away from the normal when exiting water, making objects appear closer to the surface.',
'ពន្លឺពីវត្ថុក្រោមទឹកកោងឆ្ងាយពីខ្សែកម្រិតនៅពេលចេញពីទឹក ធ្វើឲ្យវត្ថុមើលទៅជិតផ្ទៃ។'),

-- 3. Blackbody Spectrum (4f483540-6551-4cb7-9c38-bf6a0705a78e)
('4f483540-6551-4cb7-9c38-bf6a0705a78e', 1, 1, 'multiple_choice',
'What is a blackbody?',
'តើវត្ថុខ្មៅគឺជាអ្វី?',
'Choose the best definition.',
'ជ្រើសរើសនិយមន្តល្អបំផុត។',
'{"options": [{"en": "An object that absorbs all radiation", "km": "វត្ថុដែលស្រូបកាំរស្មីទាំងអស់"}, {"en": "An object that reflects all light", "km": "វត្ថុដែលឆ្លុះពន្លឺទាំងអស់"}, {"en": "A very dark object", "km": "វត្ថុងងឹតបំផុត"}, {"en": "A cold object", "km": "វត្ថុត្រជាក់"}]}',
'An object that absorbs all radiation',
15, 'medium',
'Perfect absorber and emitter.',
'អ្នកស្រូប និងបញ្ចេញដ៏ល្អឥតខ្ចោះ។',
'A blackbody is an idealized object that absorbs all electromagnetic radiation and emits radiation based only on its temperature.',
'វត្ថុខ្មៅគឺជាវត្ថុល្អឥតខ្ចោះដែលស្រូបកាំរស្មីអេឡិចត្រុមប៉ាញេទីសទាំងអស់ និងបញ្ចេញកាំរស្មីផ្អែកតែលើសីតុណ្ហភាពរបស់វា។'),

('4f483540-6551-4cb7-9c38-bf6a0705a78e', 1, 2, 'true_false',
'Hotter objects emit more radiation at shorter wavelengths.',
'វត្ថុក្តៅជាងបញ្ចេញកាំរស្មីច្រើនជាងនៅរលកវែងខ្លី។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Wiens displacement law.',
'ច្បាប់ផ្លាស់ទីវីន។',
'According to Wiens law, peak wavelength is inversely proportional to temperature - hotter objects peak at shorter wavelengths.',
'យោងតាមច្បាប់វីន រលកវែងកំពស់គឺសមាមាត្រច្រាសទៅនឹងសីតុណ្ហភាព - វត្ថុក្តៅជាងកំពស់នៅរលកវែងខ្លី។'),

('4f483540-6551-4cb7-9c38-bf6a0705a78e', 1, 3, 'calculation',
'A star has surface temperature 6000K. At what wavelength does it emit peak radiation?',
'ផ្កាយមួយមានសីតុណ្ហភាពផ្ទៃ 6000K។ តើនៅរលកវែងប៉ុន្មានដែលវាបញ្ចេញកាំរស្មីកំពស់?',
'Use Wiens law: λmax = 2.9×10⁻³/T',
'ប្រើច្បាប់វីន៖ λmax = 2.9×10⁻³/T',
NULL,
'483 nm',
20, 'hard',
'Blue-green light region.',
'តំបន់ពន្លឺខៀវ-បៃតង។',
'λmax = 2.9×10⁻³ m·K / 6000 K = 4.83×10⁻⁷ m = 483 nm (blue-green light)',
'λmax = 2.9×10⁻³ m·K / 6000 K = 4.83×10⁻⁷ m = 483 nm (ពន្លឺខៀវ-បៃតង)'),

('4f483540-6551-4cb7-9c38-bf6a0705a78e', 1, 4, 'short_answer',
'Why do hot objects glow red first, then white as they get hotter?',
'ហេតុអ្វីបានជាវត្ថុក្តៅពន្លឺក្រហមដំបូង បន្ទាប់មកពន្លឺសនៅពេលក្តៅជាង?',
'Explain the color progression.',
'ពន្យល់ការវិវត្តពណ៌។',
NULL,
'Peak wavelength shifts from red to shorter wavelengths',
15, 'medium',
'Temperature affects peak emission.',
'សីតុណ្ហភាពប៉ះពាល់ការបញ្ចេញកំពស់។',
'As temperature increases, peak emission shifts from red (longer wavelengths) to shorter wavelengths, eventually covering all visible spectrum (white).',
'នៅពេលសីតុណ្ហភាពកើនឡើង ការបញ្ចេញកំពស់ផ្លាស់ប្តូរពីក្រហម (រលកវែងវែង) ទៅរលកវែងខ្លី ទីបំផុតគ្របដណ្តប់រាំងពន្លឺដែលមើលឃើញទាំងអស់ (ស)។'),

('4f483540-6551-4cb7-9c38-bf6a0705a78e', 1, 5, 'fill_blank',
'The Stefan-Boltzmann law states that total power radiated is proportional to T to the _____ power.',
'ច្បាប់ស្តេហ្វាន-ប៉ុលហ្សមន្នថា កម្លាំងសរុបដែលបញ្ចេញកាំរស្មីសមាមាត្រទៅនឹង T រំលឹកកម្លាំង _____។',
'Complete the law.',
'បំពេញច្បាប់។',
NULL,
'fourth',
15, 'medium',
'T⁴ relationship.',
'ទំនាក់ទំនង T⁴។',
'Stefan-Boltzmann law: Power = σT⁴, where power is proportional to temperature to the fourth power.',
'ច្បាប់ស្តេហ្វាន-ប៉ុលហ្សមន្ន៖ Power = σT⁴ ដែលកម្លាំងសមាមាត្រទៅនឹងសីតុណ្ហភាពរំលឹកកម្លាំងទីបួន។'),

-- 4. Build a Fraction (f1da0772-c24b-48a5-a16d-2ac243fb140c)
('f1da0772-c24b-48a5-a16d-2ac243fb140c', 1, 1, 'multiple_choice',
'What does the numerator in a fraction represent?',
'តើលេខកំពូលក្នុងប្រភាគតំណាងឲ្យអ្វី?',
'Choose the correct meaning.',
'ជ្រើសរើសន័យត្រឹមត្រូវ។',
'{"options": [{"en": "Total number of parts", "km": "ចំនួនផ្នែកសរុប"}, {"en": "Number of selected parts", "km": "ចំនួនផ្នែកដែលបានជ្រើសរើស"}, {"en": "The whole", "km": "ភាគច្រើន"}, {"en": "The remainder", "km": "ផ្នែកដែលនៅសល់"}]}',
'Number of selected parts',
10, 'easy',
'Top number counts selected parts.',
'លេខកំពូលរាប់ផ្នែកដែលបានជ្រើសរើស។',
'The numerator (top number) represents how many parts are selected or being considered.',
'លេខកំពូល (លេខខាងលើ) តំណាងឲ្យចំនួនផ្នែកដែលត្រូវបានជ្រើសរើស ឬកំពុងពិចារណា។'),

('f1da0772-c24b-48a5-a16d-2ac243fb140c', 1, 2, 'calculation',
'What is 3/4 + 1/4?',
'តើ 3/4 + 1/4 គឺប៉ុន្មាន?',
'Add the fractions.',
'បូកប្រភាគ។',
NULL,
'1',
10, 'easy',
'Same denominator.',
'ភាគបែងដូចគ្នា។',
'3/4 + 1/4 = (3+1)/4 = 4/4 = 1',
'3/4 + 1/4 = (3+1)/4 = 4/4 = 1'),

('f1da0772-c24b-48a5-a16d-2ac243fb140c', 1, 3, 'true_false',
'2/3 is greater than 3/5.',
'2/3 ធំជាង 3/5។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Convert to common denominator.',
'បម្លែងទៅភាគបែងធម្មតា។',
'2/3 = 10/15 and 3/5 = 9/15, so 2/3 > 3/5 is true.',
'2/3 = 10/15 និង 3/5 = 9/15 ដូច្នេះ 2/3 > 3/5 ពិត។'),

('f1da0772-c24b-48a5-a16d-2ac243fb140c', 1, 4, 'fill_blank',
'To multiply fractions, multiply the numerators and multiply the _____.',
'ដើម្បីគុណប្រភាគ គុណលេខកំពូល និងគុណ _____។',
'Complete the rule.',
'បំពេញច្បាប់។',
NULL,
'denominators',
10, 'easy',
'Bottom numbers.',
'លេខខាងក្រោម។',
'To multiply fractions: (a/b) × (c/d) = (a×c)/(b×d) - multiply numerators and denominators.',
'ដើម្បីគុណប្រភាគ៖ (a/b) × (c/d) = (a×c)/(b×d) - គុណលេខកំពូល និងភាគបែង។'),

('f1da0772-c24b-48a5-a16d-2ac243fb140c', 1, 5, 'short_answer',
'How do you convert an improper fraction to a mixed number?',
'តើអ្នកបម្លែងប្រភាគមិនសមស្របទៅលេខចម្រុះដោយរបៀបណា?',
'Explain the process.',
'ពន្យល់ដំណើរការ។',
NULL,
'Divide numerator by denominator',
15, 'medium',
'Use division.',
'ប្រើការចែក។',
'Divide the numerator by denominator: quotient becomes whole number, remainder becomes new numerator.',
'ចែកលេខកំពូលដោយភាគបែង៖ ប្រធានបទក្លាយជាលេខគត់ ផ្នែកដែលនៅសល់ក្លាយជាលេខកំពូលថ្មី។'),

-- 5. Capacitor Lab: Basics (3649be5b-3c1d-4468-a690-00675ae843a4) - Already done in previous batch, skip

-- 6. Center and Variability (6e40860a-bdf2-4d87-915e-ae7562e11c3e)
('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 1, 'multiple_choice',
'Which measure of center is most affected by outliers?',
'តើវិធីវាស់វែងចំណុចកណ្តាលមួយណាដែលរងផលប៉ះពាល់បំផុតដោយតម្លៃខុសធម្មតា?',
'Choose the most sensitive measure.',
'ជ្រើសរើសវិធីវាស់វែងដែលរសើបបំផុត។',
'{"options": [{"en": "Mean", "km": "មធ្យម"}, {"en": "Median", "km": "មេដ្យាន"}, {"en": "Mode", "km": "ម៉ូដ"}, {"en": "Range", "km": "ជួរ"}]}',
'Mean',
15, 'medium',
'Average includes all values.',
'មធ្យមរួមបញ្ចូលតម្លៃទាំងអស់។',
'The mean is most affected by outliers because it includes all values in its calculation.',
'មធ្យមរងផលប៉ះពាល់បំផុតដោយតម្លៃខុសធម្មតា ពីព្រោះវារួមបញ្ចូលតម្លៃទាំងអស់ក្នុងការគណនារបស់វា។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 2, 'calculation',
'Find the median of: 3, 7, 2, 9, 5, 1, 8',
'រកមេដ្យាននៃ៖ 3, 7, 2, 9, 5, 1, 8',
'Sort first, then find middle.',
'តម្រៀបជាមុនសិន បន្ទាប់មករកកណ្តាល។',
NULL,
'5',
15, 'medium',
'Arrange in order: 1,2,3,5,7,8,9',
'រៀបតាមលំដាប់៖ 1,2,3,5,7,8,9',
'Sorted: 1,2,3,5,7,8,9. The median is the middle value: 5.',
'តម្រៀប៖ 1,2,3,5,7,8,9។ មេដ្យានគឺតម្លៃកណ្តាល៖ 5។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 3, 'true_false',
'Standard deviation measures how spread out data points are from the mean.',
'គម្លាតស្តង់ដារវាស់វែងពីរបៀបដែលចំណុចទិន្នន័យរាលដាលពីមធ្យម។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Measures variability.',
'វាស់វែងការប្រែប្រួល។',
'Standard deviation quantifies how much individual data points deviate from the mean.',
'គម្លាតស្តង់ដារកំណត់បរិមាណនៃការគម្លាតចំណុចទិន្នន័យបុគ្គលពីមធ្យម។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 4, 'fill_blank',
'The _____ is the difference between the maximum and minimum values in a dataset.',
'_____ គឺជាភាពខុសគ្នារវាងតម្លៃអតិបរមា និងអប្បបរមាក្នុងសំណុំទិន្នន័យ។',
'Complete the definition.',
'បំពេញនិយមន្ត។',
NULL,
'range',
10, 'easy',
'Max minus min.',
'អតិបរមាដកអប្បបរមា។',
'Range = Maximum value - Minimum value, showing the spread of the data.',
'ជួរ = តម្លៃអតិបរមា - តម្លៃអប្បបរមា បង្ហាញការរាលដាលនៃទិន្នន័យ។'),

('6e40860a-bdf2-4d87-915e-ae7562e11c3e', 1, 5, 'short_answer',
'Why might you choose median over mean for income data?',
'ហេតុអ្វីបានជាអ្នកអាចជ្រើសរើសមេដ្យានជាជាងមធ្យមសម្រាប់ទិន្នន័យចំណូល?',
'Explain the reasoning.',
'ពន្យល់យុត្តិកម្ម។',
NULL,
'Income data often has outliers (very high earners)',
15, 'medium',
'High earners skew the mean.',
'អ្នករកចំណូលខ្ពស់ធ្វើឲ្យមធ្យមលេច។',
'Income data typically has extreme high values (outliers) that inflate the mean, making median a better representation of typical income.',
'ទិន្នន័យចំណូលជាធម្មតាមានតម្លៃខ្ពស់ខ្លាំង (តម្លៃខុសធម្មតា) ដែលធ្វើឲ្យមធ្យមកើនឡើង ធ្វើឲ្យមេដ្យានជាតំណាងល្អជាងនៃចំណូលធម្មតា។');