-- Stage 4 Batch 3: Exercises for next 10 simulations (50 exercises total - 5 per simulation)

INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

-- 1. Capacitor Lab: Basics (3649be5b-3c1d-4468-a690-00675ae843a4)
('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 1, 'multiple_choice',
'What is a capacitor?',
'តើកាប៉ាស៊ីតរ័គឺជាអ្វី?',
'Choose the best definition.',
'ជ្រើសរើសនិយមន្តល្អបំផុត។',
'{"options": [{"en": "A device that stores electric charge", "km": "ឧបករណ៍រក្សាទុកបន្ទុកអគ្គិសនី"}, {"en": "A device that creates electricity", "km": "ឧបករណ៍បង្កើតអគ្គិសនី"}, {"en": "A type of battery", "km": "ប្រភេទថ្ម"}, {"en": "A resistor", "km": "ធាតុទប់"}]}',
'A device that stores electric charge',
10, 'easy',
'It holds electrical energy.',
'វារក្សាទុកថាមពលអគ្គិសនី។',
'A capacitor stores electric charge on two conducting plates separated by an insulator (dielectric).',
'កាប៉ាស៊ីតរ័រក្សាទុកបន្ទុកអគ្គិសនីលើបន្ទះចំនួនពីរដែលបំបែកដោយអ៊ីសូឡង់ (ដាយអេឡិចត្រិច)។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 2, 'calculation',
'A capacitor has a capacitance of 10 μF and is charged to 12 V. How much charge does it store?',
'កាប៉ាស៊ីតរ័មួយមានកាប៉ាស៊ីតង់ 10 μF និងត្រូវបានបញ្ចូលបន្ទុកទៅ 12 V។ តើវារក្សាទុកបន្ទុកប៉ុន្មាន?',
'Use Q = CV',
'ប្រើ Q = CV',
NULL,
'120 μC',
15, 'medium',
'Q = C × V',
'Q = C × V',
'Q = CV = 10 μF × 12 V = 120 μC (microcoulombs)',
'Q = CV = 10 μF × 12 V = 120 μC (មីក្រូកូឡុម)'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 3, 'true_false',
'Increasing the distance between capacitor plates decreases capacitance.',
'ការបង្កើនចម្ងាយរវាងបន្ទះកាប៉ាស៊ីតរ័បន្ថយកាប៉ាស៊ីតង់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Think about the capacitance formula.',
'គិតអំពីរូបមន្តកាប៉ាស៊ីតង់។',
'Capacitance C = ε₀A/d, so increasing distance d decreases capacitance.',
'កាប៉ាស៊ីតង់ C = ε₀A/d ដូច្នេះការបង្កើនចម្ងាយ d បន្ថយកាប៉ាស៊ីតង់។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 4, 'short_answer',
'What happens to the electric field when you increase the voltage across a capacitor?',
'តើអ្វីកើតឡើងចំពោះវាលអគ្គិសនីនៅពេលអ្នកបង្កើនវ៉ុលនៅលើកាប៉ាស៊ីតរ័?',
'Describe the relationship.',
'ពិពណ៌នាទំនាក់ទំនង។',
NULL,
'Electric field increases',
10, 'easy',
'E = V/d',
'E = V/d',
'Electric field E = V/d, so increasing voltage V increases the electric field between the plates.',
'វាលអគ្គិសនី E = V/d ដូច្នេះការបង្កើនវ៉ុល V បង្កើនវាលអគ្គិសនីរវាងបន្ទះ។'),

('3649be5b-3c1d-4468-a690-00675ae843a4', 1, 5, 'fill_blank',
'The energy stored in a capacitor is given by U = ½_____ .',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័ត្រូវបានផ្តល់ដោយ U = ½_____ ។',
'Complete the energy formula.',
'បំពេញរូបមន្តថាមពល។',
NULL,
'CV²',
15, 'medium',
'Energy formula for capacitors.',
'រូបមន្តថាមពលសម្រាប់កាប៉ាស៊ីតរ័។',
'The energy stored in a capacitor is U = ½CV², where C is capacitance and V is voltage.',
'ថាមពលរក្សាទុកក្នុងកាប៉ាស៊ីតរ័គឺ U = ½CV² ដែល C គឺកាប៉ាស៊ីតង់ និង V គឺវ៉ុល។'),

-- 2. Charges and Fields (1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f)
('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 1, 'multiple_choice',
'What happens to the electric field strength as you move farther from a point charge?',
'តើអ្វីកើតឡើងចំពោះកម្លាំងវាលអគ្គិសនីនៅពេលអ្នកផ្លាស់ទីឆ្ងាយពីបន្ទុកចំណុច?',
'Choose the correct relationship.',
'ជ្រើសរើសទំនាក់ទំនងត្រឹមត្រូវ។',
'{"options": [{"en": "It increases", "km": "វាកើនឡើង"}, {"en": "It decreases", "km": "វាថយចុះ"}, {"en": "It stays constant", "km": "វានៅថេរ"}, {"en": "It becomes zero", "km": "វាក្លាយជាសូន្យ"}]}',
'It decreases',
15, 'medium',
'Follows inverse square law.',
'តាមច្បាប់ការេក្រាសប្រឡាយ។',
'Electric field strength decreases with the square of distance: E ∝ 1/r²',
'កម្លាំងវាលអគ្គិសនីថយចុះតាមការេនៃចម្ងាយ៖ E ∝ 1/r²'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 2, 'calculation',
'Two charges +2μC and -3μC are 0.1 m apart. What is the force between them? (k = 9×10⁹ N⋅m²/C²)',
'បន្ទុកពីរ +2μC និង -3μC ឆ្ងាយគ្នា 0.1 m។ តើកម្លាំងរវាងពួកវាគឺប៉ុន្មាន? (k = 9×10⁹ N⋅m²/C²)',
'Use Coulombs law.',
'ប្រើច្បាប់កូឡុម។',
NULL,
'5.4 N',
20, 'hard',
'F = kq₁q₂/r²',
'F = kq₁q₂/r²',
'F = (9×10⁹)(2×10⁻⁶)(3×10⁻⁶)/(0.1)² = 54×10⁻³/0.01 = 5.4 N',
'F = (9×10⁹)(2×10⁻⁶)(3×10⁻⁶)/(0.1)² = 54×10⁻³/0.01 = 5.4 N'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 3, 'true_false',
'Electric field lines always point away from positive charges.',
'ខ្សែវាលអគ្គិសនីតែងតែចង្អុលឆ្ងាយពីបន្ទុកវិជ្ជមាន។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Direction shows force on positive test charge.',
'ទិសបង្ហាញកម្លាំងលើបន្ទុកសាកល្បងវិជ្ជមាន។',
'Electric field lines point away from positive charges and toward negative charges.',
'ខ្សែវាលអគ្គិសនីចង្អុលឆ្ងាយពីបន្ទុកវិជ្ជមាន និងទៅរកបន្ទុកអវិជ្ជមាន។'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 4, 'fill_blank',
'The SI unit for electric field is _____ .',
'ឯកតា SI សម្រាប់វាលអគ្គិសនីគឺ _____ ។',
'Name the unit.',
'បញ្ជាក់ឈ្មោះឯកតា។',
NULL,
'N/C',
10, 'easy',
'Force per unit charge.',
'កម្លាំងក្នុងមួយឯកតាបន្ទុក។',
'Electric field is measured in Newtons per Coulomb (N/C) or equivalently Volts per meter (V/m).',
'វាលអគ្គិសនីត្រូវបានវាស់ជានូតុនក្នុងមួយកូឡុម (N/C) ឬស្មើគ្នានឹងវ៉ុលក្នុងមួយម៉ែត្រ (V/m)។'),

('1fb0bbb7-fbb3-4673-aeb1-dcb2ba46d74f', 1, 5, 'short_answer',
'Why do electric field lines never cross each other?',
'ហេតុអ្វីបានជាខ្សែវាលអគ្គិសនីមិនដែលកាត់គ្នា?',
'Explain the physical reason.',
'ពន្យល់មូលហេតុផ្នែករូបវិទ្យា។',
NULL,
'Field has unique direction at each point',
15, 'medium',
'One direction per point.',
'ទិសមួយក្នុងមួយចំណុច។',
'If field lines crossed, there would be two different field directions at the same point, which is physically impossible.',
'ប្រសិនបើខ្សែវាលកាត់គ្នា នឹងមានទិសវាលពីរខុសគ្នានៅចំណុចដូចគ្នា ដែលមិនអាចកើតឡើងខាងរូបវិទ្យា។'),

-- 3. Circuit Construction Kit: AC (c0ee9bf6-3691-4cee-931d-33e3106b5413)
('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 1, 'multiple_choice',
'What does AC stand for in electricity?',
'តើ AC តំណាងឲ្យអ្វីក្នុងអគ្គិសនី?',
'Choose the correct term.',
'ជ្រើសរើសពាក្យត្រឹមត្រូវ។',
'{"options": [{"en": "Alternating Current", "km": "ចរន្តឆ្លាស់"}, {"en": "Advanced Circuit", "km": "សៀគ្វីកម្រិតខ្ពស់"}, {"en": "Active Component", "km": "សមាសធាតុសកម្ម"}, {"en": "Additional Capacity", "km": "ទំហំបន្ថែម"}]}',
'Alternating Current',
10, 'easy',
'Current changes direction.',
'ចរន្តផ្លាស់ប្តូរទិស។',
'AC (Alternating Current) is electric current that periodically changes direction.',
'AC (ចរន្តឆ្លាស់) គឺជាចរន្តអគ្គិសនីដែលផ្លាស់ប្តូរទិសជាកាលកំណត់។'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 2, 'true_false',
'AC current in homes typically has a frequency of 60 Hz in the US.',
'ចរន្ត AC ក្នុងផ្ទះជាធម្មតាមានប្រេកង់ 60 Hz នៅអាមេរិក។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Standard household frequency.',
'ប្រេកង់ស្តង់ដារក្នុងគ្រួសារ។',
'In the US, household AC current has a frequency of 60 Hz, while many other countries use 50 Hz.',
'នៅអាមេរិក ចរន្ត AC ក្នុងគ្រួសារមានប្រេកង់ 60 Hz ខណៈប្រទេសជាច្រើនផ្សេងទៀតប្រើ 50 Hz។'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 3, 'calculation',
'If an AC voltage has peak value of 170 V, what is its RMS value?',
'ប្រសិនបើវ៉ុលតាស AC មានតម្លៃកំពស់ 170 V តើតម្លៃ RMS របស់វាគឺប៉ុន្មាន?',
'Use Vrms = Vpeak/√2',
'ប្រើ Vrms = Vpeak/√2',
NULL,
'120 V',
15, 'medium',
'RMS = peak/√2',
'RMS = កំពស់/√2',
'Vrms = 170V / √2 = 170V / 1.414 ≈ 120V',
'Vrms = 170V / √2 = 170V / 1.414 ≈ 120V'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 4, 'fill_blank',
'In an AC circuit, capacitors oppose changes in _____ while inductors oppose changes in _____ .',
'ក្នុងសៀគ្វី AC កាប៉ាស៊ីតរ័ប្រឆាំងការផ្លាស់ប្តូរ _____ ខណៈអាំងឌុចទ័រប្រឆាំងការផ្លាស់ប្តូរ _____ ។',
'Complete both blanks.',
'បំពេញកន្លែងទំនេរទាំងពីរ។',
NULL,
'voltage, current',
15, 'medium',
'Capacitor-voltage, Inductor-current.',
'កាប៉ាស៊ីតរ័-វ៉ុល អាំងឌុចទ័រ-ចរន្ត។',
'Capacitors resist voltage changes, inductors resist current changes in AC circuits.',
'កាប៉ាស៊ីតរ័ទប់ការផ្លាស់ប្តូរវ៉ុល អាំងឌុចទ័រទប់ការផ្លាស់ប្តូរចរន្តក្នុងសៀគ្វី AC។'),

('c0ee9bf6-3691-4cee-931d-33e3106b5413', 1, 5, 'short_answer',
'Why do we use AC instead of DC for power transmission?',
'ហេតុអ្វីបានជាយើងប្រើ AC ជំនួស DC សម្រាប់ការបញ្ជូនថាមពល?',
'Explain the advantage.',
'ពន្យល់គុណសម្បត្តិ។',
NULL,
'AC voltage can be easily changed with transformers',
15, 'medium',
'Transformers work with AC.',
'ឧបករណ៍បម្លែងដំណើរការជាមួយ AC។',
'AC can be easily stepped up or down using transformers, reducing power losses in long-distance transmission.',
'AC អាចត្រូវបានបង្កើន ឬបន្ថយយ៉ាងងាយស្រួលដោយប្រើឧបករណ៍បម្លែង កាត់បន្ថយការបាត់បង់ថាមពលក្នុងការបញ្ជូនចម្ងាយឆ្ងាយ។'),

-- 4. Circuit Construction Kit: AC - Virtual Lab (5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7)
('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 1, 'multiple_choice',
'What tool would you use to measure AC voltage in a virtual circuit?',
'តើអ្នកនឹងប្រើឧបករណ៍អ្វីដើម្បីវាស់វ៉ុល AC ក្នុងសៀគ្វីនិម្មិត?',
'Choose the correct instrument.',
'ជ្រើសរើសឧបករណ៍ត្រឹមត្រូវ។',
'{"options": [{"en": "Voltmeter", "km": "ឧបករណ៍វាស់វ៉ុល"}, {"en": "Ammeter", "km": "ឧបករណ៍វាស់អាំង"}, {"en": "Ohmmeter", "km": "ឧបករណ៍វាស់អូម"}, {"en": "Wattmeter", "km": "ឧបករណ៍វាស់វ៉ាត់"}]}',
'Voltmeter',
10, 'easy',
'Measures potential difference.',
'វាស់ភាពខុសគ្នាសក្តានុពល។',
'A voltmeter is connected in parallel to measure voltage across circuit elements.',
'ឧបករណ៍វាស់វ៉ុលត្រូវបានតភ្ជាប់ស្របគ្នាដើម្បីវាស់វ៉ុលនៅលើធាតុសៀគ្វី។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 2, 'true_false',
'In a virtual lab, you can observe how current and voltage change over time in AC circuits.',
'ក្នុងមិនទ្រន្សុទ្ធិម្មិត អ្នកអាចសង្កេតពីរបៀបដែលចរន្ត និងវ៉ុលផ្លាស់ប្តូរទៅតាមពេលវេលាក្នុងសៀគ្វី AC។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Virtual oscilloscope shows waveforms.',
'អូស៊ីឡូស្កុបនិម្មិតបង្ហាញរូបរលក។',
'Virtual labs often include oscilloscopes to display AC waveforms showing how quantities vary with time.',
'បន្ទប់ពិសោធន៍និម្មិតជាញឹកញាប់រួមបញ្ចូលអូស៊ីឡូស្កុបដើម្បីបង្ហាញរូបរលក AC ដែលបង្ហាញពីរបៀបដែលបរិមាណប្រែប្រួលតាមពេលវេលា។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 3, 'short_answer',
'What advantage does a virtual AC circuit lab have over a physical lab?',
'តើបន្ទប់ពិសោធន៍សៀគ្វី AC និម្មិតមានគុណសម្បត្តិអ្វីជាងបន្ទប់ពិសោធន៍រាងកាយ?',
'Name one key benefit.',
'បញ្ជាក់អត្ថប្រយោជន៍សំខាន់មួយ។',
NULL,
'Can visualize invisible electrical quantities',
15, 'medium',
'Shows electric field, current flow.',
'បង្ហាញវាលអគ្គិសនី ស្ទាបចរន្ត។',
'Virtual labs can visualize invisible phenomena like electric fields, current flow, and allow unlimited experimentation without safety concerns.',
'បន្ទប់ពិសោធន៍និម្មិតអាចមើលឃើញបាតុភូតដែលមើលមិនឃើញដូចជាវាលអគ្គិសនី ស្ទាបចរន្ត និងអនុញ្ញាតឲ្យធ្វើពិសោធន៍គ្មានដែនកំណត់ដោយគ្មានបន្ទុកសុវត្ថិភាព។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 4, 'fill_blank',
'In AC circuit analysis, _____ diagrams help visualize the relationship between voltage and current.',
'ក្នុងការវិភាគសៀគ្វី AC ដ្យាក្រាម _____ ជួយមើលឃើញទំនាក់ទំនងរវាងវ៉ុល និងចរន្ត។',
'What type of diagram?',
'ដ្យាក្រាមប្រភេទអ្វី?',
NULL,
'phasor',
15, 'medium',
'Shows phase relationships.',
'បង្ហាញទំនាក់ទំនងដំណាក់កាល។',
'Phasor diagrams represent AC quantities as rotating vectors, showing magnitude and phase relationships.',
'ដ្យាក្រាមហ្វាសរ័តំណាងបរិមាណ AC ជាវ៉ិចទ័របង្វិល បង្ហាញទំហំ និងទំនាក់ទំនងដំណាក់កាល។'),

('5e9a25d6-4fc4-4eb1-b6e7-42a89470cda7', 1, 5, 'multiple_choice',
'Which component would cause voltage to lead current in an AC circuit?',
'តើសមាសធាតុមួយណាដែលបណ្តាលឲ្យវ៉ុលនាំមុខចរន្តក្នុងសៀគ្វី AC?',
'Choose the correct component.',
'ជ្រើសរើសសមាសធាតុត្រឹមត្រូវ។',
'{"options": [{"en": "Resistor", "km": "ធាតុទប់"}, {"en": "Capacitor", "km": "កាប៉ាស៊ីតរ័"}, {"en": "Inductor", "km": "អាំងឌុចទ័រ"}, {"en": "Battery", "km": "ថ្ម"}]}',
'Capacitor',
15, 'medium',
'Capacitor opposes voltage changes.',
'កាប៉ាស៊ីតរ័ប្រឆាំងការផ្លាស់ប្តូរវ៉ុល។',
'In a capacitive circuit, voltage leads current by 90°, while in inductive circuits current leads voltage.',
'ក្នុងសៀគ្វីកាប៉ាស៊ីតិវ វ៉ុលនាំមុខចរន្ត 90° ខណៈក្នុងសៀគ្វីអាំងឌុចទីវ ចរន្តនាំមុខវ៉ុល។'),

-- 5. Circuit Construction Kit: DC (8d1f5409-fc3b-431d-b418-5446f0121cf1)
('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 1, 'multiple_choice',
'What does DC stand for in electricity?',
'តើ DC តំណាងឲ្យអ្វីក្នុងអគ្គិសនី?',
'Choose the correct term.',
'ជ្រើសរើសពាក្យត្រឹមត្រូវ។',
'{"options": [{"en": "Direct Current", "km": "ចរន្តផ្ទាល់"}, {"en": "Dynamic Circuit", "km": "សៀគ្វីថាមវន្ត"}, {"en": "Dual Component", "km": "សមាសធាតុទ្វេ"}, {"en": "Distributed Charge", "km": "បន្ទុកចែកចាយ"}]}',
'Direct Current',
10, 'easy',
'Current flows in one direction.',
'ចរន្តហូរក្នុងទិសមួយ។',
'DC (Direct Current) is electric current that flows in only one direction.',
'DC (ចរន្តផ្ទាល់) គឺជាចរន្តអគ្គិសនីដែលហូរក្នុងទិសតែមួយគត់។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 2, 'calculation',
'In a series circuit with 12V battery and resistors of 4Ω and 8Ω, what is the total current?',
'ក្នុងសៀគ្វីសេរីជាមួយថ្ម 12V និងធាតុទប់ 4Ω និង 8Ω តើចរន្តសរុបគឺប៉ុន្មាន?',
'Use Ohms law with total resistance.',
'ប្រើច្បាប់អូមជាមួយធាតុទប់សរុប។',
NULL,
'1 A',
15, 'medium',
'Rtotal = R1 + R2 in series',
'Rសរុប = R1 + R2 ក្នុងសេរី',
'Rtotal = 4Ω + 8Ω = 12Ω. I = V/R = 12V/12Ω = 1A',
'Rសរុប = 4Ω + 8Ω = 12Ω។ I = V/R = 12V/12Ω = 1A'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 3, 'true_false',
'In a parallel circuit, voltage across each branch is the same.',
'ក្នុងសៀគ្វីស្របគ្នា វ៉ុលនៅលើផ្នែកនីមួយៗដូចគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'All branches connected to same points.',
'ផ្នែកទាំងអស់តភ្ជាប់ទៅចំណុចដូចគ្នា។',
'In parallel circuits, each branch experiences the same voltage as the source.',
'ក្នុងសៀគ្វីស្របគ្នា ផ្នែកនីមួយៗទទួលបានវ៉ុលដូចគ្នានឹងប្រភព។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 4, 'fill_blank',
'Kirchhoffs _____ law states that the sum of currents entering a junction equals the sum leaving.',
'ច្បាប់ _____ របស់គិចផុបថា ផលបូកចរន្តចូលទៅក្នុងចំណុចប្រសព្វស្មើផលបូកចេញ។',
'Which law?',
'ច្បាប់មួយណា?',
NULL,
'current',
10, 'easy',
'Conservation of charge.',
'ការអភិរក្សបន្ទុក។',
'Kirchhoffs Current Law (KCL) is based on conservation of electric charge at circuit junctions.',
'ច្បាប់ចរន្តគិចផុប (KCL) ផ្អែកលើការអភិរក្សបន្ទុកអគ្គិសនីនៅចំណុចប្រសព្វសៀគ្វី។'),

('8d1f5409-fc3b-431d-b418-5446f0121cf1', 1, 5, 'short_answer',
'Why do batteries eventually run out in DC circuits?',
'ហេតុអ្វីបានជាថ្មទីបំផុតអស់ក្នុងសៀគ្វី DC?',
'Explain the energy conversion.',
'ពន្យល់ការបម្លែងថាមពល។',
NULL,
'Chemical energy converts to electrical energy',
15, 'medium',
'Limited chemical reactions.',
'ប្រតិកម្មគីមីមានកំណត់។',
'Batteries convert stored chemical energy to electrical energy, and when chemical reactants are depleted, the battery dies.',
'ថ្មបម្លែងថាមពលគីមីរក្សាទុកទៅថាមពលអគ្គិសនី និងនៅពេលសារធាតុប្រតិកម្មគីមីអស់ ថ្មក៏ដាច់។'),

-- 6. Circuit Construction Kit: DC - Virtual Lab (da313250-729a-4c2b-9558-d55f8126cc05)
('da313250-729a-4c2b-9558-d55f8126cc05', 1, 1, 'multiple_choice',
'What can you observe about current in a series DC circuit using virtual instruments?',
'តើអ្នកអាចសង្កេតអ្វីអំពីចរន្តក្នុងសៀគ្វី DC សេរីដោយប្រើឧបករណ៍និម្មិត?',
'Choose the correct observation.',
'ជ្រើសរើសការសង្កេតត្រឹមត្រូវ។',
'{"options": [{"en": "Current is same everywhere", "km": "ចរន្តដូចគ្នានៅគ្រប់ទីកន្លែង"}, {"en": "Current varies by location", "km": "ចរន្តប្រែប្រួលតាមទីតាំង"}, {"en": "Current is zero", "km": "ចរន្តសូន្យ"}, {"en": "Current changes direction", "km": "ចរន្តផ្លាស់ប្តូរទិស"}]}',
'Current is same everywhere',
10, 'easy',
'Series circuit property.',
'លក្ខណៈសៀគ្វីសេរី។',
'In series circuits, current is constant throughout because there is only one path for current flow.',
'ក្នុងសៀគ្វីសេរី ចរន្តថេរនៅទូទាំង ពីព្រោះមានផ្លូវតែមួយសម្រាប់ចរន្តហូរ។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 2, 'calculation',
'If you measure 3V across a 6Ω resistor in a virtual circuit, what current is flowing?',
'ប្រសិនបើអ្នកវាស់បាន 3V នៅលើធាតុទប់ 6Ω ក្នុងសៀគ្វីនិម្មិត តើចរន្តប៉ុន្មានកំពុងហូរ?',
'Apply Ohms law.',
'អនុវត្តច្បាប់អូម។',
NULL,
'0.5 A',
10, 'easy',
'I = V/R',
'I = V/R',
'I = V/R = 3V/6Ω = 0.5A',
'I = V/R = 3V/6Ω = 0.5A'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 3, 'true_false',
'Virtual DC circuit labs allow you to see electron flow direction.',
'បន្ទប់ពិសោធន៍សៀគ្វី DC និម្មិតអនុញ្ញាតឲ្យអ្នកមើលឃើញទិសស្ទាបអេឡិចត្រុង។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Animation shows electron movement.',
'ការស្វ័យបង្ហាញពីចលនាអេឡិចត្រុង។',
'Many virtual labs animate electron flow, showing that electrons actually move opposite to conventional current direction.',
'បន្ទប់ពិសោធន៍និម្មិតជាច្រើនបង្ហាញចរន្តអេឡិចត្រុង បង្ហាញថាអេឡិចត្រុងពិតប្រាកដផ្លាស់ទីផ្ទុយទៅនឹងទិសចរន្តធម្មតា។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 4, 'fill_blank',
'Virtual ammeters must be connected in _____ to measure current correctly.',
'ឧបករណ៍វាស់អាំងនិម្មិតត្រូវតភ្ជាប់ _____ ដើម្បីវាស់ចរន្តឲ្យត្រឹមត្រូវ។',
'How should ammeters be connected?',
'តើឧបករណ៍វាស់អាំងគួរតភ្ជាប់យ៉ាងដូចម្តេច?',
NULL,
'series',
10, 'easy',
'Current flows through ammeter.',
'ចរន្តហូរកាត់ឧបករណ៍វាស់អាំង។',
'Ammeters measure current by being placed in series so all current flows through them.',
'ឧបករណ៍វាស់អាំងវាស់ចរន្តដោយដាក់ក្នុងសេរីដើម្បីឲ្យចរន្តទាំងអស់ហូរកាត់ពួកវា។'),

('da313250-729a-4c2b-9558-d55f8126cc05', 1, 5, 'short_answer',
'What happens to total resistance when you add more resistors in parallel in a virtual circuit?',
'តើអ្វីកើតឡើងចំពោះធាតុទប់សរុបនៅពេលអ្នកបន្ថែមធាតុទប់ច្រើនក្នុងស្របគ្នាក្នុងសៀគ្វីនិម្មិត?',
'Describe the effect.',
'ពិពណ៌នាឥទ្ធិពល។',
NULL,
'Total resistance decreases',
15, 'medium',
'More paths for current.',
'ផ្លូវច្រើនសម្រាប់ចរន្ត។',
'Adding parallel resistors decreases total resistance because it provides more paths for current flow.',
'ការបន្ថែមធាតុទប់ស្របគ្នាបន្ថយធាតុទប់សរុប ពីព្រោះវាផ្តល់ផ្លូវច្រើនសម្រាប់ចរន្តហូរ។'),

-- 7. Collision Lab (8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04)
('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 1, 'multiple_choice',
'What is conserved in all collisions?',
'តើអ្វីត្រូវបានអភិរក្សក្នុងការប៉ះទង្គិចទាំងអស់?',
'Choose what is always conserved.',
'ជ្រើសរើសអ្វីដែលតែងតែអភិរក្ស។',
'{"options": [{"en": "Kinetic energy", "km": "ថាមពលកិណេទិច"}, {"en": "Momentum", "km": "ម៉ូម៉ង់ទិស"}, {"en": "Velocity", "km": "ល្បឿន"}, {"en": "Mass", "km": "ម៉ាស់"}]}',
'Momentum',
15, 'medium',
'Conservation law of physics.',
'ច្បាប់អភិរក្សរូបវិទ្យា។',
'Momentum is always conserved in collisions, while kinetic energy is only conserved in elastic collisions.',
'ម៉ូម៉ង់ទិសតែងតែអភិរក្សក្នុងការប៉ះទង្គិច ខណៈថាមពលកិណេទិចអភិរក្សតែក្នុងការប៉ះទង្គិចយឺតយ៉ាវ។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 2, 'calculation',
'A 2 kg ball moving at 3 m/s collides with a stationary 1 kg ball. If they stick together, what is their final velocity?',
'បាល់ 2 kg ជាមួយល្បឿន 3 m/s ប៉ះទង្គិចបាល់ 1 kg ដែលនៅស្ងៀម។ ប្រសិនបើពួកវាជាប់គ្នា តើល្បឿនចុងក្រោយគឺប៉ុន្មាន?',
'Use conservation of momentum.',
'ប្រើការអភិរក្សម៉ូម៉ង់ទិស។',
NULL,
'2 m/s',
20, 'hard',
'pi = pf, m1v1 = (m1+m2)vf',
'pi = pf, m1v1 = (m1+m2)vf',
'(2kg)(3m/s) = (2kg+1kg)vf, so 6 = 3vf, therefore vf = 2 m/s',
'(2kg)(3m/s) = (2kg+1kg)vf ដូច្នេះ 6 = 3vf ដូច្នេះ vf = 2 m/s'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 3, 'true_false',
'In elastic collisions, both momentum and kinetic energy are conserved.',
'ក្នុងការប៉ះទង្គិចយឺតយ៉ាវ ទាំងម៉ូម៉ង់ទិស និងថាមពលកិណេទិចត្រូវបានអភិរក្ស។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Definition of elastic collision.',
'និយមន្តការប៉ះទង្គិចយឺតយ៉ាវ។',
'Elastic collisions conserve both momentum and kinetic energy, while inelastic collisions only conserve momentum.',
'ការប៉ះទង្គិចយឺតយ៉ាវអភិរក្សទាំងម៉ូម៉ង់ទិស និងថាមពលកិណេទិច ខណៈការប៉ះទង្គិចមិនយឺតយ៉ាវអភិរក្សតែម៉ូម៉ង់ទិស។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 4, 'fill_blank',
'The coefficient of restitution equals _____ for a perfectly elastic collision.',
'មេគុណនៃការស្តារទៅដើមស្មើ _____ សម្រាប់ការប៉ះទង្គិចយឺតយ៉ាវឥតខ្ចោះ។',
'What is the value?',
'តើតម្លៃគឺប៉ុន្មាន?',
NULL,
'1',
15, 'medium',
'Perfect elastic collision.',
'ការប៉ះទង្គិចយឺតយ៉ាវឥតខ្ចោះ។',
'Coefficient of restitution = 1 for elastic, 0 for perfectly inelastic, between 0-1 for partially inelastic.',
'មេគុណនៃការស្តារទៅដើម = 1 សម្រាប់យឺតយ៉ាវ 0 សម្រាប់មិនយឺតយ៉ាវឥតខ្ចោះ រវាង 0-1 សម្រាប់មិនយឺតយ៉ាវមួយផ្នែក។'),

('8b0ccd6a-8a3a-4e04-bc3b-38de84a7ee04', 1, 5, 'short_answer',
'Why do airbags in cars help reduce injury during collisions?',
'ហេតុអ្វីបានជាបាល់ខ្យល់ក្នុងរថយន្តជួយកាត់បន្ថយរបួសក្នុងអំឡុងការប៉ះទង្គិច?',
'Explain the physics principle.',
'ពន្យល់គោលការណ៍រូបវិទ្យា។',
NULL,
'Increases collision time, reduces force',
15, 'medium',
'F = Δp/Δt',
'F = Δp/Δt',
'Airbags increase collision time, and since F = Δp/Δt, longer time means smaller force on passengers.',
'បាល់ខ្យល់បង្កើនពេលវេលាប៉ះទង្គិច និងដោយសារ F = Δp/Δt ពេលវេលាវែងមានន័យថាកម្លាំងតូចលើអ្នកដំណើរ។'),

-- 8. Color Vision (b5e80869-d70e-4596-89e0-36d9c3a753c4)
('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 1, 'multiple_choice',
'Which colors combine to make white light?',
'តើពណ៌អ្វីខ្លះបញ្ចូលគ្នាដើម្បីធ្វើពន្លឺស?',
'Choose the correct combination.',
'ជ្រើសរើសការបញ្ចូលគ្នាត្រឹមត្រូវ។',
'{"options": [{"en": "Red, Green, Blue", "km": "ក្រហម បៃតង ខៀវ"}, {"en": "Red, Yellow, Blue", "km": "ក្រហម លឿង ខៀវ"}, {"en": "Red, Green, Yellow", "km": "ក្រហម បៃតង លឿង"}, {"en": "All colors", "km": "ពណ៌ទាំងអស់"}]}',
'Red, Green, Blue',
10, 'easy',
'RGB primary colors.',
'ពណ៌បឋម RGB។',
'Red, Green, and Blue are the additive primary colors that combine to make white light.',
'ក្រហម បៃតង និងខៀវ គឺជាពណ៌បឋមបន្ថែមដែលបញ្ចូលគ្នាធ្វើពន្លឺស។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 2, 'true_false',
'The human eye has three types of color receptors.',
'ភ្នែកមនុស្សមានអ្នកទទួលពណ៌បីប្រភេទ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Cone cells in retina.',
'កោសិការាងកំប៉ុងក្នុងរ៉េទីន។',
'The eye has three types of cone cells sensitive to red, green, and blue light wavelengths.',
'ភ្នែកមានកោសិការាងកំប៉ុងបីប្រភេទដែលរសើបទៅនឹងរលកវែងពន្លឺក្រហម បៃតង និងខៀវ។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 3, 'short_answer',
'Why do we see a red apple as red?',
'ហេតុអ្វីបានជាយើងមើលឃើញផ្លែប៉ោមក្រហមជាពណ៌ក្រហម?',
'Explain the color perception.',
'ពន្យល់ការយល់ឃើញពណ៌។',
NULL,
'It reflects red light and absorbs other colors',
15, 'medium',
'Selective reflection.',
'ការឆ្លុះជ្រើសរើស។',
'Red apples appear red because they reflect red wavelengths while absorbing most other colors.',
'ផ្លែប៉ោមមើលទៅក្រហម ពីព្រោះពួកវាឆ្លុះរលកវែងក្រហម ខណៈស្រូបពណ៌ផ្សេងៗភាគច្រើន។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 4, 'fill_blank',
'Color blindness is usually caused by problems with _____ cells in the eye.',
'ភាពងងឹតពណ៌ជាធម្មតាបណ្តាលមកពីបញ្ហាជាមួយកោសិកា _____ ក្នុងភ្នែក។',
'Which type of cells?',
'កោសិកាប្រភេទអ្វី?',
NULL,
'cone',
10, 'easy',
'Color receptors.',
'អ្នកទទួលពណ៌។',
'Color blindness results from missing or malfunctioning cone cells that detect specific colors.',
'ភាពងងឹតពណ៌កើតចេញពីកោសិការាងកំប៉ុងដែលបាត់បង់ ឬមិនដំណើរការល្អដែលរកឃើញពណ៌ជាក់លាក់។'),

('b5e80869-d70e-4596-89e0-36d9c3a753c4', 1, 5, 'multiple_choice',
'What happens when you mix red and green light?',
'តើអ្វីកើតឡើងនៅពេលអ្នកលាយពន្លឺក្រហម និងបៃតង?',
'Choose the resulting color.',
'ជ្រើសរើសពណ៌លទ្ធផល។',
'{"options": [{"en": "Yellow", "km": "លឿង"}, {"en": "Orange", "km": "ប្រទាលី"}, {"en": "Purple", "km": "ស្វាយ"}, {"en": "Brown", "km": "ត្នោត"}]}',
'Yellow',
15, 'medium',
'Additive color mixing.',
'ការលាយពណ៌បន្ថែម។',
'In additive color mixing (light), red + green = yellow, which is different from pigment mixing.',
'ក្នុងការលាយពណ៌បន្ថែម (ពន្លឺ) ក្រហម + បៃតង = លឿង ដែលខុសពីការលាយសារធាតុពណ៌។'),

-- 9. Concentration (b75fc5d8-caf2-4684-b516-fa5a52267f6b)
('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 1, 'multiple_choice',
'What is concentration in chemistry?',
'តើកំហាប់ក្នុងគីមីវិទ្យាគឺជាអ្វី?',
'Choose the best definition.',
'ជ្រើសរើសនិយមន្តល្អបំផុត។',
'{"options": [{"en": "Amount of solute per unit of solution", "km": "បរិមាណសារធាតុរលាយក្នុងមួយឯកតាសោះស្រាយ"}, {"en": "Total volume of liquid", "km": "បរិមាណសរុបនៃរាវ"}, {"en": "Temperature of solution", "km": "សីតុណ្ហភាពសោះស្រាយ"}, {"en": "Color intensity", "km": "ភាពខ្លាំងពណ៌"}]}',
'Amount of solute per unit of solution',
10, 'easy',
'Solute divided by solution.',
'សារធាតុរលាយចែកដោយសោះស្រាយ។',
'Concentration measures how much solute is dissolved in a given amount of solution.',
'កំហាប់វាស់ថាមានសារធាតុរលាយប៉ុន្មានរលាយក្នុងបរិមាណសោះស្រាយដែលកំណត់។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 2, 'calculation',
'If you dissolve 20g of salt in 500mL of water, what is the concentration in g/L?',
'ប្រសិនបើអ្នករលាយអំបិល 20g ក្នុងទឹក 500mL តើកំហាប់គឺប៉ុន្មានជា g/L?',
'Convert mL to L first.',
'បម្លែង mL ទៅ L ជាមុនសិន។',
NULL,
'40 g/L',
15, 'medium',
'500 mL = 0.5 L',
'500 mL = 0.5 L',
'Concentration = 20g / 0.5L = 40 g/L',
'កំហាប់ = 20g / 0.5L = 40 g/L'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 3, 'true_false',
'Adding more water to a solution increases its concentration.',
'ការបន្ថែមទឹកច្រើនទៅសោះស្រាយបង្កើនកំហាប់របស់វា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Dilution decreases concentration.',
'ការបន្សាបបន្ថយកំហាប់។',
'Adding water dilutes the solution, decreasing concentration by increasing the total volume.',
'ការបន្ថែមទឹកធ្វើឲ្យសោះស្រាយស្រាល បន្ថយកំហាប់ដោយបង្កើនបរិមាណសរុប។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 4, 'fill_blank',
'Molarity is concentration expressed as moles of solute per _____ of solution.',
'ម៉ូឡារិតេគឺកំហាប់បង្ហាញជាម៉ូលសារធាតុរលាយក្នុងមួយ _____ នៃសោះស្រាយ។',
'What unit of volume?',
'ឯកតាបរិមាណអ្វី?',
NULL,
'liter',
10, 'easy',
'Standard volume unit.',
'ឯកតាបរិមាណស្តង់ដារ។',
'Molarity (M) = moles of solute / liters of solution, commonly used in chemistry.',
'ម៉ូឡារិតេ (M) = ម៉ូលសារធាតុរលាយ / លីត្រសោះស្រាយ ប្រើជាទូទៅក្នុងគីមីវិទ្យា។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 5, 'short_answer',
'How would you make a solution more concentrated?',
'តើអ្នកនឹងធ្វើយ៉ាងដូចម្តេចដើម្បីធ្វើឲ្យសោះស្រាយកាន់តែខ្ញាប់?',
'Name two methods.',
'បញ្ជាក់វិធីពីរ។',
NULL,
'Add more solute or remove solvent',
15, 'medium',
'Increase solute or decrease solvent.',
'បង្កើនសារធាតុរលាយ ឬបន្ថយសារធាតុរំលាយ។',
'You can increase concentration by adding more solute or by removing solvent (like evaporation).',
'អ្នកអាចបង្កើនកំហាប់ដោយបន្ថែមសារធាតុរលាយច្រើន ឬដោយដកសារធាតុរំលាយ (ដូចជាការហាលថ្ងៃ)។'),

-- 10. Coulombs Law (03d96604-735d-480d-ab18-89033ec90361)
('03d96604-735d-480d-ab18-89033ec90361', 1, 1, 'multiple_choice',
'What does Coulombs Law describe?',
'តើច្បាប់កូឡុមពិពណ៌នាអំពីអ្វី?',
'Choose the correct description.',
'ជ្រើសរើសការពិពណ៌នាត្រឹមត្រូវ។',
'{"options": [{"en": "Force between electric charges", "km": "កម្លាំងរវាងបន្ទុកអគ្គិសនី"}, {"en": "Speed of light", "km": "ល្បឿនពន្លឺ"}, {"en": "Magnetic field strength", "km": "កម្លាំងវាលម៉ាញេទិច"}, {"en": "Current in wires", "km": "ចរន្តក្នុងលួស"}]}',
'Force between electric charges',
10, 'easy',
'Electrostatic force law.',
'ច្បាប់កម្លាំងអេឡិចត្រុស្តាទិច។',
'Coulombs Law describes the electrostatic force between two point charges.',
'ច្បាប់កូឡុមពិពណ៌នាកម្លាំងអេឡិចត្រុស្តាទិចរវាងបន្ទុកចំណុចពីរ។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 2, 'calculation',
'Two charges of +3μC and +6μC are 0.2m apart. What is the force between them? (k = 9×10⁹ N⋅m²/C²)',
'បន្ទុកពីរ +3μC និង +6μC ឆ្ងាយគ្នា 0.2m។ តើកម្លាំងរវាងពួកវាគឺប៉ុន្មាន? (k = 9×10⁹ N⋅m²/C²)',
'Apply Coulombs Law formula.',
'អនុវត្តរូបមន្តច្បាប់កូឡុម។',
NULL,
'4.05 N',
20, 'hard',
'F = kq₁q₂/r²',
'F = kq₁q₂/r²',
'F = (9×10⁹)(3×10⁻⁶)(6×10⁻⁶)/(0.2)² = 162×10⁻³/0.04 = 4.05 N',
'F = (9×10⁹)(3×10⁻⁶)(6×10⁻⁶)/(0.2)² = 162×10⁻³/0.04 = 4.05 N'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 3, 'true_false',
'The force between charges decreases with the square of the distance.',
'កម្លាំងរវាងបន្ទុកថយចុះតាមការេនៃចម្ងាយ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
15, 'medium',
'Inverse square law.',
'ច្បាប់ការេច្រាស។',
'Coulombs Law follows an inverse square relationship: F ∝ 1/r²',
'ច្បាប់កូឡុមតាមទំនាក់ទំនងការេច្រាស៖ F ∝ 1/r²'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 4, 'fill_blank',
'The constant k in Coulombs Law equals _____ N⋅m²/C².',
'ថេរកាល k ក្នុងច្បាប់កូឡុមស្មើ _____ N⋅m²/C²។',
'Give the numerical value.',
'ផ្តល់តម្លៃលេខ។',
NULL,
'9×10⁹',
10, 'medium',
'Coulomb constant.',
'ថេរកាលកូឡុម។',
'The Coulomb constant k = 9×10⁹ N⋅m²/C² (or 8.99×10⁹ more precisely).',
'ថេរកាលកូឡុម k = 9×10⁹ N⋅m²/C² (ឬ 8.99×10⁹ កាន់តែច្បាស់)។'),

('03d96604-735d-480d-ab18-89033ec90361', 1, 5, 'short_answer',
'How does the force between two charges change if you double both charges?',
'តើកម្លាំងរវាងបន្ទុកពីរផ្លាស់ប្តូរយ៉ាងដូចម្តេចប្រសិនបើអ្នកបង្កើនបន្ទុកទាំងពីរឲ្យទ្វេដង?',
'Describe the change.',
'ពិពណ៌នាការផ្លាស់ប្តូរ។',
NULL,
'Force increases by factor of 4',
15, 'medium',
'F ∝ q₁q₂',
'F ∝ q₁q₂',
'Since F ∝ q₁q₂, doubling both charges increases the force by 2×2 = 4 times.',
'ដោយសារ F ∝ q₁q₂ ការបង្កើនបន្ទុកទាំងពីរឲ្យទ្វេដងបង្កើនកម្លាំងដោយ 2×2 = 4 ដង។');