-- Stage 1: Exercises for first 25 simulations (Biology and Chemistry)
-- Each simulation gets 5-8 exercises with different types

-- BIOLOGY SIMULATIONS EXERCISES

-- 1. Gene Expression Essentials (1714de17-ab64-40b8-beba-34f3d1e88b04)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 1, 'multiple_choice',
'What is the primary function of mRNA in gene expression?',
'តើអ្វីជាមុខងារចម្បងនៃ mRNA ក្នុងការបញ្ចេញហ្សែន?',
'Choose the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "Store genetic information", "km": "រក្សាទុកព័ត៌មានហ្សែន"}, {"en": "Carry genetic information from DNA to ribosomes", "km": "ដឹកព័ត៌មានហ្សែនពី DNA ទៅរីបូសូម"}, {"en": "Build proteins directly", "km": "សាងសង់ប្រូតេអ៊ីនដោយផ្ទាល់"}, {"en": "Replicate DNA", "km": "ចម្លង DNA"}]}',
'Carry genetic information from DNA to ribosomes',
10, 'medium',
'Think about the role of messenger RNA.',
'គិតអំពីតួនាទីនៃ RNA សារ។',
'mRNA acts as a messenger, carrying genetic information from DNA in the nucleus to ribosomes in the cytoplasm where proteins are synthesized.',
'mRNA ដើរតួជាសារ ដឹកព័ត៌មានហ្សែនពី DNA ក្នុងស្នូលទៅរីបូសូមក្នុងស៊ីតូប្លាស្មា ដែលជាកន្លែងសំយោគប្រូតេអ៊ីន។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 2, 'true_false',
'Transcription occurs in the cytoplasm of the cell.',
'ការចម្លងកើតឡើងក្នុងស៊ីតូប្លាស្មានៃកោសិកា។',
'Determine if this statement is true or false.',
'កំណត់ថាតើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត។',
NULL,
'false',
10, 'easy',
'Where does transcription actually occur?',
'តើការចម្លងពិតជាកើតឡើងនៅកន្លែងណា?',
'Transcription occurs in the nucleus where DNA is located, not in the cytoplasm.',
'ការចម្លងកើតឡើងក្នុងស្នូលដែលជាកន្លែងមាន DNA មិនមែនក្នុងស៊ីតូប្លាស្មាទេ។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 3, 'short_answer',
'Name the three main steps of protein synthesis.',
'បញ្ជាក់ជំហានសំខាន់បីនៃការសំយោគប្រូតេអ៊ីន។',
'List the three steps in order.',
'រាយបញ្ជីជំហានទាំងបីតាមលំដាប់។',
NULL,
'Transcription, Translation, Protein folding',
15, 'medium',
'Think about the journey from DNA to functional protein.',
'គិតអំពីដំណើរពី DNA ទៅប្រូតេអ៊ីនដែលមានមុខងារ។',
'The three main steps are: 1) Transcription (DNA to mRNA), 2) Translation (mRNA to amino acid chain), 3) Protein folding (amino acid chain to functional protein).',
'ជំហានសំខាន់បីគឺ៖ 1) ការចម្លង (DNA ទៅ mRNA), 2) ការបកប្រែ (mRNA ទៅខ្សែអាស៊ីតអាមីណូ), 3) ការបត់ប្រូតេអ៊ីន (ខ្សែអាស៊ីតអាមីណូទៅប្រូតេអ៊ីនមានមុខងារ)។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 4, 'calculation',
'If a gene has 600 base pairs, how many amino acids will the resulting protein have? (Assume no stop codons within the sequence)',
'ប្រសិនបើហ្សែនមួយមាន 600 គូបាស តើប្រូតេអ៊ីនលទ្ធផលនឹងមានអាស៊ីតអាមីណូប៉ុន្មាន? (សន្មតថាគ្មានកូដុងបញ្ឈប់ក្នុងលំដាប់)',
'Remember that each amino acid is coded by 3 base pairs (a codon).',
'ចងចាំថាអាស៊ីតអាមីណូនីមួយៗត្រូវបានកូដដោយគូបាស 3 (កូដុងមួយ)។',
NULL,
'200',
15, 'medium',
'Divide the total base pairs by 3.',
'ចែកគូបាសសរុបនឹង 3។',
'Each codon consists of 3 base pairs and codes for 1 amino acid. Therefore, 600 base pairs ÷ 3 = 200 amino acids.',
'កូដុងនីមួយៗមានគូបាស 3 និងកូដសម្រាប់អាស៊ីតអាមីណូ 1។ ដូច្នេះ គូបាស 600 ÷ 3 = អាស៊ីតអាមីណូ 200។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 5, 'multiple_choice',
'Which type of RNA brings amino acids to the ribosome during translation?',
'តើប្រភេទ RNA មួយណាដែលនាំអាស៊ីតអាមីណូទៅរីបូសូមក្នុងអំឡុងពេលបកប្រែ?',
'Select the correct type of RNA.',
'ជ្រើសរើសប្រភេទ RNA ត្រឹមត្រូវ។',
'{"options": [{"en": "mRNA", "km": "mRNA"}, {"en": "tRNA", "km": "tRNA"}, {"en": "rRNA", "km": "rRNA"}, {"en": "DNA", "km": "DNA"}]}',
'tRNA',
10, 'easy',
'Think about transfer RNA.',
'គិតអំពី RNA ផ្ទេរ។',
'tRNA (transfer RNA) carries specific amino acids to the ribosome during translation, matching its anticodon with the mRNA codon.',
'tRNA (RNA ផ្ទេរ) ដឹកអាស៊ីតអាមីណូជាក់លាក់ទៅរីបូសូមក្នុងអំឡុងពេលបកប្រែ ដោយផ្គូផ្គងអង់ទីកូដុងរបស់វាជាមួយកូដុង mRNA។'),

-- 2. Natural Selection (43cfa204-f71f-4b51-9275-747393fc5bbe)
('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 1, 'multiple_choice',
'What is the main driving force behind natural selection?',
'តើអ្វីជាកម្លាំងជំរុញចម្បងនៅពីក្រោយការជ្រើសរើសធម្មជាតិ?',
'Choose the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "Environmental pressures", "km": "សម្ពាធបរិស្ថាន"}, {"en": "Random mutations", "km": "ការផ្លាស់ប្តូរចៃដន្យ"}, {"en": "Artificial breeding", "km": "ការបង្កាត់សិប្បនិម្មិត"}, {"en": "Genetic engineering", "km": "វិស្វកម្មហ្សែន"}]}',
'Environmental pressures',
10, 'medium',
'Think about what causes organisms to adapt.',
'គិតអំពីអ្វីដែលធ្វើឲ្យសារពាង្គកាយសម្របខ្លួន។',
'Environmental pressures create conditions where certain traits are more advantageous for survival and reproduction, driving natural selection.',
'សម្ពាធបរិស្ថានបង្កើតលក្ខខណ្ឌដែលលក្ខណៈជាក់លាក់មានគុណប្រយោជន៍ជាងសម្រាប់ការរស់រានមានជីវិត និងការបន្តពូជ ដែលជំរុញការជ្រើសរើសធម្មជាតិ។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 2, 'true_false',
'Evolution occurs within an individual organism during its lifetime.',
'ការវិវត្តកើតឡើងក្នុងសារពាង្គកាយនីមួយៗក្នុងអំឡុងជីវិតរបស់វា។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Does evolution happen to individuals or populations?',
'តើការវិវត្តកើតឡើងចំពោះបុគ្គល ឬប្រជាកររូប?',
'Evolution occurs in populations over many generations, not within individual organisms during their lifetime.',
'ការវិវត្តកើតឡើងក្នុងប្រជាកររូបរយៈពេលជំនាន់ជាច្រើន មិនមែនក្នុងសារពាង្គកាយនីមួយៗក្នុងអំឡុងជីវិតរបស់ពួកវាទេ។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 3, 'fill_blank',
'The process by which organisms with favorable traits are more likely to survive and reproduce is called ___________.',
'ដំណើរការដែលសារពាង្គកាយដែលមានលក្ខណៈអំណោយផលទំនងជារស់រានមានជីវិត និងបន្តពូជត្រូវបានគេហៅថា ___________។',
'Fill in the blank with the correct term.',
'បំពេញចន្លោះជាមួយពាក្យត្រឹមត្រូវ។',
NULL,
'natural selection',
10, 'easy',
'This is Darwin''s famous theory.',
'នេះគឺជាទ្រឹស្តីដ៏ល្បីរបស់ដាវីន។',
'Natural selection is the process where organisms better adapted to their environment tend to survive and produce more offspring.',
'ការជ្រើសរើសធម្មជាតិគឺជាដំណើរការដែលសារពាង្គកាយសម្របខ្លួនបានល្អជាងទៅនឹងបរិស្ថានរបស់ពួកវាមានទំនោររស់រានមានជីវិត និងបង្កើតកូនចៅច្រើន។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 4, 'short_answer',
'List three factors that contribute to genetic variation in a population.',
'រាយបញ្ជីកត្តាបីដែលរួមចំណែកដល់ការប្រែប្រួលហ្សែនក្នុងប្រជាកររូប។',
'Provide three distinct factors.',
'ផ្តល់កត្តាផ្សេងគ្នាបី។',
NULL,
'Mutation, Sexual reproduction, Gene flow',
15, 'medium',
'Think about sources of genetic diversity.',
'គិតអំពីប្រភពនៃភាពចម្រុះហ្សែន។',
'Three main factors are: 1) Mutation (random changes in DNA), 2) Sexual reproduction (combining genes from two parents), 3) Gene flow (migration of individuals between populations).',
'កត្តាសំខាន់បីគឺ៖ 1) ការផ្លាស់ប្តូរ (ការផ្លាស់ប្តូរចៃដន្យក្នុង DNA), 2) ការបន្តពូជផ្លូវភេទ (ការរួមបញ្ចូលហ្សែនពីឪពុកម្តាយពីរ), 3) លំហូរហ្សែន (ការធ្វើចំណាកស្រុករបស់បុគ្គលរវាងប្រជាកររូប)។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 5, 'multiple_choice',
'In the peppered moth example, what caused the change in moth population color during the Industrial Revolution?',
'ក្នុងឧទាហរណ៍ខែម្រេច តើអ្វីបណ្តាលឲ្យមានការផ្លាស់ប្តូរពណ៌ប្រជាកររូបខែក្នុងអំឡុងបដិវត្តន៍ឧស្សាហកម្ម?',
'Select the primary cause.',
'ជ្រើសរើសមូលហេតុចម្បង។',
'{"options": [{"en": "Pollution darkened tree bark", "km": "ការបំពុលធ្វើឲ្យសំបកឈើងងឹត"}, {"en": "Moths changed color voluntarily", "km": "ខែផ្លាស់ប្តូរពណ៌ដោយស្ម័គ្រចិត្ត"}, {"en": "New species appeared", "km": "ប្រភេទថ្មីបានលេចឡើង"}, {"en": "Chemical mutations", "km": "ការផ្លាស់ប្តូរគីមី"}]}',
'Pollution darkened tree bark',
10, 'medium',
'Think about camouflage and predation.',
'គិតអំពីការក្លែងបន្លំ និងការស៊ីសាច់។',
'Industrial pollution darkened tree bark, making light-colored moths more visible to predators while dark moths were better camouflaged, leading to their increased survival.',
'ការបំពុលឧស្សាហកម្មធ្វើឲ្យសំបកឈើងងឹត ធ្វើឲ្យខែពណ៌ស្រាលងាយមើលឃើញដោយសត្វមំសាសី ខណៈខែងងឹតត្រូវបានក្លែងបន្លំបានល្អជាង នាំឲ្យការរស់រានមានជីវិតរបស់ពួកវាកើនឡើង។'),

-- 3. Neuron (276f57a5-835d-4f8c-8e3c-812cb77dd703)
('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 1, 'multiple_choice',
'What is the main function of dendrites in a neuron?',
'តើអ្វីជាមុខងារចម្បងនៃដង់ដ្រីតក្នុងណឺរ៉ូន?',
'Choose the correct function.',
'ជ្រើសរើសមុខងារត្រឹមត្រូវ។',
'{"options": [{"en": "Transmit signals away from the cell body", "km": "បញ្ជូនសញ្ញាចេញពីតួកោសិកា"}, {"en": "Receive signals from other neurons", "km": "ទទួលសញ្ញាពីណឺរ៉ូនផ្សេងទៀត"}, {"en": "Produce neurotransmitters", "km": "ផលិតសារធាតុបញ្ជូនសរសៃប្រសាទ"}, {"en": "Insulate the axon", "km": "អ៊ីសូឡង់អាក់សុង"}]}',
'Receive signals from other neurons',
10, 'easy',
'Think about the input structures of a neuron.',
'គិតអំពីរចនាសម្ព័ន្ធបញ្ចូលនៃណឺរ៉ូន។',
'Dendrites are branched extensions that receive chemical signals from other neurons and convert them to electrical signals.',
'ដង់ដ្រីតគឺជាផ្នែកពង្រីកមែកធាងដែលទទួលសញ្ញាគីមីពីណឺរ៉ូនផ្សេងទៀត និងបម្លែងពួកវាទៅជាសញ្ញាអគ្គិសនី។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 2, 'true_false',
'Action potentials travel in both directions along an axon.',
'សក្តានុពលសកម្មធ្វើដំណើរក្នុងទិសដៅទាំងពីរតាមបណ្តោយអាក់សុង។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Consider the direction of nerve impulses.',
'ពិចារណាទិសដៅនៃជំរុញសរសៃប្រសាទ។',
'Action potentials travel in only one direction - from the cell body down the axon to the axon terminals.',
'សក្តានុពលសកម្មធ្វើដំណើរក្នុងទិសដៅតែមួយ - ពីតួកោសិកាចុះតាមអាក់សុងទៅចុងអាក់សុង។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 3, 'calculation',
'If a nerve impulse travels at 120 meters per second, how long would it take to travel from your spine to your toe (assume 1 meter distance)?',
'ប្រសិនបើជំរុញសរសៃប្រសាទធ្វើដំណើរក្នុងល្បឿន 120 ម៉ែត្រក្នុងមួយវិនាទី តើវានឹងចំណាយពេលប៉ុន្មានដើម្បីធ្វើដំណើរពីឆ្អឹងខ្នងទៅម្រាមជើង (សន្មតចម្ងាយ 1 ម៉ែត្រ)?',
'Calculate the time in seconds. Round to 3 decimal places.',
'គណនាពេលវេលាជាវិនាទី។ បង្គត់ទៅទសភាគ 3 ខ្ទង់។',
NULL,
'0.008',
15, 'medium',
'Use the formula: time = distance ÷ speed',
'ប្រើរូបមន្ត៖ ពេលវេលា = ចម្ងាយ ÷ ល្បឿន',
'Time = Distance ÷ Speed = 1 meter ÷ 120 meters/second = 0.00833... seconds ≈ 0.008 seconds',
'ពេលវេលា = ចម្ងាយ ÷ ល្បឿន = 1 ម៉ែត្រ ÷ 120 ម៉ែត្រ/វិនាទី = 0.00833... វិនាទី ≈ 0.008 វិនាទី'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 4, 'short_answer',
'Name the gap between two neurons where neurotransmitters are released.',
'បញ្ជាក់ឈ្មោះគម្លាតរវាងណឺរ៉ូនពីរដែលសារធាតុបញ្ជូនសរសៃប្រសាទត្រូវបានបញ្ចេញ។',
'Provide the scientific term.',
'ផ្តល់ពាក្យវិទ្យាសាស្ត្រ។',
NULL,
'synapse',
10, 'easy',
'This is where chemical communication occurs.',
'នេះជាកន្លែងដែលការទំនាក់ទំនងគីមីកើតឡើង។',
'The synapse (or synaptic cleft) is the small gap between neurons where neurotransmitters are released to transmit signals.',
'ស៊ីណាប (ឬច្រកស៊ីណាប) គឺជាគម្លាតតូចរវាងណឺរ៉ូនដែលសារធាតុបញ្ជូនសរសៃប្រសាទត្រូវបានបញ្ចេញដើម្បីបញ្ជូនសញ្ញា។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 5, 'multiple_choice',
'What maintains the resting potential of a neuron?',
'តើអ្វីរក្សាសក្តានុពលសម្រាករបស់ណឺរ៉ូន?',
'Select the primary mechanism.',
'ជ្រើសរើសយន្តការចម្បង។',
'{"options": [{"en": "Sodium-potassium pump", "km": "ស្នប់សូដ្យូម-ប៉ូតាស្យូម"}, {"en": "Calcium channels", "km": "ឆានែលកាល់ស្យូម"}, {"en": "Myelin sheath", "km": "ស្រោមម៊ីយេលីន"}, {"en": "Neurotransmitters", "km": "សារធាតុបញ្ជូនសរសៃប្រសាទ"}]}',
'Sodium-potassium pump',
10, 'medium',
'Think about ion concentrations.',
'គិតអំពីកំហាប់អ៊ីយ៉ុង។',
'The sodium-potassium pump actively transports 3 sodium ions out and 2 potassium ions in, maintaining the negative charge inside the neuron.',
'ស្នប់សូដ្យូម-ប៉ូតាស្យូមដឹកជញ្ជូនអ៊ីយ៉ុងសូដ្យូម 3 ចេញ និងអ៊ីយ៉ុងប៉ូតាស្យូម 2 ចូល រក្សាបន្ទុកអវិជ្ជមានខាងក្នុងណឺរ៉ូន។'),

-- CHEMISTRY SIMULATIONS EXERCISES

-- 4. Acid-Base Solutions (33291077-21da-44d8-b0f2-e575f39082d8)
('33291077-21da-44d8-b0f2-e575f39082d8', 1, 1, 'multiple_choice',
'What is the pH range for acidic solutions?',
'តើជួរ pH សម្រាប់សូលុយស្យុងអាស៊ីតគឺជាអ្វី?',
'Select the correct pH range.',
'ជ្រើសរើសជួរ pH ត្រឹមត្រូវ។',
'{"options": [{"en": "0 to 6.9", "km": "0 ទៅ 6.9"}, {"en": "7.1 to 14", "km": "7.1 ទៅ 14"}, {"en": "Exactly 7", "km": "គ្រាន់តែ 7"}, {"en": "Above 14", "km": "លើស 14"}]}',
'0 to 6.9',
10, 'easy',
'Remember that 7 is neutral.',
'ចងចាំថា 7 គឺអព្យាក្រឹត។',
'Acidic solutions have a pH less than 7 (0-6.9), neutral is exactly 7, and basic solutions have pH greater than 7 (7.1-14).',
'សូលុយស្យុងអាស៊ីតមាន pH តិចជាង 7 (0-6.9) អព្យាក្រឹតគឺ 7 ហើយសូលុយស្យុងបាសមាន pH ធំជាង 7 (7.1-14)។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 2, 'calculation',
'If a solution has [H+] = 1 × 10^-4 M, what is its pH?',
'ប្រសិនបើសូលុយស្យុងមាន [H+] = 1 × 10^-4 M តើ pH របស់វាគឺប៉ុន្មាន?',
'Use the formula pH = -log[H+]',
'ប្រើរូបមន្ត pH = -log[H+]',
NULL,
'4',
15, 'medium',
'The negative log of 10^-4 is 4.',
'ឡូការីតអវិជ្ជមាននៃ 10^-4 គឺ 4។',
'pH = -log[H+] = -log(1 × 10^-4) = -(-4) = 4',
'pH = -log[H+] = -log(1 × 10^-4) = -(-4) = 4'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 3, 'true_false',
'Strong acids completely dissociate in water.',
'អាស៊ីតខ្លាំងរលាយទាំងស្រុងក្នុងទឹក។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about what "strong" means for acids.',
'គិតអំពីអ្វីដែល "ខ្លាំង" មានន័យសម្រាប់អាស៊ីត។',
'Strong acids like HCl, HNO3, and H2SO4 completely dissociate into ions in aqueous solution.',
'អាស៊ីតខ្លាំងដូចជា HCl, HNO3, និង H2SO4 រលាយទាំងស្រុងទៅជាអ៊ីយ៉ុងក្នុងសូលុយស្យុងទឹក។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 4, 'fill_blank',
'The pH scale ranges from _____ to _____.',
'មាត្រដ្ឋាន pH មានចាប់ពី _____ ទៅ _____។',
'Fill in both blanks with numbers.',
'បំពេញចន្លោះទាំងពីរជាមួយលេខ។',
NULL,
'0, 14',
10, 'easy',
'Standard pH scale limits.',
'ដែនកំណត់មាត្រដ្ឋាន pH ស្តង់ដារ។',
'The pH scale typically ranges from 0 (most acidic) to 14 (most basic), with 7 being neutral.',
'មាត្រដ្ឋាន pH ជាទូទៅមានចាប់ពី 0 (អាស៊ីតបំផុត) ទៅ 14 (បាសបំផុត) ដោយ 7 ជាអព្យាក្រឹត។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 5, 'short_answer',
'Name three common household acids.',
'បញ្ជាក់ឈ្មោះអាស៊ីតក្នុងផ្ទះទូទៅបី។',
'List three examples of acidic substances found at home.',
'រាយបញ្ជីឧទាហរណ៍បីនៃសារធាតុអាស៊ីតដែលរកឃើញនៅផ្ទះ។',
NULL,
'Vinegar, Lemon juice, Orange juice',
15, 'easy',
'Think about sour-tasting liquids.',
'គិតអំពីវត្ថុរាវដែលមានរសជាតិជូរ។',
'Common household acids include vinegar (acetic acid), citrus juices (citric acid), and soft drinks (carbonic/phosphoric acid).',
'អាស៊ីតក្នុងផ្ទះទូទៅរួមមានទឹកខ្មេះ (អាស៊ីតអាសេទិច) ទឹកផ្លែឈើក្រូច (អាស៊ីតស៊ីត្រិច) និងភេសជ្ជៈ (អាស៊ីតកាបូនិច/ផូស្វ័រិច)។'),

-- 5. Atomic Interactions (18f3a22e-3059-44df-add5-ac621da8a13c)
('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 1, 'multiple_choice',
'Which type of force is responsible for holding atoms together in a molecule?',
'តើប្រភេទកម្លាំងមួយណាទទួលខុសត្រូវក្នុងការភ្ជាប់អាតូមជាមួយគ្នាក្នុងម៉ូលេគុល?',
'Choose the primary force.',
'ជ្រើសរើសកម្លាំងចម្បង។',
'{"options": [{"en": "Gravitational force", "km": "កម្លាំងទំនាញ"}, {"en": "Electromagnetic force", "km": "កម្លាំងអេឡិចត្រូម៉ាញេទិច"}, {"en": "Nuclear force", "km": "កម្លាំងនុយក្លេអ៊ែរ"}, {"en": "Friction force", "km": "កម្លាំងកកិត"}]}',
'Electromagnetic force',
10, 'medium',
'Think about electron interactions.',
'គិតអំពីអន្តរកម្មអេឡិចត្រុង។',
'Electromagnetic forces between electrons and nuclei are responsible for chemical bonding and holding atoms together in molecules.',
'កម្លាំងអេឡិចត្រូម៉ាញេទិចរវាងអេឡិចត្រុង និងស្នូលទទួលខុសត្រូវចំពោះចំណងគីមី និងការភ្ជាប់អាតូមជាមួយគ្នាក្នុងម៉ូលេគុល។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 2, 'true_false',
'Van der Waals forces are stronger than covalent bonds.',
'កម្លាំងវ៉ាន់ដឺវ៉ាល់ខ្លាំងជាងចំណងកូវ៉ាឡង់។',
'Is this true or false?',
'តើនេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Compare intermolecular vs intramolecular forces.',
'ប្រៀបធៀបកម្លាំងអន្តរម៉ូលេគុល និងក្នុងម៉ូលេគុល។',
'Van der Waals forces are weak intermolecular forces, much weaker than covalent bonds which are strong intramolecular forces.',
'កម្លាំងវ៉ាន់ដឺវ៉ាល់គឺជាកម្លាំងអន្តរម៉ូលេគុលខ្សោយ ខ្សោយជាងចំណងកូវ៉ាឡង់ដែលជាកម្លាំងក្នុងម៉ូលេគុលខ្លាំង។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 3, 'short_answer',
'What happens to potential energy as two atoms approach each other from far apart?',
'តើអ្វីកើតឡើងចំពោះថាមពលប៉ូតង់ស្យែលនៅពេលអាតូមពីរខិតជិតគ្នាពីចម្ងាយឆ្ងាយ?',
'Describe the general trend.',
'ពិពណ៌នានិន្នាការទូទៅ។',
NULL,
'It decreases then increases',
15, 'hard',
'Think about attractive and repulsive forces.',
'គិតអំពីកម្លាំងទាក់ទាញ និងច្រានចោល។',
'Potential energy initially decreases due to attraction, reaches a minimum at optimal distance, then increases sharply due to repulsion at very close distances.',
'ថាមពលប៉ូតង់ស្យែលដំបូងថយចុះដោយសារការទាក់ទាញ ឈានដល់អប្បបរមានៅចម្ងាយល្អបំផុត បន្ទាប់មកកើនឡើងយ៉ាងខ្លាំងដោយសារការច្រានចោលនៅចម្ងាយជិតខ្លាំង។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 4, 'multiple_choice',
'At what point is a chemical bond considered formed between two atoms?',
'តើនៅចំណុចណាដែលចំណងគីមីត្រូវបានចាត់ទុកថាបានបង្កើតរវាងអាតូមពីរ?',
'Select the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "When they first touch", "km": "នៅពេលពួកវាប៉ះគ្នាដំបូង"}, {"en": "At minimum potential energy", "km": "នៅថាមពលប៉ូតង់ស្យែលអប្បបរមា"}, {"en": "At maximum kinetic energy", "km": "នៅថាមពលស៊ីនេទិចអតិបរមា"}, {"en": "When they are infinitely far apart", "km": "នៅពេលពួកវានៅឆ្ងាយគ្នាគ្មានដែនកំណត់"}]}',
'At minimum potential energy',
10, 'medium',
'Think about energy stability.',
'គិតអំពីស្ថិរភាពថាមពល។',
'A chemical bond forms when atoms reach the distance where potential energy is minimized, representing the most stable configuration.',
'ចំណងគីមីបង្កើតនៅពេលអាតូមឈានដល់ចម្ងាយដែលថាមពលប៉ូតង់ស្យែលត្រូវបានបន្ថយអប្បបរមា តំណាងឲ្យការកំណត់រចនាសម្ព័ន្ធស្ថិរភាពបំផុត។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 5, 'calculation',
'If the bond energy of H2 is 436 kJ/mol, how much energy is needed to break 2 moles of H2 molecules?',
'ប្រសិនបើថាមពលចំណងនៃ H2 គឺ 436 kJ/mol តើត្រូវការថាមពលប៉ុន្មានដើម្បីបំបែកម៉ូលេគុល H2 ចំនួន 2 ម៉ូល?',
'Calculate the total energy required.',
'គណនាថាមពលសរុបដែលត្រូវការ។',
NULL,
'872 kJ',
15, 'easy',
'Multiply bond energy by number of moles.',
'គុណថាមពលចំណងនឹងចំនួនម៉ូល។',
'Energy required = Bond energy × Number of moles = 436 kJ/mol × 2 mol = 872 kJ',
'ថាមពលដែលត្រូវការ = ថាមពលចំណង × ចំនួនម៉ូល = 436 kJ/mol × 2 mol = 872 kJ');-- Stage 1 Continued: More exercises for Chemistry simulations

-- 6. Balancing Chemical Equations (e8755c96-44da-4567-841d-bcb918b83a2e)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 1, 'multiple_choice',
'What does the Law of Conservation of Mass state?',
'តើច្បាប់អភិរក្សម៉ាស់ចែងយ៉ាងដូចម្តេច?',
'Choose the correct statement.',
'ជ្រើសរើសសេចក្តីថ្លែងការណ៍ត្រឹមត្រូវ។',
'{"options": [{"en": "Mass can be created but not destroyed", "km": "ម៉ាស់អាចបង្កើតបានប៉ុន្តែមិនអាចបំផ្លាញបាន"}, {"en": "Mass is neither created nor destroyed in chemical reactions", "km": "ម៉ាស់មិនត្រូវបានបង្កើត ឬបំផ្លាញក្នុងប្រតិកម្មគីមីទេ"}, {"en": "Mass increases during reactions", "km": "ម៉ាស់កើនឡើងក្នុងអំឡុងប្រតិកម្ម"}, {"en": "Mass always decreases", "km": "ម៉ាស់តែងតែថយចុះ"}]}',
'Mass is neither created nor destroyed in chemical reactions',
10, 'easy',
'This is a fundamental law in chemistry.',
'នេះគឺជាច្បាប់មូលដ្ឋានក្នុងគីមីវិទ្យា។',
'The Law of Conservation of Mass states that in a chemical reaction, the total mass of reactants equals the total mass of products.',
'ច្បាប់អភិរក្សម៉ាស់ចែងថាក្នុងប្រតិកម្មគីមី ម៉ាស់សរុបនៃសារធាតុប្រតិកម្មស្មើនឹងម៉ាស់សរុបនៃផលិតផល។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 2, 'fill_blank',
'In the equation 2H2 + O2 → 2H2O, the coefficient in front of H2 is _____.',
'ក្នុងសមីការ 2H2 + O2 → 2H2O មេគុណនៅមុខ H2 គឺ _____។',
'Enter the number.',
'បញ្ចូលលេខ។',
NULL,
'2',
10, 'easy',
'Look at the number before H2.',
'មើលលេខនៅមុខ H2។',
'The coefficient 2 in front of H2 indicates that 2 molecules of hydrogen gas are needed for the reaction.',
'មេគុណ 2 នៅមុខ H2 បង្ហាញថាម៉ូលេគុលឧស្ម័នអ៊ីដ្រូសែនចំនួន 2 ត្រូវការសម្រាប់ប្រតិកម្ម។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 3, 'short_answer',
'Balance this equation: Fe + O2 → Fe2O3',
'តុល្យភាពសមីការនេះ៖ Fe + O2 → Fe2O3',
'Write the balanced equation with coefficients.',
'សរសេរសមីការតុល្យភាពជាមួយមេគុណ។',
NULL,
'4Fe + 3O2 → 2Fe2O3',
20, 'medium',
'Count atoms on both sides.',
'រាប់អាតូមនៅលើភាគីទាំងពីរ។',
'Balanced: 4Fe + 3O2 → 2Fe2O3. This gives 4 Fe atoms and 6 O atoms on each side.',
'តុល្យភាព៖ 4Fe + 3O2 → 2Fe2O3។ នេះផ្តល់អាតូម Fe 4 និងអាតូម O 6 នៅលើភាគីនីមួយៗ។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 4, 'true_false',
'Changing subscripts in chemical formulas is an acceptable way to balance equations.',
'ការផ្លាស់ប្តូរអក្សរតូចក្នុងរូបមន្តគីមីគឺជាវិធីដែលអាចទទួលយកបានដើម្បីតុល្យភាពសមីការ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'What do subscripts represent?',
'តើអក្សរតូចតំណាងឲ្យអ្វី?',
'Subscripts indicate the number of atoms in a molecule and cannot be changed. Only coefficients can be adjusted to balance equations.',
'អក្សរតូចបង្ហាញចំនួនអាតូមក្នុងម៉ូលេគុល និងមិនអាចផ្លាស់ប្តូរបានទេ។ មានតែមេគុណប៉ុណ្ណោះដែលអាចកែតម្រូវដើម្បីតុល្យភាពសមីការ។'),

('e8755c96-44da-4567-841d-bcb918b83a2e', 1, 5, 'calculation',
'In the balanced equation 2Al + 3Cl2 → 2AlCl3, how many moles of Cl2 are needed to react with 4 moles of Al?',
'ក្នុងសមីការតុល្យភាព 2Al + 3Cl2 → 2AlCl3 តើត្រូវការ Cl2 ប៉ុន្មានម៉ូលដើម្បីប្រតិកម្មជាមួយ Al 4 ម៉ូល?',
'Use stoichiometry to calculate.',
'ប្រើស្តូអ៊ីចូម៉ែត្រីដើម្បីគណនា។',
NULL,
'6',
15, 'medium',
'Use the mole ratio from the balanced equation.',
'ប្រើផលធៀបម៉ូលពីសមីការតុល្យភាព។',
'From the equation: 2 mol Al : 3 mol Cl2. So for 4 mol Al: (4 mol Al) × (3 mol Cl2 / 2 mol Al) = 6 mol Cl2',
'ពីសមីការ៖ 2 mol Al : 3 mol Cl2។ ដូច្នេះសម្រាប់ 4 mol Al: (4 mol Al) × (3 mol Cl2 / 2 mol Al) = 6 mol Cl2'),

-- 7. Beer's Law Lab (7c7346a5-9428-414e-a203-dce04e727747)
('7c7346a5-9428-414e-a203-dce04e727747', 1, 1, 'multiple_choice',
'According to Beer''s Law, absorbance is directly proportional to:',
'យោងតាមច្បាប់បៀរ ការស្រូបមានសមាមាត្រដោយផ្ទាល់ទៅនឹង៖',
'Select all that apply.',
'ជ្រើសរើសទាំងអស់ដែលអនុវត្ត។',
'{"options": [{"en": "Concentration only", "km": "កំហាប់តែប៉ុណ្ណោះ"}, {"en": "Path length only", "km": "ប្រវែងផ្លូវតែប៉ុណ្ណោះ"}, {"en": "Both concentration and path length", "km": "ទាំងកំហាប់ និងប្រវែងផ្លូវ"}, {"en": "Neither", "km": "គ្មានមួយណា"}]}',
'Both concentration and path length',
10, 'medium',
'Remember A = εbc',
'ចងចាំ A = εbc',
'Beer''s Law states that A = εbc, where absorbance (A) is proportional to both concentration (c) and path length (b).',
'ច្បាប់បៀរចែងថា A = εbc ដែលការស្រូប (A) មានសមាមាត្រទៅនឹងទាំងកំហាប់ (c) និងប្រវែងផ្លូវ (b)។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 2, 'calculation',
'If a solution with concentration 0.1 M has an absorbance of 0.4, what is the absorbance of a 0.25 M solution? (Same substance and path length)',
'ប្រសិនបើសូលុយស្យុងដែលមានកំហាប់ 0.1 M មានការស្រូប 0.4 តើការស្រូបនៃសូលុយស្យុង 0.25 M គឺប៉ុន្មាន? (សារធាតុដូចគ្នា និងប្រវែងផ្លូវដូចគ្នា)',
'Use the proportional relationship.',
'ប្រើទំនាក់ទំនងសមាមាត្រ។',
NULL,
'1.0',
15, 'medium',
'Absorbance is proportional to concentration.',
'ការស្រូបមានសមាមាត្រទៅនឹងកំហាប់។',
'Since A ∝ c: A₁/c₁ = A₂/c₂. So: 0.4/0.1 = A₂/0.25. Therefore: A₂ = (0.4 × 0.25)/0.1 = 1.0',
'ដោយសារ A ∝ c: A₁/c₁ = A₂/c₂។ ដូច្នេះ៖ 0.4/0.1 = A₂/0.25។ ហេតុនេះ៖ A₂ = (0.4 × 0.25)/0.1 = 1.0'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 3, 'short_answer',
'What instrument is used to measure the absorbance of a solution?',
'តើឧបករណ៍អ្វីត្រូវបានប្រើដើម្បីវាស់ការស្រូបនៃសូលុយស្យុង?',
'Name the analytical instrument.',
'បញ្ជាក់ឈ្មោះឧបករណ៍វិភាគ។',
NULL,
'spectrophotometer',
10, 'easy',
'It measures how much light passes through.',
'វាវាស់បរិមាណពន្លឺដែលឆ្លងកាត់។',
'A spectrophotometer measures the absorbance by comparing the intensity of light before and after passing through a sample.',
'ស្ប៉ិចត្រូហ្វូតូម៉ែត្រវាស់ការស្រូបដោយប្រៀបធៀបអាំងតង់ស៊ីតេពន្លឺមុន និងក្រោយឆ្លងកាត់គំរូ។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 4, 'true_false',
'Darker colored solutions always have higher concentrations.',
'សូលុយស្យុងពណ៌ងងឹតជាងតែងតែមានកំហាប់ខ្ពស់ជាង។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'Consider different substances.',
'ពិចារណាសារធាតុផ្សេងៗ។',
'Color intensity depends on both concentration AND the molar absorptivity of the substance. Different substances absorb differently.',
'អាំងតង់ស៊ីតេពណ៌អាស្រ័យលើទាំងកំហាប់ និងការស្រូបម៉ូលនៃសារធាតុ។ សារធាតុផ្សេងៗស្រូបខុសគ្នា។'),

('7c7346a5-9428-414e-a203-dce04e727747', 1, 5, 'multiple_choice',
'What happens to transmittance as absorbance increases?',
'តើអ្វីកើតឡើងចំពោះការបញ្ជូនពេលការស្រូបកើនឡើង?',
'Choose the correct relationship.',
'ជ្រើសរើសទំនាក់ទំនងត្រឹមត្រូវ។',
'{"options": [{"en": "Transmittance increases", "km": "ការបញ្ជូនកើនឡើង"}, {"en": "Transmittance decreases", "km": "ការបញ្ជូនថយចុះ"}, {"en": "No change", "km": "គ្មានការផ្លាស់ប្តូរ"}, {"en": "Random change", "km": "ការផ្លាស់ប្តូរចៃដន្យ"}]}',
'Transmittance decreases',
10, 'medium',
'They have an inverse relationship.',
'ពួកវាមានទំនាក់ទំនងច្រាស។',
'Transmittance and absorbance are inversely related: A = -log(T). As more light is absorbed, less is transmitted.',
'ការបញ្ជូន និងការស្រូបមានទំនាក់ទំនងច្រាស៖ A = -log(T)។ នៅពេលពន្លឺត្រូវបានស្រូបច្រើន ការបញ្ជូនតិច។'),

-- 8. Build a Molecule (b68766ea-36ad-4535-addb-877f78a44a2f)
('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 1, 'multiple_choice',
'How many bonds can a carbon atom typically form?',
'តើអាតូមកាបូនអាចបង្កើតចំណងប៉ុន្មានជាទូទៅ?',
'Select the correct number.',
'ជ្រើសរើសលេខត្រឹមត្រូវ។',
'{"options": [{"en": "1", "km": "1"}, {"en": "2", "km": "2"}, {"en": "3", "km": "3"}, {"en": "4", "km": "4"}]}',
'4',
10, 'easy',
'Think about carbon''s valence electrons.',
'គិតអំពីអេឡិចត្រុងវ៉ាឡង់របស់កាបូន។',
'Carbon has 4 valence electrons and needs 4 more to complete its octet, so it typically forms 4 bonds.',
'កាបូនមានអេឡិចត្រុងវ៉ាឡង់ 4 និងត្រូវការ 4 ទៀតដើម្បីបំពេញអុកតេតរបស់វា ដូច្នេះវាជាទូទៅបង្កើតចំណង 4។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 2, 'fill_blank',
'The molecular formula for water is _____.',
'រូបមន្តម៉ូលេគុលសម្រាប់ទឹកគឺ _____។',
'Write the chemical formula.',
'សរសេររូបមន្តគីមី។',
NULL,
'H2O',
10, 'easy',
'Two hydrogen, one oxygen.',
'អ៊ីដ្រូសែនពីរ អុកស៊ីសែនមួយ។',
'Water consists of 2 hydrogen atoms bonded to 1 oxygen atom, giving the formula H2O.',
'ទឹកមានអាតូមអ៊ីដ្រូសែន 2 ភ្ជាប់ទៅអាតូមអុកស៊ីសែន 1 ផ្តល់រូបមន្ត H2O។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 3, 'short_answer',
'Name three different molecules you can build using only carbon and hydrogen atoms.',
'បញ្ជាក់ឈ្មោះម៉ូលេគុលផ្សេងគ្នាបីដែលអ្នកអាចសាងសង់ដោយប្រើតែអាតូមកាបូន និងអ៊ីដ្រូសែន។',
'List three hydrocarbons.',
'រាយបញ្ជីអ៊ីដ្រូកាបូនបី។',
NULL,
'Methane, Ethane, Propane',
15, 'medium',
'Think of simple alkanes.',
'គិតអំពីអាល់កានសាមញ្ញ។',
'Examples include methane (CH4), ethane (C2H6), propane (C3H8), ethene (C2H4), and many other hydrocarbons.',
'ឧទាហរណ៍រួមមានមេតាន (CH4) អេតាន (C2H6) ប្រូប៉ាន (C3H8) អេតែន (C2H4) និងអ៊ីដ្រូកាបូនជាច្រើនទៀត។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 4, 'true_false',
'All atoms follow the octet rule when forming molecules.',
'អាតូមទាំងអស់អនុវត្តតាមក្រឹត្យអុកតេតនៅពេលបង្កើតម៉ូលេគុល។',
'Is this always true?',
'តើនេះតែងតែពិតទេ?',
NULL,
'false',
10, 'medium',
'Consider hydrogen and other exceptions.',
'ពិចារណាអ៊ីដ្រូសែន និងករណីលើកលែងផ្សេងទៀត។',
'Hydrogen only needs 2 electrons (duet rule), and some atoms like sulfur and phosphorus can exceed the octet.',
'អ៊ីដ្រូសែនត្រូវការតែអេឡិចត្រុង 2 (ក្រឹត្យឌួអេត) ហើយអាតូមខ្លះដូចជាស្ពាន់ និងផូស្វ័រអាចលើសអុកតេត។'),

('b68766ea-36ad-4535-addb-877f78a44a2f', 1, 5, 'multiple_choice',
'What type of bond forms between two chlorine atoms in Cl2?',
'តើប្រភេទចំណងអ្វីបង្កើតរវាងអាតូមក្លរពីរក្នុង Cl2?',
'Choose the bond type.',
'ជ្រើសរើសប្រភេទចំណង។',
'{"options": [{"en": "Ionic bond", "km": "ចំណងអ៊ីយ៉ុង"}, {"en": "Covalent bond", "km": "ចំណងកូវ៉ាឡង់"}, {"en": "Metallic bond", "km": "ចំណងលោហៈ"}, {"en": "Hydrogen bond", "km": "ចំណងអ៊ីដ្រូសែន"}]}',
'Covalent bond',
10, 'easy',
'Both atoms are the same nonmetal.',
'អាតូមទាំងពីរគឺអលោហៈដូចគ្នា។',
'Two chlorine atoms share electrons equally to form a nonpolar covalent bond in Cl2.',
'អាតូមក្លរពីរចែករំលែកអេឡិចត្រុងស្មើគ្នាដើម្បីបង្កើតចំណងកូវ៉ាឡង់អប៉ូលក្នុង Cl2។'),

-- 9. Build a Nucleus (a2d8910c-0b52-4954-927a-a4a8d498cd21)
('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 1, 'multiple_choice',
'What particles are found in the nucleus of an atom?',
'តើភាគល្អិតអ្វីខ្លះត្រូវបានរកឃើញក្នុងស្នូលនៃអាតូម?',
'Select all correct answers.',
'ជ្រើសរើសចម្លើយត្រឹមត្រូវទាំងអស់។',
'{"options": [{"en": "Protons and neutrons", "km": "ប្រូតុង និងនឺត្រុង"}, {"en": "Protons and electrons", "km": "ប្រូតុង និងអេឡិចត្រុង"}, {"en": "Neutrons and electrons", "km": "នឺត្រុង និងអេឡិចត្រុង"}, {"en": "Only protons", "km": "តែប្រូតុងប៉ុណ្ណោះ"}]}',
'Protons and neutrons',
10, 'easy',
'Electrons orbit outside the nucleus.',
'អេឡិចត្រុងគោចរនៅខាងក្រៅស្នូល។',
'The nucleus contains protons (positive charge) and neutrons (neutral), while electrons orbit outside.',
'ស្នូលមានប្រូតុង (បន្ទុកវិជ្ជមាន) និងនឺត្រុង (អព្យាក្រឹត) ខណៈអេឡិចត្រុងគោចរនៅខាងក្រៅ។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 2, 'calculation',
'An atom has 6 protons and 8 neutrons. What is its mass number?',
'អាតូមមួយមានប្រូតុង 6 និងនឺត្រុង 8។ តើលេខម៉ាស់របស់វាគឺប៉ុន្មាន?',
'Add the nucleons.',
'បូកនុយក្លេអុង។',
NULL,
'14',
10, 'easy',
'Mass number = protons + neutrons',
'លេខម៉ាស់ = ប្រូតុង + នឺត្រុង',
'Mass number = number of protons + number of neutrons = 6 + 8 = 14',
'លេខម៉ាស់ = ចំនួនប្រូតុង + ចំនួននឺត្រុង = 6 + 8 = 14'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 3, 'fill_blank',
'Atoms of the same element with different numbers of neutrons are called _____.',
'អាតូមនៃធាតុដូចគ្នាដែលមានចំនួននឺត្រុងខុសគ្នាត្រូវបានគេហៅថា _____។',
'Fill in the scientific term.',
'បំពេញពាក្យវិទ្យាសាស្ត្រ។',
NULL,
'isotopes',
10, 'medium',
'Same protons, different neutrons.',
'ប្រូតុងដូចគ្នា នឺត្រុងខុសគ្នា។',
'Isotopes are atoms of the same element (same number of protons) with different numbers of neutrons.',
'អ៊ីសូតូបគឺជាអាតូមនៃធាតុដូចគ្នា (ចំនួនប្រូតុងដូចគ្នា) ដែលមានចំនួននឺត្រុងខុសគ្នា។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 4, 'true_false',
'All isotopes of an element have the same chemical properties.',
'អ៊ីសូតូបទាំងអស់នៃធាតុមួយមានលក្ខណៈសម្បត្តិគីមីដូចគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Chemical properties depend on electrons.',
'លក្ខណៈសម្បត្តិគីមីអាស្រ័យលើអេឡិចត្រុង។',
'Isotopes have the same number of electrons and thus the same chemical properties, but different physical properties.',
'អ៊ីសូតូបមានចំនួនអេឡិចត្រុងដូចគ្នា ហើយដូច្នេះមានលក្ខណៈសម្បត្តិគីមីដូចគ្នា ប៉ុន្តែលក្ខណៈសម្បត្តិរូបវិទ្យាខុសគ្នា។'),

('a2d8910c-0b52-4954-927a-a4a8d498cd21', 1, 5, 'short_answer',
'What determines the identity of an element?',
'តើអ្វីកំណត់អត្តសញ្ញាណនៃធាតុ?',
'Name the specific particle.',
'បញ្ជាក់ឈ្មោះភាគល្អិតជាក់លាក់។',
NULL,
'number of protons',
10, 'medium',
'This is the atomic number.',
'នេះគឺជាលេខអាតូម។',
'The number of protons (atomic number) uniquely identifies an element. All atoms of the same element have the same number of protons.',
'ចំនួនប្រូតុង (លេខអាតូម) កំណត់អត្តសញ្ញាណធាតុយ៉ាងពិសេស។ អាតូមទាំងអស់នៃធាតុដូចគ្នាមានចំនួនប្រូតុងដូចគ្នា។'),

-- 10. Build an Atom (d33f834a-20e4-49b5-97b6-2bb73b4dc72f)
('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 1, 'multiple_choice',
'Which subatomic particle has a negative charge?',
'តើភាគល្អិតតូចជាងអាតូមមួយណាមានបន្ទុកអវិជ្ជមាន?',
'Choose the correct particle.',
'ជ្រើសរើសភាគល្អិតត្រឹមត្រូវ។',
'{"options": [{"en": "Proton", "km": "ប្រូតុង"}, {"en": "Neutron", "km": "នឺត្រុង"}, {"en": "Electron", "km": "អេឡិចត្រុង"}, {"en": "Nucleus", "km": "ស្នូល"}]}',
'Electron',
10, 'easy',
'It orbits the nucleus.',
'វាគោចរជុំវិញស្នូល។',
'Electrons have a negative charge (-1), protons have a positive charge (+1), and neutrons are neutral (0).',
'អេឡិចត្រុងមានបន្ទុកអវិជ្ជមាន (-1) ប្រូតុងមានបន្ទុកវិជ្ជមាន (+1) និងនឺត្រុងអព្យាក្រឹត (0)។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 2, 'true_false',
'A neutral atom has equal numbers of protons and electrons.',
'អាតូមអព្យាក្រឹតមានចំនួនប្រូតុង និងអេឡិចត្រុងស្មើគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about charge balance.',
'គិតអំពីតុល្យភាពបន្ទុក។',
'In a neutral atom, the positive charges from protons balance the negative charges from electrons.',
'ក្នុងអាតូមអព្យាក្រឹត បន្ទុកវិជ្ជមានពីប្រូតុងតុល្យភាពបន្ទុកអវិជ្ជមានពីអេឡិចត្រុង។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 3, 'calculation',
'An ion has 11 protons and 10 electrons. What is its charge?',
'អ៊ីយ៉ុងមួយមានប្រូតុង 11 និងអេឡិចត្រុង 10។ តើបន្ទុករបស់វាគឺប៉ុន្មាន?',
'Calculate the net charge.',
'គណនាបន្ទុកសុទ្ធ។',
NULL,
'+1',
10, 'easy',
'Compare positive and negative charges.',
'ប្រៀបធៀបបន្ទុកវិជ្ជមាន និងអវិជ្ជមាន។',
'Charge = number of protons - number of electrons = 11 - 10 = +1',
'បន្ទុក = ចំនួនប្រូតុង - ចំនួនអេឡិចត្រុង = 11 - 10 = +1'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 4, 'short_answer',
'What element has 79 protons?',
'តើធាតុអ្វីមានប្រូតុង 79?',
'Name the element.',
'បញ្ជាក់ឈ្មោះធាតុ។',
NULL,
'Gold',
10, 'medium',
'Check the periodic table.',
'ពិនិត្យតារាងខួបធាតុគីមី។',
'Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.',
'មាស (Au) មានលេខអាតូម 79 មានន័យថាវាមានប្រូតុង 79 ក្នុងស្នូលរបស់វា។'),

('d33f834a-20e4-49b5-97b6-2bb73b4dc72f', 1, 5, 'fill_blank',
'The atomic number of an element equals the number of _____ in its atoms.',
'លេខអាតូមនៃធាតុស្មើនឹងចំនួន _____ ក្នុងអាតូមរបស់វា។',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
NULL,
'protons',
10, 'easy',
'This defines the element.',
'នេះកំណត់ធាតុ។',
'The atomic number is defined as the number of protons in an atom and determines which element it is.',
'លេខអាតូមត្រូវបានកំណត់ជាចំនួនប្រូតុងក្នុងអាតូម និងកំណត់ថាវាជាធាតុមួយណា។');