-- Stage 1: Exercises for first 25 simulations (Biology and Chemistry)
-- Each simulation gets 5-8 exercises with different types

-- BIOLOGY SIMULATIONS EXERCISES

-- 1. Gene Expression Essentials (1714de17-ab64-40b8-beba-34f3d1e88b04)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 1, 'multiple_choice',
'What is the primary function of mRNA in gene expression?',
'តើអ្វីជាមុខងារចម្បងនៃ mRNA ក្នុងការបញ្ចេញហ្សែន?',
'Choose the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "Store genetic information", "km": "រក្សាទុកព័ត៌មានហ្សែន"}, {"en": "Carry genetic information from DNA to ribosomes", "km": "ដឹកព័ត៌មានហ្សែនពី DNA ទៅរីបូសូម"}, {"en": "Build proteins directly", "km": "សាងសង់ប្រូតេអ៊ីនដោយផ្ទាល់"}, {"en": "Replicate DNA", "km": "ចម្លង DNA"}]}',
'Carry genetic information from DNA to ribosomes',
10, 'medium',
'Think about the role of messenger RNA.',
'គិតអំពីតួនាទីនៃ RNA សារ។',
'mRNA acts as a messenger, carrying genetic information from DNA in the nucleus to ribosomes in the cytoplasm where proteins are synthesized.',
'mRNA ដើរតួជាសារ ដឹកព័ត៌មានហ្សែនពី DNA ក្នុងស្នូលទៅរីបូសូមក្នុងស៊ីតូប្លាស្មា ដែលជាកន្លែងសំយោគប្រូតេអ៊ីន។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 2, 'true_false',
'Transcription occurs in the cytoplasm of the cell.',
'ការចម្លងកើតឡើងក្នុងស៊ីតូប្លាស្មានៃកោសិកា។',
'Determine if this statement is true or false.',
'កំណត់ថាតើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត។',
NULL,
'false',
10, 'easy',
'Where does transcription actually occur?',
'តើការចម្លងពិតជាកើតឡើងនៅកន្លែងណា?',
'Transcription occurs in the nucleus where DNA is located, not in the cytoplasm.',
'ការចម្លងកើតឡើងក្នុងស្នូលដែលជាកន្លែងមាន DNA មិនមែនក្នុងស៊ីតូប្លាស្មាទេ។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 3, 'short_answer',
'Name the three main steps of protein synthesis.',
'បញ្ជាក់ជំហានសំខាន់បីនៃការសំយោគប្រូតេអ៊ីន។',
'List the three steps in order.',
'រាយបញ្ជីជំហានទាំងបីតាមលំដាប់។',
NULL,
'Transcription, Translation, Protein folding',
15, 'medium',
'Think about the journey from DNA to functional protein.',
'គិតអំពីដំណើរពី DNA ទៅប្រូតេអ៊ីនដែលមានមុខងារ។',
'The three main steps are: 1) Transcription (DNA to mRNA), 2) Translation (mRNA to amino acid chain), 3) Protein folding (amino acid chain to functional protein).',
'ជំហានសំខាន់បីគឺ៖ 1) ការចម្លង (DNA ទៅ mRNA), 2) ការបកប្រែ (mRNA ទៅខ្សែអាស៊ីតអាមីណូ), 3) ការបត់ប្រូតេអ៊ីន (ខ្សែអាស៊ីតអាមីណូទៅប្រូតេអ៊ីនមានមុខងារ)។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 4, 'calculation',
'If a gene has 600 base pairs, how many amino acids will the resulting protein have? (Assume no stop codons within the sequence)',
'ប្រសិនបើហ្សែនមួយមាន 600 គូបាស តើប្រូតេអ៊ីនលទ្ធផលនឹងមានអាស៊ីតអាមីណូប៉ុន្មាន? (សន្មតថាគ្មានកូដុងបញ្ឈប់ក្នុងលំដាប់)',
'Remember that each amino acid is coded by 3 base pairs (a codon).',
'ចងចាំថាអាស៊ីតអាមីណូនីមួយៗត្រូវបានកូដដោយគូបាស 3 (កូដុងមួយ)។',
NULL,
'200',
15, 'medium',
'Divide the total base pairs by 3.',
'ចែកគូបាសសរុបនឹង 3។',
'Each codon consists of 3 base pairs and codes for 1 amino acid. Therefore, 600 base pairs ÷ 3 = 200 amino acids.',
'កូដុងនីមួយៗមានគូបាស 3 និងកូដសម្រាប់អាស៊ីតអាមីណូ 1។ ដូច្នេះ គូបាស 600 ÷ 3 = អាស៊ីតអាមីណូ 200។'),

('1714de17-ab64-40b8-beba-34f3d1e88b04', 1, 5, 'multiple_choice',
'Which type of RNA brings amino acids to the ribosome during translation?',
'តើប្រភេទ RNA មួយណាដែលនាំអាស៊ីតអាមីណូទៅរីបូសូមក្នុងអំឡុងពេលបកប្រែ?',
'Select the correct type of RNA.',
'ជ្រើសរើសប្រភេទ RNA ត្រឹមត្រូវ។',
'{"options": [{"en": "mRNA", "km": "mRNA"}, {"en": "tRNA", "km": "tRNA"}, {"en": "rRNA", "km": "rRNA"}, {"en": "DNA", "km": "DNA"}]}',
'tRNA',
10, 'easy',
'Think about transfer RNA.',
'គិតអំពី RNA ផ្ទេរ។',
'tRNA (transfer RNA) carries specific amino acids to the ribosome during translation, matching its anticodon with the mRNA codon.',
'tRNA (RNA ផ្ទេរ) ដឹកអាស៊ីតអាមីណូជាក់លាក់ទៅរីបូសូមក្នុងអំឡុងពេលបកប្រែ ដោយផ្គូផ្គងអង់ទីកូដុងរបស់វាជាមួយកូដុង mRNA។'),

-- 2. Natural Selection (43cfa204-f71f-4b51-9275-747393fc5bbe)
('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 1, 'multiple_choice',
'What is the main driving force behind natural selection?',
'តើអ្វីជាកម្លាំងជំរុញចម្បងនៅពីក្រោយការជ្រើសរើសធម្មជាតិ?',
'Choose the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "Environmental pressures", "km": "សម្ពាធបរិស្ថាន"}, {"en": "Random mutations", "km": "ការផ្លាស់ប្តូរចៃដន្យ"}, {"en": "Artificial breeding", "km": "ការបង្កាត់សិប្បនិម្មិត"}, {"en": "Genetic engineering", "km": "វិស្វកម្មហ្សែន"}]}',
'Environmental pressures',
10, 'medium',
'Think about what causes organisms to adapt.',
'គិតអំពីអ្វីដែលធ្វើឲ្យសារពាង្គកាយសម្របខ្លួន។',
'Environmental pressures create conditions where certain traits are more advantageous for survival and reproduction, driving natural selection.',
'សម្ពាធបរិស្ថានបង្កើតលក្ខខណ្ឌដែលលក្ខណៈជាក់លាក់មានគុណប្រយោជន៍ជាងសម្រាប់ការរស់រានមានជីវិត និងការបន្តពូជ ដែលជំរុញការជ្រើសរើសធម្មជាតិ។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 2, 'true_false',
'Evolution occurs within an individual organism during its lifetime.',
'ការវិវត្តកើតឡើងក្នុងសារពាង្គកាយនីមួយៗក្នុងអំឡុងជីវិតរបស់វា។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Does evolution happen to individuals or populations?',
'តើការវិវត្តកើតឡើងចំពោះបុគ្គល ឬប្រជាកររូប?',
'Evolution occurs in populations over many generations, not within individual organisms during their lifetime.',
'ការវិវត្តកើតឡើងក្នុងប្រជាកររូបរយៈពេលជំនាន់ជាច្រើន មិនមែនក្នុងសារពាង្គកាយនីមួយៗក្នុងអំឡុងជីវិតរបស់ពួកវាទេ។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 3, 'fill_blank',
'The process by which organisms with favorable traits are more likely to survive and reproduce is called ___________.',
'ដំណើរការដែលសារពាង្គកាយដែលមានលក្ខណៈអំណោយផលទំនងជារស់រានមានជីវិត និងបន្តពូជត្រូវបានគេហៅថា ___________។',
'Fill in the blank with the correct term.',
'បំពេញចន្លោះជាមួយពាក្យត្រឹមត្រូវ។',
NULL,
'natural selection',
10, 'easy',
'This is Darwin''s famous theory.',
'នេះគឺជាទ្រឹស្តីដ៏ល្បីរបស់ដាវីន។',
'Natural selection is the process where organisms better adapted to their environment tend to survive and produce more offspring.',
'ការជ្រើសរើសធម្មជាតិគឺជាដំណើរការដែលសារពាង្គកាយសម្របខ្លួនបានល្អជាងទៅនឹងបរិស្ថានរបស់ពួកវាមានទំនោររស់រានមានជីវិត និងបង្កើតកូនចៅច្រើន។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 4, 'short_answer',
'List three factors that contribute to genetic variation in a population.',
'រាយបញ្ជីកត្តាបីដែលរួមចំណែកដល់ការប្រែប្រួលហ្សែនក្នុងប្រជាកររូប។',
'Provide three distinct factors.',
'ផ្តល់កត្តាផ្សេងគ្នាបី។',
NULL,
'Mutation, Sexual reproduction, Gene flow',
15, 'medium',
'Think about sources of genetic diversity.',
'គិតអំពីប្រភពនៃភាពចម្រុះហ្សែន។',
'Three main factors are: 1) Mutation (random changes in DNA), 2) Sexual reproduction (combining genes from two parents), 3) Gene flow (migration of individuals between populations).',
'កត្តាសំខាន់បីគឺ៖ 1) ការផ្លាស់ប្តូរ (ការផ្លាស់ប្តូរចៃដន្យក្នុង DNA), 2) ការបន្តពូជផ្លូវភេទ (ការរួមបញ្ចូលហ្សែនពីឪពុកម្តាយពីរ), 3) លំហូរហ្សែន (ការធ្វើចំណាកស្រុករបស់បុគ្គលរវាងប្រជាកររូប)។'),

('43cfa204-f71f-4b51-9275-747393fc5bbe', 1, 5, 'multiple_choice',
'In the peppered moth example, what caused the change in moth population color during the Industrial Revolution?',
'ក្នុងឧទាហរណ៍ខែម្រេច តើអ្វីបណ្តាលឲ្យមានការផ្លាស់ប្តូរពណ៌ប្រជាកររូបខែក្នុងអំឡុងបដិវត្តន៍ឧស្សាហកម្ម?',
'Select the primary cause.',
'ជ្រើសរើសមូលហេតុចម្បង។',
'{"options": [{"en": "Pollution darkened tree bark", "km": "ការបំពុលធ្វើឲ្យសំបកឈើងងឹត"}, {"en": "Moths changed color voluntarily", "km": "ខែផ្លាស់ប្តូរពណ៌ដោយស្ម័គ្រចិត្ត"}, {"en": "New species appeared", "km": "ប្រភេទថ្មីបានលេចឡើង"}, {"en": "Chemical mutations", "km": "ការផ្លាស់ប្តូរគីមី"}]}',
'Pollution darkened tree bark',
10, 'medium',
'Think about camouflage and predation.',
'គិតអំពីការក្លែងបន្លំ និងការស៊ីសាច់។',
'Industrial pollution darkened tree bark, making light-colored moths more visible to predators while dark moths were better camouflaged, leading to their increased survival.',
'ការបំពុលឧស្សាហកម្មធ្វើឲ្យសំបកឈើងងឹត ធ្វើឲ្យខែពណ៌ស្រាលងាយមើលឃើញដោយសត្វមំសាសី ខណៈខែងងឹតត្រូវបានក្លែងបន្លំបានល្អជាង នាំឲ្យការរស់រានមានជីវិតរបស់ពួកវាកើនឡើង។'),

-- 3. Neuron (276f57a5-835d-4f8c-8e3c-812cb77dd703)
('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 1, 'multiple_choice',
'What is the main function of dendrites in a neuron?',
'តើអ្វីជាមុខងារចម្បងនៃដង់ដ្រីតក្នុងណឺរ៉ូន?',
'Choose the correct function.',
'ជ្រើសរើសមុខងារត្រឹមត្រូវ។',
'{"options": [{"en": "Transmit signals away from the cell body", "km": "បញ្ជូនសញ្ញាចេញពីតួកោសិកា"}, {"en": "Receive signals from other neurons", "km": "ទទួលសញ្ញាពីណឺរ៉ូនផ្សេងទៀត"}, {"en": "Produce neurotransmitters", "km": "ផលិតសារធាតុបញ្ជូនសរសៃប្រសាទ"}, {"en": "Insulate the axon", "km": "អ៊ីសូឡង់អាក់សុង"}]}',
'Receive signals from other neurons',
10, 'easy',
'Think about the input structures of a neuron.',
'គិតអំពីរចនាសម្ព័ន្ធបញ្ចូលនៃណឺរ៉ូន។',
'Dendrites are branched extensions that receive chemical signals from other neurons and convert them to electrical signals.',
'ដង់ដ្រីតគឺជាផ្នែកពង្រីកមែកធាងដែលទទួលសញ្ញាគីមីពីណឺរ៉ូនផ្សេងទៀត និងបម្លែងពួកវាទៅជាសញ្ញាអគ្គិសនី។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 2, 'true_false',
'Action potentials travel in both directions along an axon.',
'សក្តានុពលសកម្មធ្វើដំណើរក្នុងទិសដៅទាំងពីរតាមបណ្តោយអាក់សុង។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Consider the direction of nerve impulses.',
'ពិចារណាទិសដៅនៃជំរុញសរសៃប្រសាទ។',
'Action potentials travel in only one direction - from the cell body down the axon to the axon terminals.',
'សក្តានុពលសកម្មធ្វើដំណើរក្នុងទិសដៅតែមួយ - ពីតួកោសិកាចុះតាមអាក់សុងទៅចុងអាក់សុង។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 3, 'calculation',
'If a nerve impulse travels at 120 meters per second, how long would it take to travel from your spine to your toe (assume 1 meter distance)?',
'ប្រសិនបើជំរុញសរសៃប្រសាទធ្វើដំណើរក្នុងល្បឿន 120 ម៉ែត្រក្នុងមួយវិនាទី តើវានឹងចំណាយពេលប៉ុន្មានដើម្បីធ្វើដំណើរពីឆ្អឹងខ្នងទៅម្រាមជើង (សន្មតចម្ងាយ 1 ម៉ែត្រ)?',
'Calculate the time in seconds. Round to 3 decimal places.',
'គណនាពេលវេលាជាវិនាទី។ បង្គត់ទៅទសភាគ 3 ខ្ទង់។',
NULL,
'0.008',
15, 'medium',
'Use the formula: time = distance ÷ speed',
'ប្រើរូបមន្ត៖ ពេលវេលា = ចម្ងាយ ÷ ល្បឿន',
'Time = Distance ÷ Speed = 1 meter ÷ 120 meters/second = 0.00833... seconds ≈ 0.008 seconds',
'ពេលវេលា = ចម្ងាយ ÷ ល្បឿន = 1 ម៉ែត្រ ÷ 120 ម៉ែត្រ/វិនាទី = 0.00833... វិនាទី ≈ 0.008 វិនាទី'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 4, 'short_answer',
'Name the gap between two neurons where neurotransmitters are released.',
'បញ្ជាក់ឈ្មោះគម្លាតរវាងណឺរ៉ូនពីរដែលសារធាតុបញ្ជូនសរសៃប្រសាទត្រូវបានបញ្ចេញ។',
'Provide the scientific term.',
'ផ្តល់ពាក្យវិទ្យាសាស្ត្រ។',
NULL,
'synapse',
10, 'easy',
'This is where chemical communication occurs.',
'នេះជាកន្លែងដែលការទំនាក់ទំនងគីមីកើតឡើង។',
'The synapse (or synaptic cleft) is the small gap between neurons where neurotransmitters are released to transmit signals.',
'ស៊ីណាប (ឬច្រកស៊ីណាប) គឺជាគម្លាតតូចរវាងណឺរ៉ូនដែលសារធាតុបញ្ជូនសរសៃប្រសាទត្រូវបានបញ្ចេញដើម្បីបញ្ជូនសញ្ញា។'),

('276f57a5-835d-4f8c-8e3c-812cb77dd703', 1, 5, 'multiple_choice',
'What maintains the resting potential of a neuron?',
'តើអ្វីរក្សាសក្តានុពលសម្រាករបស់ណឺរ៉ូន?',
'Select the primary mechanism.',
'ជ្រើសរើសយន្តការចម្បង។',
'{"options": [{"en": "Sodium-potassium pump", "km": "ស្នប់សូដ្យូម-ប៉ូតាស្យូម"}, {"en": "Calcium channels", "km": "ឆានែលកាល់ស្យូម"}, {"en": "Myelin sheath", "km": "ស្រោមម៊ីយេលីន"}, {"en": "Neurotransmitters", "km": "សារធាតុបញ្ជូនសរសៃប្រសាទ"}]}',
'Sodium-potassium pump',
10, 'medium',
'Think about ion concentrations.',
'គិតអំពីកំហាប់អ៊ីយ៉ុង។',
'The sodium-potassium pump actively transports 3 sodium ions out and 2 potassium ions in, maintaining the negative charge inside the neuron.',
'ស្នប់សូដ្យូម-ប៉ូតាស្យូមដឹកជញ្ជូនអ៊ីយ៉ុងសូដ្យូម 3 ចេញ និងអ៊ីយ៉ុងប៉ូតាស្យូម 2 ចូល រក្សាបន្ទុកអវិជ្ជមានខាងក្នុងណឺរ៉ូន។'),

-- CHEMISTRY SIMULATIONS EXERCISES

-- 4. Acid-Base Solutions (33291077-21da-44d8-b0f2-e575f39082d8)
('33291077-21da-44d8-b0f2-e575f39082d8', 1, 1, 'multiple_choice',
'What is the pH range for acidic solutions?',
'តើជួរ pH សម្រាប់សូលុយស្យុងអាស៊ីតគឺជាអ្វី?',
'Select the correct pH range.',
'ជ្រើសរើសជួរ pH ត្រឹមត្រូវ។',
'{"options": [{"en": "0 to 6.9", "km": "0 ទៅ 6.9"}, {"en": "7.1 to 14", "km": "7.1 ទៅ 14"}, {"en": "Exactly 7", "km": "គ្រាន់តែ 7"}, {"en": "Above 14", "km": "លើស 14"}]}',
'0 to 6.9',
10, 'easy',
'Remember that 7 is neutral.',
'ចងចាំថា 7 គឺអព្យាក្រឹត។',
'Acidic solutions have a pH less than 7 (0-6.9), neutral is exactly 7, and basic solutions have pH greater than 7 (7.1-14).',
'សូលុយស្យុងអាស៊ីតមាន pH តិចជាង 7 (0-6.9) អព្យាក្រឹតគឺ 7 ហើយសូលុយស្យុងបាសមាន pH ធំជាង 7 (7.1-14)។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 2, 'calculation',
'If a solution has [H+] = 1 × 10^-4 M, what is its pH?',
'ប្រសិនបើសូលុយស្យុងមាន [H+] = 1 × 10^-4 M តើ pH របស់វាគឺប៉ុន្មាន?',
'Use the formula pH = -log[H+]',
'ប្រើរូបមន្ត pH = -log[H+]',
NULL,
'4',
15, 'medium',
'The negative log of 10^-4 is 4.',
'ឡូការីតអវិជ្ជមាននៃ 10^-4 គឺ 4។',
'pH = -log[H+] = -log(1 × 10^-4) = -(-4) = 4',
'pH = -log[H+] = -log(1 × 10^-4) = -(-4) = 4'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 3, 'true_false',
'Strong acids completely dissociate in water.',
'អាស៊ីតខ្លាំងរលាយទាំងស្រុងក្នុងទឹក។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Think about what "strong" means for acids.',
'គិតអំពីអ្វីដែល "ខ្លាំង" មានន័យសម្រាប់អាស៊ីត។',
'Strong acids like HCl, HNO3, and H2SO4 completely dissociate into ions in aqueous solution.',
'អាស៊ីតខ្លាំងដូចជា HCl, HNO3, និង H2SO4 រលាយទាំងស្រុងទៅជាអ៊ីយ៉ុងក្នុងសូលុយស្យុងទឹក។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 4, 'fill_blank',
'The pH scale ranges from _____ to _____.',
'មាត្រដ្ឋាន pH មានចាប់ពី _____ ទៅ _____។',
'Fill in both blanks with numbers.',
'បំពេញចន្លោះទាំងពីរជាមួយលេខ។',
NULL,
'0, 14',
10, 'easy',
'Standard pH scale limits.',
'ដែនកំណត់មាត្រដ្ឋាន pH ស្តង់ដារ។',
'The pH scale typically ranges from 0 (most acidic) to 14 (most basic), with 7 being neutral.',
'មាត្រដ្ឋាន pH ជាទូទៅមានចាប់ពី 0 (អាស៊ីតបំផុត) ទៅ 14 (បាសបំផុត) ដោយ 7 ជាអព្យាក្រឹត។'),

('33291077-21da-44d8-b0f2-e575f39082d8', 1, 5, 'short_answer',
'Name three common household acids.',
'បញ្ជាក់ឈ្មោះអាស៊ីតក្នុងផ្ទះទូទៅបី។',
'List three examples of acidic substances found at home.',
'រាយបញ្ជីឧទាហរណ៍បីនៃសារធាតុអាស៊ីតដែលរកឃើញនៅផ្ទះ។',
NULL,
'Vinegar, Lemon juice, Orange juice',
15, 'easy',
'Think about sour-tasting liquids.',
'គិតអំពីវត្ថុរាវដែលមានរសជាតិជូរ។',
'Common household acids include vinegar (acetic acid), citrus juices (citric acid), and soft drinks (carbonic/phosphoric acid).',
'អាស៊ីតក្នុងផ្ទះទូទៅរួមមានទឹកខ្មេះ (អាស៊ីតអាសេទិច) ទឹកផ្លែឈើក្រូច (អាស៊ីតស៊ីត្រិច) និងភេសជ្ជៈ (អាស៊ីតកាបូនិច/ផូស្វ័រិច)។'),

-- 5. Atomic Interactions (18f3a22e-3059-44df-add5-ac621da8a13c)
('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 1, 'multiple_choice',
'Which type of force is responsible for holding atoms together in a molecule?',
'តើប្រភេទកម្លាំងមួយណាទទួលខុសត្រូវក្នុងការភ្ជាប់អាតូមជាមួយគ្នាក្នុងម៉ូលេគុល?',
'Choose the primary force.',
'ជ្រើសរើសកម្លាំងចម្បង។',
'{"options": [{"en": "Gravitational force", "km": "កម្លាំងទំនាញ"}, {"en": "Electromagnetic force", "km": "កម្លាំងអេឡិចត្រូម៉ាញេទិច"}, {"en": "Nuclear force", "km": "កម្លាំងនុយក្លេអ៊ែរ"}, {"en": "Friction force", "km": "កម្លាំងកកិត"}]}',
'Electromagnetic force',
10, 'medium',
'Think about electron interactions.',
'គិតអំពីអន្តរកម្មអេឡិចត្រុង។',
'Electromagnetic forces between electrons and nuclei are responsible for chemical bonding and holding atoms together in molecules.',
'កម្លាំងអេឡិចត្រូម៉ាញេទិចរវាងអេឡិចត្រុង និងស្នូលទទួលខុសត្រូវចំពោះចំណងគីមី និងការភ្ជាប់អាតូមជាមួយគ្នាក្នុងម៉ូលេគុល។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 2, 'true_false',
'Van der Waals forces are stronger than covalent bonds.',
'កម្លាំងវ៉ាន់ដឺវ៉ាល់ខ្លាំងជាងចំណងកូវ៉ាឡង់។',
'Is this true or false?',
'តើនេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Compare intermolecular vs intramolecular forces.',
'ប្រៀបធៀបកម្លាំងអន្តរម៉ូលេគុល និងក្នុងម៉ូលេគុល។',
'Van der Waals forces are weak intermolecular forces, much weaker than covalent bonds which are strong intramolecular forces.',
'កម្លាំងវ៉ាន់ដឺវ៉ាល់គឺជាកម្លាំងអន្តរម៉ូលេគុលខ្សោយ ខ្សោយជាងចំណងកូវ៉ាឡង់ដែលជាកម្លាំងក្នុងម៉ូលេគុលខ្លាំង។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 3, 'short_answer',
'What happens to potential energy as two atoms approach each other from far apart?',
'តើអ្វីកើតឡើងចំពោះថាមពលប៉ូតង់ស្យែលនៅពេលអាតូមពីរខិតជិតគ្នាពីចម្ងាយឆ្ងាយ?',
'Describe the general trend.',
'ពិពណ៌នានិន្នាការទូទៅ។',
NULL,
'It decreases then increases',
15, 'hard',
'Think about attractive and repulsive forces.',
'គិតអំពីកម្លាំងទាក់ទាញ និងច្រានចោល។',
'Potential energy initially decreases due to attraction, reaches a minimum at optimal distance, then increases sharply due to repulsion at very close distances.',
'ថាមពលប៉ូតង់ស្យែលដំបូងថយចុះដោយសារការទាក់ទាញ ឈានដល់អប្បបរមានៅចម្ងាយល្អបំផុត បន្ទាប់មកកើនឡើងយ៉ាងខ្លាំងដោយសារការច្រានចោលនៅចម្ងាយជិតខ្លាំង។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 4, 'multiple_choice',
'At what point is a chemical bond considered formed between two atoms?',
'តើនៅចំណុចណាដែលចំណងគីមីត្រូវបានចាត់ទុកថាបានបង្កើតរវាងអាតូមពីរ?',
'Select the best answer.',
'ជ្រើសរើសចម្លើយល្អបំផុត។',
'{"options": [{"en": "When they first touch", "km": "នៅពេលពួកវាប៉ះគ្នាដំបូង"}, {"en": "At minimum potential energy", "km": "នៅថាមពលប៉ូតង់ស្យែលអប្បបរមា"}, {"en": "At maximum kinetic energy", "km": "នៅថាមពលស៊ីនេទិចអតិបរមា"}, {"en": "When they are infinitely far apart", "km": "នៅពេលពួកវានៅឆ្ងាយគ្នាគ្មានដែនកំណត់"}]}',
'At minimum potential energy',
10, 'medium',
'Think about energy stability.',
'គិតអំពីស្ថិរភាពថាមពល។',
'A chemical bond forms when atoms reach the distance where potential energy is minimized, representing the most stable configuration.',
'ចំណងគីមីបង្កើតនៅពេលអាតូមឈានដល់ចម្ងាយដែលថាមពលប៉ូតង់ស្យែលត្រូវបានបន្ថយអប្បបរមា តំណាងឲ្យការកំណត់រចនាសម្ព័ន្ធស្ថិរភាពបំផុត។'),

('18f3a22e-3059-44df-add5-ac621da8a13c', 1, 5, 'calculation',
'If the bond energy of H2 is 436 kJ/mol, how much energy is needed to break 2 moles of H2 molecules?',
'ប្រសិនបើថាមពលចំណងនៃ H2 គឺ 436 kJ/mol តើត្រូវការថាមពលប៉ុន្មានដើម្បីបំបែកម៉ូលេគុល H2 ចំនួន 2 ម៉ូល?',
'Calculate the total energy required.',
'គណនាថាមពលសរុបដែលត្រូវការ។',
NULL,
'872 kJ',
15, 'easy',
'Multiply bond energy by number of moles.',
'គុណថាមពលចំណងនឹងចំនួនម៉ូល។',
'Energy required = Bond energy × Number of moles = 436 kJ/mol × 2 mol = 872 kJ',
'ថាមពលដែលត្រូវការ = ថាមពលចំណង × ចំនួនម៉ូល = 436 kJ/mol × 2 mol = 872 kJ');