-- Stage 2: Exercises for next 15 simulations (Chemistry and Mathematics)
-- Each simulation gets 5-8 exercises with different types

-- CHEMISTRY SIMULATIONS EXERCISES (continued)

-- 11. Concentration (b75fc5d8-caf2-4684-b516-fa5a52267f6b)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 1, 'multiple_choice',
'What is the unit of molarity?',
'តើឯកតានៃម៉ូលារីតេគឺអ្វី?',
'Select the correct unit.',
'ជ្រើសរើសឯកតាត្រឹមត្រូវ។',
'{"options": [{"en": "g/L", "km": "g/L"}, {"en": "mol/L", "km": "mol/L"}, {"en": "g/mol", "km": "g/mol"}, {"en": "L/mol", "km": "L/mol"}]}',
'mol/L',
10, 'easy',
'Molarity measures moles per liter.',
'ម៉ូលារីតេវាស់ម៉ូលក្នុងមួយលីត្រ។',
'Molarity (M) is defined as moles of solute per liter of solution, expressed as mol/L or M.',
'ម៉ូលារីតេ (M) ត្រូវបានកំណត់ជាម៉ូលនៃសារធាតុរលាយក្នុងមួយលីត្រនៃសូលុយស្យុង បង្ហាញជា mol/L ឬ M។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 2, 'calculation',
'If you dissolve 58.5 g of NaCl (molar mass = 58.5 g/mol) in water to make 500 mL of solution, what is the molarity?',
'ប្រសិនបើអ្នករលាយ NaCl 58.5 g (ម៉ាស់ម៉ូល = 58.5 g/mol) ក្នុងទឹកដើម្បីបង្កើតសូលុយស្យុង 500 mL តើម៉ូលារីតេគឺប៉ុន្មាន?',
'Calculate M = moles/volume(L)',
'គណនា M = ម៉ូល/មាឌ(L)',
NULL,
'2.0 M',
15, 'medium',
'First find moles, then divide by volume in liters.',
'ដំបូងរកម៉ូល បន្ទាប់មកចែកនឹងមាឌជាលីត្រ។',
'Moles = 58.5 g ÷ 58.5 g/mol = 1.0 mol. Volume = 500 mL = 0.5 L. M = 1.0 mol ÷ 0.5 L = 2.0 M',
'ម៉ូល = 58.5 g ÷ 58.5 g/mol = 1.0 mol។ មាឌ = 500 mL = 0.5 L។ M = 1.0 mol ÷ 0.5 L = 2.0 M'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 3, 'true_false',
'Adding more solvent to a solution increases its concentration.',
'ការបន្ថែមសារធាតុរំលាយច្រើនទៅសូលុយស្យុងបង្កើនកំហាប់របស់វា។',
'Is this statement true or false?',
'តើសេចក្តីថ្លែងការណ៍នេះពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Think about dilution.',
'គិតអំពីការរលាយ។',
'Adding more solvent dilutes the solution, decreasing its concentration (C = n/V, increasing V decreases C).',
'ការបន្ថែមសារធាតុរំលាយច្រើនរលាយសូលុយស្យុង បន្ថយកំហាប់របស់វា (C = n/V ការបង្កើន V បន្ថយ C)។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 4, 'short_answer',
'Name three ways to increase the concentration of a solution.',
'បញ្ជាក់វិធីបីដើម្បីបង្កើនកំហាប់នៃសូលុយស្យុង។',
'List three different methods.',
'រាយបញ្ជីវិធីសាស្ត្រផ្សេងគ្នាបី។',
NULL,
'Add more solute, Evaporate solvent, Remove solvent',
15, 'medium',
'Think about changing amount of solute or solvent.',
'គិតអំពីការផ្លាស់ប្តូរបរិមាណសារធាតុរលាយ ឬសារធាតុរំលាយ។',
'You can: 1) Add more solute, 2) Evaporate/remove some solvent, 3) Add a concentrated solution of the same solute.',
'អ្នកអាច៖ 1) បន្ថែមសារធាតុរលាយច្រើន 2) រំហួត/ដកសារធាតុរំលាយខ្លះ 3) បន្ថែមសូលុយស្យុងកំហាប់នៃសារធាតុរលាយដូចគ្នា។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 5, 'fill_blank',
'The process of adding solvent to decrease concentration is called _____.',
'ដំណើរការបន្ថែមសារធាតុរំលាយដើម្បីបន្ថយកំហាប់ត្រូវបានគេហៅថា _____។',
'Fill in the term.',
'បំពេញពាក្យ។',
NULL,
'dilution',
10, 'easy',
'Making something less concentrated.',
'ធ្វើឲ្យអ្វីមួយមានកំហាប់តិច។',
'Dilution is the process of decreasing concentration by adding more solvent to a solution.',
'ការរលាយគឺជាដំណើរការនៃការបន្ថយកំហាប់ដោយបន្ថែមសារធាតុរំលាយច្រើនទៅសូលុយស្យុង។'),

('b75fc5d8-caf2-4684-b516-fa5a52267f6b', 1, 6, 'multiple_choice',
'Which factor does NOT affect the concentration of a solution?',
'តើកត្តាមួយណាមិនប៉ះពាល់ដល់កំហាប់នៃសូលុយស្យុង?',
'Choose the factor that has no effect.',
'ជ្រើសរើសកត្តាដែលគ្មានឥទ្ធិពល។',
'{"options": [{"en": "Amount of solute", "km": "បរិមាណសារធាតុរលាយ"}, {"en": "Volume of solution", "km": "មាឌសូលុយស្យុង"}, {"en": "Temperature of preparation", "km": "សីតុណ្ហភាពនៃការរៀបចំ"}, {"en": "Color of container", "km": "ពណ៌ធុង"}]}',
'Color of container',
10, 'easy',
'Which is just external?',
'មួយណាគ្រាន់តែខាងក្រៅ?',
'The color of the container has no effect on the actual concentration of the solution inside.',
'ពណ៌ធុងគ្មានឥទ្ធិពលលើកំហាប់ពិតប្រាកដនៃសូលុយស្យុងខាងក្នុងទេ។'),

-- 12. Diffusion (56c6cff8-17d8-4ff3-bcbc-8048fbab868e)
('56c6cff8-17d8-4ff3-bcbc-8048fbab868e', 1, 1, 'multiple_choice',
'What is the driving force behind diffusion?',
'តើអ្វីជាកម្លាំងជំរុញនៅពីក្រោយការសាយភាយ?',
'Select the primary cause.',
'ជ្រើសរើសមូលហេតុចម្បង។',
'{"options": [{"en": "Gravity", "km": "ទំនាញ"}, {"en": "Random molecular motion", "km": "ចលនាម៉ូលេគុលចៃដន្យ"}, {"en": "Magnetic force", "km": "កម្លាំងម៉ាញេទិច"}, {"en": "Electric current", "km": "ចរន្តអគ្គិសនី"}]}',
'Random molecular motion',
10, 'easy',
'Think about kinetic theory.',
'គិតអំពីទ្រឹស្តីស៊ីនេទិច។',
'Diffusion is driven by the random thermal motion of molecules, causing them to spread from high to low concentration.',
'ការសាយភាយត្រូវបានជំរុញដោយចលនាកំដៅចៃដន្យនៃម៉ូលេគុល ធ្វើឲ្យពួកវារីករាលពីកំហាប់ខ្ពស់ទៅកំហាប់ទាប។'),

('56c6cff8-17d8-4ff3-bcbc-8048fbab868e', 1, 2, 'true_false',
'Diffusion occurs faster at higher temperatures.',
'ការសាយភាយកើតឡើងលឿនជាងនៅសីតុណ្ហភាពខ្ពស់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Consider molecular kinetic energy.',
'ពិចារណាថាមពលស៊ីនេទិចម៉ូលេគុល។',
'Higher temperature means greater molecular kinetic energy and faster random motion, increasing diffusion rate.',
'សីតុណ្ហភាពខ្ពស់មានន័យថាថាមពលស៊ីនេទិចម៉ូលេគុលធំជាង និងចលនាចៃដន្យលឿនជាង បង្កើនអត្រាការសាយភាយ។'),

('56c6cff8-17d8-4ff3-bcbc-8048fbab868e', 1, 3, 'short_answer',
'List three factors that affect the rate of diffusion.',
'រាយបញ្ជីកត្តាបីដែលប៉ះពាល់ដល់អត្រាការសាយភាយ។',
'Provide three distinct factors.',
'ផ្តល់កត្តាផ្សេងគ្នាបី។',
NULL,
'Temperature, Concentration gradient, Molecular size',
15, 'medium',
'Think about what speeds up or slows down molecular movement.',
'គិតអំពីអ្វីដែលបង្កើនល្បឿន ឬបន្ថយចលនាម៉ូលេគុល។',
'Key factors: 1) Temperature (higher = faster), 2) Concentration gradient (steeper = faster), 3) Molecular size (smaller = faster), 4) Medium viscosity.',
'កត្តាសំខាន់៖ 1) សីតុណ្ហភាព (ខ្ពស់ = លឿន) 2) ជម្រាលកំហាប់ (ចោត = លឿន) 3) ទំហំម៉ូលេគុល (តូច = លឿន) 4) ភាពស្អិតមជ្ឈដ្ឋាន។'),

('56c6cff8-17d8-4ff3-bcbc-8048fbab868e', 1, 4, 'fill_blank',
'Diffusion continues until _____ is reached.',
'ការសាយភាយបន្តរហូតដល់ _____ ត្រូវបានឈានដល់។',
'Complete with the correct term.',
'បំពេញជាមួយពាក្យត្រឹមត្រូវ។',
NULL,
'equilibrium',
10, 'medium',
'When concentrations become equal.',
'នៅពេលកំហាប់ក្លាយជាស្មើគ្នា។',
'Diffusion continues until equilibrium is reached, where concentrations are equal throughout the system.',
'ការសាយភាយបន្តរហូតដល់លំនឹងត្រូវបានឈានដល់ ដែលកំហាប់ស្មើគ្នាពេញប្រព័ន្ធ។'),

('56c6cff8-17d8-4ff3-bcbc-8048fbab868e', 1, 5, 'multiple_choice',
'Which gas would diffuse fastest at the same temperature?',
'តើឧស្ម័នមួយណានឹងសាយភាយលឿនបំផុតនៅសីតុណ្ហភាពដូចគ្នា?',
'Consider molecular mass.',
'ពិចារណាម៉ាស់ម៉ូលេគុល។',
'{"options": [{"en": "H2 (2 g/mol)", "km": "H2 (2 g/mol)"}, {"en": "O2 (32 g/mol)", "km": "O2 (32 g/mol)"}, {"en": "CO2 (44 g/mol)", "km": "CO2 (44 g/mol)"}, {"en": "Cl2 (71 g/mol)", "km": "Cl2 (71 g/mol)"}]}',
'H2 (2 g/mol)',
10, 'medium',
'Lighter molecules move faster.',
'ម៉ូលេគុលស្រាលផ្លាស់ទីលឿនជាង។',
'According to Graham''s law, lighter molecules diffuse faster. H2 has the lowest molecular mass, so it diffuses fastest.',
'យោងតាមច្បាប់ហ្គ្រាហាម ម៉ូលេគុលស្រាលជាងសាយភាយលឿនជាង។ H2 មានម៉ាស់ម៉ូលេគុលទាបបំផុត ដូច្នេះវាសាយភាយលឿនបំផុត។'),

-- 13. Gases Intro (8b8a7835-0bf5-4c73-8158-16c4a699e60f)
('8b8a7835-0bf5-4c73-8158-16c4a699e60f', 1, 1, 'multiple_choice',
'According to the kinetic theory, gas particles are in constant...',
'យោងតាមទ្រឹស្តីស៊ីនេទិច ភាគល្អិតឧស្ម័ននៅក្នុង... ថេរ',
'Complete the statement.',
'បំពេញសេចក្តីថ្លែងការណ៍។',
'{"options": [{"en": "Rest", "km": "ការសម្រាក"}, {"en": "Random motion", "km": "ចលនាចៃដន្យ"}, {"en": "Circular motion", "km": "ចលនារង្វង់"}, {"en": "Vibration only", "km": "រំញ័រតែប៉ុណ្ណោះ"}]}',
'Random motion',
10, 'easy',
'Think about gas behavior.',
'គិតអំពីឥរិយាបថឧស្ម័ន។',
'Gas particles are in constant, rapid, random motion in all directions, colliding with each other and container walls.',
'ភាគល្អិតឧស្ម័ននៅក្នុងចលនាថេរ រហ័ស ចៃដន្យក្នុងទិសដៅទាំងអស់ ប៉ះទង្គិចគ្នា និងជញ្ជាំងធុង។'),

('8b8a7835-0bf5-4c73-8158-16c4a699e60f', 1, 2, 'true_false',
'The volume of individual gas particles is negligible compared to the container volume.',
'មាឌនៃភាគល្អិតឧស្ម័ននីមួយៗអាចមើលរំលងបានបើប្រៀបធៀបនឹងមាឌធុង។',
'According to ideal gas assumptions.',
'យោងតាមការសន្មតឧស្ម័នឧត្តមគតិ។',
NULL,
'true',
10, 'easy',
'This is an ideal gas assumption.',
'នេះគឺជាការសន្មតឧស្ម័នឧត្តមគតិ។',
'In the ideal gas model, particles are considered point masses with negligible volume compared to the container.',
'ក្នុងគំរូឧស្ម័នឧត្តមគតិ ភាគល្អិតត្រូវបានចាត់ទុកជាម៉ាស់ចំណុចដែលមានមាឌអាចមើលរំលងបានបើប្រៀបធៀបនឹងធុង។'),

('8b8a7835-0bf5-4c73-8158-16c4a699e60f', 1, 3, 'calculation',
'If the temperature of a gas doubles (in Kelvin), what happens to the average kinetic energy?',
'ប្រសិនបើសីតុណ្ហភាពនៃឧស្ម័នកើនទ្វេដង (ជាខែលវីន) តើអ្វីកើតឡើងចំពោះថាមពលស៊ីនេទិចមធ្យម?',
'Express as a multiple.',
'បង្ហាញជាពហុគុណ។',
NULL,
'doubles',
10, 'medium',
'KE is proportional to temperature.',
'KE មានសមាមាត្រទៅនឹងសីតុណ្ហភាព។',
'Average kinetic energy is directly proportional to absolute temperature: KE ∝ T. If T doubles, KE doubles.',
'ថាមពលស៊ីនេទិចមធ្យមមានសមាមាត្រដោយផ្ទាល់ទៅនឹងសីតុណ្ហភាពដាច់ខាត៖ KE ∝ T។ ប្រសិនបើ T កើនទ្វេដង KE កើនទ្វេដង។'),

('8b8a7835-0bf5-4c73-8158-16c4a699e60f', 1, 4, 'short_answer',
'What causes gas pressure in a container?',
'តើអ្វីបណ្តាលឲ្យមានសម្ពាធឧស្ម័នក្នុងធុង?',
'Explain the molecular cause.',
'ពន្យល់មូលហេតុម៉ូលេគុល។',
NULL,
'Collisions with walls',
10, 'medium',
'Think about particle impacts.',
'គិតអំពីការប៉ះទង្គិចភាគល្អិត។',
'Gas pressure results from countless collisions of gas particles with the container walls, each collision exerting a tiny force.',
'សម្ពាធឧស្ម័នបណ្តាលមកពីការប៉ះទង្គិចរាប់មិនអស់នៃភាគល្អិតឧស្ម័នជាមួយជញ្ជាំងធុង ការប៉ះទង្គិចនីមួយៗបញ្ចេញកម្លាំងតូច។'),

('8b8a7835-0bf5-4c73-8158-16c4a699e60f', 1, 5, 'multiple_choice',
'Which gas law relates pressure and volume at constant temperature?',
'តើច្បាប់ឧស្ម័នមួយណាទាក់ទងសម្ពាធ និងមាឌនៅសីតុណ្ហភាពថេរ?',
'Name the specific law.',
'បញ្ជាក់ឈ្មោះច្បាប់ជាក់លាក់។',
'{"options": [{"en": "Boyle''s Law", "km": "ច្បាប់បូយល៍"}, {"en": "Charles''s Law", "km": "ច្បាប់ឆាល"}, {"en": "Gay-Lussac''s Law", "km": "ច្បាប់ហ្គេ-លូសាក់"}, {"en": "Avogadro''s Law", "km": "ច្បាប់អាវ៉ូហ្គាដ្រូ"}]}',
'Boyle''s Law',
10, 'easy',
'P and V are inversely related.',
'P និង V មានទំនាក់ទំនងច្រាស។',
'Boyle''s Law states that at constant temperature, pressure and volume are inversely proportional: P₁V₁ = P₂V₂',
'ច្បាប់បូយល៍ចែងថានៅសីតុណ្ហភាពថេរ សម្ពាធ និងមាឌមានសមាមាត្រច្រាស៖ P₁V₁ = P₂V₂'),

-- 14. Isotopes and Atomic Mass (08478245-4a10-4e09-8701-f6312d8c008d)
('08478245-4a10-4e09-8701-f6312d8c008d', 1, 1, 'multiple_choice',
'What defines different isotopes of the same element?',
'តើអ្វីកំណត់អ៊ីសូតូបផ្សេងគ្នានៃធាតុដូចគ្នា?',
'Choose the distinguishing feature.',
'ជ្រើសរើសលក្ខណៈពិសេសប្លែក។',
'{"options": [{"en": "Different number of protons", "km": "ចំនួនប្រូតុងខុសគ្នា"}, {"en": "Different number of neutrons", "km": "ចំនួននឺត្រុងខុសគ្នា"}, {"en": "Different number of electrons", "km": "ចំនួនអេឡិចត្រុងខុសគ្នា"}, {"en": "Different atomic numbers", "km": "លេខអាតូមខុសគ្នា"}]}',
'Different number of neutrons',
10, 'easy',
'Same element means same protons.',
'ធាតុដូចគ្នាមានន័យថាប្រូតុងដូចគ្នា។',
'Isotopes are atoms of the same element (same protons) with different numbers of neutrons, giving different mass numbers.',
'អ៊ីសូតូបគឺជាអាតូមនៃធាតុដូចគ្នា (ប្រូតុងដូចគ្នា) ដែលមានចំនួននឺត្រុងខុសគ្នា ផ្តល់លេខម៉ាស់ខុសគ្នា។'),

('08478245-4a10-4e09-8701-f6312d8c008d', 1, 2, 'calculation',
'Carbon-12 has an abundance of 98.9% and Carbon-13 has 1.1%. Calculate the average atomic mass.',
'កាបូន-12 មានភាពស៊ុីស៊ីវ 98.9% និងកាបូន-13 មាន 1.1%។ គណនាម៉ាស់អាតូមមធ្យម។',
'Use weighted average formula.',
'ប្រើរូបមន្តមធ្យមថ្លឹង។',
NULL,
'12.011',
15, 'medium',
'Multiply each mass by its abundance.',
'គុណម៉ាស់នីមួយៗនឹងភាពស៊ុីស៊ីវរបស់វា។',
'Average = (12 × 0.989) + (13 × 0.011) = 11.868 + 0.143 = 12.011 amu',
'មធ្យម = (12 × 0.989) + (13 × 0.011) = 11.868 + 0.143 = 12.011 amu'),

('08478245-4a10-4e09-8701-f6312d8c008d', 1, 3, 'true_false',
'All isotopes of an element are radioactive.',
'អ៊ីសូតូបទាំងអស់នៃធាតុមួយមានវិទ្យុសកម្ម។',
'Is this always true?',
'តើនេះតែងតែពិតទេ?',
NULL,
'false',
10, 'easy',
'Many isotopes are stable.',
'អ៊ីសូតូបជាច្រើនមានស្ថិរភាព។',
'Many isotopes are stable and non-radioactive. Only certain isotopes with unstable nuclear configurations are radioactive.',
'អ៊ីសូតូបជាច្រើនមានស្ថិរភាព និងគ្មានវិទ្យុសកម្ម។ មានតែអ៊ីសូតូបជាក់លាក់ដែលមានការកំណត់រចនាសម្ព័ន្ធនុយក្លេអ៊ែរអស្ថិរភាពទេដែលមានវិទ្យុសកម្ម។'),

('08478245-4a10-4e09-8701-f6312d8c008d', 1, 4, 'short_answer',
'Write the notation for carbon-14 isotope.',
'សរសេរសញ្ញាសម្រាប់អ៊ីសូតូបកាបូន-14។',
'Use standard isotope notation.',
'ប្រើសញ្ញាអ៊ីសូតូបស្តង់ដារ។',
NULL,
'C-14 or ¹⁴C',
10, 'medium',
'Mass number goes with element symbol.',
'លេខម៉ាស់ទៅជាមួយនិមិត្តសញ្ញាធាតុ។',
'Carbon-14 can be written as C-14 or ¹⁴C, where 14 is the mass number (6 protons + 8 neutrons).',
'កាបូន-14 អាចសរសេរជា C-14 ឬ ¹⁴C ដែល 14 គឺជាលេខម៉ាស់ (ប្រូតុង 6 + នឺត្រុង 8)។'),

('08478245-4a10-4e09-8701-f6312d8c008d', 1, 5, 'fill_blank',
'The weighted average of all isotope masses of an element is called the _____ atomic mass.',
'មធ្យមថ្លឹងនៃម៉ាស់អ៊ីសូតូបទាំងអស់នៃធាតុត្រូវបានគេហៅថាម៉ាស់អាតូម _____។',
'Fill in the descriptor.',
'បំពេញពាក្យពិពណ៌នា។',
NULL,
'average',
10, 'easy',
'It''s an average value.',
'វាជាតម្លៃមធ្យម។',
'The average atomic mass is the weighted average of all naturally occurring isotopes of an element.',
'ម៉ាស់អាតូមមធ្យមគឺជាមធ្យមថ្លឹងនៃអ៊ីសូតូបដែលកើតឡើងដោយធម្មជាតិទាំងអស់នៃធាតុ។'),

-- 15. Molarity (9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5)
('9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5', 1, 1, 'calculation',
'How many moles of NaCl are in 250 mL of a 0.5 M solution?',
'តើមាន NaCl ប៉ុន្មានម៉ូលក្នុងសូលុយស្យុង 0.5 M ចំនួន 250 mL?',
'Use M = n/V, solve for n.',
'ប្រើ M = n/V ដោះស្រាយសម្រាប់ n។',
NULL,
'0.125 mol',
15, 'medium',
'Convert mL to L first.',
'បម្លែង mL ទៅ L ជាមុនសិន។',
'n = M × V = 0.5 mol/L × 0.250 L = 0.125 mol',
'n = M × V = 0.5 mol/L × 0.250 L = 0.125 mol'),

('9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5', 1, 2, 'multiple_choice',
'What happens to molarity when you dilute a solution?',
'តើអ្វីកើតឡើងចំពោះម៉ូលារីតេនៅពេលអ្នករលាយសូលុយស្យុង?',
'Consider the dilution effect.',
'ពិចារណាឥទ្ធិពលការរលាយ។',
'{"options": [{"en": "Increases", "km": "កើនឡើង"}, {"en": "Decreases", "km": "ថយចុះ"}, {"en": "Stays the same", "km": "នៅដដែល"}, {"en": "Doubles", "km": "កើនទ្វេដង"}]}',
'Decreases',
10, 'easy',
'Adding solvent increases volume.',
'ការបន្ថែមសារធាតុរំលាយបង្កើនមាឌ។',
'Dilution adds solvent, increasing volume while moles of solute stay constant, so molarity (M = n/V) decreases.',
'ការរលាយបន្ថែមសារធាតុរំលាយ បង្កើនមាឌខណៈម៉ូលនៃសារធាតុរលាយនៅថេរ ដូច្នេះម៉ូលារីតេ (M = n/V) ថយចុះ។'),

('9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5', 1, 3, 'short_answer',
'What is the dilution equation?',
'តើសមីការរលាយគឺជាអ្វី?',
'Write the formula relating initial and final concentrations.',
'សរសេររូបមន្តទាក់ទងកំហាប់ដំបូង និងចុងក្រោយ។',
NULL,
'M1V1 = M2V2',
10, 'medium',
'Moles before = moles after.',
'ម៉ូលមុន = ម៉ូលក្រោយ។',
'M₁V₁ = M₂V₂ because the number of moles of solute remains constant during dilution.',
'M₁V₁ = M₂V₂ ពីព្រោះចំនួនម៉ូលនៃសារធាតុរលាយនៅថេរក្នុងអំឡុងការរលាយ។'),

('9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5', 1, 4, 'true_false',
'A 1 M solution always contains 1 mole of solute.',
'សូលុយស្យុង 1 M តែងតែមានសារធាតុរលាយ 1 ម៉ូល។',
'Think carefully about the definition.',
'គិតដោយប្រុងប្រយ័ត្នអំពីនិយមន័យ។',
NULL,
'false',
10, 'medium',
'Consider the volume.',
'ពិចារណាមាឌ។',
'A 1 M solution contains 1 mole per LITER. The total moles depend on the volume of solution you have.',
'សូលុយស្យុង 1 M មាន 1 ម៉ូលក្នុងមួយលីត្រ។ ម៉ូលសរុបអាស្រ័យលើមាឌសូលុយស្យុងដែលអ្នកមាន។'),

('9e7b2f7a-41b4-4002-8e7f-4d4abfe651f5', 1, 5, 'fill_blank',
'To prepare a solution of exact molarity, you would use a _____ flask.',
'ដើម្បីរៀបចំសូលុយស្យុងនៃម៉ូលារីតេជាក់លាក់ អ្នកនឹងប្រើដប _____។',
'Name the laboratory glassware.',
'បញ្ជាក់ឈ្មោះឧបករណ៍កែវមន្ទីរពិសោធន៍។',
NULL,
'volumetric',
10, 'easy',
'It has a precise volume mark.',
'វាមានសញ្ញាមាឌច្បាស់លាស់។',
'A volumetric flask has a precise volume marking, allowing accurate preparation of solutions with specific molarity.',
'ដបវ៉ូលុយម៉េត្រិចមានសញ្ញាមាឌច្បាស់លាស់ អនុញ្ញាតការរៀបចំសូលុយស្យុងដោយត្រឹមត្រូវជាមួយម៉ូលារីតេជាក់លាក់។');