-- Stage 2: Complete exercises for simulations 11-17
-- This completes exercises for Stage 2 (continuing from Stage 1 which had simulations 1-10)

-- 11. pH Scale (ac77db6e-031d-438d-a5a3-f9327f32aa3a)
INSERT INTO simulation_exercises (simulation_id, teacher_id, question_number, question_type, question_en, question_km, instructions_en, instructions_km, options, correct_answer, points, difficulty_level, hints_en, hints_km, explanation_en, explanation_km) VALUES

('ac77db6e-031d-438d-a5a3-f9327f32aa3a', 1, 1, 'multiple_choice',
'What is the pH range of acidic solutions?',
'តើជួរ pH នៃសូលុយស្យុងអាស៊ីតគឺប៉ុន្មាន?',
'Choose the correct range.',
'ជ្រើសរើសជួរត្រឹមត្រូវ។',
'{"options": [{"en": "0-7", "km": "0-7"}, {"en": "7-14", "km": "7-14"}, {"en": "0-14", "km": "0-14"}, {"en": "7 only", "km": "តែ 7 ប៉ុណ្ណោះ"}]}',
'0-7',
10, 'easy',
'pH 7 is neutral.',
'pH 7 គឺអព្យាក្រឹត។',
'Acidic solutions have pH values less than 7 (0-7), neutral is 7, and basic solutions have pH greater than 7 (7-14).',
'សូលុយស្យុងអាស៊ីតមានតម្លៃ pH តិចជាង 7 (0-7) អព្យាក្រឹតគឺ 7 និងសូលុយស្យុងមូលដ្ឋានមាន pH ធំជាង 7 (7-14)។'),

('ac77db6e-031d-438d-a5a3-f9327f32aa3a', 1, 2, 'calculation',
'What is the pH of a solution with [H+] = 1 × 10^-3 M?',
'តើ pH នៃសូលុយស្យុងដែលមាន [H+] = 1 × 10^-3 M គឺប៉ុន្មាន?',
'Calculate using pH = -log[H+]',
'គណនាដោយប្រើ pH = -log[H+]',
NULL,
'3',
15, 'medium',
'pH = -log of hydrogen ion concentration',
'pH = -log នៃកំហាប់អ៊ីយ៉ុងអ៊ីដ្រូសែន',
'pH = -log[H+] = -log(1 × 10^-3) = -(-3) = 3',
'pH = -log[H+] = -log(1 × 10^-3) = -(-3) = 3'),

('ac77db6e-031d-438d-a5a3-f9327f32aa3a', 1, 3, 'true_false',
'Pure water has a pH of exactly 7 at all temperatures.',
'ទឹកសុទ្ធមាន pH ពិតប្រាកដ 7 នៅគ្រប់សីតុណ្ហភាព។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'Temperature affects water ionization.',
'សីតុណ្ហភាពប៉ះពាល់ដល់អ៊ីយ៉ូនីភាវូបនីយកម្មទឹក។',
'The pH of pure water is 7 only at 25°C. At higher temperatures, water ionizes more and pH decreases slightly.',
'pH នៃទឹកសុទ្ធគឺ 7 តែនៅ 25°C ប៉ុណ្ណោះ។ នៅសីតុណ្ហភាពខ្ពស់ ទឹកអ៊ីយ៉ូនីកម្មច្រើនជាង និង pH ថយចុះបន្តិច។'),

('ac77db6e-031d-438d-a5a3-f9327f32aa3a', 1, 4, 'short_answer',
'Name two common household items that are acidic.',
'បញ្ជាក់ឈ្មោះរបស់របរប្រើប្រាស់ក្នុងផ្ទះធម្មតាពីរដែលមានអាស៊ីត។',
'List two acidic items.',
'រាយបញ្ជីរបស់អាស៊ីតពីរ។',
NULL,
'lemon juice, vinegar',
10, 'easy',
'Think of sour-tasting items.',
'គិតអំពីរបស់ដែលមានរសជាតិជូរ។',
'Common acidic household items include lemon juice (pH ~2), vinegar (pH ~3), orange juice, tomatoes, and coffee.',
'របស់របរប្រើប្រាស់ក្នុងផ្ទះអាស៊ីតធម្មតារួមមានទឹកក្រូចឆ្មា (pH ~2) ទឹកខ្មេះ (pH ~3) ទឹកក្រូច ប៉េងប៉ោះ និងកាហ្វេ។'),

('ac77db6e-031d-438d-a5a3-f9327f32aa3a', 1, 5, 'fill_blank',
'A solution with pH 10 is _____ times more basic than a solution with pH 8.',
'សូលុយស្យុងដែលមាន pH 10 គឺមូលដ្ឋាន _____ ដងជាងសូលុយស្យុងដែលមាន pH 8។',
'Enter the number.',
'បញ្ចូលលេខ។',
NULL,
'100',
15, 'medium',
'Each pH unit represents a 10-fold change.',
'រង្វាស់ pH នីមួយៗតំណាងឲ្យការផ្លាស់ប្តូរ 10 ដង។',
'pH is logarithmic. The difference of 2 pH units means 10^2 = 100 times difference in H+ concentration.',
'pH គឺលោការីត។ ភាពខុសគ្នានៃរង្វាស់ pH 2 មានន័យថា 10^2 = 100 ដងភាពខុសគ្នានៃកំហាប់ H+។'),

-- 12. pH Scale: Basics (e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7)
('e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7', 1, 1, 'multiple_choice',
'Which color typically indicates an acidic solution on pH paper?',
'តើពណ៌មួយណាជាទូទៅបង្ហាញសូលុយស្យុងអាស៊ីតនៅលើក្រដាស pH?',
'Select the common color.',
'ជ្រើសរើសពណ៌ទូទៅ។',
'{"options": [{"en": "Red", "km": "ក្រហម"}, {"en": "Blue", "km": "ខៀវ"}, {"en": "Green", "km": "បៃតង"}, {"en": "Yellow", "km": "លឿង"}]}',
'Red',
10, 'easy',
'Think of litmus paper.',
'គិតអំពីក្រដាសលីត្មូស។',
'Red indicates acidic solutions on pH paper, while blue indicates basic solutions. Green is usually neutral.',
'ក្រហមបង្ហាញសូលុយស្យុងអាស៊ីតនៅលើក្រដាស pH ខណៈខៀវបង្ហាញសូលុយស្យុងមូលដ្ឋាន។ បៃតងជាទូទៅអព្យាក្រឹត។'),

('e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7', 1, 2, 'true_false',
'Stomach acid has a higher pH than soap.',
'អាស៊ីតក្រពះមាន pH ខ្ពស់ជាងសាប៊ូ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'easy',
'Stomach acid is very acidic.',
'អាស៊ីតក្រពះមានអាស៊ីតខ្លាំង។',
'Stomach acid has pH ~2 (very acidic), while soap has pH ~10-11 (basic). Lower pH means more acidic.',
'អាស៊ីតក្រពះមាន pH ~2 (អាស៊ីតខ្លាំង) ខណៈសាប៊ូមាន pH ~10-11 (មូលដ្ឋាន)។ pH ទាបមានន័យថាអាស៊ីតច្រើន។'),

('e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7', 1, 3, 'fill_blank',
'The pH of neutral water is _____.',
'pH នៃទឹកអព្យាក្រឹតគឺ _____។',
'Enter the number.',
'បញ្ចូលលេខ។',
NULL,
'7',
10, 'easy',
'Middle of the pH scale.',
'កណ្តាលនៃមាត្រដ្ឋាន pH។',
'pH 7 is neutral - neither acidic nor basic. This is the pH of pure water at 25°C.',
'pH 7 គឺអព្យាក្រឹត - មិនមែនអាស៊ីត ឬមូលដ្ឋាន។ នេះគឺជា pH នៃទឹកសុទ្ធនៅ 25°C។'),

('e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7', 1, 4, 'multiple_choice',
'What happens when you add lemon juice to water?',
'តើអ្វីកើតឡើងនៅពេលអ្នកបន្ថែមទឹកក្រូចឆ្មាទៅក្នុងទឹក?',
'Choose the correct effect.',
'ជ្រើសរើសឥទ្ធិពលត្រឹមត្រូវ។',
'{"options": [{"en": "pH increases", "km": "pH កើនឡើង"}, {"en": "pH decreases", "km": "pH ថយចុះ"}, {"en": "pH stays the same", "km": "pH នៅដដែល"}, {"en": "Water becomes neutral", "km": "ទឹកក្លាយជាអព្យាក្រឹត"}]}',
'pH decreases',
10, 'easy',
'Lemon juice is acidic.',
'ទឹកក្រូចឆ្មាមានអាស៊ីត។',
'Lemon juice is acidic (pH ~2), so adding it to water makes the solution more acidic, lowering the pH.',
'ទឹកក្រូចឆ្មាមានអាស៊ីត (pH ~2) ដូច្នេះការបន្ថែមវាទៅក្នុងទឹកធ្វើឲ្យសូលុយស្យុងមានអាស៊ីតច្រើន បន្ថយ pH។'),

('e9fd85a0-dcd5-4e6d-abd8-416666d8f3e7', 1, 5, 'short_answer',
'Name one common basic (alkaline) household item.',
'បញ្ជាក់ឈ្មោះរបស់របរប្រើប្រាស់ក្នុងផ្ទះមូលដ្ឋាន (អាល់កាឡាំង) ធម្មតាមួយ។',
'Give one example.',
'ផ្តល់ឧទាហរណ៍មួយ។',
NULL,
'baking soda',
10, 'easy',
'Used for cleaning or cooking.',
'ប្រើសម្រាប់សម្អាត ឬចម្អិនអាហារ។',
'Common basic items include baking soda (pH ~9), ammonia cleaner (pH ~11), soap, and bleach (pH ~13).',
'របស់មូលដ្ឋានធម្មតារួមមានសូដាដុតនំ (pH ~9) សម្អាតអាម៉ូញាក (pH ~11) សាប៊ូ និងទឹកលាងស (pH ~13)។'),

-- 13. Reactants, Products and Leftovers (a5e769ac-5837-4f0a-8cae-4f2478526c10)
('a5e769ac-5837-4f0a-8cae-4f2478526c10', 1, 1, 'multiple_choice',
'In a chemical reaction, what are the starting materials called?',
'ក្នុងប្រតិកម្មគីមី តើសម្ភារៈចាប់ផ្តើមត្រូវបានហៅថាអ្វី?',
'Choose the correct term.',
'ជ្រើសរើសពាក្យត្រឹមត្រូវ។',
'{"options": [{"en": "Products", "km": "ផលិតផល"}, {"en": "Reactants", "km": "សារធាតុប្រតិកម្ម"}, {"en": "Leftovers", "km": "សំណល់"}, {"en": "Catalysts", "km": "កាតាលីករ"}]}',
'Reactants',
10, 'easy',
'They react to form new substances.',
'ពួកវាប្រតិកម្មដើម្បីបង្កើតសារធាតុថ្មី។',
'Reactants are the starting materials in a chemical reaction that are transformed into products.',
'សារធាតុប្រតិកម្មគឺជាសម្ភារៈចាប់ផ្តើមក្នុងប្រតិកម្មគីមីដែលត្រូវបានបំប្លែងទៅជាផលិតផល។'),

('a5e769ac-5837-4f0a-8cae-4f2478526c10', 1, 2, 'short_answer',
'What is the limiting reactant in a reaction?',
'តើអ្វីជាសារធាតុប្រតិកម្មកំណត់ក្នុងប្រតិកម្ម?',
'Explain briefly.',
'ពន្យល់ខ្លីៗ។',
NULL,
'The reactant that runs out first',
15, 'medium',
'It limits how much product forms.',
'វាកំណត់បរិមាណផលិតផលបង្កើត។',
'The limiting reactant is completely consumed first and determines the maximum amount of product that can form.',
'សារធាតុប្រតិកម្មកំណត់ត្រូវបានប្រើប្រាស់អស់មុនគេ និងកំណត់បរិមាណអតិបរមានៃផលិតផលដែលអាចបង្កើត។'),

('a5e769ac-5837-4f0a-8cae-4f2478526c10', 1, 3, 'calculation',
'If you have 3 molecules of A and 5 molecules of B, and the reaction is A + 2B → C, how many molecules of C can form?',
'ប្រសិនបើអ្នកមានម៉ូលេគុល A 3 និងម៉ូលេគុល B 5 ហើយប្រតិកម្មគឺ A + 2B → C តើម៉ូលេគុល C ប៉ុន្មានអាចបង្កើត?',
'Find the limiting reactant first.',
'ស្វែងរកសារធាតុប្រតិកម្មកំណត់មុន។',
NULL,
'2',
20, 'medium',
'Each A needs 2 B molecules.',
'A នីមួយៗត្រូវការម៉ូលេគុល B 2។',
'For 3 A, you need 6 B, but only have 5 B. So B is limiting. 5 B ÷ 2 = 2.5, but we can only make 2 complete C molecules.',
'សម្រាប់ A 3 អ្នកត្រូវការ B 6 ប៉ុន្តែមានតែ B 5។ ដូច្នេះ B កំណត់។ 5 B ÷ 2 = 2.5 ប៉ុន្តែយើងអាចបង្កើតតែម៉ូលេគុល C ពេញលេញ 2។'),

('a5e769ac-5837-4f0a-8cae-4f2478526c10', 1, 4, 'true_false',
'In every chemical reaction, all reactants are completely used up.',
'ក្នុងប្រតិកម្មគីមីទាំងអស់ សារធាតុប្រតិកម្មទាំងអស់ត្រូវបានប្រើប្រាស់អស់ទាំងស្រុង។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'Think about limiting reactants.',
'គិតអំពីសារធាតុប្រតិកម្មកំណត់។',
'Usually one reactant (limiting) is used up completely while others (excess) have leftovers.',
'ជាទូទៅសារធាតុប្រតិកម្មមួយ (កំណត់) ត្រូវបានប្រើអស់ ខណៈផ្សេងទៀត (លើស) មានសំណល់។'),

('a5e769ac-5837-4f0a-8cae-4f2478526c10', 1, 5, 'fill_blank',
'The substances formed in a chemical reaction are called _____.',
'សារធាតុដែលបង្កើតក្នុងប្រតិកម្មគីមីត្រូវបានហៅថា _____។',
'Fill in the term.',
'បំពេញពាក្យ។',
NULL,
'products',
10, 'easy',
'Opposite of reactants.',
'ផ្ទុយពីសារធាតុប្រតិកម្ម។',
'Products are the new substances formed when reactants undergo a chemical reaction.',
'ផលិតផលគឺជាសារធាតុថ្មីដែលបង្កើតនៅពេលសារធាតុប្រតិកម្មឆ្លងកាត់ប្រតិកម្មគីមី។'),

-- 14. States of Matter (c149d515-f28b-41c3-bea7-e83f113abfbb)
('c149d515-f28b-41c3-bea7-e83f113abfbb', 1, 1, 'multiple_choice',
'Which state of matter has a definite shape and volume?',
'តើស្ថានភាពរូបធាតុមួយណាមានរូបរាង និងមាឌច្បាស់លាស់?',
'Select one state.',
'ជ្រើសរើសស្ថានភាពមួយ។',
'{"options": [{"en": "Solid", "km": "រឹង"}, {"en": "Liquid", "km": "រាវ"}, {"en": "Gas", "km": "ឧស្ម័ន"}, {"en": "Plasma", "km": "ប្លាស្មា"}]}',
'Solid',
10, 'easy',
'Particles are tightly packed.',
'ភាគល្អិតត្រូវបានបង្រួមយ៉ាងតឹង។',
'Solids have definite shape and volume because particles are closely packed in fixed positions.',
'រឹងមានរូបរាង និងមាឌច្បាស់លាស់ពីព្រោះភាគល្អិតត្រូវបានបង្រួមយ៉ាងជិតស្និទ្ធក្នុងទីតាំងថេរ។'),

('c149d515-f28b-41c3-bea7-e83f113abfbb', 1, 2, 'true_false',
'Particles in a gas move faster than particles in a liquid at the same temperature.',
'ភាគល្អិតក្នុងឧស្ម័នផ្លាស់ទីលឿនជាងភាគល្អិតក្នុងរាវនៅសីតុណ្ហភាពដូចគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Consider kinetic energy.',
'ពិចារណាថាមពលស៊ីនេទិច។',
'Gas particles have more kinetic energy and move faster than liquid particles at the same temperature.',
'ភាគល្អិតឧស្ម័នមានថាមពលស៊ីនេទិចច្រើន និងផ្លាស់ទីលឿនជាងភាគល្អិតរាវនៅសីតុណ្ហភាពដូចគ្នា។'),

('c149d515-f28b-41c3-bea7-e83f113abfbb', 1, 3, 'short_answer',
'What is the process called when a liquid changes to a gas?',
'តើដំណើរការត្រូវបានហៅថាអ្វីនៅពេលរាវផ្លាស់ប្តូរទៅជាឧស្ម័ន?',
'Name the phase change.',
'បញ្ជាក់ឈ្មោះការផ្លាស់ប្តូរដំណាក់កាល។',
NULL,
'evaporation',
10, 'easy',
'Or vaporization.',
'ឬការហួត។',
'Evaporation (or vaporization) is the process where liquid particles gain enough energy to become gas.',
'ការហួត (ឬការចំហាយ) គឺជាដំណើរការដែលភាគល្អិតរាវទទួលបានថាមពលគ្រប់គ្រាន់ដើម្បីក្លាយជាឧស្ម័ន។'),

('c149d515-f28b-41c3-bea7-e83f113abfbb', 1, 4, 'fill_blank',
'The temperature at which a solid changes to a liquid is called the _____ point.',
'សីតុណ្ហភាពដែលរឹងផ្លាស់ប្តូរទៅជារាវត្រូវបានហៅថាចំណុច _____។',
'Fill in the term.',
'បំពេញពាក្យ។',
NULL,
'melting',
10, 'easy',
'Ice becomes water.',
'ទឹកកកក្លាយជាទឹក។',
'The melting point is the temperature at which a solid changes to liquid state.',
'ចំណុចរលាយគឺជាសីតុណ្ហភាពដែលរឹងផ្លាស់ប្តូរទៅស្ថានភាពរាវ។'),

('c149d515-f28b-41c3-bea7-e83f113abfbb', 1, 5, 'multiple_choice',
'What happens to particle spacing when a substance changes from liquid to gas?',
'តើអ្វីកើតឡើងចំពោះគម្លាតភាគល្អិតនៅពេលសារធាតុផ្លាស់ប្តូរពីរាវទៅឧស្ម័ន?',
'Choose the correct change.',
'ជ្រើសរើសការផ្លាស់ប្តូរត្រឹមត្រូវ។',
'{"options": [{"en": "Spacing decreases", "km": "គម្លាតថយចុះ"}, {"en": "Spacing increases", "km": "គម្លាតកើនឡើង"}, {"en": "No change", "km": "គ្មានការផ្លាស់ប្តូរ"}, {"en": "Particles merge", "km": "ភាគល្អិតរួមបញ្ចូលគ្នា"}]}',
'Spacing increases',
10, 'easy',
'Gases expand.',
'ឧស្ម័នពង្រីក។',
'When liquid becomes gas, particles spread far apart, greatly increasing the spacing between them.',
'នៅពេលរាវក្លាយជាឧស្ម័ន ភាគល្អិតរីករាលដាច់ឆ្ងាយពីគ្នា បង្កើនគម្លាតរវាងពួកវាយ៉ាងខ្លាំង។'),

-- 15. States of Matter: Basics (15934a8f-9806-4293-86d1-3120a2157709)
('15934a8f-9806-4293-86d1-3120a2157709', 1, 1, 'multiple_choice',
'Which state of matter takes the shape of its container?',
'តើស្ថានភាពរូបធាតុមួយណាយករូបរាងនៃធុងផ្ទុករបស់វា?',
'Select all that apply.',
'ជ្រើសរើសទាំងអស់ដែលអនុវត្ត។',
'{"options": [{"en": "Solid only", "km": "តែរឹងប៉ុណ្ណោះ"}, {"en": "Liquid only", "km": "តែរាវប៉ុណ្ណោះ"}, {"en": "Gas only", "km": "តែឧស្ម័នប៉ុណ្ណោះ"}, {"en": "Liquid and gas", "km": "រាវ និងឧស្ម័ន"}]}',
'Liquid and gas',
10, 'easy',
'Which can flow?',
'មួយណាអាចហូរ?',
'Liquids take the shape of their container but have definite volume. Gases take both shape and volume of container.',
'រាវយករូបរាងនៃធុងផ្ទុកប៉ុន្តែមានមាឌច្បាស់លាស់។ ឧស្ម័នយកទាំងរូបរាង និងមាឌនៃធុង។'),

('15934a8f-9806-4293-86d1-3120a2157709', 1, 2, 'true_false',
'Ice is less dense than liquid water.',
'ទឹកកកមានដង់ស៊ីតេតិចជាងទឹករាវ។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'medium',
'Why does ice float?',
'ហេតុអ្វីទឹកកកអណ្តែត?',
'Ice is less dense than water due to its crystal structure, which is why ice floats on water.',
'ទឹកកកមានដង់ស៊ីតេតិចជាងទឹកដោយសាររចនាសម្ព័ន្ធគ្រីស្តាល់របស់វា ដែលជាហេតុផលទឹកកកអណ្តែតលើទឹក។'),

('15934a8f-9806-4293-86d1-3120a2157709', 1, 3, 'fill_blank',
'When water vapor cools and becomes liquid water, this is called _____.',
'នៅពេលចំហាយទឹកត្រជាក់ និងក្លាយជាទឹករាវ នេះត្រូវបានហៅថា _____។',
'Name the process.',
'បញ្ជាក់ឈ្មោះដំណើរការ។',
NULL,
'condensation',
10, 'easy',
'Opposite of evaporation.',
'ផ្ទុយពីការហួត។',
'Condensation occurs when gas particles lose energy and come together to form liquid.',
'ការកំណក់កើតឡើងនៅពេលភាគល្អិតឧស្ម័នបាត់បង់ថាមពល និងមកជាមួយគ្នាដើម្បីបង្កើតរាវ។'),

('15934a8f-9806-4293-86d1-3120a2157709', 1, 4, 'short_answer',
'What happens to water at 0°C?',
'តើអ្វីកើតឡើងចំពោះទឹកនៅ 0°C?',
'Describe the phase change.',
'ពិពណ៌នាការផ្លាស់ប្តូរដំណាក់កាល។',
NULL,
'It freezes',
10, 'easy',
'This is the freezing point.',
'នេះគឺជាចំណុចកក។',
'At 0°C (32°F), water freezes and changes from liquid to solid state (ice).',
'នៅ 0°C (32°F) ទឹកកក និងផ្លាស់ប្តូរពីស្ថានភាពរាវទៅរឹង (ទឹកកក)។'),

('15934a8f-9806-4293-86d1-3120a2157709', 1, 5, 'multiple_choice',
'In which state of matter are particles most organized?',
'តើក្នុងស្ថានភាពរូបធាតុមួយណាភាគល្អិតត្រូវបានរៀបចំច្រើនបំផុត?',
'Think about particle arrangement.',
'គិតអំពីការរៀបចំភាគល្អិត។',
'{"options": [{"en": "Solid", "km": "រឹង"}, {"en": "Liquid", "km": "រាវ"}, {"en": "Gas", "km": "ឧស្ម័ន"}, {"en": "All the same", "km": "ទាំងអស់ដូចគ្នា"}]}',
'Solid',
10, 'easy',
'Fixed positions.',
'ទីតាំងថេរ។',
'Solid particles are arranged in organized, fixed patterns (crystal lattice), while liquids and gases are more random.',
'ភាគល្អិតរឹងត្រូវបានរៀបចំក្នុងលំនាំថេរ រៀបចំ (បណ្តាញគ្រីស្តាល់) ខណៈរាវ និងឧស្ម័នចៃដន្យជាង។'),

-- 16. Area Builder (57b2faca-283e-40d6-93ce-ac6797d35902)
('57b2faca-283e-40d6-93ce-ac6797d35902', 1, 1, 'calculation',
'What is the area of a rectangle with length 5 units and width 3 units?',
'តើផ្ទៃនៃចតុកោណកែងដែលមានប្រវែង 5 ឯកតា និងទទឹង 3 ឯកតាគឺប៉ុន្មាន?',
'Calculate the area.',
'គណនាផ្ទៃ។',
NULL,
'15',
10, 'easy',
'Area = length × width',
'ផ្ទៃ = ប្រវែង × ទទឹង',
'Area of rectangle = length × width = 5 × 3 = 15 square units',
'ផ្ទៃចតុកោណកែង = ប្រវែង × ទទឹង = 5 × 3 = 15 ឯកតាការ៉េ'),

('57b2faca-283e-40d6-93ce-ac6797d35902', 1, 2, 'multiple_choice',
'Which formula calculates the area of a square?',
'តើរូបមន្តមួយណាគណនាផ្ទៃនៃការ៉េ?',
'Select the correct formula.',
'ជ្រើសរើសរូបមន្តត្រឹមត្រូវ។',
'{"options": [{"en": "side × side", "km": "ជ្រុង × ជ្រុង"}, {"en": "4 × side", "km": "4 × ជ្រុង"}, {"en": "side + side", "km": "ជ្រុង + ជ្រុង"}, {"en": "2 × side", "km": "2 × ជ្រុង"}]}',
'side × side',
10, 'easy',
'All sides are equal.',
'ជ្រុងទាំងអស់ស្មើគ្នា។',
'Area of square = side × side = side². The perimeter would be 4 × side.',
'ផ្ទៃការ៉េ = ជ្រុង × ជ្រុង = ជ្រុង²។ បរិមាត្រនឹងជា 4 × ជ្រុង។'),

('57b2faca-283e-40d6-93ce-ac6797d35902', 1, 3, 'true_false',
'Two shapes with the same perimeter always have the same area.',
'រូបរាងពីរដែលមានបរិមាត្រដូចគ្នាតែងតែមានផ្ទៃដូចគ្នា។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'false',
10, 'medium',
'Consider different rectangles.',
'ពិចារណាចតុកោណកែងផ្សេងៗ។',
'Different shapes can have the same perimeter but different areas. Example: 4×4 square and 2×6 rectangle both have perimeter 16, but areas 16 and 12.',
'រូបរាងផ្សេងៗអាចមានបរិមាត្រដូចគ្នាប៉ុន្តែផ្ទៃខុសគ្នា។ ឧទាហរណ៍៖ ការ៉េ 4×4 និងចតុកោណកែង 2×6 ទាំងពីរមានបរិមាត្រ 16 ប៉ុន្តែផ្ទៃ 16 និង 12។'),

('57b2faca-283e-40d6-93ce-ac6797d35902', 1, 4, 'fill_blank',
'The distance around the outside of a shape is called its _____.',
'ចម្ងាយជុំវិញខាងក្រៅនៃរូបរាងត្រូវបានហៅថា _____ របស់វា។',
'Fill in the term.',
'បំពេញពាក្យ។',
NULL,
'perimeter',
10, 'easy',
'The boundary length.',
'ប្រវែងព្រំដែន។',
'Perimeter is the total distance around the edge of a 2D shape.',
'បរិមាត្រគឺជាចម្ងាយសរុបជុំវិញគែមនៃរូបរាង 2D។'),

('57b2faca-283e-40d6-93ce-ac6797d35902', 1, 5, 'short_answer',
'How many unit squares fit in a 3×4 rectangle?',
'តើការ៉េឯកតាប៉ុន្មានសមក្នុងចតុកោណកែង 3×4?',
'Count the squares.',
'រាប់ការ៉េ។',
NULL,
'12',
10, 'easy',
'Think of area.',
'គិតអំពីផ្ទៃ។',
'A 3×4 rectangle has area 12 square units, so 12 unit squares fit inside.',
'ចតុកោណកែង 3×4 មានផ្ទៃ 12 ឯកតាការ៉េ ដូច្នេះការ៉េឯកតា 12 សមនៅខាងក្នុង។'),

-- 17. Arithmetic (51b65340-1a15-47de-a89e-c77e59c96a75)
('51b65340-1a15-47de-a89e-c77e59c96a75', 1, 1, 'calculation',
'Calculate: 456 + 789',
'គណនា៖ 456 + 789',
'Find the sum.',
'រកផលបូក។',
NULL,
'1245',
10, 'easy',
'Add column by column.',
'បូកតាមជួរឈរ។',
'456 + 789 = 1245. Remember to carry when column sum exceeds 9.',
'456 + 789 = 1245។ ចងចាំត្រូវចងនៅពេលផលបូកជួរឈរលើស 9។'),

('51b65340-1a15-47de-a89e-c77e59c96a75', 1, 2, 'multiple_choice',
'What is 15 × 12?',
'តើ 15 × 12 គឺប៉ុន្មាន?',
'Calculate the product.',
'គណនាផលគុណ។',
'{"options": [{"en": "150", "km": "150"}, {"en": "170", "km": "170"}, {"en": "180", "km": "180"}, {"en": "190", "km": "190"}]}',
'180',
10, 'easy',
'15 × 10 + 15 × 2',
'15 × 10 + 15 × 2',
'15 × 12 = 15 × 10 + 15 × 2 = 150 + 30 = 180',
'15 × 12 = 15 × 10 + 15 × 2 = 150 + 30 = 180'),

('51b65340-1a15-47de-a89e-c77e59c96a75', 1, 3, 'fill_blank',
'843 - 567 = _____',
'843 - 567 = _____',
'Calculate the difference.',
'គណនាផលដក។',
NULL,
'276',
10, 'easy',
'Borrow if needed.',
'ខ្ចីប្រសិនបើត្រូវការ។',
'843 - 567 = 276. Use borrowing when needed.',
'843 - 567 = 276។ ប្រើការខ្ចីនៅពេលត្រូវការ។'),

('51b65340-1a15-47de-a89e-c77e59c96a75', 1, 4, 'true_false',
'Division by zero is undefined.',
'ការចែកនឹងសូន្យមិនបានកំណត់។',
'True or false?',
'ពិត ឬមិនពិត?',
NULL,
'true',
10, 'easy',
'Mathematical rule.',
'ច្បាប់គណិតវិទ្យា។',
'Division by zero is undefined because there is no number that when multiplied by 0 gives a non-zero result.',
'ការចែកនឹងសូន្យមិនបានកំណត់ពីព្រោះគ្មានលេខដែលនៅពេលគុណនឹង 0 ផ្តល់លទ្ធផលមិនមែនសូន្យ។'),

('51b65340-1a15-47de-a89e-c77e59c96a75', 1, 5, 'calculation',
'What is 144 ÷ 12?',
'តើ 144 ÷ 12 គឺប៉ុន្មាន?',
'Find the quotient.',
'រកផលចែក។',
NULL,
'12',
10, 'easy',
'Think: 12 × ? = 144',
'គិត៖ 12 × ? = 144',
'144 ÷ 12 = 12 because 12 × 12 = 144.',
'144 ÷ 12 = 12 ពីព្រោះ 12 × 12 = 144។');